### ISSUE TITLE
Enhancement: [no-explicit-any] Adding the ability to ignore any in extends in generic (again)

### ISSUE THREAD

**Issue by MichaelMitchell-at** [typescript-eslint/typescript-eslint#6535] opened 2023-02-26 23:13 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-explicit-any

### Description

This is a rehashing of https://github.com/typescript-eslint/typescript-eslint/issues/6252. I would have commented on it instead of opening a new proposal, but it seemed like commenting was locked aggressively.

I will respond to some of the comments in the previous thread that argued why this proposal should be rejected.

>This rule is over 4 years old (it's really one of the first rules implemented!) and you're the first person to want an option for this case.
From that I would infer that this is not something that would benefit even a minority of the TS community.

Definitely not the first person. I've known this to be an issue for years, but for me it's usually been me working in:
- a codebase that has too many existing usages of `any` and we just disable the lint rule globally (very common).
- a codebase that just accepts having to disable the rule per line/block and everyone is apathetic to filing an issue (what has been the case for me... every `eslint-disable` I have to write building up to be the straw that broke the camel's back).

> any is simply not a thing in the type system. If you trace your program's variance carefully, there should not be a single reason for you to write any.

The example code I provided below demonstrates why this is not the case.

### Fail

```typescript
/** Foo is invariant over T */
interface Foo<in out T> {
    ref: {value: T},
    updateRef: (value: T) => void;
}

class ConcreteFoo1 implements Foo<number> {
    constructor(
        public ref: {value: number},
        public updateRef: (value: number) => void,
    ) {}

    name = 'ConcreteFoo1' as const;
}

class ConcreteFoo2 implements Foo<string> {
    constructor(
        public ref: {value: string},
        public updateRef: (value: string) => void,
    ) {}

    name = 'ConcreteFoo2' as const
}

function makeFoo(): ConcreteFoo1 | ConcreteFoo2 {
    const ref = {value: 42};
    const updateRef = (value: number) => {ref.value = value};
    return new ConcreteFoo1(ref, updateRef);
}

const concreteFoo = makeFoo();

{
    function receiveFoo<FooT extends Foo<unknown>>(foo: FooT): FooT { return foo; };

    // @ts-expect-error Fails because of `updateRef`
    receiveFoo(concreteFoo);
}

{
    function receiveFoo<FooT extends Foo<never>>(foo: FooT): FooT { return foo; };

    // @ts-expect-error Fails because of `data`
    receiveFoo(concreteFoo);
}

{
    function receiveFoo<T>(foo: Foo<T>) { return foo; }

    // @ts-expect-error Fails because TypeScript loses information about `foo`
    receiveFoo(concreteFoo).name;
}

{
    function receiveFoo<T, FooT extends Foo<T>>(foo: FooT): FooT { return foo; }

    // @ts-expect-error Fails because TypeScript incorrectly infers T as unknown
    receiveFoo(concreteFoo);
}

{
    function receiveFoo<T, FooT extends Foo<T>>(foo: FooT & Foo<T>): FooT { return foo; }

    // @ts-expect-error Fails to work with unions of Foo subtypes
    receiveFoo(concreteFoo);
}

{
    // Comical hack
    function receiveFoo<FooT>(foo: FooT extends Foo<infer _> ? FooT : never): FooT { return foo; }

    receiveFoo(concreteFoo).name;
}

{
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    function receiveFoo<FooT extends Foo<any>>(foo: FooT): FooT { return foo; };

    const foo: ConcreteFoo1 | ConcreteFoo2 = receiveFoo(concreteFoo);
    const fooName: 'ConcreteFoo1' | 'ConcreteFoo2' = foo.name;
}
```

### Pass

```typescript
{
    // ** not needed ** eslint-disable-next-line @typescript-eslint/no-explicit-any
    function receiveFoo<FooT extends Foo<any>>(foo: FooT): FooT { return foo; };

    const foo: ConcreteFoo1 | ConcreteFoo2 = receiveFoo(concreteFoo);
    const fooName: 'ConcreteFoo1' | 'ConcreteFoo2' = foo.name;
}
```

### Additional Info

Who knows how many of [these hundreds of DefinitelyTyped definitions](https://cs.github.com/DefinitelyTyped/DefinitelyTyped?q=%2F+extends+%5BA-z%5D%2B%3C%5B%5E%3E%5D*%5Cbany%5Cb%2F) use `any` due this

**Comment by Josh-Cena** [comment] 2023-02-26 23:34
I'm not going to deny that `any` seems the most ergonomic type in this case, however (1) you can simply use `eslint-disable` (we actually recommend using it where it's inevitable) (2) it introduces more unsoundness downstream. `no-explicit-any` has the benefit that it doesn't rely on type information, so in a codebase not set up for type-aware linting, this rule is the best protection against outright unsoundness. Consider how a slightly non-contrived `receiveFoo` would be implemented:

```ts
function receiveFoo<FooT extends Foo<any>>(foo: FooT): FooT {
  foo.ref.value; // Oh no, here `value` is `any`
  foo.updateRef(1); // Oh no, here you can pass anything to `updateRef()`
  return foo;
}
```

If you don't turn on `no-unsafe-*` rules, this quickly leaks `any`s.

The reason why your code is particularly hard to type—as far as I understand—is because it needs rank-2 types, which TypeScript doesn't have.

**Comment by MichaelMitchell-at** [comment] 2023-02-26 23:46
That is a fair point with respect to the tension between providing well-typed interfaces versus having type-safety in implementations. If one were to ship real library code, they may consider getting the best of both worlds by having something like:
```tsx
    function receiveFoo<FooT extends Foo<any>>(foo: FooT): FooT;
    function receiveFoo<T>(foo: Foo<T>): Foo<T> {
        foo.ref.value; // T
        foo.updateRef(1); // Error
        return foo;
    };
```
The trade-off being that the author must be certain that the overload signature is logically consistent with the implementation's.

Considering that TS will foreseeably never have higher-kinded types, I'm biased in favor of enabling patterns that developers currently have to write.

**Comment by bradzacher** [comment] 2023-02-26 23:48
duplicate of #6252
The `any` may be ergonomic but it's also highly unsafe, as Josh mentioned.

If you are intentionally using an `any` in your code, that's a prime candidate for a disable comment explaining why you're writing unsafe code.

**Closed by bradzacher** 2023-02-26 23:48 UTC
Labels: package: eslint-plugin, triage, enhancement: plugin rule option
