### ISSUE TITLE
Enhancement: `member-ordering` default configuration

### ISSUE THREAD

**Issue by nbouvrette** [typescript-eslint/typescript-eslint#5452] opened 2022-08-09 18:19 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/member-ordering

### Description

Based on my experimentations and also on the documentation, to apply the "default configuration" you have to copy/paste this list: https://typescript-eslint.io/rules/member-ordering/#default-configuration which contains 88 lines.

Adding this in the ESLint config will make it less maintainable and having an option to omit this list and use the default would be preferable.

One idea would be to add a new option called `memberTypesPreset` where you could pick `default` - or maybe even its default value would be `default` and you don't have to specify it.

Or another idea would be that if `memberTypes: []` (empty array) or, if `memberTypes` is simply omitted, the default configuration is applied.

### Fail

```typescript
---
# eslintrc.yaml
root: true # Disables inheritance from parent config.
overrides:
  # TypeScript configurations
  - files:
      - '*.ts'
      - '*.mts'
      - '*.cts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - 'tsconfig.json'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    rules:
      # Checks members (classes, interfaces, types) and applies consistent ordering.
      # @see https://typescript-eslint.io/rules/member-ordering/
      '@typescript-eslint/member-ordering':
        - error
        - default:
            memberTypesPreset: default
            order: alphabetically-case-insensitive
```

### Pass

```typescript
---
# eslintrc.yaml
root: true # Disables inheritance from parent config.
overrides:
  # TypeScript configurations
  - files:
      - '*.ts'
      - '*.mts'
      - '*.cts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - 'tsconfig.json'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    rules:
      # Checks members (classes, interfaces, types) and applies consistent ordering.
      # @see https://typescript-eslint.io/rules/member-ordering/
      '@typescript-eslint/member-ordering':
        - error
        - default:
            memberTypes:
              - signature
              - public-static-field
              - protected-static-field
              - private-static-field
              - public-decorated-field
              - protected-decorated-field
              - private-decorated-field
              - public-instance-field
              - protected-instance-field
              - private-instance-field
              - public-abstract-field
              - protected-abstract-field
              - private-abstract-field
              - public-field
              - protected-field
              - private-field
              - static-field
              - instance-field
              - abstract-field
              - decorated-field
              - field
              - static-initialization
              - public-constructor
              - protected-constructor
              - private-constructor
              - constructor
              - public-static-get
              - protected-static-get
              - private-static-get
              - public-decorated-get
              - protected-decorated-get
              - private-decorated-get
              - public-instance-get
              - protected-instance-get
              - private-instance-get
              - public-abstract-get
              - protected-abstract-get
              - private-abstract-get
              - public-get
              - protected-get
              - private-get
              - static-get
              - instance-get
              - abstract-get
              - decorated-get
              - get
              - public-static-set
              - protected-static-set
              - private-static-set
              - public-decorated-set
              - protected-decorated-set
              - private-decorated-set
              - public-instance-set
              - protected-instance-set
              - private-instance-set
              - public-abstract-set
              - protected-abstract-set
              - private-abstract-set
              - public-set
              - protected-set
              - private-set
              - static-set
              - instance-set
              - abstract-set
              - decorated-set
              - set
              - public-static-method
              - protected-static-method
              - private-static-method
              - public-decorated-method
              - protected-decorated-method
              - private-decorated-method
              - public-instance-method
              - protected-instance-method
              - private-instance-method
              - public-abstract-method
              - protected-abstract-method
              - private-abstract-method
              - public-method
              - protected-method
              - private-method
              - static-method
              - instance-method
              - abstract-method
              - decorated-method
              - method
            order: alphabetically-case-insensitive
```

**Comment by bradzacher** [comment] 2022-08-09 19:51
> Based on my experimentations and also on the documentation, to apply the "default configuration" you have to copy/paste this list 

[this is not the case at all](https://typescript-eslint.io/play#ts=4.7.2&sourceType=module&code=MYewdgzgLgBAYiEMC8NgBsCGEIwN4BQMMADgE4CWAbplAKYwDCAXDNJWAOYDcMA9HxgBaAHwwAZhTroAJkVIBXAEboKwGABFW7Cl14DhYydLnzQkKGQXAoIMgAoAlPhgBffoNFpw7a7bIE8iTKqurQtGowAIJOrFQgFDIu7gZeALZ0UAAWIHLEwSqRAEKxMPGJyR6GMBnZuYHEANoAWtqWupwAuqyYYACe+p5iEBScYLQKZHQNpGQg9DZ0SeFQkQCibRw8VV7GsgSuQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0kPtCGRwYAL4hFQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA).

The default config us automatically applied if you provide no `default` key in your config. This means you can keep the default whilst also applying overrides for the non-default cases.

---

What is the goal you're trying to achieve?

**Comment by nbouvrette** [comment] 2022-08-09 20:23
I'm trying to apply `order: alphabetically-case-insensitive` on the default configuration.

The only way I was able to achieve this was by using the example in the **Pass** comment.

**Comment by nbouvrette** [comment] 2022-08-09 21:06
FYI I updated the [playground](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=MYewdgzgLgBAYiEMC8NgBsCGEIwN4CwAUDDAA4BOAlgG6ZQCmMAggFwzTVgDmA3DAHoBMALQA+GADMqDdABNipSrXpMAWu05Ue-IaInTZCkuWp1GMAMKaoXPoOHipM+YphuyAVwBG6KsBgAERs7XUcDF2M3UEhbT2AoEAoACgBKfBgAXwd9NHBOeMSKYg8fPwDoen8WNPYaECo5DOy9JwBbBigACxBjJTLqyqhqy1qYesbmnPbOnr7yAYqoKoC1MYmmvCzpiQ7u3pKTL19qgCF1hs3t1t3Zg6I3AG0NDlttbgBddkwwAE8w3IQKjcMD0TwUBiHJQUECMBIMJpDaoAURC7wBTkMriImSAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0YANrhsOPtCGQANHPlZ52SKIBmAQwT4pmrdqGjoUyPvjEAFvt75KZW-EKR1WgL7eIfvIAunJ+PkA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA) and what I can tell:

- If you omit `memberTypes`, it is applying the order on `never` which is not the default configuration
- If you leave the default configuration empty then it's not applying the order on anything

Unless I missed something the only way to apply default configuration ordering is to copy/paste it in the configuration, which is also what the [documentation](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-ordering.md#sorting-options) is mentionning:

> You can copy and paste the default order from [Default Configuration](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-ordering.md#default-configuration).

**Comment by bradzacher** [comment] 2022-08-10 02:12
Yes you have describe the config working as intended.

The default is still setup using the array style config which forces case sensitive alphabetical sorting.
(the config listed in the docs is the exact config that's used)

Which means if you specify an object for `default`, you override the entire default config (as an array and an object cannot be merged together).

I.e. If you want to change the `default` ordering then you have to specify an object config which wipes away the the default ordering.

---

We could switch it to an object with explicit alphabetical ordering which would enable you to change the ordering and it shouldn't be a breaking change as it is equivalent.

**Comment by nbouvrette** [comment] 2022-08-10 12:21
From the [documentation](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-ordering.md)

> By default, the members are not sorted. If you want to sort them alphabetically, you have to provide a custom configuration.

So basically as soon as you want to use sorting, there is no way right now to re-use the default configuration (without copy/pasting it) which in my opinion should be there by default because it's quite good.

I might consider doing a PR on [member-ordering](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/member-ordering.ts) but I am not sure what you are proposing exactly.

Do you mean changing this [line](https://github.com/typescript-eslint/typescript-eslint/blob/3637f8b5da3a6fbfc1694fc7accc30e502f7208a/packages/eslint-plugin/src/rules/member-ordering.ts#L89)

```ts
oneOf: [arrayConfig(memberTypes), neverConfig],
```

To this:

```ts
oneOf: [arrayConfig(memberTypes), defaultConfig, neverConfig],
```

**Comment by bradzacher** [comment] 2022-08-13 07:38
> Do you mean changing this [line](https://github.com/typescript-eslint/typescript-eslint/blob/3637f8b5da3a6fbfc1694fc7accc30e502f7208a/packages/eslint-plugin/src/rules/member-ordering.ts#L89)

No I mean changing the default config from
```json5
{
  default: [ ... ]
}
```
to
```json5
{
  default: {
    memberTypes: [ ... ],
    order: 'alphabetically' 
  }
}
```

that way you could specify your config like this:
```json5
{
  rules: {
    '@typescript-eslint/member-ordering': [
      'error',
      {
        default: {
          order: 'alphabetically-case-insensitive',
        },
      }
    ],
  },
}
```

and our tooling would merge it in - retaining the defaults whilst changing the ordering config

**Closed** 2024-01-28 02:34 UTC
Labels: good first issue, package: eslint-plugin, enhancement: plugin rule option, accepting prs
