### ISSUE TITLE
Bug: [no-shadow] ignoreFunctionTypeParameterNameValueShadow does no work for shorthand methods and call signatures

### ISSUE THREAD

**Issue by EvanCahill** [typescript-eslint/typescript-eslint#6122] opened 2022-11-28 22:42 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=MYewdgzgLgBAhgJwOYwLwwOQYNwFgBQAlmFAKYIBmcwpMAKqdAIwwDeBMMAFIkgFwxoCYkgCUAgG4hCAEzz5OAByY9kAoSPEwps+UoBMA1f0FRhYMWgB826XIIBfAgSgBPRbQbR9aNh2686maaknZ6MIoAzMZB5mKhuv6KACxGgaZxota2ifhO+EA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uQAsBDACYcA7uiiJo0DtEjgwAXxDygA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
const arg = '';
interface Test1 {
  (arg: string): void;
  p1(arg: string): void;
  p2: (arg: string) => void;
}

type Test2 = {
  (arg: string): void;
  p3(arg: string): void;
  p4: (arg: string) => void;
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-shadow": "error"
  }
}
```

### Expected Result

No errors should be reported.

### Actual Result

no-shadow reports and error on lines 3, 4, 9, and 10. e.g. `'arg' is already declared in the upper scope on line 1 column 7. 3:4 - 3:15`

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.44.0` |
| `@typescript-eslint/parser` | `5.44.0` |
| `TypeScript` | `4.9.3` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment] 2022-11-28 22:59
Duplicate of #6098 - please use the search.

**Closed by bradzacher** 2022-11-28 22:59 UTC
Labels: duplicate, package: eslint-plugin

**Comment by EvanCahill** [comment] 2022-11-28 23:42
Apologies for missing the duplicate. It does not show up in the [search link](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) from the issue template because it was missing the bug tag.

**Comment by JoshuaKGoldberg** [comment] 2022-11-29 00:34
Ah that is a good point, thanks for raising!
