### ISSUE TITLE
After creating new file or renaming it throws about that file is not included in project

### ISSUE THREAD

**Issue by cevek** [typescript-eslint/typescript-eslint#1030] opened 2019-10-01 20:13 UTC
**What code were you trying to parse?**

**What did you expect to happen?**

**What actually happened?**

Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: Foo.tsx.
The file must be included in at least one of the projects provided.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.3.3-alpha.0` |
| `TypeScript`                | `3.6` |
| `ESLint`                    | `6.4` |
| `node`                      | `12` |
| `npm`                       | `6` |

**Comment by cevek** [comment] 2019-10-01 20:17
![ezgif-2-e1d487963f65](https://user-images.githubusercontent.com/3171573/65997193-728c6700-e488-11e9-95d5-469601ec0f26.gif)

**Comment by bradzacher** [comment] 2019-10-01 20:28
duplicate of #864

**Closed by bradzacher** 2019-10-01 20:28 UTC
Labels: package: parser, triage
