### ISSUE TITLE
Repo: Enable commonjs require by adding main to package.json

### ISSUE THREAD

**Issue by ghmcadams** [typescript-eslint/typescript-eslint#7300] opened 2023-07-23 17:35 UTC
### Suggestion

I am the maintainer of [LintLens](https://marketplace.visualstudio.com/items?itemName=ghmcadams.lintlens) (a vscode extension that allows developers to see metadata for their ESLint configs).  In order to read the metadata of rules which live in plugins like this one, LintLens uses require to synchronously load the plugin at runtime from the developer's local machine.  When developers update `@typescript-eslint/eslint-plugin` to v6.1.0, the require() call in LintLens fails to find the module.  Adding main to package.json fixes this issue.

There is no downside to this change, as [node will ignore main when exports exists](https://nodejs.org/api/packages.html#conditional-exports:~:text=If%20both%20%22exports%22%20and%20%22main%22%20are%20defined%2C%20the%20%22exports%22%20field%20takes%20precedence%20over%20%22main%22%20in%20supported%20versions%20of%20Node.js.).

I created a proactive PR (#7301) for this.

**Comment by bradzacher** [comment] 2023-07-23 21:07
Our entire project runs on commonjs!

First up - what we author ESM in TS - we explicitly target CJS in our [`package.json`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/package.json#L14). This causes TS to see all of our `.ts` files as if they were `.cts` files - and thus it emits them with `require`. This is the same behaviour that node itself uses - node assumes all `.js` files are `.cjs` files and treats them as such.

When one of our packages has a dependency on another one of our packages - there isn't any special subterfuge that goes on internally - the dependency is resolved via CJS and via standard node module resolution - the same as it is on a user's system if they installed our packages.

Additionally ESLint currently only supports commonjs for its ecosystem - our plugin and parser are both `require`d by ESLint after resolving it from the user's config string. Which means that every single user that is currently using v6 of the plugin (~1m DLs) is consuming it purely via a commonjs require!

Together this means that all of the work we do is done within a pure commonjs environment:
- our jest tests are run in CJS (via jest + ts-jest)
- our linting is done in CJS (directly on built files)
    - this includes the IDE - `vscode-eslint` ultimately `require`s our tooling via eslint
- our integration tests are run in CJS (directly on built files)

---

What am I getting at with all of this...? I'm trying to illustrate that our package works just fine with `require`! 

So the question isn't "why don't we support `require`?" (because we do!) - instead the question is "why doesn't your tool support our package.json exports?"

As an example for why I believe it's specifically something unique to your tool - as mentioned before `vscode-eslint` is able to `require` our packages (via eslint) - which highlights that code running in the same environment as yours (vscode's nodejs version) is working fine.

Happy to chat further to help find a solution - but adding a `main` is not the correct solution and not one we shall be pursuing.

**Comment by ricenoddle** [comment] 2023-07-24 08:17
1.

**Comment by ricenoddle** [comment] 2023-07-24 08:17
1.

**Comment by ghmcadams** [comment] 2023-07-26 17:02
Thank you for the comprehensive response.  I apologize if I came across as rude or presumptuous.  I understand the reluctance.  `exports` is the recommended field (unless you're supporting node versions < 10 or other tools).  FYI: ESLint [has both main and exports](https://github.com/eslint/eslint/blob/853d32baa8934c08b59a738470b72522e1505f6f/package.json#L9-L14) (which @ljharb [explains](https://twitter.com/ljharb/status/1683729484246298624) is best practice).  That said, I have since found that my issue is caused by something else.

It turns out that when `require`ing a module with a **path**, rather than a **module name**, node will fail to load the module unless `main` exists in the package.json file.

LintLens loads ESLint plugins from within the dev's vscode workspace (relative to the path to their ESLint config file), and therefore it requires using the path.  I have since found [module.createRequire()](https://nodejs.org/api/module.html#modulecreaterequirefilename), which creates a new require function based on a specified path.  This resolves my issue.

**Comment by JoshuaKGoldberg** [comment] 2023-07-26 17:15
> rude or presumptuous

Not at all! We really appreciate you posting here, especially with all the info & suggested fix. ♥️

> `require` ... node will fail to load the module unless `main` exists in the package.json file.

I've been wondering about this. It's come up a couple times since v6 now. I haven't been able to find a good resource explaining it - do you have one handy?

Specifically, I don't follow why the `main` is required for just the path based imports when `exports` could (from my naive perspective) be used instead.

**Comment by ghmcadams** [comment] 2023-07-26 17:18
I have not been able to find a reason for this.  At first, the thought was that it related to the path pointing within a node_modules folder, which [node explicitly views differently](https://twitter.com/ljharb/status/1684062606758379520).  I experimented, though, and moved the package out of node_modules and the issue persists.

**Comment by ghmcadams** [comment] 2023-07-26 17:20
@MylesBorins any idea why this happens?

**Comment by ljharb** [comment] 2023-07-26 17:29
It's because node only looks at the "exports" field when it's a bare specifier loaded out of a node_modules folder, and without a "main", it looks for index.js at the root, which doesn't exist in this package.

**Comment by ghmcadams** [comment] 2023-07-26 17:35
Thanks Jordan.  It's strange to me that node would have different logic for how it processes a package based on how it was found.  I'm curious about the reasoning behind this.

**Comment by bradzacher** [comment] 2023-07-26 17:43
> I have since found module.createRequire(), which creates a new require function based on a specified path.

Ah that explains that then - if you were doing something like `path.join(workspacePath, 'node_modules', '@typescript-eslint/parser')` then yeah you end up in this weird situation and is why I couldn't reproduce it.

If you instead do `require.resolve('@typescript-eslint/parser', {path: [workspacePath]})` then node returns the `/dist/index.js` path and everything works as intended (in a pure commonjs environment).

[The `createRequire` route is what ESLint uses internally to load things as it's more "future proofed"](https://github.com/eslint/eslint/blob/853d32baa8934c08b59a738470b72522e1505f6f/lib/shared/relative-module-resolver.js#L34) which highlights why vscode-eslint worked whilst your extension didn't (because it used eslint to resolve the parser, which used createRequire)

**Comment by ljharb** [comment] 2023-07-26 17:43
If it's inside node_modules, it's a package; otherwise it's just a file. Conceptually they've always been distinct.

**Comment by bradzacher** [comment] 2023-07-26 17:51
I'm gonna close this as resolved - the usecases for dynamically constructing paths to our packages are already few and far between. Additionally as you noticed using `createRequire` is a much better solution as it relies on nodes internals.

So I still don't think us adding a `main` is a good thing.

**Closed by bradzacher** 2023-07-26 17:51 UTC
Labels: question, awaiting response, unable to repro
