### ISSUE TITLE
Bug: [consistent-type-imports] Angular dependency injection issue

### ISSUE THREAD

**Issue by sviat9440** [typescript-eslint/typescript-eslint#5960] opened 2022-11-10 10:46 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=PTAEAEBcGcFoEsDmA7A9gJwKYFgBQ8BbABw0lAG9QBlTdAN3gGNNQBfUAM3VQNAHIAdMBr0mmPgG48eEBBgIUGHPmKkKoAMI8SyTMjLsuPfuACGyRAFcANqfTBGSydNzgtq3foAU5VgEo8TAAPEnQyRltoaFAAFUxoSHcdPTJyPFBQIksAI2smUEdkBPRLRkgML3SMzPR4OlNIFmhaBmYALmoWsQAaKr91VjxB3CA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra0ipWpQC2xDtHyoMkRNGhTI4MAF8QaoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjoAHoizJ46IngCGqACL9YmNXl3Cwo9FIC+IM0A

### Repro Code

```typescript
// @ts-ignore
import { Service } from './Service';

// @ts-ignore
import { Component } from '@angular/core';

@Component({})
export class TestComponent {
  public constructor(
    private service: Service,
  ) { }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/consistent-type-imports": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "experimentalDecorators": true
  }
}
```

### Expected Result

No errors when type is used in constructor that decorated via any decorator from `@angular/core` (like @Injectable @Component @Directive @Pipe @NgModule)

### Actual Result

Import was auto replaced to 
`import { Service } from './Service';`
And angular build failed with error: `No suitable injection token for parameter {paramName} of class {className}.  Consider changing the type-only import to a regular import, or use the @Inject decorator to specify an injection token.`

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.42.1` |
| `@typescript-eslint/parser` | `5.42.1` |
| `TypeScript` | `4.8.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by sviat9440** [comment] 2022-11-10 11:04
Maybe it's worth adding an option to support Angular

**Comment by sviat9440** [comment] 2022-11-10 11:14
I suggest the 'framework' option:
```
type Framework = 'angular'; // maybe new ones will be needed in the future

interface Options {
  prefer?: "type-imports" | "no-type-imports";
  disallowTypeAnnotations?: boolean;
  fixStyle?: "separate-type-imports" | "inline-type-imports";
  framework?: Framework;
}
```

If 'framework' is set to 'angular', then need to ignore types in arguments of class constructor, decorated by any decorator from `@angular/core`.

**Comment by bradzacher** [comment] 2022-11-10 13:43
duplicate of #5468 - decorator metadata just messes the rule up because TS works differently depending on what version you're using.

**Closed by bradzacher** 2022-11-10 13:43 UTC
Labels: duplicate, package: eslint-plugin
