### ISSUE TITLE
Docs: Explain how to get around "not portable" TypeScript type errors

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7605] opened 2023-09-05 21:32 UTC
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Following up on #5032 -> #5036, it's still easy to get a dreaded _"The inferred type of '...' cannot be named without a reference to '.../node_modules/@typescript-eslint/utils/dist/ts-eslint/Rule.js'. This is likely not portable. A type annotation is necessary."_ TypeScript type error when using `ESLintUtils.RuleCreator`:

```ts
import { ESLintUtils } from "@typescript-eslint/utils";

export const createRule = ESLintUtils.RuleCreator((name) => `.../${name}.md`);
//           ~~~~~~~~~~
// The inferred type of 'createRule' cannot be named without a reference to
// '../../node_modules/@typescript-eslint/utils/dist/ts-eslint/Rule.js'.
// This is likely not portable. A type annotation is necessary.
```

How do we recommend third party packages do this?

Also mentioned by @Josh-Cena on the Discord: https://discord.com/channels/1026804805894672454/1130171307909202021/1130171307909202021. And stumbled onto (again) by me in https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/pull/88/commits/266093962bfdb14c0cbcd4cc2c90d79227b7f7aa.

Interestingly, DefinitelyTyped-tools doesn't seem to have this issue... https://github.com/microsoft/DefinitelyTyped-tools/blob/b6b22fc00eebbcfa26120cc314c3f7d2179106ba/packages/eslint-plugin/src/util.ts

I'd consider this issue to be a more specific subset of #5444.

### Affected URL(s)

https://typescript-eslint.io/developers/custom-rules

**Comment by bradzacher** [comment] 2023-09-05 22:09
This occurs when people ask TS to emit declarations and can be fixed by turning it off.

Though I don't know how to actually fix this from our side - how can you get TS to name the type?? Do we need to document that people must export it from the same place they export their rule creator?

**Comment by JoshuaKGoldberg** [comment] 2023-09-05 22:11
Maybe we can make a standalone type for ... well, `RuleCreator` is the name of the function, but what it returns?

**Comment by bradzacher** [comment] 2023-09-06 00:20
> Maybe we can make a standalone type for ... well, RuleCreator is the name of the function, but what it returns?

https://github.com/typescript-eslint/typescript-eslint/blob/8175224c46f562720e9ef9b1efbe54b33d4a423e/packages/utils/src/eslint-utils/RuleCreator.ts#L61-L64

We already have it - it returns a `RuleModule` which can easily be named by end users.

The problem is that people aren't importing their local rule creator from our module - they're importing it from their local module. So TS can't name the `RuleModule` type.

---

What I was saying is that I assume that this could be fixed like this by users:

```ts
export const createRule = ...;
export {RuleModule} from '@typescript-eslint/utils/ts-eslint';
```

As that would export the type from the same module as the function and thus TS could mutate the export during the emit without side-effects.

**Comment by bradzacher** [comment] 2023-09-06 00:22
The problem with your second edit is that you lose the options types.
It also doesn't fix the issue because TS still wants to generate types per file.

That fix would actually work if you added the import to every single rule file though!

**Comment by Josh-Cena** [comment] 2023-09-08 03:13
I feel like I've been away from serious TS coding for too long that I can't wrap my head around this error 😅

**Comment by bradzacher** [comment] 2023-09-08 03:18
@Josh-Cena this should help clarify why it happens:
https://github.com/typescript-eslint/typescript-eslint/blob/4908905e4ee2b533504fcba0c671aa869668df25/packages/eslint-plugin/rules.d.ts#L11-L34

**Comment by bradzacher** [comment] 2023-09-08 03:23
The fix is to make the source code add the required import - then TS can add the required name to that import and everything will work fine.

Hence a possible solution is to do something like document that the rule creator file should be this:
```ts
import { ESLintUtils } from "@typescript-eslint/utils/eslint-utils";

export const createRule = ESLintUtils.RuleCreator((name) => `.../${name}.md`);
export {RuleModule} from '@typescript-eslint/utils/ts-eslint';
```

So that when people call `createRule`, TS can just add the `RuleModule` import from their local module, rather than from the not imported ts-eslint module.
Maybe... IDK if it would actually work.

**Comment by antfu** [comment] 2023-09-23 07:59
This PR should fix it without actions on the userland: https://github.com/typescript-eslint/typescript-eslint/pull/7690 - Thanks to the existing discussions 😆

**Comment by JoshuaKGoldberg** [comment] 2023-09-23 14:21
If there's still documentation for steps folks should do in their code (e.g. taking on a full dependency on `@typescript-eslint/utils`), we can always re-open this issue or just take it on as part of #5444.

**Closed** 2023-09-23 14:21 UTC
Labels: documentation, accepting prs

**Comment by zanminkian** [comment] 2023-09-24 04:07
I have faced this issue for several weeks. My workaround is enabling `"stripInternal": true` in `tsconfig.json` and marking the exported rule `@internal`.
```ts
/**
 * @internal
 */
export const createRule = ESLintUtils.RuleCreator((name) => `.../${name}.md`);
```
