### ISSUE TITLE
[no-restricted-imports] Allow to ignore TS type-only imports 

### ISSUE THREAD

**Issue by DominikPalo** [typescript-eslint/typescript-eslint#3724] opened 2021-08-10 14:30 UTC
TypeScript 3.8 introduced a new feature called [Type-Only Imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export). Therefore would be great to implement also a TS version of the `no-restricted-imports` - `@typescript-eslint/no-restricted-imports` which would add an option to ignore type-only imports and apply the rule only for the standard imports.

**Example use-case**
We have a project containing TS files transpiled to Google Apps Script. That transpiler (called [Google CLASP](https://github.com/google/clasp)) doesn't support importing of modules outside the app script directory, therefore we would like to restrict developers from import such files. This could be achieved using `'no-restricted-imports': ["error", { "patterns": ["../*"] }]`. Unfortunately, this ESLint rule is also applied to type-only imports - which are perfectly compatible with the transpiler (because type-only imports are not used in runtime).

**What rule do you want to change?**
no-restricted-imports

**How will the change be implemented? (New option, new default behavior, etc.)?**
Have an option to specify if the rule is applied also to type-only import

**Please provide some example code that this change will affect:**

```js
import type { Foo } from '../helpers';
import { Bar}  from '../helpers';

```
Rule:
```
'no-restricted-imports': ["error", { "patterns": ["../*"] }]
```

**What does the rule currently do for this code?**
It shows error for both imports

**What will the rule do after it's changed?**
Optionally show error only for the `Bar` import

**Comment by bradzacher** [comment] 2021-08-10 17:11
Duplicate of #2661
Please use the search

**Closed by bradzacher** 2021-08-10 17:11 UTC
Labels: duplicate, package: eslint-plugin
