### ISSUE TITLE
[Doc] Wrong links in npm page

### ISSUE THREAD

**Issue by zhangciwu** [typescript-eslint/typescript-eslint#2756] opened 2020-11-12 03:17 UTC
https://www.npmjs.com/package/@typescript-eslint/eslint-plugin

All links in this page has a wrong href, for example:
`You can find our Getting Started docs here`: `https://github.com/typescript-eslint/typescript-eslint/docs/getting-started/linting/README.md` would get a 404 page

It would be right if click inside github page: `https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md`

Might be something to deal with relative urls

**Comment by bradzacher** [comment] 2020-11-12 03:47
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/2310

**Closed** 2020-11-12 03:47 UTC
Labels: duplicate
