### ISSUE TITLE
Bug: incorrect AST produced for nested namespaces

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#4966] opened 2022-05-12 20:37 UTC
This was forgotten when we worked around #2573

For `namespace foo { namespace bar {} }` we produce the following AST:
`TSModuleDeclaration[id = foo] > TSModuleBlock > TSModuleDeclaration[id = bar] > TSModuleBlock`

For `namespace foo.bar {}` produces the following AST:
`TSModuleDeclaration[id = foo] > TSModuleDeclaration[id = bar] > TSModuleBlock`

The AST we produce is driven by the AST TS produces - they emit the nested module declaration, so our code does as well.
Ultimately however is pretty incorrect and does not correctly represent the code as written.

Instead we should emit an `EntityName`, thus allowing `TSQualifiedName` in the `.id`:
`TSModuleDeclaration[id = foo.bar] > TSModuleBlock`

**Comment by armano2** [comment] 2022-05-14 05:26
i agree with this change, but this is not a bug 😸

**Comment by bradzacher** [comment] 2022-05-14 06:41
It is a bug because we never intended this to be the AST. Our types were wrong for the node because we didn't know TS emitted this weird AST!

**Comment by JoshuaKGoldberg** [comment] 2023-02-21 03:40
This has been merged into the `v6` branch and will be available in that major version.

**Closed by JoshuaKGoldberg** 2023-02-21 03:40 UTC
Labels: bug, breaking change, AST, accepting prs
