### ISSUE TITLE
Bug: Type inference error when using `tseslint.config()` with `eslint-plugin-react`

### ISSUE THREAD

**Issue by printfn** [typescript-eslint/typescript-eslint#8522] opened 2024-02-21 08:04 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Using `eslint-plugin-react` inside of the `tseslint.config()` function in `eslint.config.js` causes the following type error in VS Code:

```text
Argument of type '{ plugins: { react: { deprecatedRules: { [x: string]: any; [x: number]: any; [x: symbol]: any; }; rules: any; }; }; rules: { [x: string]: number; [x: number]: number; [x: symbol]: number; }; readonly languageOptions: any; } & { ...; }' is not assignable to parameter of type 'ConfigWithExtends'.
  Types of property 'plugins' are incompatible.
    Type '{ react: { deprecatedRules: { [x: string]: any; [x: number]: any; [x: symbol]: any; }; rules: any; }; }' is not assignable to type 'Plugins'.
      Property 'react' is incompatible with index signature.
        Object literal may only specify known properties, and 'deprecatedRules' does not exist in type 'Omit<Plugin, "configs">'.
```

`eslint.config.js`:

```javascript
// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintReact from 'eslint-plugin-react/configs/recommended.js';
import jsxRuntime from 'eslint-plugin-react/configs/jsx-runtime.js';

export default tseslint.config(
	eslint.configs.recommended,
	...tseslint.configs.recommended,
	eslintReact, // type error is on this line
	jsxRuntime,
	{
		settings: {
			react: {
				version: 'detect',
			},
		},
		languageOptions: {
			parserOptions: {
				project: ['./tsconfig.json', './tsconfig.node.json'],
			},
		},
	},
);

```

I'm not sure if this is a bug in `eslint-plugin-react` or `typescript-eslint`, but given that eslint still works correctly and this is purely a type error I opened an issue here.

### Reproduction Repository Link

https://github.com/printfn/tseslint-react-repro

### Repro Steps

1) Clone the repo
2) `npm install`
3) Open the repository in VS Code and open the `eslint.config.js` file
4) Notice that the line `eslintReact` has a type error

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.0.2` |
| `@typescript-eslint/parser`            | `7.0.2` |
| `@typescript-eslint/scope-manager`     | `7.0.2` |
| `@typescript-eslint/typescript-estree` | `7.0.2` |
| `@typescript-eslint/type-utils`        | `7.0.2` |
| `@typescript-eslint/utils`             | `7.0.2` |
| `TypeScript`                           | `5.3.3` |
| `ESLint`                               | `8.56.0` |
| `node`                                 | `21.6.2` |

**Comment by bradzacher** [comment] 2024-02-21 10:13
For some reason they export a `deprecatedRules` property on their plugin. It's been there for quite some time (>8y). Dunno why but that's neither here nor there. 🤷‍♂️ 

There's a weird thing happening. I can reproduce the error in your repro but I can't reproduce it [in the playground](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&target=7&useUnknownInCatchVariables=false&exactOptionalPropertyTypes=false&allowImportingTsExtensions=true&filetype=ts#code/CYUwxgNghgTiAEYD2A7AzgF3nKYMC54BvAKHngAcIBXAcwEt1CjsRcDj5QK4woMQwAErUIINISgoAngG5so8ZJnwAvmtlkFYifClytOYKgjT40FLWpRaIAPIUM9VLv2b1AMmJaLVm-cdnJj0ZTXIYRV1ScnIAIhw8AHpgejQqKGkAWhQoAFsQWMIUalyAIxAYMJj4tiSAKzQAD0yAaxBpQvhisoqquISMRIbmlCRM5Fz8lAxMgUaMUdA0Tu7yyq1+2sG4AEdqejhMuBRQGCOQDGoYFBWStb74RMT4ADo3l61Vd00SUEhYBAAM2oKDwQUQqEB9FoAAp3rBaIQAMKQ6EAdXoGAAFgBReYgE5oADaAF0AJSEABuSHowBIyBQUNhAzJPxI7I5nK53KevL5TxI-KFgqFfPgGGkFHEEIo9EE8EBMCQuXgAAEJVK0GAYPRHJlxBBGINqE4IGgRaKBZbeSQjRVAbgECjGejMbj8YT4CAPcA0PAAGLQDDOpkvEPQ7wxR4AKmjG3I0fgAEEIBAkAB3P3SJDUcVIeCxb0CE6xPTwNAXeBIQEQl20P1oei5ejQGB5+AAAyLBN9HYVSpV2JA8fgif+aEbYFrTLQHyjo5HiYAKljUvA13VqJgywzKQS5aCEGgsUgYDMsVJgO2sSAIBRWMBqGAEI+qPQ+E5UHOo3H54mOwBDSLl6jQUKeWCgA6ohYBgFZoIa0wvAyTIwtEP4xFCOiEESADksYxi8sE4SSAA0wHkN2hLYeRMQGkaSGovWLy8MqUygMAZF-vOsF0YhyHQrOLGTD2giceh5CkTRERYZG4kxDh6qSuI2q6jMvGDLAMAZLMSk4YQOEVEqMA4WJMSJlGCkaspOp6upiQMo2mAEjMVmZE2YFnmgenwAZMBGSZNGqKZCZqGSi7AU8IEUJefoYEg4Vcd6HkQSAUEQFgRI0WhZnzu86kMXWgngKxIkcTR5CYUo8C4fhiTRoRXmSVx5BBTR7w8fB9H8UxQlsYILy5FAFAwsh8AALwAHzwKh5WvG8yHBaO86VboNWJnVDXEYt5mhWS20xNlIVRit2F4et9VEU1cnhJEzCzeQllKVqNlqZ10yJJp2lWd5vn+ft84+YpmoqbZb2DA5qTFi5SlubkyVefphmngFzUxK1qPo+hJLAQBHaLok8aUb6AD8hCBvw4a0GGjFJn5GTuOydowA6z7wAACrAFYwAAshcUCyXVv4hSuCAgvQewIDk+RVjWQ6UJzFTfqOBPkFLICEJgOqWFUgsbMuN5lprjC0OuoDTPQgLSMb4oG3uMCNqgMs2wg0X24resq-AdsOygpPlhgWu0AzVnwAAMkgSAVhzbs80gj5iONWgAD6yVGusA0tACSjKnoNn4oHopQ5jBBuu1z7ZixLpim85FtmJi8DpjeBdc-QUCGgAXsbSs-p7Ub5BgUB+9HTjtwAPNHXO84PE0POQ6cA4mk-SnLDB7gXcxYEa+ZSPAOIAMpLnACBJofI4Jn3MRlyAMKbxrAfGyRVaBC4fsgi0ozpigFLwO-n8oA8VQydU4xAXlxbOgJc78HBFAIuJpnbyxjhXFA4tqC3nrmbJwlt1xYCbgScsFQ26d27ufZW58B5D0ICPIhE8FY8z5rPc+YD0LL1igbNe+DN7rmmDvAup8lykOjJfcg19-SngPqHI0MJSHiiLPfQOi0YhIBfugN+KAP4ZhQIon+h0oxEhaNw+AbRsw1j-pokkhAzFfznhoeMXxbTTHtI6dmSpnwTlPNPfmaEwH61FigiWXQ8gIGrAgngSA3FoFPErIRWg1byONjrWMet4Ai0Ng-SwNdzaW2tnLb24IQlyzCREqJHstB5NQH7I22sSBAKZizBA4dI4gDZq48QkTY7xwQN4pJOUIFQPzoXYuoTWnuLbHFX+-i0HV1pLXbBDc8Et0Ie3egXdLDRM9hQ4esBR4QAniM9pnjGHzx6cLA2wJQQDPGUWLSeAISgHgKUNMYAWizlKSIuARS2l+1vnI-2CiFQtgJEE+JlgyTjSmm4LQPiUlnJBGCR24z8gwFsPAfIE5-CvLMp7MCmBPkTm+WitAGLJGYGUNIJ+lU4l-ONmCyaIQDDHKFlnGsHYA5oL7EOAuDd8hSDYS7fZp5yzUAoPDPQJpqz0EaOsrQaBhXwyTOKqEjQ-ZFyQGIKQwclJhwjhWEQYgkQ4AEP6OFAyxrTS0AyO+9KyK0qmkIYqMBgBjyqbQJ+xqLnghTiCSCjBBCMJDo03VigAAiqVGCYnBGNYBgaQB6pAAatgRqTVBGAbo1FfM-ZIFKHUcAGAbHakTerbVTS40Jv4CAd18KAF2J+HU5x+8LxwGAJTK40DUD7wuE4Swfo0JEipS6ixEyNHWJqeyAN9BSiJ3ICnQsaAACssRgGzoAGyLunQWcQAAmAADAARgXUu8QAB2Nd8AZ1br3auw9aAd27pPde29AAOU956b17oAJwvo3W+ndX7Z07s3buv9F7N2buAz+gAzOBlARY-3GFyHB5ULxMQVFgWIP96YQClHTKeNoMAMNYZwzAPDyG4bgWeqpZYS7MPYdw4rFDWlHkFCXRRxwJ5MDgdvXOhicBON7u48gVMuagh8f3S8WwMGtJxXww+-jyGBCMfQ7JsTYTmwVlE9xsJjQOjKe43AQEYg8AaZeGgaQZQ1XGdM+ZiALxMOpmHTcZTy6XifWkMh0ENBQCiaPS8YA5bvMvCzTmozymfPHgBMAfIuRTw6fXf+vdYX0m0AC0aCAAWrJ+bptIKjcWL27sfS50zoIJOoek6JgrUAitgAY2h5juW335fcxgNLymCuqdSHVs936n3MRALYUCon30uay4NwL2bc2jZdZNszRcWv1dvUN1LfGd0vFKNCI0y3t2+f87Jlb7X1O7a2+FptUWYubZM0l87VnZu2dvBABz52luHZeKsCoy3d0vH25119AGPtTd2x9zDUAWj6fe01ubXX4ugeG1pWLkOQObpeEjGT83t3Q6e6j6HQWJu7cR8dwQp2YBw5+2jvHl3ce9f6xQZbEGYcZBpwxITVboNFjp8T79MH5iM8M-nFnXPrsWevZzjAhXpCghq0xvnIuMfw7QML3zqQcW1al6t9b0wVf-fq-Lr7Kugcg9Sirv4p5+Cnhy5Do3UnTdwYdSb+2LwxC0FwOz+Lu7nPAlTAF93EOSeNa96Nv3z2A+Y4+0H2XAHEeh5J5u2nkeOes9j7EQ0pRYiaBDqG0odBQ4gD3BAca01Z0IQwKWGdVlWOvUL8XgspeQZF7JKSLrqr1XVpDkiXAN5g2tvzh2hkvo8+vbbDOiB4aJQp5ICHHEYBBoADUKg+ynV1iDwC53AOXcAo9wDH3APfcA3d26d+7p35unfi-127oACw7+X+urjwDb2r+vwl2-e7N8P93dvh-O6n+Aa-0fj-J+usAYX5xZBjiBF6p5ar7w5gwDPhLhKRIjQATjvh56xDRadKV6xBl6j4hyQFXAwFapmo4HQEgCwFSjwGVaTiQ4TDRYoANBYFaoABS+8wa4Sk8xs3MccCAZqsQ7caWkOowMG6BrkjAkCo+darMy8MADg+cPaWg4Ag0-oiaVw4gfsh0tAaYpQ7c9qlw1wKqEcTeDwwwuhaqbA1aeixiIKtAg6ViphtiFEk+UAM+9sQQfsE+0+s+QQVQwwLSNgg0lSSWXWxQqYnhTQ-oWktAUwGAAAckEn4YHAEaIBAFUEnn7JIqUKSFUCAM2BgKGsgJbvQoPH5oPEYfoRaiVNMMUSYVUKABnrQFnjnn7OnpntnreBkX5KeHYCgCQSAPvDXvvGLoPGCGAEmCcB2oNObGAJnBOGgmgBURqrIW0ZISgAAKrqL-z8JdGzE2E4gAAabMOIQgmc3MOIkRS4SYocAA+luM0kqMFhgB2jAJSO+CAJsVUDsXsQcUcScWcZcRWIQc+HYICC0kgLcfaoCBUASM+PaikLwBgC8bIfMFpP6ICniMWD7DMRYekVoJVBzNiLEQkloA0MwWAKwZYOwaAH7IwUSSSbQGSSAEkeEnCfPM8GErQFpLkOiS4kgKyXkPXinIEYkVoGErcXiZYLydShkinI3iYfEUEYKTcbmmIhAKcJnLQKMHACSrCYQDCParQHiPeCnC6nXiSFUFpJYM8YQFKXMeQJErgcQUpH7H8XaVKFUHFG0KohaXoZUVoLBN1EIBHNkQcCKUHFoOmLACgB0SsbKiKuBIIF0T0S9I4T7IyYgG3iAJImCU4PkCofGGoVmn7K3mAO3p3kEN3qgL6FUPYuQESFAMACkPnO3ECVKGeHKLoAOpYqsZogzIKPhKqEzDkLnjEklOBFwOAK2JLEEmkPWo2oIJTLJNgc0TqBKHntul1rugAS6RAQuZiNIPvP4VwcjugdWICOgaGdcKPuQCHHGnUbeHnh2nbNuV1neYQhKLuYHBuVKPAFec0RAMMcAFIUEH6GakSF+Tnk-O8NYaSMad6VqnGjiNMETnniBTeSnEhT+ScP+S4O+QgHGmgParkVeGatQuPHhaeE6i6k-LBfBdIBNEcuKFqgAOLqHtxT6wBtxMYYUoAABClWnBBYR56BRgJgHQkO6Yi5yuWF8AjFWazFrFtWHFeeUlGhEALFOoclKi3FFYDenpVp3CCm9SklTFZos5h0fawK4plhhAilMlql7FKiFZWgYhCAcFjxSoKAERxl8Ypl+QFhg6lpNhQC5Ajl7MNADAKAniICzCS0qSFCL2QSlASoTZS5x4OYSpqK-AhZCCKAFAKo0Uzy-ggS0skCbY2YVwlAIVjAPcZCUY-aSWDwkVvi6ag8Lw5SBcYSiVZgyVogV4ecGVcsWVOVuALQ+VLVCogqJVbYVAdAFV+M8YLVFh9lQCQ5Z4I5-wcABV4guVCA5MwYjEc5DFhlaAs5BB05zajELwVlRljEElEheeMaEhZJig115VYVfMt5J1lMLwbMz1ni11AqbYZqd1f1D1YgEllFAcZgx1EWH1YNROoNig15uekNTa0N8N35cNYgCNv5HFgF8ADaUNZ1qFWNKiaA6N0oSNM5BNkQJFjqElHaGAXa9Yb1+NdYxZ7anaxsJN0FH5T5i5ENuN71Z1PN25tNW5L5e5-NzNoYQtYtb5DljizMU5ktAkIC+i7QPlyIV1nwctelziX1U1Bch09VEtTa040IrN6ADy3qYgV46YbooSz1lViYSxXMfottqYrAYJxwrMQ4ml0Jua0yG8N4BwptJsMI9ASOLwnYk1oVBUM4vWVBpUHYZIjtl83UHJeNyNjEnNacJyOUnihR-MsCQy41ZV+to1bYbAjYFQI5NRoVJsl4qKp4CAqUYJYIe4KZhZ1sIS0djAmKvc8YmyVC2yNCetoVhydVudpyL4YaKCAy3dz18V4SbSpujt8Azts+KZLcSW1c+m4Jh4wyS9oyv8jYGScsxihiQ4wd3U004dIALwT8HYsQPdKA0R+QiQeK7Sr9BQSdKd8YH9pufs1NZFSWT8QJxSMAtFjKwEqSPqs9+SNYz92g4gq9qS59uQW4WA5QmVcVBSBs0kCA2I-Ax9G9btueVxwE699sm95lO9qUe93teDigx9OSBs59Q4ZgcADATkJthSC93q1dEwa2MGNtdtcs+D61q9t9kdRVCCVxbY19HYz9UQo1SAhAz9oJ9DCAqgfYmQCCu9XtCAOGXVDyCAj9kCSAiQ+DX9sQHYv9UY+DHJQDzqIDxaQaYgoaUIcDqAtFAVulTi4hz1MhOdTKIUaICAdo5sqAPBZgyoDccsHYadfY59ioyoNsa42Oty5QfAVxOCeg1ItI5oXEIcyEhoeArtdtaqV4SjNsRDF468OEWAwqhR8ol98jWd7YBmRDad8A0gFwq9mcGAOEfolIyyV44y+jEJBDN4mllTpdoVfoWTUAOTEiRojcqADTegYAESzsOMsd0IfYbVFQS5IS-MiDCyXoIzNA0CGS-MnTWA3UdjMQRIz9KYbcrZSWg6dgWRE8z1T8sQadsQPj2t-jDSTM2NEVk9S0SY8AnF2lBclzaC3CKQH41sFs3CCECA3U5t64foPBGY-UM11VSA2cGLlMyZUDXE0LFY95SV-hjAyL1zJsaLDdJ46YEyVxV4KQRKTGIQV4QKTGwEftbd0onVqVWDAcg18oDdHyMZwAkdYibYDuTuEIcM0Ca2hoEoD9bKIAeMXEa4IAew9Alzzk7Yj9p5NwfYDdHYDoZoOrOLXohrxr0wprsQ-FtjwEqokESz6UfFgIx5hLMQMrZ4KxHLwaqQtWYbMJRryh+A58KcGdFNdYLw0t0gcbxtibUtotO5SWabfl9lgV8t+locUgfgtg4LhtkLDVI1ISOISI3Mp8Ne7YUZyUq93MGQJj9KPTbAbYYdEdD94eSdVYbYI1vbd9D9c6P9wEdNLrIBHGfYMjcs0W24vAJrzbsrXs7hX4HrXr0EBYs7ReAbdhbhThFShArhDhm7NhFL6EwxVY42tyaQ4Adc1sNZdZQQ7cd7txbCRDorV4WDr7LT+Yq8hl5YyAH5j4cRheJCf4l8uZSlHJF1h1mtwTwEt7GT9zqAg84aNzUdCsMIZIfYA8J4V4gq-MijCsCrKz0w+HhHFwxHq9nrqU3rGAOMAEEUzwWI9NFAEgTwDA2I1ApQDEuQiQdkG1x8wEuw+wcAMIBkaQx8OEYUXEuMh7iCXMWyMcE9ITULBc6H5YUo1W2SNztZEaUTueyi0hNTWAAI8sE48oQrzWZg4yhSdCKDBsUAIzLYtWz8Fn1n18Zw3AIkiEKnfn2N6nXM2Nmn0DBsIcIS9B7nUA8Zqk5YUBrMyAoAq9bMkcjYPLCL0o1nj9mB87gqErb7pnoHL0AKOgD9KBccigNj5de8dbDbFXqBkQ00B83Me0vLnY-zrEqAtBRXbYKIkwqAjBlXyD27TH0ErHur6EkUMjtjDQlrJwnYA0S343hT6ENXaB7HDXtjYA63K0wEvXI3NBZuOUynMH8YNpRBGxhAjpXR+bdFH5SJYg+8+neeLqXWMIMI2J-AWIFhtqDycLrIwLCtrMHlKHlLBcrmTscH8s9NFQFt9L74jLCCK0lnCCWLUm+S97WAv7egIq1ccU-TNYow+P+nFscoHEWPjE2LunQ0b4K8O87tGPPVN4f7Zg+gVYQ4bTLNOPjs6HjzFUgKHJMIr33RH3KcEv734ApIRpkX0PegWWcP6hCPCmyPJwqPDN6PovmPcs2PbaOneP5YJ4xj5PhPVAjnSApPXQSAFPT7UIoktP-PRvn7ualvhozPegrPev7P8opQZgK0wv64qpTdHJMv+nmJUPN7xvtxtYWHKCGSFY9NHNrAIBYz+YrL8AcXIziXjg9r2P8oMjUHayKnvg1gZbxNKRJblfAQ0hivsf7vtylqUA2HJsKfDNfocAGf7YcspfJsH9IfheFQoXhAki8tEX8YRtaHJvrf7fZYasmQuXaVIqXdCDC9assU+YiD6HfdOUaIzcnYK0fYa4j7Bn1PT8PtLsgTyvwSKA1c8XnnPLTnBs7P1swfwXgTw8gTjfOUOIboaurvF07z8k+JsRRh8n2Q0duuijSOBgA-rQCiOccP0KeGAj8wvuKPFFqfQNhqwnYpzP6twkbD3ITmczRgMBFHb30euz9L+u-T+rWNJ2V3KMP-RgBBkusYDZeusBj45RZ+8fUASw0xZ08TaDjVeof3wTWtRefYQVB2GhBqlxAlrNaufyp7O9r+SDEOubVxZrUhKeTNvtABf5Ac3+6VVcBkk-6MDA2kQQBpED-4hQeBHvPgRkiX4r9ooBwFATWGEL9JwQhDfHmbzFYIAn+ughOOMh4JIN9+F8a7uzW7QOlwh9YJ7i3hpgq8zUlMaPs9ydCMQgSamXimkI6xjxKYtMWHLRViF1gJeeeHISrxTiUxMhFYBmE8AADEyXW0m2zX6WAliQgUOGNA+pytYIA0IaOyCWpYAiA9iIAA).

I'm not sure why TS is erroring on this.
The assignment is completely valid based on structural typing.

Filed an upstream issue:
https://github.com/microsoft/TypeScript/issues/57460

**Comment by bradzacher** [comment] 2024-02-21 22:40
Filed https://github.com/jsx-eslint/eslint-plugin-react/pull/3694 which should fix a flat config bug and also fix this type issue.

**Comment by bradzacher** [comment] 2024-02-21 22:41
Closing as there's nothing we can do about this:
1) it's a confirmed bug in TS's inference for untyped modules and not an issue with our types
2) it can be improved and fixed by some minimal annotations to the react plugin

**Closed** 2024-02-21 22:42 UTC
Labels: bug, external, blocked by external API
