### ISSUE TITLE
Bug: consistent-return not compatible with switch-exhaustiveness-check

### ISSUE THREAD

**Issue by ST-DDT** [typescript-eslint/typescript-eslint#8577] opened 2024-02-29 13:25 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=GYVwdgxgLglg9mABAgwggznANgUwDJwDmAFFAJ4AOOAXIgOQCGdAPnQEYt0R0CUtYIALZscAJ0QBvALAAoRInQB3GFAgALRKUo4ek2fPkQG6HPSbV9B%2BaJxQQopAEYA3JcPHT7OhblXENuwdEACZXX3cTem4fP39beyQAZjD5AF9ZVKA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1oifLGhN0URNGgdokcGAC%2BAGkWRkI-MwDmqDFmyQAVsgAmHMpMPYoAWw5nEkyEVLIK1fAttLFfpSA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTolHoAebANOBqR4sACYBXDACVOsVBILF2kIuPSRBNKKMkYVnbn01DaJPJmTQ2lCxPRbhagKLxkNsHYemoY9NFRGeiUidi9HMwtkRABJIjwsInpUMMx7CLAAekywABUAC050MEZiuCIAM2QmEjASRH9kKuhk1ABPMArYTDAAQgAjCTQxEqIR-PoAN2K8WDB%2B4sx0acwEkeQiT0LPEnKqpgA6QeGDgCsSYh9IEgBraIAZZH6AYULoG9T0q9bYAHcAZTa8UKBGgABF0BV6FI8DEkN08GRbGlvNpIEsLqhpgApC5EACy4ikGmR9iEAF9HJBeAEJH52ABtK5qPwAfV0xLIGUgYmQ5hM2myYCWAEchksRl0enhtng2g0xLBoML0IE1p5OIiwMQwPB6NBsP8wABiABMpoAHAAGK4JcyZXaWfAkTL0FCK6CZBJISBCAC6IHJQA&tokens=false

### Repro Code

```TypeScript
function onConsoleLog(type: 'a'|'b'|'c'): number {
  switch (type) {
    case 'a':
      return 1;
    case 'b':
      return 2;
    case 'c':
      return 3;
  }
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/consistent-return": "error"
  },
  "settings": {
    "jsdoc": {
      "mode": "typescript"
    }
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "node",
    "module": "esnext",
    "strict": true,
    "noEmit": true,
    "declaration": true,
    "stripInternal": true,
    // These are configs specifically for !build and have to be reverted in the tsconfig.build.json
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true
  }
}
```

### Expected Result

No error.

### Actual Result

Expected to return a value at the end of function 'onConsoleLog'. 1:10 - 1:22

### Additional Info

https://typescript-eslint.io/rules/switch-exhaustiveness-check/

**Comment by bradzacher** [comment] 2024-02-29 18:51
`consistent-return` doesn't work with or without the rule for switches because it's not type-aware so it cannot tell that a switch is exhaustive.

In general we recommend not using `consistent-return` because it is limited in what it can do. We recommend not using it because the errors it's trying to catch are covered by TS's type checking and control flow analysis.

We are not looking to extend the rule.
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/4510

**Closed by bradzacher** 2024-02-29 18:51 UTC
Labels: bug, package: eslint-plugin, triage
