### ISSUE TITLE
[@typescript-eslint/no-unused-vars] produces error in 4.14.0

### ISSUE THREAD

**Issue by sfabriece** [typescript-eslint/typescript-eslint#2950] opened 2021-01-19 20:32 UTC
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Working code (4.13.0): https://github.com/sfabriece/typescript-eslint-repro/tree/old
Broken code (4.14.0): https://github.com/sfabriece/typescript-eslint-repro/tree/main

Instructions in both branches: 
```sh
npm install
npm run lint
```

tsconfig in repro repo

debug output
[lint-report.txt](https://github.com/typescript-eslint/typescript-eslint/files/5838446/lint-report.txt)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.14.0 `|
| `@typescript-eslint/parser`        | `4.14.0` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.18.0` |
| `node`                             | `15.5.1` |

**Comment by bradzacher** [comment] 2021-01-19 20:34
Duplicate of #2941, #2942, #2945

Fixed in #2943

***Please use the search next time.***

**Closed by bradzacher** 2021-01-19 20:34 UTC
Labels: duplicate, package: eslint-plugin

**Comment by sfabriece** [comment] 2021-01-19 21:56
@bradzacher it's not always easy to describe the problem. Without knowing the internals of the project it's hard to know if the other issues are related the one I'm experiencing.  This is one of those cases.😄
