### ISSUE TITLE
[parser] Can't use @typescript-eslint/parser in shareable configs.

### ISSUE THREAD

**Issue by SevenOutman** [typescript-eslint/typescript-eslint#2025] opened 2020-05-14 09:38 UTC
I used `@typescript-eslint/parser` along with `@typescript-eslint/eslint-plugin` in my sharable config like this:
```json
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"]
}
```

According to [ESLint documentation](https://eslint.org/docs/developer-guide/shareable-configs), third-party parsers should be listed as `dependencies`, so I did as instructed. But when I use my shareable config, ESLint throws an error going 
```
Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc » @hypers/eslint-config': Cannot find module 'typescript';
```
It seems that the parser is looking for `typescript` in my shareable config's dependencies, which is not reasonable. My shareable config should not have a typescript dependency as the version may differ from the project who uses it.

I'm not sure whether this is an issue with ESLint's loading mechanism or this parser itself.

**Comment by glen-84** [comment] 2020-05-14 15:40
Are you using `npm link` to install it locally, or is your package installed via a registry?

I also have this issue when installing locally, and I end up having to run something like this in the shareable config in order to avoid errors when running ESLint:

```sh
npm install eslint@6.8.0 typescript@3.8.3 --no-save
```

This might be related to #828. I'm not sure if adding the `typescript` peer dependency to the `parser` package would solve this problem.

**Comment by bradzacher** [comment] 2020-05-14 16:36
Our tooling just does `require("typescript")` - there's no wizardry there.
If it can't find typescript it's likely something to do with your local setup as it should "just work".

We have typescript listed as a peer dependency on the parser as well.

**Comment by glen-84** [comment] 2020-05-14 17:37
> We have typescript listed as a peer dependency on the parser as well.

I don't see it [here](https://github.com/typescript-eslint/typescript-eslint/blob/1d3a5ce20cbbc39672a78f744821a6cff6c96d5b/packages/parser/package.json#L41).

Listing it in `peerDependenciesMeta` doesn't automatically make it a peer dependency, does it?

**Comment by bradzacher** [comment] 2020-05-14 17:40
Ah sorry, It's not actually listed there.
It actually probably should be.

`parser` doesn't directly use typescript, but it's listed as an optional peer dependency of `typescript-estree`
https://github.com/typescript-eslint/typescript-eslint/blob/1d3a5ce20cbbc39672a78f744821a6cff6c96d5b/packages/typescript-estree/package.json#L65-L69
and of `eslint-plugin`
https://github.com/typescript-eslint/typescript-eslint/blob/1d3a5ce20cbbc39672a78f744821a6cff6c96d5b/packages/eslint-plugin/package.json#L60-L64

So the systems like yarn should be able to pick it up (I think - I don't know how pnp and such actually work).

**Comment by glen-84** [comment] 2020-05-14 17:50
I thought that `peerDependenciesMeta` would just apply metadata to existing peer dependencies. If the peer dependency is not listed, is it actually doing anything?

A reminder about [your comment here](https://github.com/typescript-eslint/typescript-eslint/issues/828#issuecomment-519974952):

> IIRC yarn supports the notion of optional peer dependencies, but NPM doesn't. The plan is to add the deps back in using that notation when both tools support it.

npm has supported `peerDependenciesMeta` since v6.11.0.

**Comment by bradzacher** [comment] 2020-05-14 18:02
> I thought that peerDependenciesMeta would just apply metadata to existing peer dependencies. If the peer dependency is not listed, is it actually doing anything?

A core maintainer of yarn added it to the parser (#1327), so I assume it "just works".
I don't actually know - but people stopped complaining about pnp not working when we had it in every package so I think it works that way 🤷‍♂️
IDK if npm works the same way though...

NPM does have support now! I'm not sure how widespread v6 is.
But 6.11.0 was released [1 Aug 19](https://npm.community/t/release-6-11-0/9572), so it's probably long enough to add it back in.

**Comment by toddbluhm** [comment] 2020-05-14 19:23
A user of my project just ran into this issue as well. I was able to reproduce it successfully. 

In my case, the user was executing my tool (which uses a shared config) using `npx` without installing the tool locally (allowing `npx` to do the installation). 

Here is the issue for more info: https://github.com/toddbluhm/ts-standard/issues/35

I'm not sure where `npx` installs my tool (I could not find it in my global node_modules or in my local one), but where ever it gets installed, it cannot find the local install of `typescript`. This may not be an issue with `@typescript-eslint/parser`, but rather an `npm` install location issue.  Just providing some additional info and use cases.

**Comment by bradzacher** [comment] 2020-05-14 19:33
As mentioned - we just `require('typescript')` - so it's up to node as to how it resolves that.

If your user is doing a global install and run via `npx` (however that works), then I'd assume that they also need to install `typescript` into the same location.

**Comment by Raynos** [comment] 2020-05-22 10:38
eslint has a feature for this use case called `--resolve-plugins-relative-to`

This PR fixes it. https://github.com/eslint/eslint/pull/13234

The problem is that eslint itself has a `--resolve-plugins-relative-to` flag but parsers are not resolved relative.

I don't think this solves the problem of "Cannot require typescript" but it does allow for shareable configs.

**Comment by bradzacher** [comment] 2020-05-22 17:36
I'm going to close this as this is a user installation issue.
Nothing to action from our side.

**Closed by bradzacher** 2020-05-22 17:36 UTC
Labels: awaiting response, package: parser
