### ISSUE TITLE
Bug: AST-Spec has wrong parent types for MethodDefinition Nodes and others

### ISSUE THREAD

**Issue by SebastianWendorf** [typescript-eslint/typescript-eslint#9792] opened 2024-08-14 14:01 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### Repro Code

```TypeScript
// ES-Lint is used for its parsing capabilities here, to parse external code and analyse it using the provided AST data

import { Node } from "@typescript-eslint/types/dist/generated/ast-spec";
import { AST_NODE_TYPES } from "@typescript-eslint/utils";

let node: Node;

// obtain AST node

if ((node.type === AST_NODE_TYPES.MethodDefinition ||
     node.type === AST_NODE_TYPES.TSAbstractMethodDefinition ||
     node.type === AST_NODE_TYPES.TSMethodSignature) &&
    !node.computed &&
    !!node.parent &&
    (node.parent.type === AST_NODE_TYPES.ClassDeclaration || node.parent.type === AST_NODE_TYPES.TSInterfaceDeclaration)) { ... }
```

### tsconfig

```jsonc
{
    "include": ["./src/**/*"],
    "compilerOptions": {
        "target": "ESNext",
        "experimentalDecorators": true,
         "module": "Node16",
         "moduleResolution": "node16",
         "paths": {
             "@typescript-eslint/types/dist/generated/ast-spec": ["./node_modules/@typescript-eslint/types/dist/generated/ast-spec"]
         },
        "resolveJsonModule": true,
        "allowJs": true,
        "outDir": "dist",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitOverride": true,
        "skipLibCheck": true
    }
}
```

### Expected Result

The code compiles and the check works as expected.

### Actual Result

TypeScript reports the following compile error: `This comparison appears to be unintentional because the types 'AST_NODE_TYPES.ClassBody | AST_NODE_TYPES.TSInterfaceBody | AST_NODE_TYPES.TSTypeLiteral' and 'AST_NODE_TYPES.ClassDeclaration' have no overlap.`

When changing the comparison code the suggested types and debugging to the location in the code during execution, the runtime types match the original version. There's an obvious discrepancy between the runtime types and the types defined for TypeScript. This bug only occurred after upgrading from 7.x to 8.x.

### Additional Info

The issue seems to be that @typescript-eslint/types/dist/ts-estree.d.ts seems to provide the wrong type information, e.g.:

interface MethodDefinitionNonComputedName {
        parent: TSESTree.ClassBody;
}

See also [here](https://github.com/jqassistant-plugin/jqassistant-typescript-plugin/blob/048c76098d52078764a5098718ba5479f483fc6a/typescript/src/core/processors/class-like-declaration.processor.ts#L40) for the original source code

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.1.0` |
| `@typescript-eslint/parser`            | `8.1.0` |
| `@typescript-eslint/typescript-estree` | `8.1.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `9.9.0` |
| `node`                                 | `22.3.0` |

**Comment by Josh-Cena** [comment] 2024-08-14 14:04
Do you have a sample AST to prove it's wrong? Try

```ts
class X {
  foo(): void {}
}
```

It produces `ClassDeclaration > ClassBody > MethodDefinition`.

**Comment by bradzacher** [comment] 2024-08-14 14:16
Yeah you're expecting that the parent is a ClassDeclaration. But the AST structure is and always has been a ClassBody node around the class members.

This is what the error is telling you.

If you happen to have a repro of the structure you're describing - happy to investigate. But for now closing as a misunderstanding.

**Closed** 2024-08-14 14:16 UTC
Labels: bug, working as intended, fix: user error

**Comment by SebastianWendorf** [comment] 2024-08-14 14:18
I ran it on this code:
```
class CustomClass {
    public x: number;
    public y: number;

    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }
}
```

When I  debug to the location in the code and look a the parsed AST node I get this:
![image](https://github.com/user-attachments/assets/cdc75018-867d-4901-9616-14ed67fa11c6)

**Comment by SebastianWendorf** [comment] 2024-08-14 14:20
May this be an exception with constructors?

**Comment by Josh-Cena** [comment] 2024-08-14 14:28
@SebastianWendorf Can you reproduce this in our playground? I can't. The AST shape you posted also doesn't make much sense because `node.parent` doesn't actually contain `node`?

**Comment by bradzacher** [comment] 2024-08-14 21:26
The AST you screnshotted is correct.... The ClassDeclaration has a `.body` property which is a ClassBody and on that will be a `.members` property which contains the members.

So the AST types are exactly describing the value you're seeing.

**Comment by bradzacher** [comment] 2024-08-14 21:28
You need to provide us with a reproduction.
A screenshot is not useful to us - we can't reproduce a screenshot.

Either use the playground to reproduce it https://typescript-eslint.io/play/

Or create a new github repo with the code required to reproduce your state.

**Comment by SebastianWendorf** [comment] 2024-08-15 12:06
It turns out the fault was on my side, indeed. The parent property of various node objects got reset to different values during the execution of the tool, overriding the original values provided by TS-ESLint.

Thank you for helping out!
