### ISSUE TITLE
Bug: Problem with no-unnecessary-condition rule

### ISSUE THREAD

**Issue by dfantonio** [typescript-eslint/typescript-eslint#8272] opened 2024-01-19 13:18 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Hello guys. I recently implemented the rule `no-unnecessary-condition` and it's been great so far.

But today I ran into a situation that I don't think the code is wrong:
```typescript
function demo() {
    const array = [{}, {}, {}];
    const item = array[9];

    // ERROR: Unnecessary conditional, value is always truthy. eslint[@typescript-eslint/no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition)
    if (item) {
      // Do something
    }
  }
```

I think it's proper for me to test whether an item is defined, but according to the plugin the variable `item` is always defined, so it's not necessary to verify it. I'm not sure if there is a better way to type this kind of situation or if it's a problem with the plugin.
Can someone help?

### Reproduction Repository Link

no need for repo

### Repro Steps

Just paste the code into a repo with the `no-unnecessary-condition` enabled.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.62.0` |
| `@typescript-eslint/parser`            | `5.62.0` |
| `@typescript-eslint/scope-manager`     | `5.62.0` |
| `@typescript-eslint/typescript-estree` | `5.62.0` |
| `@typescript-eslint/type-utils`        | `5.62.0` |
| `@typescript-eslint/utils`             | `5.62.0` |
| `TypeScript`                           | `4.6.3` |
| `ESLint`                               | `8.52.0` |
| `node`                                 | `18.16.1` |

**Comment by bradzacher** [comment] 2024-01-19 14:05
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/7505, https://github.com/typescript-eslint/typescript-eslint/issues/7118, https://github.com/typescript-eslint/typescript-eslint/issues/7086, https://github.com/typescript-eslint/typescript-eslint/issues/5225, https://github.com/typescript-eslint/typescript-eslint/issues/2883 

See the [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) compiler option.

The rule is powered by types.
Withe the option turned off - the types say the variable `item` is of type `T`. So the rule reports.
With the option turned on - the types would say the variable `item` is of type `T | undefined`. So the rule would not report.

**Closed by bradzacher** 2024-01-19 14:05 UTC
Labels: bug, triage
