### ISSUE TITLE
parserOptions slow down linting significantly

### ISSUE THREAD

**Issue by Luixo** [typescript-eslint/typescript-eslint#319] opened 2019-02-25 17:07 UTC
I am trying to migrate gradually from tslint to typescript-eslint. On my attempt to incorporate `@typescript-eslint/tslint/config` the linting became extremly slow. Fiddling around with the configuration file, I found out that the problem is in the `parserOptions` property.
Mine looks quite minimalistic:
```
parserOptions: {
    project: 'tsconfig.json'
}
```
I run ESLint several times with and without `parserOptions` and benchmarked the timings (based on 10 runs):

| Linter configuration                                   | Time |
| ----------------------------------------- | ------- |
| ESLint with parserOptions | 15s |
| ESLint without parserOptions | 3s |

I'm not sure if that much of a slowdown is unevitable or it's just a malconfiguration of some sort.

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin-tslint` | `1.4.1` |
| `@typescript-eslint/parser`               | `1.4.0` |
| `TypeScript`                              | `3.3.3` |
| `ESLint`                                  | `5.14.1` |
| `node`                                    | `8.9.4` |
| `npm`                                     | `5.8.0` |

**Comment by OCJvanDijk** [comment] 2019-02-26 09:41
Duplicate of #243 I think

**Comment by armano2** [comment] 2019-02-26 23:35
Duplicate of #243

**Closed** 2019-02-26 23:36 UTC
Labels: triage

**Comment by bradzacher** [comment] 2019-03-04 20:13
It's a known issue because of eslint runs each file isolated, so we're currently paying the initialisation cost of the type checker in every single file (which is slow and means a lot of duplicated work).

Tracked in #134, #243
