### ISSUE TITLE
[switch-exhaustiveness-check] ban the default case to enforce all cases are handled and prevent accidental mishandling of new cases

### ISSUE THREAD

**Issue by OliverJAsh** [typescript-eslint/typescript-eslint#3616] opened 2021-07-07 11:27 UTC
I frequently see code like this:

```ts
type MyUnion = 'a' | 'b';

declare const myUnion: MyUnion;

const f1 = () => (myUnion === 'a' ? 'a' : 'b');

f1('a') // 'a'
f1('b') // 'b'
```

The logic in `f1` makes an assumption: if `myUnion` is not `a`, it must be `b`.

Later on, someone might update the `MyUnion` type and this assumption will breakdown:

```diff
-type MyUnion = 'a' | 'b';
+type MyUnion = 'a' | 'b' | 'c';
```

The runtime behaviour is clearly incorrect, yet TypeScript will not error to remind us that we need to update the logic in `f1`:

```ts
f1('a') // 'a'
f1('b') // 'b'
f1('c') // 'b' ❌
```

This problem is not specific to the ternary operator but also `if` and `switch` statements:

```ts
const f2 = () => {
    if (myUnion === 'a') {
        return 'a';
    } else {
        return 'b';
    }
};

const f3 = () => {
    switch (myUnion) {
        case 'a':
            return 'a';
        default:
            return 'b';
    }
};
```

As we can see, it is not safe to make assumptions about the value that reaches the `else`/`default` case because it can change.

Instead we need to explicitly specify all cases:

```ts
import assertNever from 'assert-never';

type MyUnion = 'a' | 'b';

declare const myUnion: MyUnion;

const f2 = () => {
    if (myUnion === 'a') {
        return 'a';
    } else if (myUnion === 'b') {
        return 'b';
    } else {
        assertNever(myUnion);
    }
};

const f3 = () => {
    switch (myUnion) {
        case 'a':
            return 'a';
        case 'b':
            return 'b';
    }
};

const f3b = () => {
    switch (myUnion) {
        case 'a':
            return 'a';
        case 'b':
            return 'b';
        default:
            assertNever(myUnion);
    }
};
```

This way, when the type is eventually widened, TypeScript will generate a type error so we're reminded that we need to update our code:

```ts
import assertNever from 'assert-never';

type MyUnion = 'a' | 'b' | 'c';

declare const myUnion: MyUnion;

const f2 = () => {
    if (myUnion === 'a') {
        return 'a';
    } else if (myUnion === 'b') {
        return 'b';
    } else {
        // Argument of type 'string' is not assignable to parameter of type 'never'.
        assertNever(myUnion);
    }
};

// @noImplicitReturns: true
// Not all code paths return a value.
const f3 = () => {
    switch (myUnion) {
        case 'a':
            return 'a';
        case 'b':
            return 'b';
    }
};

const f3b = () => {
    switch (myUnion) {
        case 'a':
            return 'a';
        case 'b':
            return 'b';
        default:
            // Argument of type 'string' is not assignable to parameter of type 'never'.
            assertNever(myUnion);
    }
};
```

I would like to propose a rule that enforces this. The rule would report an error inside a ternary or `if`/`switch` statement if we're switching over a union type (except `boolean`) and we have a fallback case (`else`/`default`). The fix would be to explicitly specify all cases.

I'm really not sure what we would call it.

WDYT?

**Comment by bradzacher** [comment] 2021-07-07 21:31
Existing rule that is _somewhat_ related to this request - [`switch-exhaustiveness-check`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md)

---

For `switch`es it's definitely easy to parse, understand, and report against.
Switches are unambiguous in their subject and the cases that are checked - so it's easy to see.

When paired with `switch-exhaustiveness-check` it would allow you to easily ensure all switches are always guaranteed to be exhaustive!

However `if`s are a lot more tricky.
Solving for `if`'s is a "hard problem"™ to solve because they support arbitrary logic that can be in weird combinations and orderings, and can be interleaved with other checks.

For example
```ts
type MyUnion = 'a' | 'b' | 'c';

declare const myUnion: MyUnion;
if (myUnion === 'a' || myUnion === 'b') {
  // ...
} else {
  // ...
}

if (myUnion !== 'b' && myUnion !== 'c') {
  // ...
} else {
  // ...
}

if (myUnion === 'a' && otherCondition === 'someValue') {
  // ...
} else if ((myUnion === 'b' || myUnion === 'c') && otherCondition === 'other') {
  // ...
}
```

**Comment by OliverJAsh** [comment] 2021-07-07 21:55
TS seems to understand the control flow and narrow the type, so I was hoping we could benefit from this information in a lint rule—rather than trying to infer it for ourselves.

```ts
type MyUnion = 'a' | 'b' | 'c';

declare const myUnion: MyUnion;
if (myUnion === 'a' || myUnion === 'b') {
  // ...
} else {
  myUnion; // TS knows this is `'c'`
}

if (myUnion !== 'b' && myUnion !== 'c') {
  // ...
} else {
    myUnion; // TS knows this is `'b' | 'c'`
}

declare const otherCondition: 'someValue' | 'other' | 'foo'

if (myUnion === 'a' && otherCondition === 'someValue') {
  // ...
} else if ((myUnion === 'b' || myUnion === 'c') && otherCondition === 'other') {
    myUnion; // TS knows this is `'b' | 'c'`
}
```

Is that possible?

**Comment by OliverJAsh** [comment] 2021-07-07 21:56
Ah I think I see what you're saying now, my bad!

**Comment by bradzacher** [comment] 2021-07-07 22:08
yeah the problem isn't know what type the thing is - we can definitely do that whenever we've got the identifier in the code.

The problems are:

(1) an `if` can have multiple things as its subject - so it's really difficult for static analysis to handle this.
Eg the last case I listed - what if `otherCondition` is also a union type? Would it complain about both?

(2) I don't believe that there's an easy way for us to speculatively ask TS things at certain points in the code. Eg "hey TS, we have an `else` block - tell us type of this identifier within this block based on the control-flow".

(3) Because ifs are so flexible, it's really hard to understand developer intent or provide strong lint guidance.

For example:
```ts
declare const myUnion: 'a' | 'b' | 'c';
if (myUnion === 'a') {
 // ..
} else {
 // ..
}
```
Is this a bad `if`? Should it instead be listing `else if (myUnion === 'b' || myUnion === 'c')`?
What about if there are `n` members of the union, and only 1/2 of them are checked?
What do you do if there are negative matchers?

The logic and number of cases sort of explodes every quickly for `if`s.

---

But switch/cases are very simple in structure and are thus easy to deal with :)

**Comment by OliverJAsh** [comment] 2021-07-08 11:50
That makes sense, thanks for explaining.

I guess for switches it could be as simple as banning `default`, in combination with `switch-exhaustiveness-check`?

**Comment by bradzacher** [comment] 2021-07-08 16:58
I'd be happy to see an option in `switch-exhaustiveness-check` which bans `default`

**Comment by k-funk** [comment] 2021-07-23 00:18
Similarly, I'd like an option to simultaneously allow `default` AND require all cases on a switch.

```
const HandledErrorCodes = [1,2,3]
type HandledErrorCodesType = typeof HandledErrorCodes[number] // 1 | 2 | 3
...
async foo() {
  try {
    await ApiCall()
  } catch (err) { 
    If (!HandledErrorCodes.includes(err)) { Sentry.captureException() } // if we got an unknown error, it'll be reported
    this.setState({ err })
  }
}

render() {
  switch (this.state.err) { 
    case 1: return 'Error 1'
    case 2: return 'Error 2'
    // case 3 missing. linter warning wanted
    default: return 'whoops' // i do want a default as a catchall, for unknown errors
  }
}
```

**Comment by JoshuaKGoldberg** [comment] 2021-10-31 21:17
A counterexample to banning `default` altogether is when the value isn't a finite set (i.e. isn't a union of literals). There's no way to enforce types such as `string` with infinite members are handled before a `default`:

```ts
function test(value: string) {
  switch(value) {
    case 'apple': return 0;
    case 'banana': return -1;
    default: return -1;
  }
}
```

Banning `default` for _all_ `switch` statements, even those with where it's not possible to hit all `case`s, seems a little harsh to me. Suggestion: ✔️ on this discussion for adding an option to ban `default`s -- but only for `switch`es that act on a union of literals?

**Comment by OliverJAsh** [comment] 2021-11-01 11:26
@k-funk Isn't that https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md?

**Comment by k-funk** [comment] 2021-11-07 20:28
> @k-funk Isn't that https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md?

It doesn't appear so. The difference is that I am looking for exhaustive AND an optional `default`. That rule seems to turn off exhaustiveness once `default` is used.

**Comment by Josh-Cena** [comment] 2023-03-18 23:10
So to summarize. Here are the things being proposed here. For a non-exhaustive `switch` that...

| | Has `default` | No `default` |
| -- | -- | -- |
| `switch (literal union)` | 1 | 2 |
| `switch (infinite type)` | 3 | 4 |

Note: switches against infinite types are always non-exhaustive by definition.

<details>
<summary>Examples</summary>

```ts
declare const literal: "a" | "b";
declare const infinite: string;

// 1
switch (literal) {
  case "a": break;
  default: break;
}

// 2
switch (literal) {
  case "a": break;
}

// 3
switch (infinite) {
  case "a": break;
  default: break;
}

// 4
switch (infinite) {
  case "a": break;
}
```

</details>

| Rule + Options | Errors for... |
| -- | -- |
| `default-case` | 2, 4 |
| `switch-exhaustiveness-check` | 2 |
| `switch-exhaustiveness-check` + `banDefault` | 1, 2, 3 |
| `switch-exhaustiveness-check` + `ignoreDefault` | 1, 2 |

Is this correct?

**Comment by jakeleventhal** [comment] 2024-01-02 16:21
@JoshuaKGoldberg there is still a bug here:
```ts
    '@typescript-eslint/switch-exhaustiveness-check': [
      'error',
      {
        allowDefaultCaseForExhaustiveSwitch: false,
        requireDefaultForNonUnion: true
      }
    ],
```
```ts
    const getRandomString = (): string => 'asdf';

    const x = getRandomString();
    switch (x) {
      case 'aszdfasdf':
        break;
      default:
        break;
    }
```
`The switch statement is exhaustive, so the default case is unnecessary.eslint[@typescript-eslint/switch-exhaustiveness-check](https://typescript-eslint.io/rules/switch-exhaustiveness-check)`

The switch statement is not exhaustive.

**Comment by jakeleventhal** [comment] 2024-01-02 16:22
This needs to reopen

**Comment by Josh-Cena** [comment] 2024-01-03 03:31
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/8165. This issue is for implementing a feature; bugs related to the feature are separate issues.

**Closed by Josh-Cena** 2024-01-03 03:31 UTC
Labels: package: eslint-plugin, triage, enhancement: plugin rule option
