### ISSUE TITLE
New rule: avoid assertions if you can just use !

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#1922] opened 2020-04-20 16:14 UTC
```
TS2532: Object is possibly 'undefined'.
```

I saw many newcomers (including myself) occasionally solving this error with assertions. For example:

```ts
function (text: string | undefined): string {
	return text as string; // ❌
}
```

Can be also written as:

```ts
function (text: string | undefined): string {
	return text!; // ✅
}
```

The assertion is unnecessary, longer and less safe

**Comment by bradzacher** [comment] 2020-04-20 16:17
My question would be "why are you using a non-null assertion at all?

**Comment by fregante** [comment] 2020-04-20 16:22
Because the DOM.

`Event#target` is pretty much guaranteed to be present, but its type is Node | `undefined`

**Comment by adidahiya** [comment] 2020-04-20 16:57
How would you write a general rule which allows `!` like that? The example function in your OP is not safe in all cases. And re: https://github.com/typescript-eslint/typescript-eslint/issues/1922#issuecomment-616661607... TypeScript doesn't know what your DOM looks like.

**Comment by fregante** [comment] 2020-04-20 17:21
> TypeScript doesn't know what your DOM looks like.

Right. That's why I have to use `!` and assertions. I was just answering to @bradzacher.

> How would you write a general rule which allows `!` like that?

I don't know what you're asking. I don't know how to write rules 😅

**Comment by bradzacher** [comment] 2020-04-20 17:22
> TypeScript doesn't know what your DOM looks like.

This is the point - the types must be defined based on supporting every single query-case, and have no context on how you're actually querying or consuming them.

This is a common problem in every typed language when it comes to boundaries between a query language that generates no types. There is just some weirdness that needs to be worked around with non-null assertions or similar. That, or you add always-true checks into the code to correct the code.

I hate it, but the alternative is ad-hoc, automatic generation of types based on a separate build chain, which is a lot of work. 

As another example, we have similar problems in this project with ESLint selectors and types - eg:
```ts
const selectors = {
  'TSNonNullExpression > TSNonNullExpression'(node: TSESTree. TSNonNullExpression) {
    // guaranteed by the selector, but currently impossible to represent in types
    const parent = node.parent as TSESTree.TSNonNullExpression;
  },
  'VariableDeclarator[init]'(node: TSESTree.VariableDeclarator) {
    // selector guarantees non-null, but is impossible to nicely represent in types
    const init = node.init!;
  },
  // the only way to properly type this at declaration time
  'VariableDeclarator[init]'(node: TSESTree.VariableDeclarator & {
    init: NonNullable<TSESTree.VariableDeclarator['init']>;
  }) {
    const init = node.init; // correctly non-nullish
  },
  // or solve it with runtime checks
  'VariableDeclarator[init]'(node: TSESTree.VariableDeclarator) {
    /* istanbul ignore if */ if (node.init == null) {
      return;
    }
    const init = node.init;
  },
  'VariableDeclarator[init]'(node: TSESTree.VariableDeclarator) {
    const init = nullthrows(node.init, 'found no init on VariableDeclarator');
  },
}

function nullthrows<T>(thing: T, msg: string): NonNullable<T> {
  if (thing == null) { throw new Error(msg) }
  return thing;
}
```

------

> How would you write a general rule which allows ! like that

quick-and-dirty-very-rough-and-untested-pseudocode:

```ts
return {
  'TSAsExpression, TSTypeAssertion'(node) {
    const baseType = getTypeAtLocation(node.expression);
    if (!isUnionType(baseType) || !containsNullishTypes(baseType)) {
      // non-nullish and non-union types cannot be non-null asserted on
      return;
    }
    const assertedType = getTypeAtLocation(node.expression);
    if (containsNullishTypes(baseType)) {
      // asserting from string | null | undefined to string | null is fine
      return;
    }
    
    for (const base of baseType.filter(nullishTypes)) {
      if (!assertedType.contains(base)) {
        return; // asserted type is not an exact NonNullable conversion
      }
    }
    
    context.report('use a ! instead');
  },
}
```

**Comment by glen-84** [comment] 2020-12-16 08:11
Duplicate of #202.

**Comment by bradzacher** [comment] 2020-12-16 16:43
Yup!

The new rule `non-nullable-assertion-style` covers this.

**Closed by bradzacher** 2020-12-16 16:43 UTC
Labels: enhancement: new plugin rule, package: eslint-plugin
