### ISSUE TITLE
After upgrading to eslint 6.0.0 an exception is thrown

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#637] opened 2019-06-22 07:38 UTC
**Repro**

```JS
module.exports = {
	parser: '@typescript-eslint/parser',
	parserOptions: {
		project: './tsconfig.json'
	},
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended'
	],
	rules: {
		'@typescript-eslint/explicit-function-return-type': 'off',
		'@typescript-eslint/indent': ['warn', 'tab'],
		'@typescript-eslint/unbound-method': 'warn',
	}
};
```

```TS
// your repro code case
```

**Expected Result**

**Actual Result**
```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'eslint/lib/util/traverser'
Require stack:
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescript-eslint\parser\dist\parser.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\config-array-factory.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\cli-engine.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\index.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescript-eslint\parser\dist\parser.js:7:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
```

**Additional Info**

```

D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6>npx eslint *.{js,jsx,ts,tsx} --debug
  eslint:cli CLI args: [ '*.{js,jsx,ts,tsx}', '--debug' ] +0ms
  eslint:cli Running on files +9ms
  eslint:ignored-paths baseDir = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +3ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +1ms
  eslint:ignored-paths Looking for ignore file in D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6 +1ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:ignored-paths baseDir = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths Looking for ignore file in D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6 +0ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:file-enumerator Start to iterate files: [ '*.{js,jsx,ts,tsx}' ] +0ms
  eslint:file-enumerator Glob: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\*.{js,jsx,ts,tsx} +1ms
  eslint:file-enumerator recursive? false +5ms
  eslint:ignored-paths contains: +9ms
  eslint:ignored-paths   target   = "D:/MyDev/ljs_app/trunk/examples/frontend/@typescript-eslint/eslint6\\" +0ms
  eslint:ignored-paths   base     = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6" +0ms
  eslint:ignored-paths   relative = "" +1ms
  eslint:ignored-paths   result   = false +0ms
  eslint:file-enumerator Enter the directory: D:/MyDev/ljs_app/trunk/examples/frontend/@typescript-eslint/eslint6 +3ms
  eslint:cascading-config-array-factory Load config files for D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6. +0ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6. +1ms
  eslint:config-array-factory Loading JS config file: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\.eslintrc.js +0ms
  eslint:config-array-factory Config file found: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\.eslintrc.js +2ms
  eslint:config-array-factory Loading {extends:"eslint:recommended"} relative to D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\.eslintrc.j
s +15ms
  eslint:config-array-factory Loading JS config file: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\conf\eslint-recomm
ended.js +1ms
  eslint:config-array-factory Loading {extends:"plugin:@typescript-eslint/recommended"} relative to D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\
eslint6\.eslintrc.js +1ms
  eslint:config-array-factory Loading plugin "@typescript-eslint" from D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\.eslintrc.js +1ms
  eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@1.10.2 (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\
@typescript-eslint\eslint-plugin\dist\index.js) +3ms
  eslint:config-array-factory Loading {extends:"./configs/base.json"} relative to D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modul
es\@typescript-eslint\eslint-plugin\dist\index.js +281ms
  eslint:config-array-factory package.json was not found: Cannot find module './configs/base.json/package.json'
Require stack:
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescript-eslint\eslint-plugin\dist\index.js +2ms
  eslint:config-array-factory Loaded: ./configs/base.json (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescript-eslint\e
slint-plugin\dist\configs\base.json) +6ms
  eslint:config-array-factory Loading JSON config file: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescript-eslint\esli
nt-plugin\dist\configs\base.json +7ms
  eslint:config-array-factory Loading parser "@typescript-eslint/parser" from D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@
typescript-eslint\eslint-plugin\dist\configs\base.json +7ms
  eslint:config-array-factory Loaded: @typescript-eslint/parser@1.10.2 (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typesc
ript-eslint\parser\dist\parser.js) +7ms
  eslint:config-array-factory Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » plugin:@typescript-eslint/recommended » ./configs/ba
se.json'. +34ms
  eslint:config-array-factory Loading plugin "@typescript-eslint" from D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescr
ipt-eslint\eslint-plugin\dist\configs\base.json +2ms
  eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@1.10.2 (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\
@typescript-eslint\eslint-plugin\dist\index.js) +7ms
  eslint:config-array-factory Loading parser "@typescript-eslint/parser" from D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\.eslintrc.js +
8ms
  eslint:config-array-factory Loaded: @typescript-eslint/parser@1.10.2 (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typesc
ript-eslint\parser\dist\parser.js) +6ms
  eslint:config-array-factory Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js'. +8ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint. +402ms
  eslint:config-array-factory Config file not found on D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint +6ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev\ljs_app\trunk\examples\frontend. +5ms
  eslint:config-array-factory Config file not found on D:\MyDev\ljs_app\trunk\examples\frontend +6ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev\ljs_app\trunk\examples. +8ms
  eslint:config-array-factory Config file not found on D:\MyDev\ljs_app\trunk\examples +7ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev\ljs_app\trunk. +6ms
  eslint:config-array-factory Config file not found on D:\MyDev\ljs_app\trunk +6ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev\ljs_app. +7ms
  eslint:config-array-factory Config file not found on D:\MyDev\ljs_app +8ms
  eslint:cascading-config-array-factory No cache found: D:\MyDev. +7ms
  eslint:config-array-factory Config file not found on D:\MyDev +6ms
  eslint:cascading-config-array-factory No cache found: D:\. +6ms
  eslint:config-array-factory Config file not found on D:\ +6ms
  eslint:rules Loading rule 'constructor-super' (remaining=265) +0ms
  eslint:rules Loading rule 'for-direction' (remaining=264) +3ms
  eslint:rules Loading rule 'getter-return' (remaining=263) +2ms
  eslint:rules Loading rule 'no-async-promise-executor' (remaining=262) +5ms
  eslint:rules Loading rule 'no-case-declarations' (remaining=261) +2ms
  eslint:rules Loading rule 'no-class-assign' (remaining=260) +4ms
  eslint:rules Loading rule 'no-compare-neg-zero' (remaining=259) +3ms
  eslint:rules Loading rule 'no-cond-assign' (remaining=258) +3ms
  eslint:rules Loading rule 'no-const-assign' (remaining=257) +4ms
  eslint:rules Loading rule 'no-constant-condition' (remaining=256) +2ms
  eslint:rules Loading rule 'no-control-regex' (remaining=255) +6ms
  eslint:rules Loading rule 'no-debugger' (remaining=254) +2ms
  eslint:rules Loading rule 'no-delete-var' (remaining=253) +3ms
  eslint:rules Loading rule 'no-dupe-args' (remaining=252) +3ms
  eslint:rules Loading rule 'no-dupe-class-members' (remaining=251) +3ms
  eslint:rules Loading rule 'no-dupe-keys' (remaining=250) +4ms
  eslint:rules Loading rule 'no-duplicate-case' (remaining=249) +3ms
  eslint:rules Loading rule 'no-empty' (remaining=248) +3ms
  eslint:rules Loading rule 'no-empty-character-class' (remaining=247) +5ms
  eslint:rules Loading rule 'no-empty-pattern' (remaining=246) +2ms
  eslint:rules Loading rule 'no-ex-assign' (remaining=245) +4ms
  eslint:rules Loading rule 'no-extra-boolean-cast' (remaining=244) +3ms
  eslint:rules Loading rule 'no-extra-semi' (remaining=243) +3ms
  eslint:rules Loading rule 'no-fallthrough' (remaining=242) +3ms
  eslint:rules Loading rule 'no-func-assign' (remaining=241) +4ms
  eslint:rules Loading rule 'no-global-assign' (remaining=240) +2ms
  eslint:rules Loading rule 'no-inner-declarations' (remaining=239) +6ms
  eslint:rules Loading rule 'no-invalid-regexp' (remaining=238) +2ms
  eslint:rules Loading rule 'no-irregular-whitespace' (remaining=237) +4ms
  eslint:rules Loading rule 'no-misleading-character-class' (remaining=236) +3ms
  eslint:rules Loading rule 'no-mixed-spaces-and-tabs' (remaining=235) +8ms
  eslint:rules Loading rule 'no-new-symbol' (remaining=234) +2ms
  eslint:rules Loading rule 'no-obj-calls' (remaining=233) +2ms
  eslint:rules Loading rule 'no-octal' (remaining=232) +2ms
  eslint:rules Loading rule 'no-prototype-builtins' (remaining=231) +4ms
  eslint:rules Loading rule 'no-redeclare' (remaining=230) +4ms
  eslint:rules Loading rule 'no-regex-spaces' (remaining=229) +4ms
  eslint:rules Loading rule 'no-self-assign' (remaining=228) +2ms
  eslint:rules Loading rule 'no-shadow-restricted-names' (remaining=227) +3ms
  eslint:rules Loading rule 'no-sparse-arrays' (remaining=226) +4ms
  eslint:rules Loading rule 'no-this-before-super' (remaining=225) +3ms
  eslint:rules Loading rule 'no-undef' (remaining=224) +3ms
  eslint:rules Loading rule 'no-unexpected-multiline' (remaining=223) +4ms
  eslint:rules Loading rule 'no-unreachable' (remaining=222) +2ms
  eslint:rules Loading rule 'no-unsafe-finally' (remaining=221) +3ms
  eslint:rules Loading rule 'no-unsafe-negation' (remaining=220) +4ms
  eslint:rules Loading rule 'no-unused-labels' (remaining=219) +3ms
  eslint:rules Loading rule 'no-unused-vars' (remaining=218) +3ms
  eslint:rules Loading rule 'no-useless-catch' (remaining=217) +5ms
  eslint:rules Loading rule 'no-useless-escape' (remaining=216) +1ms
  eslint:rules Loading rule 'no-with' (remaining=215) +5ms
  eslint:rules Loading rule 'require-atomic-updates' (remaining=214) +2ms
  eslint:rules Loading rule 'require-yield' (remaining=213) +4ms
  eslint:rules Loading rule 'use-isnan' (remaining=212) +3ms
  eslint:rules Loading rule 'valid-typeof' (remaining=211) +3ms
  eslint:rules Loading rule 'camelcase' (remaining=210) +7ms
  eslint:rules Loading rule 'indent' (remaining=209) +6ms
  eslint:rules Loading rule 'no-array-constructor' (remaining=208) +15ms
  eslint:rules Loading rule 'no-use-before-define' (remaining=207) +6ms
  eslint:cascading-config-array-factory Configuration was determined: ConfigArray [ { name: '.eslintrc.js » eslint:recommended', filePath: 'D:\\MyDev\\ljs_app\\
trunk\\examples\\frontend\\@typescript-eslint\\eslint6\\node_modules\\eslint\\conf\\eslint-recommended.js', criteria: null, env: undefined, globals: undefined,
parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, root: undefined, rules: { 'constructor-super': 'error', 'for-direction':
'error', 'getter-return': 'error', 'no-async-promise-executor': 'error', 'no-case-declarations': 'error', 'no-class-assign': 'error', 'no-compare-neg-zero': 'er
ror', 'no-cond-assign': 'error', 'no-const-assign': 'error', 'no-constant-condition': 'error', 'no-control-regex': 'error', 'no-debugger': 'error', 'no-delete-v
ar': 'error', 'no-dupe-args': 'error', 'no-dupe-class-members': 'error', 'no-dupe-keys': 'error', 'no-duplicate-case': 'error', 'no-empty': 'error', 'no-empty-c
haracter-class': 'error', 'no-empty-pattern': 'error', 'no-ex-assign': 'error', 'no-extra-boolean-cast': 'error', 'no-extra-semi': 'error', 'no-fallthrough': 'e
rror', 'no-func-assign': 'error', 'no-global-assign': 'error', 'no-inner-declarations': 'error', 'no-invalid-regexp': 'error', 'no-irregular-whitespace': 'error
', 'no-misleading-character-class': 'error', 'no-mixed-spaces-and-tabs': 'error', 'no-new-symbol': 'error', 'no-obj-calls': 'error', 'no-octal': 'error', 'no-pr
ototype-builtins': 'error', 'no-redeclare': 'error', 'no-regex-spaces': 'error', 'no-self-assign': 'error', 'no-shadow-restricted-names': 'error', 'no-sparse-ar
rays': 'error', 'no-this-before-super': 'error', 'no-undef': 'error', 'no-unexpected-multiline': 'error', 'no-unreachable': 'error', 'no-unsafe-finally': 'error
', 'no-unsafe-negation': 'error', 'no-unused-labels': 'error', 'no-unused-vars': 'error', 'no-useless-catch': 'error', 'no-useless-escape': 'error', 'no-with':
'error', 'require-atomic-updates': 'error', 'require-yield': 'error', 'use-isnan': 'error', 'valid-typeof': 'error' }, settings: undefined }, { name: '.eslintrc
.js » ' + 'plugin:@typescript-eslint/recommended ' + '» ./configs/base.json', filePath: 'D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\esli
nt6\\node_modules\\@typescript-eslint\\eslint-plugin\\dist\\configs\\base.json', criteria: null, env: undefined, globals: undefined, parser: { error: [Error], f
ilePath: null, id: '@typescript-eslint/parser', importerName: '.eslintrc.js » ' + 'plugin:@typescript-eslint/recommended ' + '» ./configs/base.json', importerPa
th: 'D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6\\node_modules\\@typescript-eslint\\eslint-plugin\\dist\\configs\\base.json' }, p
arserOptions: { sourceType: 'module' }, plugins: { '@typescript-eslint': [Object] }, processor: undefined, root: undefined, rules: undefined, settings: undefine
d }, { name: '.eslintrc.js » plugin:@typescript-eslint/recommended', filePath: 'D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6\\node
_modules\\@typescript-eslint\\eslint-plugin\\dist\\index.js', criteria: null, env: undefined, globals: undefined, parser: undefined, parserOptions: undefined, p
lugins: undefined, processor: undefined, root: undefined, rules: { '@typescript-eslint/adjacent-overload-signatures': 'error', '@typescript-eslint/array-type':
'error', '@typescript-eslint/ban-types': 'error', camelcase: 'off', '@typescript-eslint/camelcase': 'error', '@typescript-eslint/class-name-casing': 'error', '@
typescript-eslint/explicit-function-return-type': 'warn', '@typescript-eslint/explicit-member-accessibility': 'error', indent: 'off', '@typescript-eslint/indent
': 'error', '@typescript-eslint/interface-name-prefix': 'error', '@typescript-eslint/member-delimiter-style': 'error', '@typescript-eslint/no-angle-bracket-type
-assertion': 'error', 'no-array-constructor': 'off', '@typescript-eslint/no-array-constructor': 'error', '@typescript-eslint/no-empty-interface': 'error', '@typ
escript-eslint/no-explicit-any': 'warn', '@typescript-eslint/no-inferrable-types': 'error', '@typescript-eslint/no-misused-new': 'error', '@typescript-eslint/no
-namespace': 'error', '@typescript-eslint/no-non-null-assertion': 'error', '@typescript-eslint/no-object-literal-type-assertion': 'error', '@typescript-eslint/n
o-parameter-properties': 'error', '@typescript-eslint/no-triple-slash-reference': 'error', 'no-unused-vars': 'off', '@typescript-eslint/no-unused-vars': 'warn',
 'no-use-before-define': 'off', '@typescript-eslint/no-use-before-define': 'error', '@typescript-eslint/no-var-requires': 'error', '@typescript-eslint/prefer-in
terface': 'error', '@typescript-eslint/prefer-namespace-keyword': 'error', '@typescript-eslint/type-annotation-spacing': 'error' }, settings: undefined }, { nam
e: '.eslintrc.js', filePath: 'D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6\\.eslintrc.js', criteria: null, env: undefined, globals
: undefined, parser: { error: [Error], filePath: null, id: '@typescript-eslint/parser', importerName: '.eslintrc.js', importerPath: 'D:\\MyDev\\ljs_app\\trunk\\
examples\\frontend\\@typescript-eslint\\eslint6\\.eslintrc.js' }, parserOptions: { project: './tsconfig.json' }, plugins: undefined, processor: undefined, root:
 undefined, rules: { '@typescript-eslint/explicit-function-return-type': 'off', '@typescript-eslint/indent': [Array], '@typescript-eslint/unbound-method': 'warn
' }, settings: undefined } ] on D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6 +229ms
  eslint:ignored-paths contains: +790ms
  eslint:ignored-paths   target   = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6\\.eslintrc.js" +2ms
  eslint:ignored-paths   base     = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6" +4ms
  eslint:ignored-paths   relative = ".eslintrc.js" +4ms
  eslint:ignored-paths   result   = true +2ms
  eslint:file-enumerator Yield: .eslintrc.js but ignored +805ms
  eslint:ignored-paths contains: +7ms
  eslint:ignored-paths   target   = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6\\index.ts" +3ms
  eslint:ignored-paths   base     = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\eslint6" +3ms
  eslint:ignored-paths   relative = "index.ts" +4ms
  eslint:ignored-paths   result   = false +3ms
  eslint:file-enumerator Yield: index.ts +19ms
  eslint:cli-engine Lint D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\index.ts +0ms
  eslint:linter Linting code for D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\index.ts (pass 1) +0ms
  eslint:linter Verify +4ms
  eslint:linter With ConfigArray: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\index.ts +2ms
Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'eslint/lib/util/traverser'
Require stack:
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\@typescript-eslint\parser\dist\parser.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\config-array-factory.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\cli-engine.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli-engine\index.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\lib\cli.js
- D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6\node_modules\eslint\bin\eslint.js

D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\eslint6>
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.10.2` |
| `@typescript-eslint/parser`        | `1.10.2` |
| `TypeScript`                       | `3.5.2` |
| `ESLint`                           | `6.0.0` |
| `node`                             | `12.4.0` |
| `npm`                              | `6.9.0` |

**Comment by lll000111** [comment] 2019-06-22 08:44
This is easily fixed, by the way:

In file parser/dist/parser.js change the import path `"eslint/lib/util/traverser"` to `"eslint/lib/shared/traverser"` (filename given for the npm version for people to do it themselves, until the source code is changed and a new package pushed to npm).

**Comment by swernerx** [comment] 2019-06-22 09:19
Would be probably a good idea to somehow support both major versions though.

**Comment by platinumazure** [comment] 2019-06-22 13:53
I think this might be a duplicate of #563 and is already resolved in master. Maybe someone could check by trying the nightly build in their setup? (Apologies if I am mistaken.)

If I'm correct, then this will be resolved in the next release.

**Comment by bradzacher** [comment] 2019-06-22 17:02
it is a duplicate, and it should be fixed in master.
try `yarn add @typescript-eslint/eslint-plugin@canary`.

Closing this in favour of #563.

**Closed by bradzacher** 2019-06-22 17:02 UTC
Labels: package: parser, triage

**Comment by JamesHenry** [comment] 2019-06-23 23:04
1.11.0 has now also been released which contains the necessary update

**Comment by gventuri** [comment] 2019-08-17 09:14
The same thing is happening to me even though I've updated the packages:

package | version
-- | --
@typescript-eslint/eslint-plugin | 2.0.0
@typescript-eslint/parser | 2.0.0
TypeScript | 3.5.3
ESLint | 6.1.0
node | 10.15.3
yarn | 1.16.0

Here's the error I get:
`Failed to load plugin '@typescript-eslint' declared in 'functions/.eslintrc.js': Cannot find module '@typescript-eslint/eslint-plugin'`

How could I fix it?

**Comment by bradzacher** [comment] 2019-08-18 00:51
please raise a new issue with more information instead of commenting on an old issue.

100% this issue is unrelated to your problem.
