### ISSUE TITLE
[2.4.0][Watch][Windows] ESLint doesn't exit after completing a cli lint

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#1079] opened 2019-10-14 18:48 UTC
Simply upgrading `eslint-plugin`and `parser` from 2.3.3 to 2.4.0 causes eslint to hang at the end of the processing.

```
npx eslint --cache --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"
```

I've enabled  basic debugging `DEBUG=eslint:cli-engine` and the last message is `eslint:cli-engine Linting complete in: 110453ms +219ms` and then the eslint command does not seem to return (within several minutes) and I can only kill the process.
I have tried this without any change to the sources to be parsed or the configuration and simply upgrading to 2.4.0 makes eslint hang and after moving back to 2.3.3 it does no longer hang.

(I'm aware that I should upload a reproducible test case but given the nature of this problem this seems not possible right now)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.4.0` |
| `@typescript-eslint/parser`        | `2.4.0` |
| `TypeScript`                       | `3.6.4` |
| `ESLint`                           | `6.5.1` |
| `node`                             | `12.12.0` |
| `npm`                              | `6.12.0` |

**Comment by bradzacher** [comment] 2019-10-14 18:57
I am unable to repro this in our repo.
I tried running:
- `eslint . --ext .js,.ts`
- `eslint . --ext .js,.ts --cache`
- `eslint . --ext .js,.ts --cache --report-unused-disable-directives`
- `eslint . --ext .js,.ts --report-unused-disable-directives`

Questions:
- What OS are you running?
- Does your codebase use symlinks or similar extensively?

---

as a temp workaround you can turn on the environment variable 
`PARSER_NO_WATCH=true npx eslint --cache --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"`

**Comment by bradzacher** [comment] 2019-10-14 19:01
Could you try adding `"extendedDiagnostics": true` to your tsconfig(s), running your command again, and inspecting the output of your run?
If you're able to, can you post the output of that here? I understand if you can't because it's a private project, but all the information possible will make solving this easier.

**Comment by doberkofler** [comment] 2019-10-14 19:04
>What OS are you running?
Windows 7 x64 (I just tried on MacOS and there it seems to work also after the update to 2.4.0)

>Does your codebase use symlinks or similar extensively?
None

I also just tried to upgrade to node 12.12.0 but the problem persists.

>as a temp workaround you can turn on the environment variable
>PARSER_NO_WATCH=true npx eslint --cache --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"
Using
```cmd
set PARSER_NO_WATCH=true
npx eslint --cache --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"
```
does seem to resolve the problem. Could you elaborate on what this settings does or rather prevents from doing?

**Comment by doberkofler** [comment] 2019-10-14 19:08
Should I use `"extendedDiagnostics": true` with or without the `PARSER_NO_WATCH=true` environment variable?

**Comment by doberkofler** [comment] 2019-10-14 19:15
This is the output of eslint when running with `"extendedDiagnostics": true` but without `PARSER_NO_WATCH=true`: [eslint.zip](https://github.com/typescript-eslint/typescript-eslint/files/3726049/eslint.zip)

**Comment by bradzacher** [comment] 2019-10-14 19:16
> Windows 7 x64 

gah. windows. the one platform we don't have any coverage on.
This is more than likely the culprit.
cc @JamesHenry - is it possible to add windows to the CI?

I'll have to dust off my windows laptop and do some investigation.

> Could you elaborate on what this settings does or rather prevents from doing?

When you run eslint, typescript will tell us which folders it wants us to watch.
In 2.3.0, we just no-oped that CB, because we thought we didn't care about setting up watchers because eslint would provide us with the most up-to-date file contents.
However this had a drawback with the 2.0.0 change we added to parse a stricter set of files - it meant that when you were in a long-running lint session (i.e. via an IDE), then typescript wouldn't know that a new file should be included in the parse, and we would thus throw errors on valid files.

2.4.0 adds support for weak file watching - it attaches watchers to the folders typescript cares about, as well as the `tsconfig` file(s). These watchers are set to be non-persistent - i.e. they are lightweight and will not hold the process open.
But it looks like there's something wrong on Windows specifically.
`chokidar` was supposed to handle the platform differences for me automatically, but I might have missed something in the docs.

The environment variable does what it says on the tin - it turns off file watching within the parser (or more accurately `typescript-estree`). I put it in because on some large, complex setups (like those with symlinks and such), file watching can have a pretty significant overhead, so you might want to turn it off for a single run.

https://github.com/typescript-eslint/typescript-eslint/blob/1918024e86acdf315dbbe659af6fea5d7244b336/packages/typescript-estree/src/tsconfig-parser.ts#L99-L119

> Should I use "extendedDiagnostics": true with or without the PARSER_NO_WATCH=true environment variable?

Without, please.

> This is the output of eslint when running with "extendedDiagnostics": true but without PARSER_NO_WATCH=true

Thank you! I'll investigate this as soon as I can.

**Comment by doberkofler** [comment] 2019-10-14 19:26
Thank you for the in-depth explanation all the good work!
Sorry that I quite often (I know) report problem on the Windows platform but this is simply because our CI always runs on multiple MacOS AND Windows versions.

**Comment by JamesHenry** [comment] 2019-10-14 19:41
Should be pretty straightforward to add a Windows agent to the Azure Pipelines build, hopefully we can figure out a minimal repro to turn into a test

**Comment by le0nik** [comment] 2019-10-14 20:47
I see a similar problem on OSX, although it doesn't hang forever, but finishes 8 seconds later than on 2.3.3:

2.3.3

```
  eslint:cli-engine Linting complete in: 4249ms +18ms
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
import/no-named-as-default              |   296.277 |    39.9%
import/no-duplicates                    |   197.532 |    26.6%
@typescript-eslint/no-unused-vars       |    57.505 |     7.8%
react/no-direct-mutation-state          |    31.897 |     4.3%
no-redeclare                            |    21.859 |     2.9%
react/require-render-return             |    16.574 |     2.2%
react/no-typos                          |    16.126 |     2.2%
@typescript-eslint/no-use-before-define |     5.260 |     0.7%
react-hooks/exhaustive-deps             |     4.855 |     0.7%
no-empty-character-class                |     4.308 |     0.6%
✨  Done in 4.52s.
```

2.4.0
```
  eslint:cli-engine Linting complete in: 4285ms +18ms
Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
import/no-named-as-default        |   297.976 |    41.6%
import/no-duplicates              |   184.723 |    25.8%
@typescript-eslint/no-unused-vars |    45.204 |     6.3%
react/no-direct-mutation-state    |    32.224 |     4.5%
no-redeclare                      |    21.312 |     3.0%
react/no-typos                    |    18.978 |     2.6%
react/require-render-return       |    13.727 |     1.9%
no-empty-character-class          |     4.702 |     0.7%
react-hooks/exhaustive-deps       |     4.589 |     0.6%
no-restricted-globals             |     4.223 |     0.6%
✨  Done in 11.57s.
```

So it finishes linting in about 4.3 seconds, but with 2.4.0 the process still hangs for about 8 more seconds, so the entire process taks about 3 times longer.

The `✨  Done in 11.57s.` line is from `yarn`. 

yarn lint` executes this command: `eslint --report-unused-disable-directives 'src/**/*.{ts,tsx,js,jsx}'`.

Running the same command(with or without `--report-unused-disable-directives` without `yarn` brngs the same results.

eslint.rc.js:

```js
module.exports = {
  "parser": "@typescript-eslint/parser",
  "extends": [
    "react-app",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/typescript",
    "prettier/react",
    "prettier/@typescript-eslint",
  ],
  "plugins": [
    "import",
    "react",
    "react-hooks",
  ],
  "rules": {
    "@typescript-eslint/no-use-before-define": ["error", {
      "functions": false,
      "typedefs": false,
    }],
    '@typescript-eslint/prefer-interface': "off",
    "no-console": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/camelcase": "off",
    "import/no-named-as-default": "warn",
    "import/no-duplicates": "warn",
  },
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "project": "./tsconfig.json",
    "tsconfigRootDir": __dirname,
    "createDefaultProgram": true
  },
  "settings": {
    "import/resolver": {
      "typescript": {}
    }
  },
  "overrides": [
    {
      "files": ["*.js", "*.jsx"],
      "extends": [
        "plugin:import/errors",
        "plugin:import/warnings"
      ]
    }
  ]
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "lib": ["esnext", "dom"],
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "isolatedModules": true,
    "allowJs": true,
    "esModuleInterop": true,
    "disableSizeLimit": true,
    "jsx": "preserve"
  },
  "include": ["src"],
  "exclude": ["node_modules", "public", ".cache", "data", "static"]
}

```

Latest stable versions of typescript, eslint and plugins.
OSX: 10.14.6
node: v12.12.0
yarn: 1.19.1

Let me know what other information I can supply(except for the repo itself, unfortunately).

**Comment by AviVahl** [comment] 2019-10-14 23:46
Its not just Windows. I got `ENOSPC: System limit for number of file watchers reached` on Travis (linux container).

https://travis-ci.com/wixplosives/sample-monorepo/jobs/245636756

It appears the plugin tries watching files in `node_modules`, which is specified in `.eslintignore`.

**Comment by bradzacher** [comment] 2019-10-14 23:52
@AviVahl - whilst these both apply to the new watching code added in 2.4.0.
This issue is about the lint session hanging on windows.

Please open a new issue so we can track and investigate that issue.

**Comment by yoyo930021** [comment] 2019-10-17 05:03
I have a similar problem with macOS.
ESLint exit after completing a cli lint and waiting for a long time.

[cpuprofile.zip](https://github.com/typescript-eslint/typescript-eslint/files/3737454/cpuprofile.zip)

**Comment by kalbert312** [comment] 2019-10-18 02:04
Running into this as well. macOS. Running with `--debug` produces `eslint:cli-engine Linting complete in: 2301ms +6ms` but it never exits.

**Comment by Favna** [comment] 2019-10-18 15:00
Can confirm I am also facing this issue on MacOS Catalina (10.15), relevant config and versions are pretty much similar to those kalbert312. Passing `PARSER_NO_WATCH=true` does work but as a better solution I downgraded back to 2.3.3 for now.

**Comment by amikheychik** [comment] 2019-10-18 20:45
Can confirm this issue on MacOS 10.14 and NodeJS 10.16.0. Rollback to 2.3.3 helps.

**Comment by bradzacher** [comment] 2019-10-18 22:16
If you're  looking for a more robust way to disable watching, there is also a config you can add to your eslintrc - `parserOptions: {noWatch: true}`.
You need not rollback to 2.3.3.

**Comment by bradzacher** [comment] 2019-10-19 18:54
I've just landed #1106, and it will be deployed to the `canary` tag imminently.
This change reworks the invalidation approach so that it doesn't need file watchers at all.

I'd appreciate if you could take a moment to test the canary tag on your codebases, and let me know if anything isn't working as expected for your real-world codebase.

**Closed** 2019-10-19 18:54 UTC
Labels: bug, package: typescript-estree

**Comment by kbradl16** [comment] 2019-10-20 19:12
On windows I was also having issues where eslint wouldn't exit after execution (it would print the problems, warnings and errors and then just hang). adding --debug I didn't see anything abnormal.

I'm currently working on ~8 different projects (all with the same .eslintrc.json file and tsconfig files) and this issue was only happening in one project. I could not figure out why it was not exiting or recreate the issue in another project.

Adding the parserOptions: {noWatch: true} fixes the hanging issue and I would like to see if your commit(s) fixes the issue for me also. I'm not sure how to tell what commits went into a canary build though. Which canary build should I try? 2.4.1-alpha.8 or 2.4.1-alpha.9 or does it matter?

**Comment by bradzacher** [comment] 2019-10-20 19:39
The canary build is built off of master on every single commit.
There's no need to think about which version to use from the canary tag - just install the latest.

**Comment by doberkofler** [comment] 2019-10-21 18:24
@bradzacher Just a quick update while still running. I've just upgraded to 2.5.0 and unfortunately things got worse for me. When running eslint with the `--debug` flag it now takes up to 30 seconds (before the average was about 75ms) for each individual file to be parsed. I must parse over 700 files so it might take more than 6 hours to finish.

**Comment by bradzacher** [comment] 2019-10-21 19:05
Weird, I tested this extensively on CLI and I didn't see any perf regressions.
I was tuning this so that the new code path shouldn't get executed when running from the CLI.
You're running on windows, right? So #1111 won't make any difference for you, because windows is case sensitive.

Could you please do a run the debug flag `DEBUG=typescript-eslint:* yarn lint` and post the results? Don't worry about the `--debug` flag.

**Comment by doberkofler** [comment] 2019-10-21 20:30
My original run did actually end after 3016382ms and I will now run with `DEBUG=typescript-eslint:*` and let you know the results

**Comment by doberkofler** [comment] 2019-10-21 20:34
I now just started running eslint again and it again runs as slow as before and should probably take about 1 hours to finish.

The (intermediate) output looks as follows:
```
# npx eslint --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"
 
 typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\activity.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\activity.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for D:\MyDev\ljs_app\trunk\periscope\tsconfig.json. +1ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for D:\MyDev\ljs_app\trunk\periscope\tsconfig.selenium.json. +11s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +13s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +3s
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +5s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +168ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +3ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +4s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\alternativeaddress.ts +4s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\alternativeaddress.ts +53ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\alternativeaddress.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\alternativeaddress.ts +4s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\book.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\book.ts +61ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\book.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\book.ts +5s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\campaign.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\campaign.ts +58ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\campaign.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\campaign.ts +4s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\client.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\client.ts +228ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\client.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\client.ts +4s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\clientinvoice.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\clientinvoice.ts +136ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\clientinvoice.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\clientinvoice.ts +4s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\collaboration.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\collaboration.ts +199ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\collaboration.ts +1ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\collaboration.ts +4s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\costestimate.ts +4s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\costestimate.ts +90ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\costestimate.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\costestimate.ts +5s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\currency.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\currency.ts +216ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\currency.ts +2ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\currency.ts +5s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\employee.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\employee.ts +56ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\employee.ts +1ms
```

**Comment by doberkofler** [comment] 2019-10-21 20:36
> You're running on windows, right? So #1111 won't make any difference for you, because windows is case sensitive.

Windows is not case sensitive

**Comment by AviVahl** [comment] 2019-10-21 20:41
Windows is not case sensitive, so it *needs* the canonical path as cache key.
Otherwise `c:\my-project\file.txt` and `C:\MY-PROJECT\file.txt` are not considered as pointing to the same path.

**Comment by doberkofler** [comment] 2019-10-21 21:40
Complete output 
[output.txt](https://github.com/typescript-eslint/typescript-eslint/files/3753002/output.txt)

**Comment by bradzacher** [comment] 2019-10-21 22:21
You know what. I knew that. It's windows that's not case sensitive, and unix that is.
I've spent too much time across OS's.

I swear I saw typescript do some weird shit as well.
I need to go back and dig into it more, as I saw a number of cases where typescript was giving me lower case paths on unix..

Either way then, #1111 will fix this for you guys.
It's currently triggering a program update for every single cycle, but the above will stop that.

**Comment by bradzacher** [comment] 2019-10-21 22:29
Just merged #1111 - there will be a canary version in ~15 minutes.

**Comment by doberkofler** [comment] 2019-10-22 06:27
I've just tested with the canary version and do not see any changes or speed improvements. It is still about 100x slower then before.

**Comment by doberkofler** [comment] 2019-10-22 06:31
I'm actually not sure if I should continue updating this SR as you already closed it. At least for me "this" issue is still unresolved and I can only revert back to 2.3.3 but I can also open a new one if you prefer keeping this ones closed.

**Comment by bradzacher** [comment] 2019-10-22 06:36
could you please dump the logs from another cli run using the DEBUG var?

**Comment by doberkofler** [comment] 2019-10-22 07:03
Sure. Already running  but it will take a while. Just wanted to give you a quick update.

**Comment by doberkofler** [comment] 2019-10-22 07:04
It starts like this...

```
# npx eslint --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\activity.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\activity.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for D:\MyDev\ljs_app\trunk\periscope\tsconfig.json. +0ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for D:\MyDev\ljs_app\trunk\periscope\tsconfig.selenium.json. +10s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +13s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +3s
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +3ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\address.ts +5s
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +176ms
  typescript-eslint:typescript-estree:createWatchProgram File was not found in program - triggering folder update. D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +1ms
  typescript-eslint:typescript-estree:createWatchProgram File was still not found in program after directory update - checking file deletions. D:\MyDev\ljs_app\trunk\periscope\src\data\agency.ts +5s
...
```

**Comment by bradzacher** [comment] 2019-10-22 07:21
Mmm that's all I need. The rest will just be the same thing repeated for each file.
It's just not finding the files in the programs for some reason.
I'll try our repo on my old windows laptop and see what happens, as it doesn't repro on mac.

Do you have `include` in your tsconfig? Or do you have nothing?
Is this a monorepo, or is there just the two tsconfigs listed in the debug?

**Comment by doberkofler** [comment] 2019-10-22 07:31
My configuration:

**eslint_typescript_project.js:**
```typescript
module.exports = {
	parserOptions: {
		project: [
			'./tsconfig.json',
			'./tsconfig.selenium.json'
		]
	}
};
```

**tsconfig.json:**
```json
{
  "extends": "./configs/tsconfig_base",
  "compilerOptions": {
    "paths": {
      "Source_Data/*": ["./src/data/*"],
      "Source_Framework/*": ["./src/framework/*"],
      "Source_Modules/*": ["./src/modules/*"],
      "Source_ODS/*": ["./src/ods/*"],
      "Source_Vendor/*": ["./vendor/*"],
      "CoreImg/*": ["./img/*"]
    }
  },
  "include": [
    "src",
    "test/unittest"
  ]
}
```

**tsconfig.selenium.json:**
```json
{
  "extends": "./configs/tsconfig_base",
  "compilerOptions": {
    "noEmit": false,
    "target": "es2018",
    "module": "commonjs"
  },
  "include": [
    "test/selenium/pageobjects",
    "test/selenium/tests",
    "test/selenium/util"
  ]
}
```

**tsconfig_base.json:**
```json
{
  "compilerOptions": {
    "extendedDiagnostics": false,
    "noEmit": true,
    "downlevelIteration": true,
    "allowJs": true,
    "checkJs": false,
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": false,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "declaration": false,
    "importHelpers": true,
    "moduleResolution": "node",
    "target": "es2015",
    "module": "es2015",
    "jsx": "react",
    "baseUrl": "../",
    "outDir": "../temp",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "compileOnSave": false,
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by doberkofler** [comment] 2019-10-22 07:36
This is the output when running with `TSESTREE_NO_INVALIDATION=true` and it is a lot faster but maybe not as fast as originally.
[output.txt](https://github.com/typescript-eslint/typescript-eslint/files/3754221/output.txt)

**Comment by bradzacher** [comment] 2019-10-22 15:41
Hmm, that output is still wrong, though.

Your tsconfig isn't missing anything like in #1110, so it's not hitting that case.
So, I don't know why you're getting a 100% cache miss rate.

It must be something different about TS's paths on windows.
I'll dig into it tonight on my windows machines.

----

As an FYI - during a CLI run, the debug output should look like this, in particular it should just be:
- "Creating watch program" (once per tsconfig)
- "Creating project program", then "Found existing program", repeated for every single file.

```
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/configs/eslint-recommended.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/configs/eslint-recommended.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/tsconfig.eslint.json. +0ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin-tslint/tsconfig.json. +909ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/tsconfig.json. +769ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/packages/experimental-utils/tsconfig.json. +1s
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/packages/parser/tsconfig.json. +624ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/packages/shared-fixtures/tsconfig.json. +549ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/bradzacher/github/typescript-eslint/packages/typescript-estree/tsconfig.json. +398ms
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/index.ts +5s
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/index.ts +684ms
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts +37ms
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts +39ms
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/rules/array-type.ts +160ms
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/rules/array-type.ts +163ms
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/rules/await-thenable.ts +310ms
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/rules/await-thenable.ts +305ms
```
