### ISSUE TITLE
Can we shorten "@typescript-eslint" somehow?

### ISSUE THREAD

**Issue by octogonz** [typescript-eslint/typescript-eslint#793] opened 2019-08-02 20:00 UTC
This is a somewhat general question.

I'm finding that it's a lot of typing to write this:
```ts
// eslint-disable-next-line @typescript-eslint/no-empty-interface
```
...when in the past I wrote this:
```ts
// tslint-disable-next-line no-empty-interface
```

I thought about proposing for ESLint to allow the scope to be omitted when it is unambiguous (e.g. `@typescript-eslint` is the only plugin in the world with a rule `no-empty-interface`).  That could be a good solution.

But the more I thought about it, it is useful to know that `react/no-deprecated` comes from the React plugin, and `security/detect-new-buffer` comes from the security plugin.

Is there a way we could shorten the name to this?

```ts
// eslint-disable-next-line typescript/no-empty-interface
```

The portion `-eslint` is completely redundant among ESLint rules.  It makes sense in the namespace of NPM packages, but perhaps ESLint could provide a shorthand of some kind. (?)

**Comment by bradzacher** [comment] 2019-08-02 22:41
unfortunately not.
If this _were_ to be fixed, it would have to be from the eslint side, as we cannot control the structure of disable comments.

---

> The portion -eslint is completely redundant among ESLint rules. It makes sense in the namespace of NPM packages, but perhaps ESLint could provide a shorthand of some kind. (?)

ESLint does provide a shorthand. The full name of the package is `@typescript-eslint/eslint-plugin`. The shorthand drops the `eslint-plugin` suffix.


We moved to the `@typescript-eslint` package namespace when we merged all 4 projects into one effort about a year ago.

We renamed the packages for the same reason that babel did it with v7, it let us:
- restart and standardise our versioning across packages (eg the parser/typescript-estree were at like v14 before the cutover),
- standardise the naming,
- indicate their relationship,
- and let the names match the github monorepo they're from.

It's a verbose name, for sure, but it's very clear.

Shortening to the `@typescript` npm package namespace would be the wrong thing for two reasons:
1) whilst we receive support from the TypeScript team, and have some people from Microsoft who contribute, we're not actually directly affiliated with TypeScript, or Microsoft.
2) we're not a collection of typescript packages - we're a collection of eslint packages for handling typescript code.

---

I guess the thing to ask is why you're disabling rules so much that typing out the name is becoming cumbersome?

There should only be edge cases for most rules where you actively want to disable them.

E.g. `no-empty-interface` can be fixed by converting to a type:
```diff
- interface Foo extends Bar<Baz> {}
+ type Foo = Bar<Baz>;
```

**Closed by bradzacher** 2019-08-02 22:41 UTC
Labels: package: eslint-plugin, question

**Comment by octogonz** [comment] 2019-08-02 23:00
> If this _were_ to be fixed, it would have to be from the eslint side, as we cannot control the structure of disable comments.

I get that.  But before proposing a change to ESLint, I was looking for an opinion as to what you would want that change to be.

> Shortening to the `@typescript` npm package namespace would be the wrong thing for two reasons:

I wasn't asking to change the NPM package name, but rather the comment-disabling user experience (which already does not correspond to the NPM package name).

> I guess the thing to ask is why you're disabling rules so much that typing out the name is becoming cumbersome?

We're migrating thousands and thousands of existing source files to use ESLint instead of TSLint.  The goal is to make the linter succeed with 0 warnings, not to refactor all those files.  A secondary goal is to avoid the impression that ESLint is cluttering the source code with suppressions, so more concise comments might be desirable.

**Comment by bradzacher** [comment] 2019-08-02 23:51
Thinking about this more - you could actually make this work with a yarn install.

`yarn add eslint-plugin-typescript@npm:@typescript-eslint/eslint-plugin`

This should create an alias in your local install, which points at our package.
then from within eslint you can just use `typescript/foo` everywhere.

---

If I was to suggest a change to eslint to fix this, it would be to allow aliasing of packages I guess?

I.e.
```js
module.exports = {
  "aliases": { "typescript": "@typescript-eslint/eslint-plugin" },
  "plugins": ["typescript"],
  "rules": { "typescript/foo": "error" }
}

// eslint-disable-next-line typescript/foo
```

**Comment by octogonz** [comment] 2019-08-03 01:04
> Thinking about this more - you could actually make this work with a yarn install.
> 
> `yarn add eslint-plugin-typescript@npm:@typescript-eslint/eslint-plugin`

Man, `eslint-plugin-typescript` was the perfect name (aside from [`eslint-plugin-ts`](https://www.npmjs.com/package/eslint-plugin-ts)).  User experience really should have trumped the GitHub project bookkeeping priorities IMHO.

The `npm:` remapping is attractive, however although this feature is supported by Yarn and PNPM it's apparently not supported by NPM.  Thus I don't think I can safely use it in a shared toolchain library.

Another idea would be for ESLint's shorthand to discard `-eslint` in the same way it discards `eslint-plugin`.  In both cases they are redundant words.  That would reduce the name to `@typescript/no-empty-interface` without opening up the possibility for every project to invent its own nonstandard aliases.

**Comment by bradzacher** [comment] 2019-08-03 03:14
> User experience really should have trumped the GitHub project bookkeeping priorities IMHO.

You say that, until you have to try and explain to someone that the correct combination of packages is v0.14.x of `eslint-plugin-typescript`, v22.x of `typescript-eslint-parser`, and v18.x of `typescript-estree`.

Then you have to try to coordinate which combination of `typescript-eslint-parser` / `typescript-estree` support what versions of typescript...

Trust me when I say that it wasn't a good UX. People got very confused, and nobody understood what was going on, nor did they understand when they could update each of the 3 packages, which further fragmented the userbase.

> Another idea would be for ESLint's shorthand to discard -eslint in the same way it discards eslint-plugin

The problem is that this naming is unique to our packages. Doing that drop would involve adding another name mapping to eslint's module resolver - I don't know if they want to take on that burden.

Feel free to suggest it to them if you'd like! https://github.com/eslint/rfcs is the place to suggest changes.

> The npm: remapping is attractive, however although this feature is supported by Yarn and PNPM it's apparently not supported by NPM.

According to https://stackoverflow.com/a/55099347/3736051, it's supported in npm 6.9.0

**Comment by octogonz** [comment] 2019-08-03 03:28
> According to https://stackoverflow.com/a/55099347/3736051, it's supported in npm 6.

Nice!
