### ISSUE TITLE
typescript-estree seems to be using a default import that doesn't exist

### ISSUE THREAD

**Issue by deifactor** [typescript-eslint/typescript-eslint#335] opened 2019-03-07 03:12 UTC
My dependencies:

```
  "dependencies": {
    "@typescript-eslint/typescript-estree": "^1.4.2",
    "typescript": "^3.3.3333"
  }
```

I have a file containing the single line 

```
import * as tsParser from "@typescript-eslint/typescript-estree";
```

which fails to typecheck:

```
node_modules/@typescript-eslint/typescript-estree/dist/ts-nodes.d.ts:1:8 - error TS1192: Module '[redacted]/node_modules/typescript/lib/typescript"' has no default export.

1 import ts from 'typescript';
         ~~
```

It works if I enable `allowSyntheticDefaultImports` in my tsconfig.json, but it might be better to just `import * as ts from 'typescript'` instead.

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `1.4.2` |
| `TypeScript`                           | `3.3.3333` |
| `node`                                 | `v11.7.0` |
| `npm`                                  | `6.7.0` |

**Comment by bradzacher** [comment] 2019-03-07 17:58
You need to turn on synthetic default imports for it to work.

**Comment by deifactor** [comment] 2019-03-12 17:41
Would it make sense to change the import so consumers don't need synthetic default imports?

**Comment by bradzacher** [comment] 2019-03-12 17:56
Certainly someone could take a look, but it's worth noting that not all npm packages support non-synthetic default imports, so it may actually be required.

Also worth noting that we haven't spent any time optimising any of the types across the repo for consumption outside of the repo.

Related: #330

**Comment by adidahiya** [comment] 2019-03-12 19:51
`esModuleInterop` + `allowSyntheticDefaultImports` are the recommended standard options in the TS ecosystem now, see the [TS 2.7 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html), so I don't think any semantic change should be made here

**Comment by deifactor** [comment] 2019-03-12 20:17
That's fair. I know relatively little about what would need to be changed to make this work, and whether that'd break other users.

**Comment by bradzacher** [comment] 2019-03-12 20:33
@adidahiya - whilst they are recommended, a lot of projects don't use them because they're not the default (yet?). So it might make sense to support not using them **if it's not too much effort**.

I haven't looked into it, but I *think* that it should be as simple as:
```diff
- import ts from 'typescript';
+ import * as ts from 'typescript';
```

If it's not that easy then I'll definitely drop it and instead opt for documenting the requirement on the options.

**Comment by adidahiya** [comment] 2019-03-12 20:35
@bradzacher the problem is that it's hard to support both export styles in a published library, and I'd rather lean towards the future-facing syntax

**Comment by deifactor** [comment] 2019-03-12 21:05
If this would break people who don't use allowSyntheticDefaultImports then I agree that it's reasonable to just document 'by the way, you'll need this' on the README.md or someplace like it.

**Comment by j-f1** [comment] 2019-03-12 21:30
That change should work either way.

**Comment by crhistianramirez** [comment] 2019-07-11 11:38
Looks like this issue should be closed? There's a merged PR from back in April

**Comment by j-f1** [comment] 2019-07-11 15:10
Thanks @crhistianramirez

**Closed by j-f1** 2019-07-11 15:10 UTC
Labels: documentation, good first issue, has pr, package: typescript-estree
