### ISSUE TITLE
[@typescript-eslint/member-ordering] Add groups for accessors

### ISSUE THREAD

**Issue by manuth** [typescript-eslint/typescript-eslint#1886] opened 2020-04-12 22:21 UTC
**Repro**
1. Write a class with accessors
2. Try to enforce accessors to be placed between constructors and methods

```JSON
{
  "rules": {
    "@typescript-eslint/member-ordering": "warn"
  }
}
```

```TS
class Test
{
    public constructor() { }

    public TestMethod() { }

    public get TestProperty()
    {
        return 1;
    }

    public set TestProperty(value)
    { }
}
```

**Expected Result**
An error should be reported that both the `get` and `set`-accessor of the `TestProperty` should be placed before the `TestMethod` and after the `constructor`.

**Actual Result**
The default configuration doesn't enforce the positioning of accessors and also doesn't provide any options to enforce their positioning.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.27.0` |
| `@typescript-eslint/parser`        | `2.27.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.4.0'` |
| `npm`                              | `6.9.0` |

**Comment by bradzacher** [comment] 2020-04-12 22:36
duplicate of #929

**Closed by bradzacher** 2020-04-12 22:36 UTC
Labels: duplicate, package: eslint-plugin
