### ISSUE TITLE
  1:1  error  Definition for rule '@typescript-eslint/no-unused-vars' was not found  @typescript-eslint/no-unused-vars

### ISSUE THREAD

**Issue by jordyvandomselaar** [typescript-eslint/typescript-eslint#379] opened 2019-03-27 20:21 UTC
I have the following `eslintrc.json`:

```
{
  "parser": "@typescript-eslint/parser",

  "extends": [
    "prettier",
    "plugin:prettier/recommended",
    "react-app"
  ],

  "rules": {
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": "error"
  },

  "parserOptions": {
    "ecmaVersion": 7,
    "ecmaFeatures": {
      "modules": true,
      "jsx": true
    }
  }
}
```

When running `eslint './src/**/*.ts' './src/**/*.tsx'`

I get the following error: `  1:1  error  Definition for rule '@typescript-eslint/no-unused-vars' was not found  @typescript-eslint/no-unused-vars` on every file it checks.

Versions: 

```
"@typescript-eslint/eslint-plugin": "^1.5.0",
    "@typescript-eslint/parser": "^1.5.0",
```

**Comment by platinumazure** [comment] 2019-03-27 20:31
I don't see a plugin declaration.

Try adding this to your configuration:

```
"plugins": ["@typescript-eslint"]
```

**Comment by jordyvandomselaar** [comment] 2019-03-29 12:47
Thanks for the reply! @platinumazure 

I've updated my eslint settings to include the plugin you pointed out. It now looks like this;

```json
{
  "parser": "@typescript-eslint/parser",

  "extends": [
    "prettier",
    "plugin:prettier/recommended",
    "react-app"
  ],

  "parserOptions": {
    "ecmaVersion": 7,
    "ecmaFeatures": {
      "modules": true,
      "jsx": true
    }
  },

  "plugins": [
    "@typescript-eslint"
  ]
}
```
When I run it on an example file I get the following warnings;

```
./node_modules/.bin/eslint ./src/actions/app.ts

/Users/jordyvandomselaar/workspace/vakantieadvies-app/src/actions/app.ts
  1:10  warning  'Category' is defined but never used  no-unused-vars
  2:10  warning  'Question' is defined but never used  no-unused-vars
  3:10  warning  'Answer' is defined but never used    no-unused-vars

✖ 3 problems (0 errors, 3 warnings)
```

The code inside said example file looks like this;

```typescript
import { Category } from "../interfaces/Category";
import { Question } from "../interfaces/Question";
import { Answer } from "../interfaces/Answer";

export type AppAction =
    | {
    type: "SET_CATEGORIES";
    payload: {
        categories: Category[];
    };
}

    | {
    type: "SET_QUESTIONS";
    payload: {
        questions: Question[];
    };
}
    | {
    type: "SET_ANSWERS";
    payload: {
        answers: Answer[];
    };
};
```
As you can see; these variables do get used. Am I missing anything?

**Comment by mgol** [comment] 2019-04-02 07:38
@platinumazure Any new info needed? I confirm @jordyvandomselaar results so the `awaiting response` label should be removed, shouldn't it?

**Comment by bradzacher** [comment] 2019-04-07 01:39
There is no bug here that I can see.
The base eslint rule `no-unused-vars` does not support typescript features.
As such we have created an extension of it in `@typescript-eslint/no-unused-vars`.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md

For an example of rules you should disable in favour of our variants, see our recommended config:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json

Looking at your 2nd posted config, you do not use our recommended config and you don't have any custom rule config defined, meaning you aren't actually using our rules at all.

**Comment by phaux** [comment] 2019-04-07 01:50
I'm having the same issue with `"extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended"]`

Every `Foo` that is used in type declaration as `typeof Foo` or in JSX `<Foo />` is marked as unused.

I disabled that rule because I have `"noUnusedLocals": true,` in tsconfig anyways :stuck_out_tongue:

**Comment by bradzacher** [comment] 2019-04-07 07:56
In terms of the JSX usages not working correctly - from our end, this is working as intended.

JSX is not standard javascript, nor is it "standard" typescript.
If you'd like to have JSX properly flagged in its usages, please use: https://www.npmjs.com/package/eslint-plugin-react

**Comment by kilgarenone** [comment] 2019-05-21 03:59
My ESlint complains violation of this rule even though I'm using my component:

```
import Header  from "./Header"  // eslint complains here..

function Nav() {
  return ( <Header /> );
}

**Comment by bradzacher** [comment] 2019-05-21 04:03
@kilgarenone - please open a new issue and fill in the issue template.

This issue is old, about a different problem, and has been solved.
It was left open for OP's response, but as he hasn't responded - I'm going to close this now.

**Closed by bradzacher** 2019-05-21 04:03 UTC
Labels: awaiting response, package: eslint-plugin, question

**Comment by fabb** [comment] 2019-08-21 08:20
So I can neither use "no-unused-vars" nor "@typescript-eslint/no-unused-vars" when using TypeScript + React?

**Comment by platinumazure** [comment] 2019-08-21 13:57
@fabb If you're writing React code and Typescript, you should use `@typescript-eslint/no-unused-vars` and `react/jsx-uses-vars` (and any other eslint-plugin-react rules that affect how variables are interpreted). I think that should work but I'm not positive.

The main point is that `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` will not be responsible for reading JSX and understanding component names as variable references, because JSX doesn't actually mandate that in its spec (that is a React semantic).

**Comment by fabb** [comment] 2019-08-22 06:34
True, I had some problems with `@typescript-eslint/no-unused-vars` previously, but it works now correctly, weird. Thanks!

**Comment by kv9991** [comment] 2020-02-10 08:09
I have similar issue. The problem was in package version `@typescript-eslint/eslint-plugin`.
It was 2.6.0, but `@typescript-eslint/no-unused-vars` rule works perfectly in 2.19.0.

**Comment by phaux** [comment] 2020-02-10 11:03
I also thought it was fixed, but nope. It still happens with the latest version.

## Repro

### `package.json`
```JSON
{
  "name": "app",
  "version": "0.0.0",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.19.0",
    "@typescript-eslint/parser": "^2.19.0",
    "eslint": "^6.8.0",
    "typescript": "^3.7.5"
  },
  "dependencies": {
    "preact": "^10.3.1"
  }
}
```

### `tsconfig.json`
```JSON
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
    "lib": ["DOM", "ESNext"],
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "target": "ESNext"
  }
}
```

### `.eslintrc.json`
```JSON
{
  "env": {
    "browser": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  "parserOptions": {
    "project": "./tsconfig.json"
  }
}
```

### `index.tsx`
```TSX
import { h, render } from "preact"

const App = (): h.JSX.Element => (
  <h1>Hello world!</h1>
)

render(<App />, document.body)
```

### Errors
> `h` is defined but never used.
> `App` is defined but never used.

**Comment by bradzacher** [comment] 2020-02-10 17:44
Kp with scope analysis. There are open issues for it.
Unrelated to this issue.
