### ISSUE TITLE
Bug: [no-unnecessary-type-assertion] Conflict with TS for variables used before assignment

### ISSUE THREAD

**Issue by liuxingbaoyu** [typescript-eslint/typescript-eslint#9206] opened 2024-06-02 06:31 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.6.2&fileType=.ts&code=JYMwBAFAsghgLgCwHQCcYDsAmB7AthASgLAG8BYAKDDADcYUwAPMAXjAEYBuSgX0se4VGAQkEBTRgAdsKOKR5A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0kOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkmsseAIsphVAHSQA04NkeAIaYA5ujztIAUQDKAOXQAPCbxpR4sACYBXDJIAKmdCSwA3dDz61UyAEbsA2lf6yFyyM4C6q-pvTRUYUECYnYAM0FUEx9aIlgpeGQJSjxMbXQY9S1ddAAlY1hUbRCiSQAhbSJNDDZMyGMAWWyMAEkiPCxYRHZU9LrkEkLg9E0mnQwyFLSM50hI1FgAdxakWEwCIhEAFRIpZXRSQlIe6bqSVORoZLBe9D4AXxB7oA&tokens=false

### Repro Code

```TypeScript
if (Math.random()) {
  var x = 1;
}
x;
x!;
export {}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/no-unnecessary-type-assertion":"error"
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "rootDir": ".",
    "target": "ESNext",
    "module": "Preserve",
    "lib": [
      "ESNext"
    ],
    "declaration": false,
    "noEmit": true,
    "moduleResolution": "Bundler",
    "esModuleInterop": true,
    "isolatedModules": true,
    "allowImportingTsExtensions": true,
    "strict": true
  }
}
```

### Expected Result

`x!;` should not be reported.

### Actual Result

`x!;` was reported. This conflicts with TS.

**Comment by Josh-Cena** [comment] 2024-06-02 07:15
Related: https://github.com/typescript-eslint/typescript-eslint/issues/4513

**Comment by JoshuaKGoldberg** [comment] 2024-06-03 01:51
Indeed, duplicate of #4513. Both of these issues are about variables that haven't been assigned yet. This one mentions a `var`; the other mentions a `let`. Same root issue. I'll note in #4513 that the `var` case is a relevant one that should be fixed for too. Thanks for mentioning it @liuxingbaoyu!

**Comment by Josh-Cena** [comment] 2024-06-03 02:04
@JoshuaKGoldberg They concern different rules so this definitely requires changing the code of two rules. Since it requires scope analysis instead of type information I don't think we can fix it with a util function

**Comment by JoshuaKGoldberg** [comment] 2024-06-03 02:09
_OH!_ 🤦 sorry, I should stop reviewing PRs at 10pm at night. I missed that these are different rules. Sorry! Undoing / editing all my comments.

**Comment by kirkwaiblinger** [comment] 2024-06-03 07:55
Huh. Note also
```ts
let x: string;
x; // TS use-before-define error
x!; // no TS error 
x as string; // TS use-before-define error
```

So 
1. This isn't a `var`-specific issue. 
2. It's _specifically_ the postfix `!` operator that's being interpreted as a(n) (unsound) "definite assignment" assertion, not an ordinary type assertion really at all.

**Comment by kirkwaiblinger** [comment] 2024-06-03 08:08
Huh. Note also
```ts
let x: string;
x; // TS use-before-define error
x!; // no TS error 
x as string; // TS use-before-define error
```

So 
1. This isn't a `var`-specific issue. 
2. It's _specifically_ the postfix `!` operator syntax that's being interpreted as a(n) (unsound) "definite assignment" assertion, whereas an ordinary type assertion does not have this behavior.

Probably good things to keep in mind for test cases on the PR.

Also, a PSA, the corollary of https://github.com/typescript-eslint/typescript-eslint/issues/4513#issuecomment-2144469399 for this issue is that you can do
```ts
if (Math.random()) {
  var x: number | undefined = 1;
  // note that there's no error about being possibly undefined.
  x.toFixed() 
}
x; 
x!; 
x.toFixed() // TS ERROR - 18048: 'x' is possibly 'undefined'. 
export {}
```
which is probably a safer fix as a user for the example in the issue report. 

But this issue is different from #4513, and, unlike that issue, I agree with this one being considered a bug.

**Closed** 2024-08-19 11:14 UTC
Labels: bug, package: eslint-plugin, accepting prs
