### ISSUE TITLE
Bug: [typescript-eslint] missing `eslint` transitive peer dependency

### ISSUE THREAD

**Issue by rtritto** [typescript-eslint/typescript-eslint#10078] opened 2024-09-30 22:22 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

NA

### Repro Code

```TypeScript
- `yarn init -y`
- `yarn set version berry`
- `yarn add -D eslint typescript typescript-eslint`
- see logs
```

### ESLint Config

```javascript
NA
```

### tsconfig

```jsonc
NA
```

### Expected Result

No warning in logs:
```console
➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed                                                                                                                       
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ No packages can be deduped using the highest strategy
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings
```

`yarn explain peer-requirements`
```console
p6025f → ✓ typescript-eslint@npm:8.8.0 [3223e] doesn't provide @types/eslint to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3] and 3 other dependencies
p815e2 → ✓ typescript-eslint@npm:8.8.0 [3223e] doesn't provide @types/typescript-eslint__parser to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3]
p97120 → ✓ typescript-eslint@npm:8.8.0 [3223e] provides @typescript-eslint/parser@npm:8.8.0 [198f3] to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3]
p8687d → ✓ typescript-eslint@npm:8.8.0 [3223e] provide eslint to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3] and 3 other dependencies
```

### Actual Result

Warning in logs:
```console
➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed                                                                                                                       
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ No packages can be deduped using the highest strategy
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings
```

`yarn explain peer-requirements`
```console
p6025f → ✓ typescript-eslint@npm:8.8.0 [3223e] doesn't provide @types/eslint to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3] and 3 other dependencies
p815e2 → ✓ typescript-eslint@npm:8.8.0 [3223e] doesn't provide @types/typescript-eslint__parser to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3]
p97120 → ✓ typescript-eslint@npm:8.8.0 [3223e] provides @typescript-eslint/parser@npm:8.8.0 [198f3] to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3]
p8687d → ✘ typescript-eslint@npm:8.8.0 [3223e] doesn't provide eslint to @typescript-eslint/eslint-plugin@npm:8.8.0 [198f3] and 3 other dependencies
```

### Additional Info

A workaround (with yarn berry):
```yml
# .yarnrc.yml
packageExtensions:
  typescript-eslint@*:
    peerDependencies:
      eslint: "*"
```

An article, related to transitive peer dependencies, written by author of yarn package manager: [Implicit Transitive Peer Dependencies](https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0).

**Comment by bradzacher** [comment] 2024-09-30 22:52
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/9224

**Closed by bradzacher** 2024-09-30 22:52 UTC
Labels: bug, package: eslint-plugin, triage
