### ISSUE TITLE
Feature request: support looking up tsconfig.json relative to linted file

### ISSUE THREAD

**Issue by Jessidhia** [typescript-eslint/typescript-eslint#101] opened 2019-01-21 03:27 UTC
Currently, the `eslint-plugin-tslint` throws if any of:

```ts
      /**
       * The user needs to have configured "project" in their parserOptions
       * for @typescript-eslint/parser
       */
      if (!parserServices || !parserServices.program) {
        throw new Error(
          `You must provide a value for the "parserOptions.project" property for @typescript-eslint/parser`
        );
      }
```

or `lintFile` are missing. If `lintFile` is missing it'll just lint nothing instead of throwing, unless there are inline configs.

---

`parserOptions.project` is completely undocumented in `@typescript-eslint/parser`, and at any rate that would need to be autodetectable for this use case to work. Currently, services are just silently not generated if it's missing:

```ts
  const shouldProvideParserServices =
    shouldGenerateServices && extra.projects && extra.projects.length > 0;
```

This is despite there being a `getASTAndDefaultProject`, which looks like it could do the right thing. It's just unreachable code unless you already gave a project to begin with.

On further reading, it looks like the `tsconfig.json` can be relative, but it's by default calculated relative to `process.cwd()` and not to the current `eslintrc` being processed, or an ancestor lookup relative to the current file. The option to change that (`tsconfigRootDir`) is also undocumented and still can't do what I want.

---

Secondly, it should be possible to make the `tslint.json` also be relative to either the current `tsconfig.json`, the current `eslintrc`, or to also do a ancestor lookup from the current file.

---

I think that for most people's use cases the `process.cwd()` or `path.resolve(__dirname, "tslint.json")` approach could work, but in my use case I'm trying to make a single shareable eslint config for a monorepo and simply reuse it with `"eslintConfig": { "extends": ["@scope/eslint-config"] }`. This works for me for everything _except_ these use cases. Note that `path.resolve(__dirname, "tslint.json")` would still be wrong if a specific project has a different `tslint.json` than the one the shared eslint-config has.

Even if I leave it to run per project, I still have some specific folders that have a different `tsconfig.json` nested inside an outer `tsconfig.json` that belongs to the same project. e.g. a service worker would have `worker` instead of `dom` in its `lib` config. I can still probably deal with this through refactoring, but it sounds like something that could/should be supported; or at least vscode can support it.

**Comment by j-f1** [comment] 2019-01-21 12:44
I think the rationale here was to avoid generating some objects needed to support the type checking if the user doesn’t request them.

**Comment by SimenB** [comment] 2019-02-01 13:39
Got bit by this as well. I'd like to use the new `no-unnecessary-type-assertion` rule, but is unable to due to our repo being a monorepo, with each package having its own `tsconfig.` extending either `tsconfg.node.json` or `tsconfig.browser.json` in the root of the repo (also using composite projects, fwiw).

>I think the rationale here was to avoid generating some objects needed to support the type checking if the user doesn’t request them.

Can I say "please generate the objects needed, I want type info"? Seems like something that should be a boolean turning "look up closest tsconfig.json" on or off

**Comment by SimenB** [comment] 2019-02-02 11:31
Yeah, something like that'd be perfect :)

**Comment by janbiasi** [comment] 2019-06-05 16:19
Any updates on this?

**Comment by bradzacher** [comment] 2019-06-06 00:22
we won't ever auto-detect the project. As soon as we do that, we would force every user to go through a complete typescript compile by just including one of rules.
A lot of users currently avoid rules that require typeinfo because they can cause large perf impacts on some codebases.

----

This can be worked around using `tsconfigRootDir`:
```js
module.exports = {
    parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: __dirname,
    },
}
```
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#configuration

If you don't specify `tsconfigRootDir`,  we default to using the CWD because that's how the rest of node works, and how the typescript compiler works.

i.e. if you were to unravel all of our code _and_ typescript's code, you'll see that essentially the algorithm for resolving the provided path is essentially:
```js
const rawConfig = fs.readFileSync(
  path.resolve(
    process.cwd(),
    options.tsconfigRootDir || process.cwd(), // note path.resolve(process.cwd(), process.cwd()) === process.cwd()
    options.project,
  ),
);
```

**Comment by Jessidhia** [comment] 2019-06-06 01:58
The idea was not to "autodetect when a rule that needs it is included", but to have an option where which `tsconfig.json` is used to check the file is not hardcoded in the config, but looked up in relation to the file being linted.

The requirement to be able to specify `__dirname` also prevents shared configs from being used via json or `package.json` configs and the individual configs must be written as a commonjs module.

It is a possible workaround, but one that is harder to make use of than an option to enable searching upwards for a `tsconfig.json`; and I still don't know what happens if different files are linted with different effective `tsconfig.json` files, as would happen in a monorepo eslint pass.

**Comment by bradzacher** [comment] 2019-06-06 06:13
> what happens if different files are linted with different effective tsconfig.json files, as would happen in a monorepo eslint pass

If you have a tsconfig.json in your root (which I think you need for vscode to handle it??) then it will work as expected as long as your compiler options are consistent between projects in a monorepo.
This is how we've got it setup in this repo - a root tsconfig which defines the compiler options and then tsconfigs for each project which extend that root config and define the output paths and includes etc.

> individual configs must be written as a commonjs module
I didn't think this was a huge problem - from the eyes of your codebase, it's 2 letters in an extension plus a one line change?

---

Don't get me wrong, I do understand that it's not a perfect solution, but it's a workaround for now.
Happy for someone to PR a change for this though.

**Comment by bencelang** [comment] 2022-06-07 18:12
This would be extremely useful in monorepos, where you have some projects with per-project unique rulesets and you want to be able to run eslint from the monorepo root and the projects roots as well. I prefer yaml for configuration and `__dirname` is not an option in that case

**Comment by bradzacher** [comment] 2022-06-07 18:22
> I prefer yaml for configuration

@bencelang I have bad news for you.
YAML configs are going away in a future version of ESLint (as are JSON configs).
https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification#the-eslintconfigjs-file

I would migrate away from YAML to JS to avoid future pain.

**Comment by bencelang** [comment] 2022-06-07 18:42
@bradzacher Thanks for the heads up! I'll give the JS migration a shot throughout my projects.

> individual configs must be written as a commonjs module

However, are ESM config files expected to be supported at some point? One of the reasons why we started using YAML configuration was to help avoid mixed commonjs/esm codebases

**Comment by bradzacher** [comment] 2022-06-07 18:51
That RFC was added in 2019, before ESM was properly supported by node. ESLint has since added support for the `.cjs` extension for the config file - which you can (and should) use if you've got an ESM project.

The ESLint team is [currently discussing the migration to ESM](https://github.com/eslint/rfcs/pull/88). It's a complicated topic to navigate for such a prominent package.

**Comment by JoshuaKGoldberg** [comment] 2022-11-25 05:27
This issue is very old but very juicy - I'd love to be able to shorthand `project: true` instead of specifying other files. Adding to the [v6 milestone](https://github.com/typescript-eslint/typescript-eslint/milestone/8). 😄

**Comment by bradzacher** [comment] 2022-11-25 05:58
It's worth noting that this would cause some perf regressions because disk lookups are going to be more expensive than a static config. Also depending on project setup you might have some "useless" tsconfigs that we waste time interrogating before finding the correct tsconfig for a file.

In terms of the config style - `project: true` probably isn't quite good enough for all usecases. For example it's not uncommon to define `tsconfig.eslint.json` (or other named tsconfigs).
Maybe we'll need to do something like this:
- `project: true` - just use the closest `tsconfig.json` on disk for each linted file.
- `project: { allowedTsconfigNames: FileName[], ignoredTsconfigs: RelativePath[] }`
  - `allowedTsconfigNames` to specify the set of names you want us to search (default `['tsconfig.json']`
  - `ignoredTsconfigs` to ignore specific tsconfigs you know would be useless.

The complicated thing in this algorithm will be determining which tsconfig to use and cache it. It's completely possible for two files in the same folder to be covered by different tsconfigs - so we can't just assume all files in a given folder are covered by the same tsconfig. This means that for every single file we'll need to do a lookup to figure out the tsconfig to use. I believe we can use TS's infra to parse the tsconfig and get the list of files it contains without having to go through the expensive program generation (which should save *some* time).

For CLI runs we can assume tsconfigs are constant and aggressively cache all this stuff so we only need calculate it once per tsconfig. It should be relatively simple to implement for this usecase.

For persistent IDE runs it's going to be a lot more complicated because we can't attach disk watchers and we can't assume that tsconfigs are static in content or location. I don't know the best way for us to handle this - maybe we need to investigate how vscode does it? I assume they probably have file watchers. We have [invalidation logic](https://github.com/typescript-eslint/typescript-eslint/blob/f02761af19848a84b8d1832bd00fd6c95d38fa0c/packages/typescript-estree/src/create-program/createWatchProgram.ts#L421) which handles the "tsconfig was changed" usecase, but I don't know how we can efficiently handle the "tsconfig was added/moved" usecase without watchers. Maybe we'll just need to fuzzily cache for some time period for perf reasons and hope that it doesn't cause too much weirdness? Not sure what the best solution will be!

**Comment by JoshuaKGoldberg** [comment] 2022-11-25 06:08
> project: true probably isn't quite good enough for all usecases
> something like this: ...

Agreed, and that feels like a followup issue to me 😄. Let's get `true` to "just" work out of the box for users first, and then add in more controls around it?

> fuzzily cache for some time period for perf reasons

Yeah, I've been playing with this. I verified locally that `createParseSettings` is called whenever a file is linted in VS Code, so as long as the _"does this `tsconfig.json` file exist on disk?"_ cache doesn't last more than a few dozen milliseconds, I feel comfortable going with a straightforward approach like that.

**Closed** 2023-02-10 03:32 UTC
Labels: enhancement, package: parser, package: typescript-estree, accepting prs

**Comment by SimenB** [comment] 2023-02-13 17:22
![Alt Text](https://media.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif)
