### ISSUE TITLE
Bug: single run mode breaks with fixers

### ISSUE THREAD

**Issue by hasakilol** [typescript-eslint/typescript-eslint#9344] opened 2024-06-13 05:03 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://github.com/hasakilol/react-vite/blob/master/src/Test.tsx

### Repro Code

1. This is update to: https://github.com/typescript-eslint/typescript-eslint/issues/9230
2. I can't give you a reproduction on https://typescript-eslint.io/play/ because I'm using latest eslint and typescript-eslint packages.

### ESLint Config

```javascript
import tseslint from 'typescript-eslint';
import globals from 'globals';
import parser from '@typescript-eslint/parser';


export default tseslint.config(
  {
    name: 'plugins',
    plugins: {
      ['@typescript-eslint']: tseslint.plugin,
    },
  },
    
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.es2015,
      },
      parserOptions: {
        allowAutomaticSingleRunInference: true,
        project: ['tsconfig.json'],
        tsconfigRootDir: '.',
      }
    },
  },

  {
    name: 'src',
    files: ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.mts', 'src/**/*.cts'],
    extends: tseslint.configs.recommendedTypeChecked,
    languageOptions: {
      parser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        },
        sourceType: 'module',
      },
      globals: {
        ...globals.browser,
        ...globals.mocha,
        ...globals.jest,
        ...globals.jasmine,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-duplicate-type-constituents': 'error'
    }
  },

    
);
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

### Expected Result

https://github.com/hasakilol/react-vite/blob/master/src/Test.tsx#L8

No matter how you configure `@typescript-eslint/consistent-type-imports` ('off' or 'error') and `@typescript-eslint/no-duplicate-type-constituents`  ('off' or 'error'),
`item: { a: string; } | typeof Null | typeof Undefined,` should not change after running `npx eslint --fix src/Test.tsx`.

### Actual Result

When both `@typescript-eslint/consistent-type-imports` and `@typescript-eslint/no-duplicate-type-constituents` are configured `error`, `item: { a: string; } | typeof Null | typeof Undefined,` is changed to `item: { a: string; } | typeof Null ,`  after running `npx eslint --fix src/Test.tsx`.

When either `@typescript-eslint/consistent-type-imports`  or `@typescript-eslint/no-duplicate-type-constituents` are configured `off`, `item: { a: string; } | typeof Null | typeof Undefined,` will not change (what I expect)  after running `npx eslint --fix src/Test.tsx`.

### Additional Info

"@typescript-eslint/eslint-plugin": "^8.0.0-alpha.14",
"@typescript-eslint/parser": "^8.0.0-alpha.14",
"@typescript-eslint/scope-manager": "^8.0.0-alpha.14",
"@typescript-eslint/type-utils": "^8.0.0-alpha.14",
"@typescript-eslint/types": "^8.0.0-alpha.14",
"@typescript-eslint/typescript-estree": "^8.0.0-alpha.14",
"@typescript-eslint/utils": "^8.0.0-alpha.14",
"@typescript-eslint/visitor-keys": "^8.0.0-alpha.14",
"typescript-eslint": "^8.0.0-alpha.14",

"eslint": "^9.3.0",

**Comment by bradzacher** [comment] 2024-06-13 07:05
You're mistaken about the cause.
It's got nothing to do with the specific rules you're using - it's a bug with the "single run" inference infrastructure.
If you pass `disallowSingleRunInference: true` it'll work around things for now.

debug output with single-run inference turned on:
```
$ DEBUG=typescript-eslint:* npx eslint --fix
  typescript-eslint:typescript-estree:parser:parseSettings:resolveProjectList parserOptions.project (excluding ignored) matched projects: Map(1) { 'tsconfig.json' => 'tsconfig.json' } +0ms
  typescript-eslint:typescript-estree:useProvidedProgram Retrieving ast for /Users/bjz/temp/react-vite-master/src/Test.tsx from provided program instance(s) +0ms
  typescript-eslint:typescript-estree:parser Detected single-run/CLI usage, creating Program once ahead of time for project: [ 'tsconfig.json', 'tsconfig.json' ] +0ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom', 'dom.iterable' ] +0ms
  typescript-eslint:typescript-estree:createIsolatedProgram Getting isolated program in TSX mode for: /Users/bjz/temp/react-vite-master/src/Test.tsx +0ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'esnext.full' ] +71ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +0ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +0ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +1ms
  typescript-eslint:typescript-estree:createIsolatedProgram Getting isolated program in TSX mode for: /Users/bjz/temp/react-vite-master/src/Test.tsx +13ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'esnext.full' ] +12ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +7ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +1ms
  typescript-eslint:typescript-estree:useProvidedProgram Retrieving ast for /Users/bjz/temp/react-vite-master/src/App.tsx from provided program instance(s) +668ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom', 'dom.iterable' ] +10ms
  typescript-eslint:typescript-estree:useProvidedProgram Retrieving ast for /Users/bjz/temp/react-vite-master/src/utils/common.ts from provided program instance(s) +55ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom', 'dom.iterable' ] +51ms
  typescript-eslint:typescript-estree:useProvidedProgram Retrieving ast for /Users/bjz/temp/react-vite-master/src/main.tsx from provided program instance(s) +3ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom', 'dom.iterable' ] +3ms
  typescript-eslint:typescript-estree:useProvidedProgram Retrieving ast for /Users/bjz/temp/react-vite-master/src/vite-env.d.ts from provided program instance(s) +6ms
  typescript-eslint:parser:parser Resolved libs from program: [ 'es2020', 'dom', 'dom.iterable' ] +6ms
```

Note all of the `Found an "error" any type` logs - these occur on the second lint pass after the `consistent-type-imports` error is fixed.

---

cc @JoshuaKGoldberg this is a blocker for the v8 release as we can't rollout single run inference by default with this bug.

Note: I haven't investigated any further than just doing a debug run in the user's repo.

**Comment by bradzacher** [comment] 2024-06-13 07:14
> This then causes `no-duplicate-type-constituents` to see `T | any | any` - so the rule then acts on this information to remove the second `any` as it is superfluous based on the types.

***TBH this is a separate bug that should be fixed***
`no-duplicate-type-constituents` should probably detect that a type is an "error `any`" and treat it as a completely unique type each time so that it doesn't accidentally change code in the case of broken types.

**Comment by JoshuaKGoldberg** [comment] 2024-06-13 08:52
_YES_ this is the bug we were talking about wanting a repro for! _(can't find the reference right now, but it's somewhere)_

Relevant: the current limitations of ESLint described in https://github.com/eslint/rfcs/pull/102, as with other issues, makes this tricky.

**Comment by JoshuaKGoldberg** [comment] 2024-07-18 03:35
I set up a more streamlined standalone repro here: https://github.com/JoshuaKGoldberg/repros/tree/tseslint-single-run-inference-introducing-bugs-in-fix

**Comment by bradzacher** [comment] 2024-07-18 04:15
@JoshuaKGoldberg I think this is the real bug we should look at fixing:

> ESLint then does a second lint pass (it tries to exhaustively apply fixers). **_During this lint pass for whatever reason the type information is borked_** and so both the Null and Undefined imports are any (hence there are 3 Found an "error" any type logs - one for each usage of the imports.)

We can disable single-run inference during a fix run as a band-aid, but we probably want to fix the underlying bug.

**Comment by JoshuaKGoldberg** [comment] 2024-07-18 04:28
> > the real bug we should look at fixing:
> ... During this lint pass for whatever reason the type information is borked

Agreed. I have no idea how to fix that right now though. 😬

**Comment by JoshuaKGoldberg** [comment] 2024-07-18 16:37
Fixed by #9577.

**Closed by JoshuaKGoldberg** 2024-07-18 16:37 UTC
Labels: bug, package: typescript-estree, team assigned
