### ISSUE TITLE
Bug: [no-wrapper-object-types] false positive for Symbol in ts namespace

### ISSUE THREAD

**Issue by HolgerJeromin** [typescript-eslint/typescript-eslint#9756] opened 2024-08-08 11:56 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I want to move away from `@typescript-eslint/ban-types` to `@typescript-eslint/no-wrapper-object-types` but I have a namespace based ts project which has `HMI.Symbol` and `HMI.System.Symbol` classes. 
They work typescript wise without problems. So when I am inside the `HMI` namespace I can use `Symbol` without the prefix.
This is not detected in any case by the new rule `@typescript-eslint/no-wrapper-object-types`. With `ban-types` I could skip check for `Symbol`. 

### Reproduction Repository Link

https://github.com/HolgerJeromin/ts-eslint_wrapper-object-types_namespace

### Repro Steps

1) clone the repo
2) `npm install`
3) `.\node_modules\.bin\eslint.cmd  -c .\.eslintrc.js  .\Symbol.ts .\Usage.ts`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.0.1` |
| `@typescript-eslint/parser`            | `8.0.1` |
| `TypeScript`                           | `5.5.x` |
| `ESLint`                               | `8.57.0` |

**Comment by bradzacher** [comment] 2024-08-08 12:28
Reporting on `Symbol` is fully expected here because as far as the rule can tell syntactically -- it looks like you're using the global `Symbol` type (And technically you _could_ actually be using it -- eg if the other file gets deleted!)

The only way for us to handle this usecase is to use type information so we can ask TS where the `Symbol` identifier is defined. However the rule is intentionally _not_ type-aware because this usecase is a fraction of a fraction of a fraction of a percent now-a-days - so bringing type info in is not worth the restrictions it brings.

Put another way - you've just unfortunately hit an edge case because you're using some very rarely used (and kind of deprecated) TS mechanisms for sharing things globally across files without an import.
In general in modern TS this style of code is very rare because ESM is the way things are done now - you export from one file and import from another.

That would be my recommendation, TBH -- update your code to use ESM.

---

In terms of ways forward...
First let me be clear that we will not be adding type info to the rule to handle this case.

You say you could work around this with the old rule because you could turn off Symbol checks and that's true. The new rule is not configurable because we didn't have a usecase for anyone wanting to be allowed to use a specific wrapper type. `ban-types` was configurable because it was a generic rule that did everything and `Symbol` was banned via our "sensible defaults".

TBH I'm not convinced that we should build options for this. It seems like a chunk of work and maintenance burden for what is a 1 in 10 million usecase now-a-days.

Thoughts @typescript-eslint/triage-team?

**Comment by JoshuaKGoldberg** [comment] 2024-08-08 13:59
I think I'm in agreement here, yeah. The combination of:

* Using namespaces merged across files: which is no longer something folks recommend
* Naming something `Symbol`: which is generally confusing in intersecting with the global type

...isn't IMO worth the cost of making this type-aware.

**Comment by HolgerJeromin** [comment] 2024-08-08 15:11
> Naming something Symbol: which is generally confusing in intersecting with the global type

You are right. But our Framework dates before the invention of `Symbol` in JS world and we have to keep the name in our API...

IMO it is fully ok to not fix the `Symbol` detection. This is probably even better regards performance.
But I would like to have an option like `{skipType: ['Symbol']}`

**Comment by Josh-Cena** [comment] 2024-08-08 15:57
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/6262?

**Comment by bradzacher** [comment] 2024-08-08 21:29
@Josh-Cena no - that one was about using the name within a file that defined the name. The new rule no longer reports on that. This case reports because the name is defined in another file and is brought in via cross-file declaration merging.

**Comment by bradzacher** [comment] 2024-08-08 21:30
> But I would like to have an option like {skipType: ['Symbol']}

That's what I [was mentioning above](https://github.com/typescript-eslint/typescript-eslint/issues/9756#issuecomment-2275700351):

> TBH I'm not convinced that we should build options for this. It seems like a chunk of work and maintenance burden for what is a 1 in 10 million usecase now-a-days.

**Comment by Josh-Cena** [comment] 2024-08-08 21:36
_Maybe_ we can have an `allow` option that allows specified identifiers—I'm +0.1 since it doesn't sound crazy complex, but also okay if we think the use case is marginal.

**Closed** 2024-08-09 09:03 UTC
Labels: bug, triage
