### ISSUE TITLE
[@typescript-eslint/indent] False positive on arguments on multi-lines when one is binary op expression that spanning two lines

### ISSUE THREAD

**Issue by jeremymeng** [typescript-eslint/typescript-eslint#292] opened 2019-02-18 06:40 UTC
**Repro**

```js
module.exports = {
  parser: '@typescript-eslint/parser', // Specifies the ESLint parser
  extends: [
    'plugin:@typescript-eslint/recommended', // Uses the recommended rules from the @typescript-eslint/eslint-plugin
  ],
  parserOptions: {
    ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
    sourceType: 'module', // Allows for the use of imports
  },
  rules: {
    // Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
    // e.g. "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/indent": ["warn", 2],
  },
};

```

```TS
let b = "s";
let c = { }
console.log("hello " +
  "world", a,
  b, c);
```

**Expected Result**
No warning, or warning on the "world" line if the indent isn't right

**Actual Result**
```
  6:1  warning  Expected indentation of 0 spaces but found 2  @typescript-eslint/indent
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.3.0` |
| `@typescript-eslint/parser`        | `1.3.0` |
| `TypeScript`                       | `3.3.3` |
| `ESLint`                           | `5.14.0` |
| `node`                             | `11.9.0` |
| `npm`                              | `6.7.0` |

**Comment by bradzacher** [comment] 2019-02-19 00:05
This is not a problem with our implementation - we just extend the base rule with typescript cases.

This is a bug in the base rule:
https://eslint.org/demo/#eyJ0ZXh0IjoibGV0IGIgPSBcInNcIjtcbmxldCBjID0geyB9XG5jb25zb2xlLmxvZyhcImhlbGxvIFwiICtcbiAgXCJ3b3JsZFwiLCBhLFxuICBiLCBjKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiaW5kZW50IjoyfSwiZW52Ijp7ImNvbW1vbmpzIjpmYWxzZSwibm9kZSI6ZmFsc2V9fX0=

**Comment by jeremymeng** [comment] 2019-02-19 19:09
@bradzacher awesome site! I didn't know about that. Thanks.

Do I need to move this issue?

**Comment by bradzacher** [comment] 2019-02-19 19:17
If you wouldn't mind raising an issue in the eslint code, that'd be great.
Please link to this issue (or vice versa) so we can track when the base rule is fixed.

**Comment by bradzacher** [comment] 2019-11-17 19:20
based on the discussion in https://github.com/eslint/eslint/issues/9706
This isn't going to be fixed in the base rule, as it's workgin as intended.
Closing.

**Closed by bradzacher** 2019-11-17 19:20 UTC
Labels: bug, package: eslint-plugin, upstream
