### ISSUE TITLE
ESLint Not Catching Missing Type Annotations for Method Parameters in TypeScript Interfaces

### ISSUE THREAD

**Issue by ngangeti** [typescript-eslint/typescript-eslint#10183] opened 2024-10-20 17:08 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

ESLint is not reporting missing type annotations for method parameters in TypeScript interfaces, even though other annotations, such as properties and return types, are enforced. The @typescript-eslint/typedef rule is configured to catch missing type annotations, and it works correctly for class methods but fails for methods defined in interfaces. Despite being set to enforce parameter type annotations, ESLint does not flag violations for method parameters within interfaces, while class methods with missing type annotations are reported as expected. This behavior creates inconsistency in how the rule is applied between interfaces and classes.

### Reproduction Repository Link

https://github.com/ngangeti/eslint-error

### Repro Steps

1. Clone the repository from [GitHub Repository](https://github.com/ngangeti/eslint-error).
2. Navigate to the project directory.
3. Install dependencies using:
npm install
4. Run ESLint against the src directory using:
npm run analyse

Observe the ESLint output to see that no errors are reported for the missing type annotation in the getHeaderElementByText method parameter in the interface, while the class method is correctly flagged for missing type annotations.

### Versions

Node.js Version: 20.12.2
NPM Version: 10.5.0
ESLint Version: 9.13.0
@typescript-eslint/eslint-plugin Version: 8.10.0
@typescript-eslint/parser Version: 8.10.0
TypeScript Version: 5.6.3

**Comment by Josh-Cena** [comment] 2024-10-20 17:19
Please don't use repos unless the reproduction requires complicated setup. In this case you could use [the playground](https://typescript-eslint.io/play#ts=5.5.4&fileType=.tsx&code=FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIASI2AJhgMoi5xJQoIDewCCA5iHMWRgKIA2IALYg0ACgAWJcjAAq4OAEoAXAgDOcGKjYBuBAHp9CALJI1a7QjgBPCAWwoUUONlr0EmWAik85C5Ayo6Fh4IAA0CE6IuNgArmwSiABG1gggavxBwAC%2BwMC4-NjmRNIYyEIQgiJoaiW%2BVDR0DMysHFylMALConCSHfJgSqoaWihsTAZGpuaWNnYIDlGuTR5ePjIDiKgIBUVqETHxiQgpaRlZrKwwnLEwDAAG3DJpVT2qACSM6xib2fc6LAQuVy%2BXoGm8HVUTzKAF5IiAAO51GRiRQA3BgqCCAB0-CgbD6vmxbWhnVe4gA5AB1ED8DEiCmKNHAIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6I0gE0QDN0wA2uGw5E0aAHtokADTCRWEUpwBDcSsIARFPjhl8sKkwDm-XbERzlyyGskB3AApqVAW0T4xZuJfnWc7q4ARmIAamqUKkFI2mTwLviUEkzeFlb%2B2JASQQBWiPrayOb6hsymGOa%2BGZnELu6e0hU%2B6dWQxJKk0ESx8dAqicmpVdVQAG4RUTH5vf1JKU0WfhAAvn4AusKry0A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false) directly.

This appears unexpected, but this rule is only designed to catch value-space identifiers that don't have types attached. It does not check type declarations to see if they are well-formed and complete. IMO we should add a check though.

**Comment by bradzacher** [comment] 2024-10-20 21:13
-1 on this
the rule is not intended to cover all cases and it's intended to be a migration rule to help you add annotations and onboard onto `noImplicitAny`.

The rule is feature frozen and is not accepting additional checks.

[The `noImplicitAny` compiler option covers this case](https://typescript-eslint.io/play#ts=5.5.4&fileType=.tsx&code=FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIASI2AJhgMoi5xJQoIDewCCA5iHMWRgKIA2IALYg0ACgAWJcjAAq4OAEoAXAgDOcGKjYBuBAHp9CALJI1a7QjgBPCAWwoUUONlr0EmWAik85C5Ayo6Fh4IAA0CE6IuNgArmwSiABG1gggavxBwAC%2BwMC4-NjmRNIYyEIQgiJoaiW%2BVDR0DMysHFylMALConCSHfJgSqoaWihsTAZGpuaWNnYIDlGuTR5ePjIDiKgIBUVqETHxiQgpaRlZrKwwnLEwDAAG3DJpVT2qACSM6xib2fc6LAQuVy%2BXoGm8HVUTzKAF5IiAAO51GRiRQA3BgqCCAB0-CgbD6vmxbWhnVe4gA5AB1ED8DEiCmKNHAIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6I0gE0QDN0wA2uGw5E0aAHtokADTCRWEUpwBDcSsIARFPjhl8sKkwDm-XbERzlyyGskB3AApqVAW0T4xZuJfnWc7q4ARmIAamqUKkFI2mTwLviUEkzeFlb%2B2JASQQBWiPrayOb6hsymGOa%2BGZnELu6e0hU%2B6dWQxJKk0ESx8dAqicmpVdVQAG4RUTH5vf1JKU0WfhAAvn4AusKry0A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUhFYASSSomyPAEEiATwphR6KQF8Q%2BoA&tokens=false)

**Comment by JoshuaKGoldberg** [comment] 2024-11-04 17:44
Looks like we have consensus as a wontfix, for Brad's posted reason. Thanks for filing!

**Closed by JoshuaKGoldberg** 2024-11-04 17:44 UTC
Labels: bug, package: eslint-plugin, triage
