### ISSUE TITLE
v2.8.0 Throws an error when webpack entry is a CSS file

### ISSUE THREAD

**Issue by Nikodermus** [typescript-eslint/typescript-eslint#1238] opened 2019-11-19 16:44 UTC
**What code were you trying to parse?**
My regular codebase, I'm using a css entry in webpack as
```javascript
config.entry = ['./src/VenueMap.css', './src/VenueMap.ts'];
```

**What did you expect to happen?**
Ignore the CSS file and parse only the TS file
```javascript
    config.module.rules.push({
                enforce: 'pre',
                exclude: /node_modules/,
                loader: 'eslint-loader',
                test: /\.(js|ts)$/,
                options: {
                    fix: true
                }
            });
```

**What actually happened?**
It throws the following error:
```
ERROR  in ./src/VenueMap.ts
Module build failed (from ./node_modules/eslint-loader/dist/cjs.js):
TypeError: Cannot read property '0' of undefined
    at Linter.autoFix (/Users/liam/projects/maps/venue-map-component/node_modules/eslint-loader/dist/Linter.js:117:20)
    at Linter.printOutput (/Users/liam/projects/maps/venue-map-component/node_modules/eslint-loader/dist/Linter.js:77:12)
    at Object.loader (/Users/liam/projects/maps/venue-map-component/node_modules/eslint-loader/dist/index.js:26:10)
 @ multi ./src/VenueMap.css ./src/VenueMap.ts main[1]
✖ Creating UMD builds
Error running command: Build failed with errors.
Error: Build failed with errors.
    at compiler.run (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/lib/webpackBuild.js:76:17)
    at finalCallback (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:259:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/liam/projects/maps/venue-map-component/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/liam/projects/maps/venue-map-component/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:372:39)
    at emitAssets.err (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:358:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/liam/projects/maps/venue-map-component/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/liam/projects/maps/venue-map-component/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/Users/liam/projects/maps/venue-map-component/node_modules/nwb/node_modules/webpack/lib/Compiler.js:355:27)
    at /Users/liam/projects/maps/venue-map-component/node_modules/neo-async/async.js:2830:7
    at done (/Users/liam/projects/maps/venue-map-component/node_modules/neo-async/async.js:2865:11)
    at /Users/liam/projects/maps/venue-map-component/node_modules/neo-async/async.js:2818:7
    at /Users/liam/projects/maps/venue-map-component/node_modules/graceful-fs/graceful-fs.js:57:14
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.8.0` |
| `TypeScript`                | `3.7.2` |
| `ESLint`                    | `6.6.0` |
| `node`                      | `12.13.0` |
| `npm`                       | `6.12.0` |

**Workaround**
I fixed parser and eslint-plugin version to 2.7.0 and it works

**Comment by bradzacher** [comment] 2019-11-19 17:21
Thanks for reporting.

Could you please provide a more minimal repro case? You've got a webpack environment setup, but we don't.
We don't have the spare time to learn how to use webpack + css-loader, and then figure out how to repro your environment and config.

If you could create an small, isolated example repo which shows the bug, it would make it easier to investigate.

**Comment by glen-84** [comment] 2019-11-19 18:17
https://github.com/webpack-contrib/eslint-loader/issues/306

**Comment by bradzacher** [comment] 2019-11-19 18:24
Interesting - so according to that issue the exact same bug is triggered without using our plugin/parser.
I'm going to assume that this is not a bug in our project then, and close this.

If it turns out that it is a bug in here, feel free to comment with more info and we can reopen and investigate.

**Closed by bradzacher** 2019-11-19 18:24 UTC
Labels: awaiting response, package: parser
