### ISSUE TITLE
Bug: typescript-eslint Playground crashes on load

### ISSUE THREAD

**Issue by yasha-spare** [typescript-eslint/typescript-eslint#7965] opened 2023-11-20 22:06 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Repro Code

The [type-script-estlint Playground](https://typescript-eslint.io/play/) (which I find wildly helpful for writing custom rules!) never loads anymore for me or my coworkers, it always shows:

```
This page crashed.
Cannot read properties of undefined (reading 'collapsedSizePercentage')
```

The full error in the JS console looks like:

```
TypeError: Cannot read properties of undefined (reading 'collapsedSizePercentage')
    at x (2532.e75e083e.js:1:43069)
    at w (2532.e75e083e.js:1:43871)
    at ce (2532.e75e083e.js:1:59747)
    at 2532.e75e083e.js:1:56300
    at Object.expand (2532.e75e083e.js:1:42559)
    at 7178.27747b44.js:1:49498
    at al (main.d2147a08.js:2:350385)
    at xc (main.d2147a08.js:2:370515)
    at cc (main.d2147a08.js:2:362816)
    at Ua (main.d2147a08.js:2:303778)
ps @ main.d2147a08.js:2
```

### Expected Result

The page loads without crashing

### Actual Result

The page fails to load, crashing with the error: `Cannot read properties of undefined (reading 'collapsedSizePercentage')`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
| `@typescript-eslint/parser`            | `X.Y.Z` |
| `@typescript-eslint/rule-tester`       | `X.Y.Z` |
| `@typescript-eslint/scope-manager`     | `X.Y.Z` |
| `@typescript-eslint/typescript-estree` | `X.Y.Z` |
| `@typescript-eslint/type-utils`        | `X.Y.Z` |
| `@typescript-eslint/utils`             | `X.Y.Z` |
| `TypeScript`                           | `X.Y.Z` |
| `ESLint`                               | `X.Y.Z` |
| `node`                                 | `X.Y.Z` |

**Comment by JoshuaKGoldberg** [comment] 2023-11-20 22:08
Duplicate of #7962 - thanks for filing though!

Fixed just a couple minutes before you posted. 😎

**Closed by JoshuaKGoldberg** 2023-11-20 22:08 UTC
Labels: bug, triage

**Comment by yasha-spare** [comment] 2023-11-20 22:17
Whoops missed that in my search, and ty for fixing, can confirm that it works for me too :)
