### ISSUE TITLE
Export rule options types

### ISSUE THREAD

**Issue by noftaly** [typescript-eslint/typescript-eslint#3853] opened 2021-09-07 17:57 UTC
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Expected Result**

It'd be great if all rule options types (interfaces) were exported, so we can use them in our configuration.

I've made a pretty big custom configuration with all the rules from typescript-eslint (and other plugins), but it's very likely that there are mistakes (rule misspelled, error in the options etc...).
If they were exported, I could type-check them (and then compile the configuration to JS, that's not a problem as it is exported as a lib). 

**Actual Result**

Rule options are not exported

**Additional Info**

Sorry if this is a duplicate, but I couldn't find any similar issues.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.31.0` |
| `@typescript-eslint/parser`        | `4.31.0` |
| `TypeScript`                       | `4.4.2` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `16.9.0` |

**Comment by bradzacher** [comment] 2021-09-07 17:59
Duplicate of #3816

**Closed by bradzacher** 2021-09-07 17:59 UTC
Labels: package: eslint-plugin, triage
