### ISSUE TITLE
npmjs.com site have invalid links to the rules

### ISSUE THREAD

**Issue by SrBrahma** [typescript-eslint/typescript-eslint#2791] opened 2020-11-21 02:18 UTC
At https://www.npmjs.com/package/@typescript-eslint/eslint-plugin, for example when I click the first rule (https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/docs/rules/adjacent-overload-signatures.md), it goes to a 404 page.

**Comment by bradzacher** [comment] 2020-11-21 03:26
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/2756

Please use the search next time

**Closed** 2020-11-21 03:27 UTC
Labels: duplicate, package: eslint-plugin
