### ISSUE TITLE
Enhancement: [class-methods-use-this] ignore `this: void` methods

### ISSUE THREAD

**Issue by stronny** [typescript-eslint/typescript-eslint#10085] opened 2024-10-02 05:01 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/class-methods-use-this/

### Description

Here's my reasoning.

1. If a method is explicitly annotated with `this: void`, it won't use `this`.
2. Refactoring it into not being a non-static class member is not always the right thing.
3. There is already special semantics established around `this: void` annotation: `unbound-method` and `max-params`.

Therefore, I propose adding an option to `class-methods-use-this` that will ignore methods that are declared with `this: void`. I don't have a strong opinion on its default value.

### Fail

```TypeScript
class Test {
  unbound() {return 123}
}
```

### Pass

```TypeScript
class Test {
  unbound(this: void) {return 123}
}
```

**Comment by bradzacher** [comment] 2024-10-02 05:57
> Refactoring it into not being a non-static class member is not always the right thing.

Why not? If it's not using `this` then the function could be refactored to be either a function outside of the class or as a static method, right?

I'm not quite sure why this case should be ignored by the rule -- why couldn't such a method be converted to a static class member or to a top-level function?

**Comment by stronny** [comment] 2024-10-02 11:58
* The most obvious case would be subclassing. It's much easier to override all methods consistently, rather than making a distinction between static and non-static methods.
* There's also no real `self` for anonymously referring to your own static methods from inside non-static methods. `this.prototype` business left me somewhat unhappy last time I've tried it.
* Finally, even if you dismiss all my use cases, there's still a question of consistency and synergy between the rules. As I've pointed out, there's already an established semantics with `this: void`. If I enable both `unbound-method` and `class-methods-use-this`, then mark a method with `this: void` to satisfy the first rule, the second one will complain.

**Comment by Josh-Cena** [comment] 2024-10-02 23:46
I agree that `this: void` should be special cased by this rule, for the reasons given above. However, I don't like this rule at all and I fail to see many reasons to ever want to enforce using `this` in methods since more often than not it's to conform to some expected interface (or to be compatible with an existing API shape).

**Comment by stronny** [comment] 2024-10-03 00:29
I've enabled it as a warning in hopes it gives me a chance to pause and think about my architecture once again. After all, it does make sense to question whether a function belongs in the class or maybe there's a better place for it.

Once I've decided that it does belong after all, I would prefer to have a semantic way of marking it as such, rather than using a disable-line comment.

**Comment by bradzacher** [comment] 2024-10-03 01:15
> However, I don't like this rule at all and I fail to see many reasons to ever want to enforce using this in methods since more often than not it's to conform to some expected interface (or to be compatible with an existing API shape).

I agree, personally. I understand the motivation behind it but yeah more often than not you need to have a `this`-less method on purpose and I've always found that when it does error, it's a false positive.

> I would prefer to have a semantic way of marking it as such, rather than using a disable-line comment.

My 2C is that the disable comment is a better thing here -- because `this: void` doesn't explain anything.

Sure - you've semantically marked the method as not using `this` -- but immediately I'd be asking "But why doesn't it use `this`? What's stopping it from being moved to a top-level function or a static method?"

**Comment by stronny** [comment] 2024-10-03 02:14
Nothing stops you from adding a comment. How is `this: void` worse than a naked `disable-line`?

I put a lot of effort into writing my own code in such a way that the answer is readily available, by naming methods, structuring classes and objects etc.

**Comment by JoshuaKGoldberg** [comment] 2024-12-07 17:45
The purpose of the `class-methods-use-this` rules is to enforce a common (but not universal) opinion: that if a function doesn't use `this`, it shouldn't be declared as a class method. `@typescript-eslint/class-methods-use-this` isn't enabled in our recommended presets because a lot of projects don't have the ability and/or desire to work with it. https://github.com/typescript-eslint/typescript-eslint/issues/10085#issuecomment-2388462714 and https://github.com/typescript-eslint/typescript-eslint/issues/10085#issuecomment-2389989021 mention some of the reasons why.

The request to use `this: void` strikes me as pretty niche. This rule's existed for quite a few years and this is the first I'm hearing of it. Marking as `evaluating community engagement` to see if other folks want this & have motivating use cases.

I personally don't think the benefit of an option to allow `this: void` is worth the maintenance cost. The rule is an extension rule, which makes it inherently harder to maintain (https://github.com/typescript-eslint/typescript-eslint/issues/6456). But hey, maybe I'm wrong and a lot of users would benefit here!

**Comment by stronny** [comment] 2024-12-07 18:33
With all due respect... huh? Did you read my comment you've linked? Did you read Josh's comment you've linked? I don't not want to come off confrontational, but it seems like you've completely failed to address objective arguments, instead just presenting your opinion.

If you can't maintain one `this: void` option, your whole project seems brittle beyond belief. Drop the rule entirely if you can't make it correct.

**Comment by JoshuaKGoldberg** [comment] 2024-12-07 19:18
😄 let's talk about it. I did read the comments. What from them don't you think my comment addressed?

> If you can't maintain one `this: void` option, your whole project seems brittle beyond belief. Drop the rule entirely if you can't make it correct.

We _could_ maintain the option. But it's extra work that would take time away from other, potentially more impactful efforts. And given that exactly one person has asked for this in over a year of the rule existing in typescript-eslint doesn't exactly point to it being a highly sought after feature by the community.

From another perspective: we have very limited bandwidth in this project. What objective reasoning would justify taking bandwidth away from other issues to specifically work on _this_ issue?

**Comment by stronny** [comment] 2024-12-07 19:55
> What from them don't you think my comment addressed?

This thing:

Finally, even if you dismiss all my use cases, there's still a question of consistency and synergy between the rules. As I've pointed out, there's already an established semantics with `this: void`. If I enable both `unbound-method` and `class-methods-use-this`, then mark a method with `this: void` to satisfy the first rule, the second one will complain.

> But it's extra work that would take time away from other, potentially more impactful efforts.

How much work would you estimate the support will require?

> From another perspective: we have very limited bandwidth in this project. What objective reasoning would justify taking bandwidth away from other issues to specifically work on _this_ issue?

The rule is incorrect.

**Comment by JoshuaKGoldberg** [comment] 2024-12-07 22:56
Aha, I see the disconnect! Thanks for the pointer.

> The rule is incorrect.

I think we see the purposes of the `class-methods-use-this` rules differently. My perspective is that:

* They're meant to discourage people from writing methods that don't use `this`
* The reasons for doing that are generally architectural: that intentionally writing a method that doesn't use `this` is considered to be an architectural code smell

From that perspective, I don't think recognizing `this: void` as an exemption to `class-methods-use-this` is in the spirit of the lint rules. Marking a method with `this: void` in a sense is _doubling down_ on the disallowed style of architecture. The code is explicitly indicating _I am writing a class method that doesn't use `this`, intentionally!_. The opposite of what `class-methods-use-this` rules are trying to enforce. Which means the issue not that `class-methods-use-this` is wrong per se, it's that by design it doesn't believe it should recognize your particular indicator of wanting to avoid it.

> there's already an established semantics with `this: void`

From my perspective, the established semantics of `this: void` are _counter_ to `class-methods-use-this`, not in support of it.

I can certainly see why, if you're consistently trying to intentionally write class methods that don't use `this`, an indicator like `this: void` would be useful. I just don't see that being a very common use case. Which is what I was trying to ask earlier: what are the real reasons why you would both enable a `class-methods-use-this` rule _and_ want to explicitly avoid it with a `this: void`?

Responding to a couple of the reasons to work around the rule that have been mentioned:

> The most obvious case would be subclassing. It's much easier to override all methods consistently, rather than making a distinction between static and non-static methods.

That's what the [`ignoreOverrideMethods` option](https://typescript-eslint.io/rules/class-methods-use-this/#ignoreoverridemethods) is for, no? I don't see why that would be a motivating use case to add more logic/workarounds for the rule.

> more often than not it's to conform to some expected interface

Speaking of which, that's what the [`ignoreClassesThatImplementAnInterface` option](https://typescript-eslint.io/rules/class-methods-use-this/#ignoreclassesthatimplementaninterface) is for, right? 

---

I do find an interesting parallel between this discussion and those around the [`@typescript-eslint/no-floating-promises` enabling its `ignoreVoid` option by default](https://typescript-eslint.io/rules/no-floating-promises/#ignorevoid). I'm personally against that because IMO it makes it very easy -IMO too easy- to avoid the rule (https://github.com/typescript-eslint/typescript-eslint/issues/2569). But the pushback against turning `ignoreVoid` to `false` by default is that it's a pretty established pattern with nice symmetry. `await` uses a Promise; `void` voids it. Clean.

I think the difference for `class-methods-use-this` is that `this: void` _in a class method_ is not, to my knowledge at least, a super common pattern. Although there are [5.5k results for `this:void` outside of tests on Sourcegraph searching](https://sourcegraph.com/search?q=context:global+%22this:+void%22+lang:TypeScript+-file:tests/*+-file:test/*+-file:node_modules&patternType=keyword&sm=0), many of those are in interfaces, standalone functions, or static functions. Not a lot of uses I'm seeing for specifically _class methods_.

That's part of why I think the `evaluating community engagement` label is valuable here. If there are actually a ton of developers actively using `this: void` in class methods then that's an ecosystem precedent we'd want to respect. But it's just the occasional individual who's picked up on it as an extra safety point for TypeScript, then that's much less compelling.

> How much work would you estimate the support will require?

The straightforward part would be adding the exemption to the part of the rule that checks whether a function uses `this`:

https://github.com/typescript-eslint/typescript-eslint/blob/8d35958494eb0c97cc36c3fc0844aea377542315/packages/eslint-plugin/src/rules/class-methods-use-this.ts#L198-L213

...as well as adding unit tests to exercise things like `this: void`, `this: NotVoid`, `this: SomeTYpeAliasThatMeansVoid`, and potentially other edge cases if we think of them.

The less-straightforward part would be keeping this logic working over the years as the rule inevitably grows in complexity. That inevitable growth in complexity is a big part of why I'm pushing back here 😄. If we added every feature a small number of folks requested to lint rules, they'd each become large unreadable beasts.

**Comment by stronny** [comment] 2024-12-07 23:19
> From that perspective, I don't think recognizing `this: void` as an exemption to `class-methods-use-this` is in the spirit of the lint rules.
> From my perspective, the established semantics of `this: void` are _counter_ to `class-methods-use-this`, not in support of it.
> I do find an interesting parallel between this discussion and those around the [`@typescript-eslint/no-floating-promises`

Have you considered the interplay with `unbound-method`? That is much more apt comparison I would propose.

> The code is explicitly indicating _I am writing a class method that doesn't use `this`, intentionally!_.

Yes, I am. How is a `disable-line` better than `this: void`? You aren't under an impression that a linter can actually prevent me from doing something, are you?

> I can certainly see why, if you're consistently trying to intentionally write class methods that don't use `this`, an indicator like `this: void` would be useful.

One method is enough to break the model. I don't do it consistently, nevertheless my point stands.

> I just don't see that being a very common use case. Which is what I was trying to ask earlier: what are the real reasons why you would both enable a `class-methods-use-this` rule _and_ want to explicitly avoid it with a `this: void`?
> But it's just the occasional individual who's picked up on it as an extra safety point for TypeScript, then that's much less compelling.

I object to this reasoning. I would understand begrudgingly admitting lack of available manpower, I would understand arguing that this isn't a bug, but appealing to popularity makes no sense to me.

The rule is incorrect. Prove me wrong.

> That's what the `ignoreOverrideMethods` is for, no? I don't see why that would be a motivating use case to add more logic/workarounds for the rule.

...Huh? The overriding method must be compatible with the overridden signature. If a superclass has a method that uses `this`, but the subclass overrides it without using `this` something has probably gone rather wrong along the way. How does this option help to mark the superclass' methods?

>> more often than not it's to conform to some expected interface

> Speaking of which, that's what the `ignoreClassesThatImplementAnInterface` is for, right?

This wasn't my point, and I don't want to derail the conversation, but I have things to say about this one too.

> Although there are 2.8k results for `this: void` outside of tests and `.d.ts` files on Sourcegraph searching, many of those are in interfaces, standalone functions, or static functions. Not a lot of uses I'm seeing for specifically _class methods_.

Um... Did you search for syntax that isn't yet implemented?

> The less-straightforward part would be keeping this logic working over the years as the rule inevitably grows in complexity. That inevitable growth in complexity is a big part of why I'm pushing back here 😄. If we added every feature a small number of folks requested to lint rules, they'd each become large unreadable beasts.

Copy-paste from (or better yet, refactor out of) `unbound-method` and Bob's your uncle.

**Comment by JoshuaKGoldberg** [comment] 2024-12-07 23:44
> Have you considered the interplay with `unbound-method`? That is much more apt comparison I would propose.

Yes, but I don't think it's applicable here. `unbound-method` detects _safety_ issues. `this: void` indicates it's safe to use a method in an unbound manner. I don't think that's the same as indicating a method intentionally goes against the intended architectural style of a project.

> How is a `disable-line` better than `this: void`?

The semantics are different:

* `disable-line` conveys that although the lint rule is normally correct, in this one specific case it's fine to go against it
* The proposed `this: void` conveys that the lint rule should treat methods in that way as fine and valid

In other words: one says the rule should be ignored for a line; the other says the rule's intention encompasses what that line represents.

> but appealing to popularity makes no sense to me.

Explaining since you bring up the point: we have finite developer resources. We need to prioritize the things that are most useful. That prioritization is done by maximizing bang for buck. Intentionally oversimplifying: it roughly comes down to sorting issues by bang-for-buck and drawing an arbitrary "line in the sand" between issues that meet the threshold and issues that don't. 

Diving in since you bring up the fallacy in particular: prioritization for lint rules and language best practices in general play differently with _argumentum ad populum_. The fact that a practice is widespread ("popular") changes its prioritization. Being popular isn't enough to justify something, of course - we wouldn't want to, say, encourage folks to use `any` just because a lot of projects still do that. But the fact that an area is applicable to many or only a few changes how much effort we should reasonably put into it.

> The rule is incorrect. Prove me wrong.

If the discussion in this issue fails to convince you, then you are welcome to [build a custom rule with the tooling provided by typescript-eslint](https://typescript-eslint.io/developers/custom-rules). You can even [build a custom ESLint plugin with that tooling](https://typescript-eslint.io/developers/eslint-plugins). That's even a strategy we recommend for _"not sure if useful enough to build into typescript-eslint"_ cases. If a lot of folks prefer your rule/plugin, then great! That's evidence I'm wrong to -1 this. Hooray!

But if you want us in typescript-eslint to mark this issue as `status: accepting prs`, review a pull request implementing the feature, and maintain it... then you need to convince us. That's the system. 🙂 

> Um... Did you search for syntax that isn't yet implemented?

No, I searched for `this: void` to see how widespread of a practice it is already. 

---

This is getting a little heated and I don't think we're going to convince each other. I'd be interested to see your thoughts on this comment. But after that I propose we wait a while to see if other folks want to chime in.

**Comment by stronny** [comment] 2024-12-08 00:07
> `unbound-method` detects _safety_ issues. `this: void` indicates it's safe to use a method in an unbound manner. I don't think that's the same as indicating a method intentionally goes against the intended architectural style of a project.

I think you are attributing THE authoritative meaning to a tool. A mistake, in my opinion. Not to go all post-structuralist on you, but what the author meant is of little concern. What matters is how users construct their own meaning, given the tools in the toolbox. It is perfectly valid TypeScript to have class methods that don't reference `this`. Sometimes it's an error, other times otherwise. It is not at all unreasonable to convey intent in the type system in order to differentiate.

Finally, this can 100% be a safety issue too.

> > How is a `disable-line` better than `this: void`?
>
> The semantics are different:
> 
>     * `disable-line` conveys that although the lint rule is normally correct, in this one specific case it's fine to go against it
> 
>     * The proposed `this: void` conveys that the lint rule should treat methods in that way as fine and valid
> 
> In other words: one says the rule should be ignored for a line; the other says the rule's intention encompasses what that line represents.

Am I correct to understand that you treat `disable-line` as syntactic and `this: void` as semantic? If so, this is the crux of my argument **for** this change. If not, I don't really get the distinction. Consider this:

```
/* This method is fine and valid. */ // eslint-disable-line
```

It is my strong conviction that intent expressed in code is infinitely better than the same intent expressed in comments.

> > but appealing to popularity makes no sense to me.
> 
> Explaining since you bring up the point.

No explanation needed, I'm very familiar with triaging issues. What I don't like is presenting this as an argument where it doesn't fit, is all.

> > The rule is incorrect. Prove me wrong.
> 
> If the discussion in this issue fails to convince you

This message is the first one where I see an argument I can actually understand.

> > Um... Did you search for syntax that isn't yet implemented?
> 
> No, I searched for `this: void` to see how widespread of a practice it is already.

And why would it be widespread?

> This is getting a little heated and I don't think we're going to convince each other. I'd be interested to see your thoughts on this comment. But after that I propose we wait a while to see if other folks want to chime in.

(/me looks at the creation date)

I'm not in a hurry ehehe.

**Comment by ronami** [comment] 2024-12-31 21:37
Adding some of my thoughts:

I see `class-methods-use-this` as an opinionated rule that doesn't fit every project. Projects that enable the rule usually want to avoid non-static class methods that don't use `this`. It has exceptions for common cases where the rule may be overly verbose, like sub-classing (`ignoreOverrideMethods`) and (`ignoreClassesThatImplementAnInterface`).

To my understanding, the issue proposes an implicit way to essentially disable the rule without explicitly using a disable comment. I think this is somewhat risky, as the rule may accidentally be disabled this way with no intent of actually disabling it. I think it's also less clear for reading through the code that this is an opt-out for the rule.

I don't see a good enough reason to have another somewhat implicit way to disable the rule, on a per-use basis, over an explicit eslint-disable comment. I'd be happy to understand if there's a common case behind some of the use cases behind this issue and if it would make sense to have them as an option, but otherwise, I'm -1.

**Comment by bradzacher** [comment] 2024-12-31 21:53
Three maintainers are -1, one is +1
Additionally in 3 months there has been zero community reactions.
Additionally this rule is some 6+ years old and this is the first proposal for such a feature.

Taking all this together - we are going to reject this proposal for this project.

If you think there's value in it we encourage you to fork the rule to allow you to deeply customise it for your codebase's codestyle.

**Closed** 2024-12-31 21:53 UTC
Labels: package: eslint-plugin, enhancement: plugin rule option, evaluating community engagement
