### ISSUE TITLE
AST change proposal: Improve `TSModuleDeclaration`

### ISSUE THREAD

**Issue by fisker** [typescript-eslint/typescript-eslint#6440] opened 2023-02-08 06:42 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Currently

```js
module a.b {}
^^^^^^^^^^^^^ TSModuleDeclaration(a)
       ^      TSModuleDeclaration(a).id
         ^^^^ TSModuleDeclaration(b)
         ^    TSModuleDeclaration(b).id
           ^^ TSModuleBlock
```

Can we change it to 

```js
module a.b {}
^^^^^^^^^^^^^ TSModuleDeclaration
       ^^^    TSModuleDeclaration.id
           ^^ TSModuleBlock
```

? 

Another problem is we parse the following code as the same ast

```js
namespace a {}
module a {}
```

Prettier can't [distinguish them without the original code](https://github.com/prettier/prettier/blob/cf409fe6a458d080ed7f673a7347e00ec3c0b405/src/language-js/print/typescript.js#L473). [Failure detection](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgHoAqAgWwlQFdNCSiCpty4BnAB2zEOwDoARgWABfADpR0WPIWatO3XoOEiQAGhAQOMAJbQ2yUHlwQA7gAUZUAymyZT2AJ4GNA3NwDWcGAGUWcABkdKDhkADM7NjhXdzAvXy4wYIBzZBhcamiQOHIBOFR0VADsKGTqbGS4ADEIXHJsGF1S5BBsahgIdRAACxhyTAB1bp14BR4fBDYRnQA3EccWsDYXEGCo3Bhzd2T68MisgCs2AA8fFLoARWoIeD3MKI0uXHWWmEcOdjBcHW0ujm-YAMdKgYN1kAAOAAMjxMUQG7g4LX+7DguBmoQ0AEdrvAtlobK02ABaEL5fJdfDYnT4LYVXZICL3LJRcg6NIZZnnOAAQUa3wE7Tg5lRQRCdweICmpUuONCDP2Ghg2AEQJBYKQACZFe4dJgUgBhCDkenZNgAVi61CiABVlTZGRKZpkAJKSBC+L4-GDcyQ+N50cVwEQiIA)

Maybe add `TSNamespaceDeclaration` or `TSModuleDeclaration.namespace`?

### Fail

```typescript
N/a
```

### Pass

```typescript
N/a
```

**Comment by bradzacher** [comment] 2023-02-08 06:53
Duplicate of #4966

We'll be fixing this in the next major!

**Comment by fisker** [comment] 2023-02-08 06:55
Sorry, didn't find it, must use the wrong keyword.

**Comment by bradzacher** [comment] 2023-02-08 06:56
> Another problem is we parse the following code as the same ast

That's cos they're exactly the same from the POV of TS.
Both emit a `ts.ModuleDeclaration` node and there are no special properties to identify one case or the other.

I think *maybe* `node.flags & ts.NodeFlags.Namespace` **might** identify the `namespace` case? It would require some research to figure out all of the cases to determine if it does.

The other option is that prettier could inspect the TS node for the specific keyword?
Maybe we could add that to the AST? 🤷

**Comment by fisker** [comment] 2023-02-08 07:28
> I think maybe node.flags & ts.NodeFlags.Namespace might identify the namespace case? It would require some research to figure out all of the cases to determine if it does.

👍 

> The other option is that prettier could inspect the TS node for the specific keyword?

Maybe already in `tokens`? We are not using any token now.

**Comment by bradzacher** [comment] 2023-02-08 07:59
yeah it's in the tokens we emit:
![image](https://user-images.githubusercontent.com/7462525/217469066-2cebe2e9-87c3-48ae-b207-8453fdd71a84.png)

It's also in the ts-ast as well as a child of the module declaration node.

**Comment by fisker** [comment] 2023-02-08 08:18
How do you think the idea

> Maybe add `TSNamespaceDeclaration` or `TSModuleDeclaration.namespace`?

**Comment by fisker** [comment] 2023-02-08 08:18
Or `TSModuleDeclaration.kind = "namespace" | "module"`?

**Closed** 2023-02-10 03:05 UTC
Labels: duplicate
