### ISSUE TITLE
Docs: "Linting with Type Information" (flat config) diff is syntactically wrong

### ISSUE THREAD

**Issue by htho** [typescript-eslint/typescript-eslint#8462] opened 2024-02-14 06:32 UTC
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

In the current version of the example for flat config, the code is syntactically wrong:

```js
export default tseslint.config(
  eslint.configs.recommended,
  //...tseslint.configs.recommended, // <-- removed
  ...tseslint.configs.recommendedTypeChecked,
  languageOptions: {
    parserOptions: {
      project: true,
      tsconfigRootDir: import.meta.dirname,
    }
  },
);
```
tseslint.config seems to expect a spread array of objects.
```js
export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  { // <-- inserted
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      }
    },
  } // <-- inserted
);
```

To workaround #8459 I manually applied [`"main": "./dist/index.js",` to my `./node_modules/typescript-eslint/package.json`](https://github.com/typescript-eslint/typescript-eslint/pull/8460/commits/da23118848d17c7f33d4bbe9024f43806d4d1369)

The worst thing is, I don't have type information for the inserted object with the `languageOptions`. This is because `@typescript-eslint/utils/ts-eslint` can not be resolved, and therefore `FlatConfig` can not be imported.

### Affected URL(s)

https://typescript-eslint.io/linting/typed-linting

**Comment by auvred** [comment] 2024-02-14 06:57
Thanks for posting! This is a duplicate of #8446. Before filing an issue, please [use our issue search](https://github.com/typescript-eslint/typescript-eslint/issues) to check for open and closed issues that already address what you're looking for.

It should be fixed by https://github.com/typescript-eslint/typescript-eslint/pull/8448

**Closed** 2024-02-14 07:11 UTC
Labels: triage, documentation

**Comment by htho** [comment] 2024-02-14 07:31
Oh. I am sorry for the duplicate.
