### ISSUE TITLE
Bug: [no-unsafe-member-access] JSDoc type assertion not applied in chained expression

### ISSUE THREAD

**Issue by karlhorky** [typescript-eslint/typescript-eslint#9568] opened 2024-07-16 16:27 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&fileType=.js&code=MYewdgzgLgBAhjAvDA9AKjTAAlAngBwFMYBvOMXAXxjRRgAoTKBKAKFfUxwOJJJlBgAZgEsA5gC4GzJAD4YAVzABrMCADuYGJWq0GrGPFbMAdINFj6zANztB0GCLBRCAJwC2hACYi4LpKgY2HhEpPzm4lJWcooqapraunT0cDasTi4e3r4uZuAWVrasQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZoloBbRCIBGiaLT5kyKVBkjToHaJHBgAviG1A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDRh9BAKWFhR6KQF8QqoA&tokens=false

### Repro Code

`index.js`

```TypeScript
const a = /** @type {any} */ ({})

/** @type {{ config: () => unknown }} */ (
  a
).config();

const intermediate = /** @type {{ config: () => unknown }} */ (a);
intermediate.config();
```

![error on `.config()` in chained expression showing "Unsafe member access .config on an `any` value. ESLint @typescript-eslint/no-unsafe-member-access"](https://github.com/user-attachments/assets/c96a7557-297c-4fbe-b028-abb9bd5f8962)

![no error on the `.config()` in `intermediate.config()`](https://github.com/user-attachments/assets/282e54f1-375f-497a-a424-746005f6b671)

#### TypeScript version

The TypeScript equivalent of the chained expression with the type assertion has no problems:

```ts
({} as { config: () => unknown }).config();
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unsafe-member-access": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "checkJs": true
  }
}
```

### Expected Result

The JSDoc type assertion on the chained expression should be treated the same way (no error) as the JSDoc type assertion on the `intermediate` variable creation

### Actual Result

The JSDoc type assertion on the chained expression results in an error on `.config()` whereas the JSDoc type assertion on the `intermediate` variable creation does not result in an error

Error message:

```
Unsafe member access .config on an `any` value. eslint (@typescript-eslint/no-unsafe-member-access)
```

### Additional Info

--

**Comment by kirkwaiblinger** [comment] 2024-07-16 16:36
Looks like you have an ASI bug!
try 
```js
// semicolon added
const a = /** @type {any} */ ({});

/** @type {{ config: () => unknown }} */ (
  a
).config();

const intermediate = /** @type {{ config: () => unknown }} */ (a);
intermediate.config();
```

**Comment by Josh-Cena** [comment] 2024-07-16 16:37
This rule does not care if you are using TypeScript or JSDoc. We ask TypeScript to give us the type of something, and it seems you failed to provide the right types for your code, probably due to ASI as @kirkwaiblinger said. In any case there's nothing we should do.

**Comment by karlhorky** [comment] 2024-07-16 16:54
@Josh-Cena I'm not sure I understand:

1. I don't see a comment by Kirk
2. the type in the type assertion is the same in both JSDoc versions (`{ config: () => unknown }`), but only the one with the intermediate variable works

**Comment by karlhorky** [comment] 2024-07-16 16:55
The semicolon has no effect:

[Playground](https://typescript-eslint.io/play/#ts=5.4.3&fileType=.js&code=MYewdgzgLgBAhjAvDA9AKjTAAlAngBwFMYBvOMXAXxjRRgAoTKBKAbgCh31McDiSSMUGABmASwDmALgbMkAPhgBXMAGswIAO5gYlarQbsY8dswB0w8RPptOw6DDFgohAE4BbQgBMxcF0lQMbDwiUkFLSRkbBWU1DW1dfTp6OFsnFw9vXxcLcCsbDnYgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZoloBbRCIBGiaLT5kyKVBkjToHaJHBgAviG1A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDRh9BAKWFhR6KQF8QqoA&tokens=false)

![Screenshot 2024-07-16 at 18 55 15](https://github.com/user-attachments/assets/8ffa4d45-af7f-4b89-9fce-3b1e79e86b13)

**Comment by kirkwaiblinger** [comment] 2024-07-16 16:55
> 1. I don't see a comment by Kirk

My bad for the confusion! I had originally posted a comment but quickly deleted it after I realized it didn't fully resolve the issue.

**Comment by Josh-Cena** [comment] 2024-07-16 16:57
It's possible that TS just doesn't accept JSDoc assertions in this position. 🤷‍♂️

**Comment by karlhorky** [comment] 2024-07-16 16:57
> resolving it doesn't resolve the JSDoc typing problem. As @Josh-Cena mentioned, the rule just uses the types as provided by TS

Understood. So this is actually a bug in TypeScript's JSDoc type assertion support.

**Comment by karlhorky** [comment] 2024-07-16 17:00
The thing that makes me reconsider / doubt that it's a bug in TypeScript is that using TypeScript IntelliSense autocomplete does show the property correctly.

VS Code does appear to know about the `.config()` method:

![Screenshot 2024-07-16 at 18 59 23](https://github.com/user-attachments/assets/dbbc0fe9-bfde-43b4-993c-4e14a0b48a75)

**Comment by karlhorky** [comment] 2024-07-16 17:06
Looking into this further, I set up a TypeScript Playground that demonstrates it:

```js
const a = /** @type {any} */ ({});

/** @type {{ config: () => unknown }} */ (
  a
).config();

/** @type {{ config: () => unknown }} */ (
  a
).unknown();
```

[TypeScript Playground](https://www.typescriptlang.org/play/?ts=5.5.3&filetype=js#code/MYewdgzgLgBAhjAvDA9AKjTAAlAngBwFMYBvOMXAXxjRRgAoTKBKAbgCh31McDiSSMUGABmASwDmALgbMkAPhgBXMAGswIAO5gYlarQbsY8dswB0w8RPptO3bHiKlBlyTJsLlajdt3669EYm5irqWmA2HEA)

![Screenshot of the TS playground, showing the above code, with the error under `unknown`](https://github.com/user-attachments/assets/8acc9b40-10b5-4ad1-afb4-f781df0aae43)


Maybe this is a bug in how `typescript-eslint` is retrieving the type from TypeScript in this chained case?

**Comment by kirkwaiblinger** [comment] 2024-07-16 17:07
Oh, _hmmmmmmm_. 

to your point,

```js
const a = /** @type {any} */ ({});

// correctly has type string
const s = (/** @type {{ config: () => string }} */ (
  a
).config());

```

**Comment by Josh-Cena** [comment] 2024-07-16 17:08
Let's investigate, but I doubt we are doing anything obviously wrong.

**Comment by Josh-Cena** [comment] 2024-07-16 17:09
My current guess is we are not tickling the compiler in the right way, so it does not fully use JSDoc in JS files... not sure.

**Comment by kirkwaiblinger** [comment] 2024-07-16 17:12
@karlhorky Sorry for the hangup on the ASI red herring!

**Comment by karlhorky** [comment] 2024-07-16 17:13
All good, totally understand that there's a lot of noise in open source issues! Really appreciate the work that the team does.

**Comment by Josh-Cena** [comment] 2024-07-16 17:19
@kirkwaiblinger I think you are totally right! Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/1682 it is :)

**Comment by kirkwaiblinger** [comment] 2024-07-16 17:24
(not actually helpful advice)

You can always work around this with 
```js
const a = /** @type {any} */ ({});

(0, /** @type {{ config: () => unknown }} */ (
  a
)).config();
```

😁

**Comment by karlhorky** [comment] 2024-07-16 17:26
nice, cool trick with the comma expression 👍 

I'll stick with the intermediate variable workaround for now:

```js
const intermediate = /** @type {{ config: () => unknown }} */ (a);
intermediate.config();
```

**Closed** 2024-07-16 17:27 UTC
Labels: duplicate, package: eslint-plugin

**Comment by Josh-Cena** [comment] 2024-07-16 17:29
I'm closing it because it will be automatically fixed by #1682, and we likely don't want to specifically make a workaround in this particular rule. Nevertheless if anyone has nice&easy tricks to make TS tell us the asserted type I'm all ears.

**Comment by bradzacher** [comment] 2024-07-16 22:16
Yeah so the issue here is that JSDoc type assertions are not part of the AST - they're just comments in the code. So the lint rules can't see them when they traverse the AST.

When a lint rule asks for the type of the "object" in the member expr it only sees the identifier - which is typed as `any`.

The correct fix, as Josh mentioned, is adding AST support for a JSDoc assertion. The difficult thing here is that for TS the "assertion node" doesn't include the comment - it's just the parentheses!

The reason the sequence expression works is because it changes the "object" from the identifier (which is typed as any) to the sequence expression, which encapsulates the assertion. It's essentially a short-hand for the separate variable approach.
