### ISSUE TITLE
Bug: package.json exports change breaks TypeScript check [v6]

### ISSUE THREAD

**Issue by christianvuerings** [typescript-eslint/typescript-eslint#7258] opened 2023-07-17 20:06 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Since #6458 imports from `@typescript-eslint/*` raise a TypeScript exception in our codebase.

# Notes

Adding `types` back to `package.json` on the root level fixes the issue for us:

```json5
// node_modules/@typescript-eslint/utils/package.json

{
  "name": "@typescript-eslint/utils",
  "version": "6.1.0",
  "type": "commonjs",

  // Fix
  "types": "./dist/index.d.ts",
```

### Reproduction Repository Link

https://github.com/christianvuerings/typescript-eslint-types-breakage-v6

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run typecheck src/repro.ts`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/utils`             | `6.1.0` |
| `TypeScript`                           | `5.1.6` |

**Comment by christianvuerings** [comment] 2023-07-17 20:07
Tagging @bradzacher & @JoshuaKGoldberg from the original PR: https://github.com/typescript-eslint/typescript-eslint/pull/6458

**Comment by JoshuaKGoldberg** [comment] 2023-07-17 21:25
Duplicate of #7185. Please see https://github.com/typescript-eslint/typescript-eslint/issues/7185#issuecomment-1631374643.

In the repro repo, if you add `--moduleResolution nodenext` or similar, the type error goes away.

Thanks for filing with such a clear repro & fix PR though!

**Closed by JoshuaKGoldberg** 2023-07-17 21:25 UTC
Labels: bug, triage
