### ISSUE TITLE
Bug: consistent-return not compatible incompatible with methods that return nothing early

### ISSUE THREAD

**Issue by ST-DDT** [typescript-eslint/typescript-eslint#8578] opened 2024-02-29 13:30 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=GYVwdgxgLglg9mABAgwggznANgUwDJwDmAFFAJ4AOOA-AFyIDkAhg4gD6MBGrHDEDASnrooAJxhhC7ROAAmOYBJyzEAbwCwAKESIYwRMQCE5KgLVadO0TighRYANwXEAX2fXb9xCZxPNLoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1oifLGhN0URNGgdokcGAC%2BAGkWRkI-MwDmqDFmyQAVsgAmHMpMPYoAWw5nEkyEVLIK1fAttLFfpSA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTolHoAebANOBqR4sACYBXDACVOsVBILF2kIuPSRBNKKMkYVnbn01DaJPJmTQ2lCxPRbhagKLxkNsHYemoY9NFRGeiUidi9HMwtkRABJIjwsInpUMMx7CLAAekywABUAC050MEZiuCIAM2QmEjASRH9kKuhk1ABPMArYTDAAQgAjCTQxEqIR-PoAN2K8WDB%2B4sx0acwEkeQiT0LPEnKqpgA6QeGDgCsSYh9IEgBraIAZZH6AYULoG9T0q9bYAHcAZTa8UKBGgABF0BV6FI8DEkN08GRbGlvNpIEsLqhpgApC5EACy4ikGmR9iEAF9HJBeAEJH52ABtK5qPwAfV0xLIGUgYmQ5hM2myYCWAEchksRl0enhtng2g0xLBoML0IE1p5OIiwMQwPB6NBsP8wABiABMpoAHAAGK4JcyZXaWfAkTL0FCK6CZBJISBCAC6IHJQA&tokens=false

### Repro Code

```TypeScript
function onConsoleLog(type?: 'a' | 'b' | 'c'): string | undefined {
  if (!type) {
    return;
  }
  return type;
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/consistent-return": "error"
  },
  "settings": {
    "jsdoc": {
      "mode": "typescript"
    }
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "node",
    "module": "esnext",
    "strict": true,
    "noEmit": true,
    "declaration": true,
    "stripInternal": true,
    // These are configs specifically for !build and have to be reverted in the tsconfig.build.json
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true
  }
}
```

### Expected Result

No Error or and error that points to the missing `undefined` at the first return.

### Actual Result

Function 'onConsoleLog' expected no return value. 5:3 - 5:15

### Additional Info

Might be related to https://github.com/typescript-eslint/typescript-eslint/issues/8576 and https://github.com/typescript-eslint/typescript-eslint/issues/8577

- https://github.com/typescript-eslint/typescript-eslint/issues/8576
- https://github.com/typescript-eslint/typescript-eslint/issues/8577

**Comment by bradzacher** [comment] 2024-02-29 18:52
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/1987, https://github.com/typescript-eslint/typescript-eslint/issues/1277

**Closed by bradzacher** 2024-02-29 18:52 UTC
Labels: bug, package: eslint-plugin, triage
