### ISSUE TITLE
Enhancement: typescript 5.6.3 support

### ISSUE THREAD

**Issue by rafaelfernandes98** [typescript-eslint/typescript-eslint#10132] opened 2024-10-11 13:54 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I received this warning "WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.3"

**Comment by JoshuaKGoldberg** [comment] 2024-10-11 13:57
> - [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.

![Kenan Thompson in SNL dubiously and amusedly saying YOU SURE?](https://github.com/user-attachments/assets/7f76515e-d33c-4f97-87a6-1545dabee56b)

Duplicate of #9653, the pinned issue. 😛

**Closed by JoshuaKGoldberg** 2024-10-11 13:57 UTC
Labels: enhancement, triage
