### ISSUE TITLE
Documentation doesn't explicitly say you need to have source files to lint first

### ISSUE THREAD

**Issue by Anshul-target** [typescript-eslint/typescript-eslint#6908] opened 2023-04-14 14:43 UTC
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

So while installing eslint using the documentation https://typescript-eslint.io/ as I headed over 
Step 3: Running ESLint
The code written for this is "npx eslint ."
and while pasting in the terminal we get the error
"No files matching the pattern "." were found.
Please check for typing mistakes in the pattern."

I would request you to remove the  "." from the documentation

### Affected URL(s)

https://typescript-eslint.io/

**Comment by JoshuaKGoldberg** [comment] 2023-04-14 14:49
Works on my machine. 😄 

Could you provide a way for us to reproduce your error? We'll need specific steps & source code we can run it on to reproduce the error you're getting.

**Comment by Anshul-target** [comment] 2023-04-14 14:53
Oh yes ....
1).Open VS Code
2).Create package.json file 
3).Follow the steps mentioned in the link 
https://typescript-eslint.io/

**Comment by Anshul-target** [comment] 2023-04-14 14:59
You can see
(https://user-images.githubusercontent.com/118791090/232080346-3e0a1a08-2fc3-47af-84ea-6326f22d6cef.png)

**Comment by JoshuaKGoldberg** [comment] 2023-04-14 15:01
...so you don't create any source files before running ESLint?

**Comment by JoshuaKGoldberg** [comment] 2023-04-14 15:15
Well there's the issue 😄 we've never heard from someone who tried creating a project from scratch. Which is a great point - thanks for filing!

We should do _something_ in the docs to mention this. Not sure yet 🤔 will think about it...

**Comment by Anshul-target** [comment] 2023-04-14 15:47
Could you assign it to me

**Comment by JoshuaKGoldberg** [comment] 2023-04-14 16:04
Ah sorry GitHub doesn't allow assigning to not-team-members 🙃. But also this one's a bit tricky because it's not clear what we'd want to do. Do we want to ...
* ... explicitly say in the docs that you need source files?
* ... make it so the `.eslintrc.(c)js` file is linted?
* ... something else?

Related: #6285, #6286. We're going to want to think about this holistically.

**Comment by JoshuaKGoldberg** [comment] 2023-07-26 15:54
Ok I've thought about this a bit and really don't think this is something we need to explicitly say in the docs. Almost all users (to our knowledge) at least 1-2 of:

* start the steps on existing code
* wait until there's at least one source file before linting
* deduced that it doesn't make much sense to run a linter before you have any source files 

We generally try not to overload our docs with not-often-helpful info. Although we could in theory add an explicit mention for this and other rarely-hit edge cases, doing so makes the docs harder to read and remember.

Closing for now. But someone please yell at me if I'm wrong that this is a rare edge case!

**Closed by JoshuaKGoldberg** 2023-07-26 15:54 UTC
Labels: documentation, accepting prs

**Comment by Josh-Cena** [comment] 2023-07-26 16:54
TBH, I think it's fine if the linter does nothing with no input (how can it do anything anyway), but if you are using the mental model of linting = inputFiles.forEach(check), then it does look surprising that inputFiles = [] is specifically designed to fail.
