### ISSUE TITLE
Upgrading to 4.14.0 causes error on decorator properties

### ISSUE THREAD

**Issue by slaweet** [typescript-eslint/typescript-eslint#2945] opened 2021-01-19 07:16 UTC
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages. -  that's why the problem started to happen
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "root": true,
  "parser": "vue-eslint-parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "ecmaVersion": 2020,
    "extraFileExtensions": [".vue"],
    "createDefaultProgram": true,
    "parser": "@typescript-eslint/parser"
  },
  "plugins": [
    "@typescript-eslint",
    "vuejs-accessibility",
    "import"
  ],
  "extends": [
    "eslint:recommended",
    "airbnb-typescript",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:vue/vue3-recommended",
    "plugin:vuejs-accessibility/recommended"
  ],
  "ignorePatterns": ["dist/", "node_modules/", "*.js"],
  "env": {
    "browser": true,
    "node": true,
    "amd": true
  },
  "rules": {
    "quotes": ["error", "single", { "avoidEscape": true }],
    "indent": ["error", 2],
    "semi": ["error", "always"],
    "camelcase": "off",
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/explicit-function-return-type": ["error", { "allowExpressions": true }],
    "@typescript-eslint/no-explicit-any": "off",
    "vue/component-tags-order": ["error", {
      "order": ["style", "template", "script"]
    }],
    "class-methods-use-this": "off",
    "complexity": ["error", 10],
    "max-depth": ["error", 3],
    "max-nested-callbacks": ["error", 3],
    "max-statements": ["error", 15],
    "max-lines": ["error", 350],
    "vuejs-accessibility/label-has-for": ["error", {
      "controlComponents": ["b-form-input", "b-form-select", "b-form-textarea"],
      "required": { "some": ["nesting", "id"] }
    }],
    "vuejs-accessibility/anchor-has-content": ["error", {
      "components": ["router-link"]
    }],
    "vuejs-accessibility/no-autofocus": "off"
  },
  "overrides": [
    {
      "files": [
        "tests/**/*.ts",
        "*.spec.ts"
      ],
      "rules": {
        "no-await-in-loop": "off",
        "max-depth": ["error", 4],
        "max-nested-callbacks": ["error", 4],
        "max-statements": ["error", 30],
        "max-lines": ["error", 450]
      }
    }
  ],
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts"]
    },
    "import/resolver": {
      "typescript": {
        "project": "./tsconfig.json"
      }
    }
  }
}
```

src/EslintErrorDemo.vue
```ts
<template>
  <div>
    <h1>Demo</h1>
    <child-component-demo />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import ChildComponentDemo from '@/ChildComponentDemo.vue';

@Component({
  components: { ChildComponentDemo },
})
export default class EslintErrorDemo extends Vue { }
</script>
```

src/ChildComponentDemo.vue
```ts
<template>
  <div>Child Demo</div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class ChildComponentDemo extends Vue { }
</script>
```

**Expected Result**

Eslint run passes on the code exmaple

```
 DONE  No lint errors found!
```

**Actual Result**

```
error: 'components' is not defined (no-undef) at src/EslintErrorDemo.vue:13:3:
```

**Additional Info**

```sh
■■■■[slaweet:~/git/demo] $ yarn add --dev @typescript-eslint/parser@4.13.0
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @typescript-eslint/parser@4.13.0
info All dependencies
└─ @typescript-eslint/parser@4.13.0
Done in 7.60s.
■■■■[slaweet:~/git/demo] $ yarn lint src/EslintErrorDemo.vue
yarn run v1.22.5
$ vue-cli-service lint src/EslintErrorDemo.vue
 DONE  No lint errors found!
Done in 6.26s.
■■■■[slaweet:~/git/demo] $ yarn add --dev @typescript-eslint/parser@4.14.0
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 0 new dependencies.
Done in 6.25s.
■■■■[slaweet:~/git/demo] $ yarn lint src/EslintErrorDemo.vue --debug
yarn run v1.22.5
$ vue-cli-service lint src/EslintErrorDemo.vue --debug
error: 'components' is not defined (no-undef) at src/EslintErrorDemo.vue:13:3:
  11 | 
  12 | @Component({
> 13 |   components: { ChildComponentDemo },
     |   ^
  14 | })
  15 | export default class EslintErrorDemo extends Vue { }
  16 | </script>


1 error found.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.14.0` |
| `TypeScript`                | `4.1.3` |
| `ESLint`                    | `7.18.0` |
| `node`                      | `12.7.0` |

**Comment by bradzacher** [comment] 2021-01-19 07:18
Duplicate of #2941, #2942
Please use the search.

**Closed by bradzacher** 2021-01-19 07:18 UTC
Labels: package: parser, triage

**Comment by slaweet** [comment] 2021-01-19 07:27
> Duplicate of #2941, #2942
> Please use the search.

Thanks for such a quick response. I was looking at open issues and didn't see any relevant. I didn't realize it could have been fixed so fast.
