### ISSUE TITLE
consistent-type-imports: add autofix option to prefer inline type keyword

### ISSUE THREAD

**Issue by jackfranklin** [typescript-eslint/typescript-eslint#4842] opened 2022-04-20 14:57 UTC
```ts
import {FooWhichIsAType, BarWhichIsValue} from './some-file.js';
```

This will cause an error with `consistent-type-imports`, but the autofix for the rule will fix it like so:

```ts
import type {FooWhichIsAType} from './some-file.js';
import {BarWhichIsValue} from './some-file.js';
```

As of TypeScript 4.5, the following is also supported (https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names):

```ts
import {BarWhichIsValue, type FooWhichIsAType} from './some-file.js';
```

I'd like to propose a configuration flag be added to `consistent-type-imports` to enable the auto-fixer to be configured to prefer either approach. 

I'm very happy to work on this PR, if this is something you would be happy landing? Thanks!

**Comment by bradzacher** [comment] 2022-04-20 16:29
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/4338

**Closed** 2022-04-20 16:30 UTC
Labels: duplicate, package: eslint-plugin
