### ISSUE TITLE
Pegged CPU usage with vscode-eslint

### ISSUE THREAD

**Issue by StephenHaney** [typescript-eslint/typescript-eslint#1042] opened 2019-10-04 05:34 UTC
Hello... I wanted to check if this was on typescript-eslint's radar.

There's an issue that people are experiencing with ESLint in VSCode where a Code Helper process pegs a CPU at 99% forever. You can trace this process back to vscode-eslint's server process. It's hard to reproduce, but happens multiple times per day randomly as you're working in VSCode and makes it very hard to work.

The common thread seems to be people using `@typescript-eslint/parser`.

This issue was originally reported on vscode-eslint's repo, but the maintainer seems to think the issue is outside of the plugin (either in ESLint itself, or something @typescript-eslint/parser is doing).

**Here's the original thread with technical details and examples:**
https://github.com/microsoft/vscode-eslint/issues/721

Since most people with this issue are using `@typescript-eslint/parser`. I'm hoping opening this issue will give some visibility to the problem over here and hopefully someone will have an a-ha moment.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.3.1` |
| `TypeScript`                | `3.6.2` |
| `ESLint`                    | `6.4.0` |
| `node`                      | `8` |

**Comment by StephenHaney** [comment] 2019-10-04 05:36
In particular, check out the post by @jbinto who traces down the actual code that's getting stuck in a loop:
https://github.com/microsoft/vscode-eslint/issues/721#issuecomment-526366654

**Comment by jbinto** [comment] 2019-10-04 12:55
Hi, thanks for tagging me into this thread. Unfortunately my traces were for work code so I couldn't share the exact token list that caused it. 

If & when I see it on one of my open source/side projects I will try to provide more info. I do remember that it was `.tsx` code that was the culprit, and my non-React colleagues on the server side haven't complained about this issue lately (though this is a small sample size, would be nice if someone else could confirm).

**Comment by JoelBrenstrum** [comment] 2019-10-10 20:20
I experienced the same issue, When i tracked down the offending line it appeared to be a react hook.
Specifically the array of dependencies on a `useMemo`.   `}, [param, param]);`

I have experienced this across a wide range of files, afaik not all of them contain hooks. 

I can confirm the code linked by @jbinto [here](https://github.com/microsoft/vscode-eslint/issues/721#issuecomment-526366654) was the same for us.

**Comment by bradzacher** [comment] 2019-10-10 20:43
I've never encountered this myself.
Without a solid repro, it's hard to even begin to investigate the cause.

It could very well be something unexpected that our parser is passing in.

This is what I'm guessing the path to cause the failure is (though IDK what inputs trigger the failure):

- something (cli or ide plugin) asks eslint to lint a file
- eslint calls the (user-specified) parser, and constructs a `SourceCode` instance from the result of the parse

https://github.com/eslint/eslint/blob/d31f3370396ec4868722bdc044aa697b135ac183/lib/linter/linter.js#L639-L663

- During construction `SourceCode` (which extends `TokenStore`) calls `super`, passing in the tokens obtained from the parser

https://github.com/eslint/eslint/blob/d31f3370396ec4868722bdc044aa697b135ac183/lib/source-code/source-code.js#L113

- `TokenStore`, as part of its constructor, calls `createIndexMap`

https://github.com/eslint/eslint/blob/d31f3370396ec4868722bdc044aa697b135ac183/lib/source-code/token-store/index.js#L215

- Infinite loop is triggered..

If someone can figure out a way to (even flakily) reproduce this, then we could track down the tokens that cause the loop.

**Comment by jbinto** [comment] 2019-10-10 21:11
I'll keep my eyes open for this issue (and I've told my team to do the same), but it's been a while since I've seen it.  Like @JoelBrenstrum I can confirm the file with troublesome tokens was a React `.tsx` file with some React hooks in it. In our case it was not `useEffect` though.

(aside: I wonder if `eslint-plugin-react-hooks` is contributing. I'd imagine that parsing is too early in the lifecycle for the plugin to come into play, but I don't understand it well enough to say that with confidence.)

**Comment by bradzacher** [comment] 2019-10-10 21:24
> imagine that parsing is too early in the lifecycle for the plugin to come into play

I believe that is correct. Plugins do not receive the AST until well after the code has been parsed. The high level workflow (from my understanding) is:
1) ESLint loads (or is given) the raw source code
2) ESLint tells parser to parse it
3) parser produces AST
3) ESLint does some processing on the AST (ensuring parent relationships are setup, etc)
4) ESLint initialises rules and gathers the list of selectors
5) ESLint traverses the AST and calls plugin rules

Unless the plugin is mutating the AST to do some funky stuff, and poisoning the cache, I doubt the plugin is contributing (the react team are pretty smart cookies, so I doubt they've done anything silly like that).

**Comment by jgoz** [comment] 2019-10-10 22:55
I've experienced this issue a number of times and it _seems_ like it's more likely to occur if I have VS Code open while I'm doing a git rebase. Could rapidly changing a file (or files) while the editor is open cause funky things to happen in the AST cache?

(If I can trigger it again, I'll try to note what I was doing and attach a debugger)

**Comment by StephenHaney** [comment] 2019-10-11 00:35
I also tend to experience this when many files are open and I'm jumping around making changes to many files at once. I have a bit of a hunch hunch it might happen when imports are broken (pointing at an old paths that I just changed) or in general when many things are broken at once due to being mid-refactoring.

**Comment by StephenHaney** [comment] 2019-10-12 00:05
Hey! I got an isolated case of this happening without a lot going on:

1. VSCode is open with ~10 random tabs from my project, it remains open this whole time
1. Git merged in a different branch, resolved a bunch of conflicts in VSCode, `git add -A`, `git commit` `git push`
2. Went and checked my diffs on GitHub, noticed something I wanted to change
3. Came back to VSCode, Cmd + P'd to my file... as soon as I hit enter and the file opened, my computer fans shot to max
4. CodeHelper 99.9% CPU, `electron_node eslintServer.js` 100% cpu in VSCode's process explorer
5. After a few minutes to make sure it was definitely stuck in a loop, I killed the 99% cpu process.
6. I restarted VSCode and ESLint is linting the file correctly.
7. If I repeat these steps, it is not reproducing.

Here is the file:
https://www.dropbox.com/s/c1ibvmewdbrhuwp/ComponentTree.tsx?dl=0

There are no compiler errors and no lint messages in this file.

**Comment by JoelBrenstrum** [comment] 2019-10-16 00:24
I have managed to repro this consistently in one of our files.
I havent been able to create a small repro



the offending lines
![image](https://user-images.githubusercontent.com/4349208/66878622-31af5900-f017-11e9-9912-6a8859ced255.png)

Stack trace (Note: its coming through Prettier) The Range values are the same for the comment and the token, which is why it can never progress. (I removed the space at the beginning of the comment to repro, but this isnt required to repro)
![image](https://user-images.githubusercontent.com/4349208/66878654-61f6f780-f017-11e9-9c6c-9691872bd8a0.png)

It also got stuck on this token once
![image](https://user-images.githubusercontent.com/4349208/66878779-ff522b80-f017-11e9-95cd-473c9da039f3.png)

I have auto fix on save enabled and prettier.

this was my attempt to repro but didn't work.
```import React, { Fragment } from 'react';

export const Child = props => props.value;

export class Repro extends React.Component {
  getRepro = (flag: string) => {
    if (Math.random() > 0.5) {
      if (Math.random() > 0.5) {
        return {
          priority: 'info',

          child: <Child value="myValue" />,
        };
      }

      //If you can handle a comment
      return { child: <Child value="info" /> };
    }
    return { child: null };
  };

  render() {
    const repro = this.getRepro(true);
    return <Fragment>{repro.child}</Fragment>;
  }
}
```

**Comment by bradzacher** [comment] 2019-10-16 00:52
That's great, thanks - now we know exactly why it's triggering - the comment has the same start range as the token.

For reference to save anyone else deciphering the code and all its ternaries, this is essentially what the loop collapses to, hence an infinite loop.
```ts
    while (true) {
        nextStart = 21178;
        while (true && 21178 < 21178) { // while (false)
            map[range[0]] = tokenIndex;
            map[range[1] - 1] = tokenIndex;
            tokenIndex += 1;
        }

        nextStart = 21178;
        while (true && 21178 < 21178) { // while (false)
            map[range[0]] = tokenIndex;
            map[range[1] - 1] = tokenIndex;
            commentIndex += 1;
        }
    }
```

---


Hmmm.. so this isn't a bug in ESLint, it's a bug somewhere else. If I had to hazard a guess, I would say that the bug would be in here:
https://github.com/typescript-eslint/typescript-eslint/blob/1918024e86acdf315dbbe659af6fea5d7244b336/packages/typescript-estree/src/convert-comments.ts
But I can't be certain without figuring out a code based repro. Though we have had some problems in the past with our comment parsing when paired with JSX.

I had a brief play within astexplorer, and I couldn't trigger it...

So now the question is instead - what triggers the comment and the `=` to share the same start location?

**Comment by JoelBrenstrum** [comment] 2019-10-16 02:02
I managed to get past the original comment but stuck on another one further down the file
![image](https://user-images.githubusercontent.com/4349208/66882081-878afd80-f025-11e9-9754-a6f276487f9b.png)

![image](https://user-images.githubusercontent.com/4349208/66882129-ad180700-f025-11e9-8cc1-e5d789d59424.png)


Same problem. The line numbers in this one look a little funny as the comment starts" on the same line as the code and finishes after it 🧐.

**Comment by JoelBrenstrum** [comment] 2019-10-16 04:16
another 
![image](https://user-images.githubusercontent.com/4349208/66887442-7fd45480-f037-11e9-9c63-a938b9833172.png)

<img width="351" alt="Screen Shot 2019-10-16 at 5 12 30 PM" src="https://user-images.githubusercontent.com/4349208/66887817-b8286280-f038-11e9-9fe3-72487bc5cbdd.png">

**Comment by StephenHaney** [comment] 2019-10-16 07:30
What's the method to get this debugging info when the loop occurs? I think I'm getting close to a solid repro as well but not sure how to get the info you're seeing @JoelBrenstrum

**Comment by JoelBrenstrum** [comment] 2019-10-16 08:06
I fire up Activity Monitor get the PID of the process stuck at 100%,
Then I open a new instance of VSCode and open the same project I've got open
Ctrl Shift + P > Debug: Attach to Node Process > Select PID from list > hit pause > voila!

I did try a bunch of additional steps before this which may have enabled this to work, let me know if it doesn't work.

**Comment by garyking** [comment] 2019-10-17 19:02
Does anyone know if this issue is relatively new (considering that this thread was made two weeks ago), and if a temporary fix would be to downgrade to a previous version of the typescript eslint parser, and if so, which version is best?

**Comment by StephenHaney** [comment] 2019-10-17 19:21
@garyking The issue I created this for is specifically for an infinite loop where your CPU pegs at 100% forever. We've been experiencing it since switching from TSLint to ESLint back when the announcement was made that new efforts were focused on ESLint.

I also experience high CPU usage with vscode-eslint and typescript when opening new files, but it normally goes away after a second. But it's probably a separate issue.

**Comment by garyking** [comment] 2019-10-17 19:24
Okay then perhaps I'll make a new issue for the one I'm having?

**Comment by StephenHaney** [comment] 2019-10-17 19:29
I am not a maintainer here, but that sounds appropriate if the CPU drops back to normal in your case.

**Comment by garyking** [comment] 2019-10-17 19:30
The CPU doesn't drop back to normal in my case.

**Comment by StephenHaney** [comment] 2019-10-17 19:40
Oh interesting, might be the same issue then, just with extreme CPU boost.

Some things you can do to provide more info:

1. When it happens, in VSCode, go to Help > Process Explorer and see which process is chewing up the CPU (for this issue it should be electron_node eslintServer.js).

2. Write down the pid from that process explorer

3. Go to Debug > Add Configuration and select `Nodejs attach to process`.

4. Add that pid into the `processId` field like this:
```
  {
    "type": "node",
    "request": "attach",
    "name": "Attach by Process ID",
    "processId": "your-runaway-cpu-pid-goes-here"
  },
```

5. Debug > Start Debugging

6. Hit 'pause' on the debugger and see where the process is stuck – it'll likely be in a function called createIndexMap.

If all this lines up, we're having the same issue. If so, it would be helpful if you can share your project source, especially if it's small, simple, and the problem is reproducible.

**Comment by domoritz** [comment] 2019-10-18 20:19
<img width="1229" alt="Screen Shot 2019-10-18 at 13 11 33" src="https://user-images.githubusercontent.com/589034/67125092-de6d1000-f1a8-11e9-9c03-ed909a578920.png">

I also have `@typescript-eslint/parser@2.4.0`.

I'm stuck in 

```
function processTimers(now) {
  if (this[owner_symbol])
    return unrefdHandle(this[owner_symbol], now);
  return listOnTimeout(this, now);
}
```

<img width="750" alt="Screen Shot 2019-10-18 at 13 19 16" src="https://user-images.githubusercontent.com/589034/67125541-e4afbc00-f1a9-11e9-96e8-7c8660136564.png">

**Comment by StephenHaney** [comment] 2019-10-18 23:22
I also got stuck in `processTimers` today.

**Comment by JoelBrenstrum** [comment] 2019-10-18 23:42
I believe process Tmers is just a purposeful loop. If you hit that line you're most likely not connected to the right PID or your process isn't actually stuck, it might just be using a lot of CPU.

**Comment by StephenHaney** [comment] 2019-10-19 00:05
Hmm, in that repro repo posted in the new duplicate issue (https://github.com/typescript-eslint/typescript-eslint/issues/1101)... if I open it in VSCode and open `App.tsx`, I immediately get locked 100% CPU eslint server.

When I pause the debugger, it goes to that `processTimers` and CPU use drops to 0 as it's paused. I double checked I'm using the right pid. When I unpause the debugger, eslint server CPU goes back to 100%. It's been running for 10 minutes like this, so I think it's really stuck.

I think you are correct that `processTimers` isn't meaningful though, maybe just a debugger process red herring. 

Curious about this new repro source though, as it seems to work to reproduce for me.

@bradzacher When you open #1101 's `App.tsx` in VSCode with vscode-eslint installed, do you get locked CPU?

**Comment by bradzacher** [comment] 2019-10-20 06:52
Sorry, this has been on the backburner because I've been working on fixing the IDE watch experience so you don't have to restart when you add new files.

I'll see if I can look into this next week.

**Comment by StephenHaney** [comment] 2019-10-20 07:22
No sweat at all, thanks for your help on this issue! Let me know if you can think of anything else we can do to help.

**Comment by sublimator** [comment] 2019-10-21 06:27
![image](https://user-images.githubusercontent.com/525211/67181296-669c2100-f406-11e9-8fcb-e47c1f363263.png)

Don't know if it is related but my cpu when running IntelliJ eslint integration goes crazy with 2.4.x series. I have downgraded to 2.3.x until it is solved.

**Comment by bradzacher** [comment] 2019-10-21 15:27
The next release will likely fix a few of the issues that are unrelated to the root cause.
Please try using the `canary` tag on npm if you need it sooner. Otherwise it will be released (automatically) in a few hours

**Comment by bradzacher** [comment] 2019-11-08 00:17
Is anyone else able to give the latest version a go, and let me know if it's fixed the issue?
2.6.0 had some general parsing fixes, and 2.6.1 had some comment parsing fixes.

I would hazard a guess that as of 2.6.1 shouldn't have this issue any more.

**Comment by StephenHaney** [comment] 2019-11-08 02:25
I haven't been in the code much since 2.6 went out, but I'm getting no reports of the issue from team members who have been coding. I'd say it's looking pretty positive over here.

**Comment by sublimator** [comment] 2019-11-08 04:52
i had some issues with intellij I think 2.5 fixed

was getting 400% cpu for the eslint node helper on macos

Likely related

**Comment by ken0x0a** [comment] 2019-11-12 13:25
I didn't see CPU 200% these days. After 2.6.0 as I remember correctly.

**Comment by sublimator** [comment] 2019-11-12 13:29
yeah, maybe it was 2.6, I cannot remember clearly

**Comment by bradzacher** [comment] 2019-11-12 16:21
I'm going to go ahead and close this then.
If anyone can still repro this on >=2.6.0 then please comment with a repro and I'll re-open and we can look into it.

**Closed by bradzacher** 2019-11-12 16:21 UTC
Labels: awaiting response, bug, package: parser, upstream

**Comment by StephenHaney** [comment] 2019-11-12 16:49
Thank you @bradzacher!
