### ISSUE TITLE
Bug: Default configuration following https://typescript-eslint.io/getting-started results in error

### ISSUE THREAD

**Issue by ben-walters** [typescript-eslint/typescript-eslint#9100] opened 2024-05-15 11:44 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

When following the "Getting Started" steps the configuration throws an error, namely: 

```
[...]/eslint.config.js:1
import eslint from '@eslint/js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

### Reproduction Repository Link

https://github.com/ben-walters/eslint-getting-started-bug

### Repro Steps

```
mkdir somefolder
cd somefolder
npm init
[accept all]
npm install --save-dev eslint @eslint/js typescript typescript-eslint
touch eslint.config.js
cat << EOF > eslint.config.js
// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
);
EOF
npx eslint .
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.9.0` |
| `TypeScript`                           | `5.4.5` |
| `ESLint`                               | `8.57.0` |
| `node`                                 | `20.13.1` |

**Comment by bradzacher** [comment] 2024-05-15 12:04
duplicate of #9094

**Closed by bradzacher** 2024-05-15 12:04 UTC
Labels: bug, triage
