### ISSUE TITLE
Enhancement: [unbound-method] Handle TS v5 decorators (like @bound)

### ISSUE THREAD

**Issue by loicraux** [typescript-eslint/typescript-eslint#6741] opened 2023-03-22 15:47 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/unbound-method/

### Description

Given this code :
```ts
/**
 * Binds the method to the instance
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function bound<This, Args extends any[], Return>(
    _target: (this: This, ...args: Args) => Return,
    { name, private: hasAPrivateName, addInitializer }: ClassMethodDecoratorContext<This, (this: This, ...args: Args) => Return>
): void {
    const methodName = String(name);

    if (hasAPrivateName) {
        throw new TypeError(`'bound' cannot decorate private properties like ${methodName}`);
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    addInitializer(function init(this: any) {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
        this[methodName] = this[methodName].bind(this);
    });
}

class Button {
    public readonly buttonElement: HTMLButtonElement;

    public constructor(buttonElement: HTMLButtonElement) {
        this.buttonElement = buttonElement;
        this.buttonElement.addEventListener('click', this.handleClick); // <== Error reported by unbound-method
    }

    public dispose(): void {
        this.buttonElement.removeEventListener('click', this.handleClick);
    }

    protected _activateButton(event: Event): this {
        event.stopPropagation();
        this.opts.onClick();
        return this;
    }

    @bound private handleClick(mouseEvent: MouseEvent): void {
        if (
            !this.isDisabled() &&
            ((mouseEvent.currentTarget as Element).tagName === 'button' ||
                (mouseEvent.currentTarget as Element).getAttribute('role') === 'button')
        ) {
            this._activateButton(mouseEvent);
        }
    }
}
```

The `unbound-method` reports an error whereas there should be a way to exclude methods annotated with a given decorator (here `@bound`).

Note that this is about the new decorators in TS 5+.
This will be more and more used.

### Fail

```typescript
var replace = 'me';
```

### Pass

```typescript
const replace = 'me';
```

**Comment by bradzacher** [comment] 2023-03-22 22:49
I'm not quite sure I understand - why would you bind via a decorator instead of just using an arrow function property?

A decorator is more work and thus will be much slower than an auto-bound property definition.

---

> Note that this is about the new decorators in TS 5+.

Why is there a difference between v5 and earlier decorators? Syntactically both are valid on a method so why is there a delineation in your eyes?

---

The problem is that a decorator doesn't change the signature of the class. As far as the types are concerned - it's still a method, not a function property.

To handle this we would have to do some very expensive checks to analyse the declaration of the method. We'd also have to handle the ambiguity of resolving to the "correct" decorator.

Maybe in future there will be a community drive to use this style - but I'm not sure if there will be for quite some time.

**Comment by bradzacher** [comment] 2023-03-27 10:43
`.bind` creates a copy of a function which is stored on each instance, and an arrow function property is similarly a new function sorted in each instance.
I.e. On the surface they should be the same in both performance and memory usage.

It's possible that under the hood engines may optimise one or both cases - it would require testing to discover!

Also worth noting that in TS methods are always mutable, but properties can be made readonly - which is a smidgeon of extra safety.

Methods are also always bivariant in their parameters, but arrow function properties can be made contravariant in their parameters with `strictFunctionTypes` on - which is extra safety again for assignments and subclassing.

---

The difficult thing for us is that there's nothing stopping someone from defining a new version of `@bound` that doesn't actually bind anything - creating a big hole in your codebase!

Currently the use of decorators depends on the frameworks used by a codebase - so it's a rarer thing across the entire ecosystem. This may become a more dominant style in future with the standardisation of decorators.

For the time being at least - I don't think there's enough benefit across the broader userbase for us to move on this right now. We'll definitely keep an eye on the state of the ecosystem.

**Closed** 2023-03-27 10:43 UTC
Labels: package: eslint-plugin, triage, enhancement: plugin rule option, evaluating community engagement

**Comment by loicraux** [comment] 2023-03-28 11:42
I don't know if this was clear, but I was just suggesting adding an option to ignore methods decorated by a list of decorators passed in the option. It's up to the ESLint user to set the right options. I wasn't asking the unbound-method rule to specifically ignore methods decorated by `@bound`.
