### ISSUE TITLE
Bug: Alias path causing error "Unsafe call of an any typed value." Vite MERN

### ISSUE THREAD

**Issue by lolikana** [typescript-eslint/typescript-eslint#7310] opened 2023-07-25 06:26 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I am expecting an import without error when using alias path "@hooks/use-title" like the screenshot using relative path "./../hooks/use-title"

![Screenshot 2023-07-25 at 11 35 23](https://github.com/eslint/eslint/assets/91938540/83080b70-2d93-40cf-a980-6df76df60612)

But when using alias path, error: `Unsafe call of an "any" typed value.eslint(@typescript-eslint/no-unsafe-call)` 

![Screenshot 2023-07-25 at 11 34 10](https://github.com/eslint/eslint/assets/91938540/86b54c6d-e77e-46c9-98c7-fde8fe5dce1b)

![Screenshot 2023-07-25 at 11 34 20](https://github.com/eslint/eslint/assets/91938540/c4dca04e-67ea-4e23-abf3-b1c28b1494f5) 

### Reproduction Repository Link
CodeSandbox:
https://codesandbox.io/p/sandbox/awesome-banach-z9pqxx
Github:
https://github.com/lolikana/vite-mern.git

### Repro Steps

If you are not seeing the error in `client/src/pages/Homepage.tsx`, open another file like `client/src/App.tsx` then go back to Homepage.tsx. 

I feel like the problem is using eslint for both, client and server folders. 

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.1.0` |
| `@typescript-eslint/parser`            | `6.1.0` |
| `TypeScript`                           | `5.0.2` |
| `ESLint`                               | `8.45.0` |
| `node`                                 | `18.13.0` |

**Comment by bradzacher** [comment] 2023-07-25 06:29
Your reproduction link is broken - I just get the message "Unable to start the microVM"

**Comment by lolikana** [comment] 2023-07-26 00:25
@bradzacher 
I see, I updated the issue and add the github repository ! 

https://github.com/lolikana/vite-mern.git

**Comment by nksfrank** [comment] 2023-09-11 09:19
I'm experiencing this problem as well.
Got path alias set up in my tsconfig.
while typescript resolves the types correctly. the linter gives me errors

![image](https://github.com/typescript-eslint/typescript-eslint/assets/7352072/0f6e024c-5fb9-48aa-9ead-07c628040f4c)

**Comment by JoshuaKGoldberg** [comment] 2023-09-12 19:26
I tried cloning the reproduction at https://github.com/lolikana/vite-mern but it doesn't have instructions for setting up. 

When I `npm run client dev`:

```plaintext
$ npm run client:dev

> sandbox@0.0.0 client:dev
> cd client && npm run dev


> sandbox@0.0.0 dev
> vite

sh: vite: command not found
```

I'm guessing you have `vite` installed globally on your system. I don't. After I `npm i vite -D` to get it installed as a dev dependency of the project:

```plaintext
$ npm run client:dev

> sandbox@0.0.0 client:dev
> cd client && npm run dev


> sandbox@0.0.0 dev
> vite

failed to load config from /Users/josh/repos/vite-mern/client/vite.config.ts
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vitejs/plugin-react-swc' imported from /Users/josh/repos/vite-mern/client/vite.config.ts.timestamp-1694546481577-bf2cb8ee43166.mjs
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:783:9)
    at moduleResolve (node:internal/modules/esm/resolve:832:20)
    at defaultResolve (node:internal/modules/esm/resolve:1069:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:305:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:156:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36)
```

Note that TypeScript itself (running with `tsc`) also gives complaints for that repository. 

```plaintext
joshgoldberg ~/repos/vite-mern $ tsc
client/src/App.tsx:3:22 - error TS2307: Cannot find module '@pages/Homepage' or its corresponding type declarations.

3 import Homepage from '@pages/Homepage';
                       ~~~~~~~~~~~~~~~~~

client/src/App.tsx:7:5 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

7     <>
      ~~

client/src/App.tsx:8:7 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

8       <Homepage />
        ~~~~~~~~~~~~

client/src/App.tsx:9:7 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

9       <p>Test</p>
        ~~~

client/src/App.tsx:9:7 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

9       <p>Test</p>
        ~~~

client/src/App.tsx:9:14 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

9       <p>Test</p>
               ~~~~

client/src/hooks/use-title.tsx:1:27 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

1 import { useEffect } from 'react';
                            ~~~~~~~

client/src/main.tsx:1:19 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

1 import React from 'react'
                    ~~~~~~~

client/src/main.tsx:2:22 - error TS2307: Cannot find module 'react-dom/client' or its corresponding type declarations.

2 import ReactDOM from 'react-dom/client'
                       ~~~~~~~~~~~~~~~~~~

client/src/main.tsx:3:17 - error TS6142: Module './App.tsx' was resolved to '/Users/josh/repos/vite-mern/client/src/App.tsx', but '--jsx' is not set.

3 import App from './App.tsx'
                  ~~~~~~~~~~~

client/src/main.tsx:7:3 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

7   <React.StrictMode>
    ~~~~~~~~~~~~~~~~~~

client/src/main.tsx:8:5 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

8     <App />
      ~~~~~~~

client/src/pages/Homepage.tsx:1:22 - error TS2307: Cannot find module '@hooks/use-title' or its corresponding type declarations.

1 import useTitle from '@hooks/use-title';
                       ~~~~~~~~~~~~~~~~~~

client/src/pages/Homepage.tsx:2:24 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

2 import { useRef } from 'react';
                         ~~~~~~~

client/src/pages/Homepage.tsx:9:5 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

9     <section>
      ~~~~~~~~~

client/src/pages/Homepage.tsx:9:5 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

9     <section>
      ~~~~~~~~~

client/src/pages/Homepage.tsx:10:7 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

10       <h1>{headTitleRef.current}</h1>
         ~~~~

client/src/pages/Homepage.tsx:10:7 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

10       <h1>{headTitleRef.current}</h1>
         ~~~~

client/src/pages/Homepage.tsx:10:33 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

10       <h1>{headTitleRef.current}</h1>
                                   ~~~~~

client/src/pages/Homepage.tsx:11:5 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

11     </section>
       ~~~~~~~~~~

client/vite.config.ts:3:19 - error TS2307: Cannot find module '@vitejs/plugin-react-swc' or its corresponding type declarations.

3 import react from '@vitejs/plugin-react-swc';
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~

server/server.ts:1:21 - error TS2307: Cannot find module 'express' or its corresponding type declarations.

1 import express from 'express';
                      ~~~~~~~~~


Found 22 errors in 6 files.

Errors  Files
     6  client/src/App.tsx:3
     1  client/src/hooks/use-title.tsx:1
     5  client/src/main.tsx:1
     8  client/src/pages/Homepage.tsx:1
     1  client/vite.config.ts:3
     1  server/server.ts:1
```

So I think the root issue is that the repository has TypeScript type errors separately from typescript-eslint. It can't resolve types because it's missing and/or cannot properly resolve some dependencies / dependency types.

Closing for now as this seems like a repository-specific issue. If you manage to fix the TypeScript type errors so that `tsc` produces no complaints, then feel free to post back an issue.

If you do, please post a full reproduction - that includes a comprehensive set of instructions necessary to get the project running locally. DOn't assume we maintainers have any project-specific tools installed globally such as `vite`. I'd recommend trying in a fresh environment such as a GitHub Codespace to be sure the issue isn't dependent on anything on your local machine.

**Closed by JoshuaKGoldberg** 2023-09-12 19:26 UTC
Labels: package: eslint-plugin, unable to repro
