### ISSUE TITLE
Bug: [no-floating-promises] return type of .catch not checked

### ISSUE THREAD

**Issue by IgorWiecz** [typescript-eslint/typescript-eslint#7135] opened 2023-06-23 16:07 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

[[Playground Link]](https://typescript-eslint.io/play/#ts=5.0.3&sourceType=module&showAST=es&code=MYewdgzgLgBADgJxAWwJYQKYwLwzBgdxgAUk1MAKChDCEAGwDcMAaGGgKw2CgEocAfO1oNmFAOSMAhvQCuGcb14BYAFCIU6DGo3kMAOmBSowABZUMCJAgBcMaAlRgA5v2xDSmzPs7coFS2slNSA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiRwYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

### Repro Code

```typescript
export const test = () => {
  const promise = new Promise((resolve, reject) => resolve('value'))
  promise.catch((error: string) => Promise.reject(error))
}
```

### ESLint Config

```javascript
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
  ],
  parserOptions: {
    project: './tsconfig.json',
    tsconfigRootDir: __dirname,
  },
  rules: {
    '@typescript-eslint/no-explicit-any': 2,
  },
  env: {
    node: true,
  },
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src", "./.eslintrc.js", "tailwind.config.js", "tests"]
}
```

### Expected Result

The no-floating-promises exception to trigger

### Actual Result

The error was not detected

**Comment by bradzacher** [comment] 2023-06-24 02:08
> Playground Link
> NA

Please don't skip parts of the template.
We have our template to help provide all of the necessary information and to help show you have done your due diligence to reproduce the issue you are reporting.

**Comment by IgorWiecz** [comment] 2023-06-26 09:13
> > Playground Link
> > NA
> 
> Please don't skip parts of the template. We have our template to help provide all of the necessary information and to help show you have done your due diligence to reproduce the issue you are reporting.

@bradzacher is this what you meant?

**Comment by bradzacher** [comment] 2023-06-26 09:30
Almost - the playground should include the rule in question showing it does not currently error. [for example](https://typescript-eslint.io/play/#ts=5.0.3&sourceType=module&code=MYewdgzgLgBADgJxAWwJYQKYwLwzBgdxgAUk1MAKChDCEAGwDcMAaGGgKw2CgEocAfO1oNmFAOSMAhvQCuGcb14BuALAAoRCnQY1msjoB0wKVGAALKhgRIEALhjQEqMAHN+2IaW2ZDnblAU1rZKGkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiRwYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

The idea behind the repro is that we as maintainers can open it and immediately see the problem (or lack of problem) to expedite investigation.
If you don't provide a playground we need to manually attempt to reproduce your problem and we may get it wrong - which wastes time and frustrates everyone!

Here's a good post by someone about the subject https://antfu.me/posts/why-reproductions-are-required

**Comment by bradzacher** [comment] 2023-06-26 09:55
The difficult thing about this issue is that in essence we would want to solve the "halting problem".

Sure, we could hard code logic which says "don't immediately return `Promise.reject()`" - but in reality this specific case a really niche case that people rarely actually do in code.

Instead the catch handler is likely more complex with branches and such, and it's unlikely that it directly returns a rejected promise. In some cases it might use `new Promise` and call the rejection callback, or it might use an async function that throws as the handler, or it might call another function entirely which is a black box and might throw.

The point is that determining whether or not a catch handler throws is really hard!

So with all that being said - could we handle this? One potential solution is to enforce that any `.catch` that returns a `Promise` should also be flowed by a `.catch` - which is "strictly correct" but also isn't really idiomatic code. There would also need to be handling for `.finally` as it suffers the same problem. And there would also need to be handling for the `.then(success, fail)` form of "then" as if either case throws then they will lead to an unhandled promise rejection...

This is often the reason that I suggest people avoid the method-based promise handlers at all cost - because they're filled with footguns and hard-to-lint code.

**Comment by kirkwaiblinger** [comment] 2023-11-11 21:27
It seems that this is nearly equivalent to the question regarding use of both handlers in `.then`s in https://github.com/typescript-eslint/typescript-eslint/issues/5692#issuecomment-1504645034, where the decision was that these sorts of handlers should not be considered liable to throw for the purposes of this rule in a context where the author is already accounting for rejections (which is certainly the case for `.catch`).

**Comment by bradzacher** [comment] 2023-11-11 22:30
@kirkwaiblinger not quite - what we're talking about here is the specific case in which the rejection handler returns a promise. That case is specifically handled as per the spec in which it continues the promise chain dependent on if the returned promise resolves or rejects.

So for example the following code prints "resolved"
```ts
Promise.reject('rejection')
  .catch(() => Promise.resolve('resolved'))
  .then((v) => console.log(v))
```

This case is different from the one described in the linked comment because that one is specifically about forcing the style `then(resolve, reject).catch(reject2)` in case `resolve` throws an error. In the general case I'm against this as I described in that comment - however in the specific case that either `resolve` or `reject` or `reject2` returns a promise then there is scope in the rule to handle this case, IMO, as the chain continues.

I think in an idea world the rule would specifically inspect the callback functions to determine if they return a promise as that is easy to determine (just check the return type) and is well-specced and requires the rule to make no assumptions about developer intent.

**Comment by kirkwaiblinger** [comment] 2023-11-11 23:21
@bradzacher Sounds good. I mostly brought it up in case you wanted to close as already decided upon.

Looking into this more closely though, it does seem surprising to me though that it's worth drawing a distinction between a handler that returns a value and a handler that returns a promise. They're both equally capable of throwing, and in each case that rejection will propagate to the overall promise. So an async handler doesn't make an unhandled rejection any more or less likely.  That is to say the following lines are essentially exactly identical for the purposes of unhandled rejections.
```
x.catch(async () => { throw Error() });
x.catch(() => { throw Error() } );
x.catch(() => Promise.reject(Error()));
```

I _would_ understand the point if the catch handler was _not_ awaited by the enclosing promise. i.e. if 
```
await x.catch(() => Promise.reject()); // exception thrown here. Can be mitigated with try/catch
```
were equivalent to 
```
await x.catch(() => void Promise.reject()); // unhandled promise rejection, but execution continues in this function. Can't be mitigated with try catch.
```
Then putting a promise in the catch handler would make the potential for unhandled rejection worse.

**Comment by kirkwaiblinger** [comment] 2023-11-11 23:37
it also occurs to me that this is related to the "checksVoidReturn" option of the `no-misused-promises` rule - ensuring that you only pass an async function as a callback if the recipient is typed to expect it. `.catch` is typed in a way passes that rule, but perhaps if there's a special case to be made, it might end up belonging in that rule.

**Comment by bradzacher** [comment] 2023-11-12 01:33
The difference is important - you are completely correct that any the or catch handler could throw.

But without the ability to statically analyse and detect if any given function could throw (see the halting problem) the lint rule can't really error for these cases or else we get into an infinite loop - how can the rule decide when to stop requiring a `catch`?

So we need to add some boundaries and assumptions around things to make things solvable. Right now the assumptions are:
1) any promise that has an `await` operator is safe.
2) if configured, any promise that has a `void` operator is safe.
3) any promise that terminates in a `.catch` is safe.
4) any promise that terminates in a `.then` with 2 arguments is safe.

The previously linked comment argued that (4) should not be an assumption because if the "success" handler throws then it causes an unhandled rejection - which we cannot detect reliably and would thus have to remove the assumption entirely.

In the case of this issue we have a very clearly defined case - if a `.catch` handler (or first handler to a 2 argument `.then`) returns a promise then there is a new promise that needs to be handled. 

This case has clear developer intent and clear consequences and more importantly has a well defined structure that can be found with static analysis (specifically if the function returns a promise). Which makes it a good candidate to add to the rule.

**Comment by kirkwaiblinger** [comment] 2023-11-12 03:09
I see, thanks for that explanation. I think my motivation for this rule in general is actually quite different than what you've laid out so it makes much better sense now to me why we'd reach different conclusions. 

Cheers,
Kirk

**Comment by JoshuaKGoldberg** [comment] 2024-03-18 18:15
It's been ~4 months since last comment and there haven't been any new motivators for this. Closing it out as having not had enough community feedback to suggest we should take action.

If anybody sees this and thinks they have a good reason not yet mentioned, please do file a new issue! We'd be happy to take a look.

Thanks for the discussion all!

**Closed by JoshuaKGoldberg** 2024-03-18 18:15 UTC
Labels: package: eslint-plugin, enhancement: plugin rule option, evaluating community engagement
