### ISSUE TITLE
Rule proposal: no unnecessary type coercion

### ISSUE THREAD

**Issue by JounQin** [typescript-eslint/typescript-eslint#3204] opened 2021-03-20 02:24 UTC
```ts
const a = 0
const b = ''
const c = false

// report following statements
const d = +a
const e = Number(a)
const f = String(b)
const g = Boolean(c)
```

**Comment by Josh-Cena** [comment] 2024-06-02 07:47
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/8515; closing this one since that one has more interactions and is newer

**Closed by Josh-Cena** 2024-06-02 07:47 UTC
Labels: package: eslint-plugin, enhancement: new plugin rule, accepting prs
