### ISSUE TITLE
Enhancement: `consistent-type-definitions` new option `disableInsideDeclare`

### ISSUE THREAD

**Issue by GreenTea124** [typescript-eslint/typescript-eslint#7147] opened 2023-06-28 16:57 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-definitions.md

### Description

Usually it's better to use a `type` keyword instead of an `interface` keyword since it leads to slightly safer code
(quick reminder why here: https://www.youtube.com/watch?v=zM9UPcIyyhQ)

In some rare cases hoverer, using an `interface` interface within a `declare` block is required, if you want to extend types of some 3rd party library (also explained in that short video).

This is why I believe an additional `disableInsideDeclare` option could be handy. Then it would be possible to enforce a `type` keyword in most cases, but allow an `interface` keyword inside `declare` without using `eslint-disable`.

It could be used like this:

```
"@typescript-eslint/consistent-type-definitions": ["warn", "type", { disableInsideDeclare: true }],
```

It this would be a default behavior, it could also potentially solve this related issue:
https://github.com/typescript-eslint/typescript-eslint/issues/7137

### Fail

```typescript
interface Parameters {
	xyz: string;
};
```

### Pass

```typescript
type Parameters = {
	xyz: string;
}

declare module "@storybook/types" {
	interface Parameters {
		xyz: string;
	}
}

declare global {
    interface Window { MyNamespace: any; }
}
```

**Comment by bradzacher** [comment] 2023-06-28 17:34
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/7137#issuecomment-1605244398
Please use the search

**Closed by bradzacher** 2023-06-28 17:34 UTC
Labels: package: eslint-plugin, triage, enhancement: plugin rule option

**Comment by GreenTea124** [comment] 2023-06-28 21:28
> Duplicate of [#7137 (comment)](https://github.com/typescript-eslint/typescript-eslint/issues/7137#issuecomment-1605244398) Please use the search

@bradzacher 
I did, I even mentioned that issue myself. I don't think it's a duplicate since it proposes a solution.
