### ISSUE TITLE
Bug: `TypeError: Cannot read properties of undefined (reading 'name')` on 8.10

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#10187] opened 2024-10-21 09:43 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Repro Code

I know this is not minimal (can add a minimal repro if needed), but see marekdedic/prosemirror-remark#404

### Expected Result

No error, as in previous typescript-eslint versions

### Actual Result

```
Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: Cannot read properties of undefined (reading 'name')
    at /home/runner/work/prosemirror-remark/prosemirror-remark/node_modules/typescript-eslint/dist/config-helper.js:32:54
    at Array.map (<anonymous>)
    at /home/runner/work/prosemirror-remark/prosemirror-remark/node_modules/typescript-eslint/dist/config-helper.js:31:27
    at Array.flatMap (<anonymous>)
    at Object.config (/home/runner/work/prosemirror-remark/prosemirror-remark/node_modules/typescript-eslint/dist/config-helper.js:25:20)
    at file:///home/runner/work/prosemirror-remark/prosemirror-remark/eslint.config.js?mtime=1729492070858:12:25
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:432:15)
    at async loadConfigFile (/home/runner/work/prosemirror-remark/prosemirror-remark/node_modules/eslint/lib/config/config-loader.js:202:21)
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`     | `8.10.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `9.13.0` |
| `node`                                 | `v18.20.4` |

**Comment by YouNesta** [comment] 2024-10-21 10:31
Same on my codebase, i need to go back to earlier version

**Comment by bradzacher** [comment] 2024-10-21 10:32
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/10176

**Closed by bradzacher** 2024-10-21 10:32 UTC
Labels: bug, triage
