### ISSUE TITLE
Rule proposal: no union type assertion

### ISSUE THREAD

**Issue by NotWoods** [typescript-eslint/typescript-eslint#8292] opened 2024-01-22 20:03 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Sometimes (usually in a place where `as const` would have worked too), we end up with code like this:
```ts
type Size = 16 | 32 | 48;
const props = { size: 32 as Size };
```

The intention here is to satisfy some other location where `props` must be of type `{ size: Size }`. But the type assertion makes it so that any number would be valid, rather than just those in the `Size` union.

The proposed rule should mark any location where a value is casted into a union type that includes that value in its set. It should suggest alternatives that don't use a type assertion.

While my examples are showing number unions I think this would be useful for any union type.

### Fail Cases

```TypeScript
type Size = 16 | 32 | 48;
interface Props {
  size: Size
}

const props = { size: 32 as Size };
```

### Pass Cases

```TypeScript
const props = { size: 32 satisfies Size };
const props = { size: 32 as const };

const size: Size = 32;
const props = { size };

const props: Props = { size };

// not dealing with enums
enum Mode {
  On = 1
}
const props = { mode: 1 as Mode };

// not dealing with brands
type Id = number & { __brand: 'id' };
const id = 123 as Id;
```

### Additional Info

This could also be an option for [no-unnecessary-type-assertion](https://typescript-eslint.io/rules/no-unnecessary-type-assertion/) or [consistent-type-assertions](https://typescript-eslint.io/rules/consistent-type-assertions/#objectliteraltypeassertions). The rule should offer similar suggestions to `objectLiteralTypeAssertions`.

**Comment by JoshuaKGoldberg** [comment] 2024-01-24 16:26
🤔 Hmm. I think I get where you're coming from here but the examples aren't super motivating for me. Given these three options:
* 🍏 `const props = { size: 32 as Size };`
* 🍌 `const props = { size: 32 satisfies Size };`
* 🍒 `const props = { size: 32 as const };`

🍒 `as const` changes the meaning of code (it's now `32`, not `Size`). 🍏 `as Size` is fewer characters than 🍌 `satisfies Size` for roughly the same thing.

Do you have any motivating examples that show concrete benefit? Even if they're not minimal or standalone, it'd be helpful to see them.

> This could also be an option for [no-unnecessary-type-assertion](https://typescript-eslint.io/rules/no-unnecessary-type-assertion/) or [consistent-type-assertions](https://typescript-eslint.io/rules/consistent-type-assertions/#objectliteraltypeassertions).

Yeah there might be something here around preferring 🍌 `satisfies` over 🍒 `as`, since 
🍌 `satisfies` is safer. Maybe that's a good standalone rule request dependent on TypeScript's type assignability API?

**Comment by bradzacher** [comment] 2024-01-24 23:11
This seems like a subclass of the problem space of "don't allow unsafe assertions".

I.e. `1 as 1 | 2 | 3` is fine, but `1 as  2 | 3 | 4` is not

**Comment by JoshuaKGoldberg** [comment] 2024-01-25 12:15
So this is a duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/7173 then?

**Comment by bradzacher** [comment] 2024-01-25 13:49
Yeah I think so.
I'm in your camp where I don't think that **safely** asserting to a union is bad. The issue is the chance of an unsafe assertion creeping in accidentally.

So reject the former the latter is covered by the other issue.

**Closed** 2024-01-25 13:49 UTC
Labels: package: eslint-plugin, enhancement: new plugin rule, awaiting response

**Comment by NotWoods** [comment] 2024-01-25 18:37
Seems like this is a duplicate, closing in favor of the other issue
