### ISSUE TITLE
Bug: [no-unused-vars] Does not recognize `@link` JSDoc usage.

### ISSUE THREAD

**Issue by brunnerh** [typescript-eslint/typescript-eslint#7944] opened 2023-11-17 08:23 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

The TS language server recognizes and processes references in [`@link`](https://jsdoc.app/tags-inline-link).
The plugin still complains about the variable not being used.

### Reproduction Repository Link

https://github.com/brunnerh/ts-eslint-link-issue

_Edit:_ [Playground](https://typescript-eslint.io/play/#ts=5.3.0-beta&fileType=.tsx&code=GYVwdgxgLglg9mABAGzhAhsgYua8wAUAlIgN6IC%2BAsAFC0D0AVI7Yo2QALIxgDWKaTDkiwE1Gm3q0ApgA8ADnABOURKBH414YmVq1xtdcQDcQA&eslintrc=N4KABGBECmB2BukBcZQQpARgJwPYHcBnabZMAF2wFdoAacdGQgJgAZmBGMym%2B9KWLgAm0btWgMAvnyjQAHuThDCZANoMM0QgBsAlrHJJs0AMa4AtuaXQhkGRgAO2qgHN9SAALkAng60nsXQdyAFotPQMAemMzS2tbBgBdGUhceBJAkRUUdX40flkEMnyCgWFRFB4JUukNRgAzXW0tNTr%2BSAA6cP1KEw7gACtCWhMhyUg2sGTJyAcAQ2xibAB5YN1cWGzUSYxCXCpsE2gAFV8KqEIAoPIJmrrJJJT5xZIySC8zy8DgsJ0eyOeSzsDFmCyWq3I602xTqMBM5jmADUSIQoW9tHNFIQbvYLvtDiczm9zMIqM1bmBao5nG5oTlYR8-F9rr8IjdHiDqM0tiUoIz-N9Qt0ooIQlRYFRiEIQvAwW8MrhSFIQJIgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.11.0` |
| `@typescript-eslint/parser`            | `6.11.0` |
| `ESLint`                               | `8.53.0` |
| `node`                                 | `18.13.0` |

**Comment by brunnerh** [comment] 2023-11-17 08:29
Just realized I could have reproduced with a module-local function e.g.
[Playground](https://typescript-eslint.io/play/#ts=5.3.0-beta&fileType=.tsx&code=GYVwdgxgLglg9mABAGzhAhsgYua8wAUAlIgN6IC%2BAsAFC0D0AVI7Yo2QALIxgDWKaTDkiwE1Gm3q0ApgA8ADnABOURKBH414YmVq1xtdcQDcQA&eslintrc=N4KABGBECmB2BukBcZQQpARgJwPYHcBnabZMAF2wFdoAacdGQgJgAZmBGMym%2B9KWLgAm0btWgMAvnyjQAHuThDCZANoMM0QgBsAlrHJJs0AMa4AtuaXQhkGRgAO2qgHN9SAALkAng60nsXQdyAFotPQMAemMzS2tbBgBdGUhceBJAkRUUdX40flkEMnyCgWFRFB4JUukNRgAzXW0tNTr%2BSAA6cP1KEw7gACtCWhMhyUg2sGTJyAcAQ2xibAB5YN1cWGzUSYxCXCpsE2gAFV8KqEIAoPIJmrrJJJT5xZIySC8zy8DgsJ0eyOeSzsDFmCyWq3I602xTqMBM5jmADUSIQoW9tHNFIQbvYLvtDiczm9zMIqM1bmBao5nG5oTlYR8-F9rr8IjdHiDqM0tiUoIz-N9Qt0ooIQlRYFRiEIQvAwW8MrhSFIQJIgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

**Comment by bradzacher** [comment] 2023-11-17 08:38
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/6967 https://github.com/typescript-eslint/typescript-eslint/issues/5017

Please use the search.

**Closed by bradzacher** 2023-11-17 08:38 UTC
Labels: bug, triage

**Comment by brunnerh** [comment] 2023-11-17 08:44
It *did* search, unfortunately the search is completely useless:
![image](https://github.com/typescript-eslint/typescript-eslint/assets/834235/27380b63-4737-4aae-8c34-b79534969de4)

**Comment by bradzacher** [comment] 2023-11-17 09:12
Drop the @ and add another keyword (jsdoc) and you'll find more relevant results.

https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+link+jsdoc
