### ISSUE TITLE
Bug: `recommended-requiring-type-checking`

### ISSUE THREAD

**Issue by unofficialquant** [typescript-eslint/typescript-eslint#6478] opened 2023-02-16 07:12 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

When `recommended-requiring-type-checking` is enabled, running `eslint` will result in an error `TypeError: Cannot read properties of undefined (reading 'type')`.

### Reproduction Repository Link

https://github.com/unofficialquant/test-ts-eslint

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.52.0` |
| `@typescript-eslint/parser`            | `5.52.0` |
| `TypeScript`                           | `4.9.5` |
| `ESLint`                               | `8.34.0` |
| `node`                                 | `18.14.0` |

**Comment by Josh-Cena** [comment] 2023-02-16 07:17
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/6477

**Closed by Josh-Cena** 2023-02-16 07:17 UTC
Labels: bug, triage
