### ISSUE TITLE
Bug: [no-unnecessary-condition] mistakenly reports only on symbol property when tsconfig exactOptionalPropertyTypes is enabled

### ISSUE THREAD

**Issue by miguel-leon** [typescript-eslint/typescript-eslint#10440] opened 2024-12-02 08:19 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=MYewdgzgLgBBCeBbGBeGBlJAjEAbAFAJQDcAsAFAUCWYUApgE4BmAhsHTAGIggwDeFGDADaCRAF0A-AC44UBjQDmZckJZQoMuQrDKKAXwpHyAEzrBcLBh1CRYIWdxAqKIUUnExJktAHIAFlS%2BKiAAdOqw3n6BwRRAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk6AHgIbR64HGOoAKmsiWeAJ4AVQfzKU8mAK7oANOBqQSU5CwBy01KgDCAC3TQA1hLBTZigL4hLQA&tokens=false

### Repro Code

```TypeScript
const sym = Symbol();

interface Foo {
  [sym]?: string;
  att?: string;
}


declare const o: Foo;

o[sym] ??= 'hi'; // reports here!
o.att ??= 'hi';
```

### ESLint Config

```jsonc
{
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "exactOptionalPropertyTypes": true,
    "strictNullChecks": true
  }
}
```

### Expected Result

No error in line 11

### Actual Result

 Errors in line 11 but not in 12.

**Comment by bradzacher** [comment] 2024-12-02 08:30
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/6632

**Closed by bradzacher** 2024-12-02 08:30 UTC
Labels: bug, package: eslint-plugin, triage
