### ISSUE TITLE
[no-unsafe-return] `ReturnType<T>` is marked unsafe

### ISSUE THREAD

**Issue by JounQin** [typescript-eslint/typescript-eslint#3856] opened 2021-09-08 03:29 UTC
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

[Playground](https://typescript-eslint.io/play#ts=5.3.2&fileType=.tsx&code=CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQAlERAHgBUA%2BACgEoAueAb3jGRjlQxavgBfANwAoUJFgIU6bHgLEAwlAgQARlDABravBAAPDCFTBC8OgDorsAOaEWqEADcQMANoBdBvAC8NAqhaqDgA7qj0YGr8zPBUYqIGAA44MBgceIRpRCAAoqgAFlDoIMDKqhravvC6BkYmZpbWMHYsRQCent5%2B8O30ovAcKuqaWvwANP3woIn2AUGhqJ5VnhNd-qyTYBlpcIhV2WSUZBhcqFRtiSDUNPQMopvbHGr7SkMVWnSNFrazAAqwUAAtiAjDBCNc1mxJgMtqhMvA4IRkBA0j5BuURl8ft4oGZjqdzpdrtCEeQLJxuMZUaSkSiSQB6enwAAGwQAtGhCFBECA2XATjBUMz4FgzHBkqkSiT%2BacaciMJNBHdJoz4DgMPlXPAIDgbFgwPcBjLBU8emYqKJBKIgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolrRE%2BWNCbooiaNA7RI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

```JSON
{
  "rules": {
    "@typescript-eslint/no-unsafe-return": 2
  }
}
```

```TS
import { useCallback, useRef } from 'react'

export const useEnhancedCallback = <T extends (...args: any[]) => any>(
  callback: T,
  deps: unknown[] = [],
) => {
  const ref = useRef<ReturnType<T>>()

  const cb = useCallback((...args: Parameters<T>) => {
    const result = callback(...args) as ReturnType<T>
    ref.current = result
    // `no-unsafe-return` is reported
    return result
  }, deps)

  // other logic

  return cb as T
}
```

**Expected Result**

No report

**Actual Result**

```log
Unsafe return of type `any` from function with return type `ReturnType<T>`.
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.30.0` |
| `@typescript-eslint/parser`        | `4.30.0` |
| `TypeScript`                       | `4.4.2` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `12.22.5` |

**Comment by bradzacher** [comment] 2021-09-08 05:42
`T` is constrained as `T extends (...args: any[]) => any`.
Which means that `ReturnType<T>` is constrained as `ReturnType<T extends (...args: any[]) => any>`.
If we ask TS to get the base constraint of `ReturnType<T>` then it gives us the `any` type

In order for the rule to work at all, when we work with generics, we resolve them to their base constraint.
Which means that `ReturnType<T>` is resolved by TS as `any`.

You can see this behaviour [by playing with the TS APIs](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwgOwM7wK6uAUWQCwENkFgATAYUIBtqAjQhAazgF44AeAFTlBmGRlUcABQA6CYSgBzVAC44xAJ4BtALoBKNgD5FyJdpEAoOIhr1GTBVwA0JuGWBh5cDMibIIAd2Tq2cdTstVl0Ab3skNHgEOn9xSRkXAAUpQgBbYH4oVG5tYLD7U0j0OChgVAxqeHYEcwZmeLEpWS1CYQAlTIwoZC4lMGBcgG5CuAB6MbgAA08AWjdUQgAzYFmymG7kKbgAS2EyyFhyUfXN0vLKmHsAXxH7CbgIGHxgKDhqCGkdhCN7U57ELE2nAuCNrkA)

![image](https://user-images.githubusercontent.com/7462525/132452311-62e2b85c-9e04-4a72-a2f1-d46522e6c860.png)

----

The problem here is that we don't know what `T` actually is - so we can either treat it as this black box of unknown - or we can treat it as its constraint.

If we go with the former, then it means that every generic type is either going to lead to false positives or false negatives - both due to the lint rule just seeing this weird type that isn't anything.
If we go with the latter, then it means that lint rules have something to use to interrogate, but it does also leave a little to be desired in some cases.

There's not a good solution unfortunately. Generics are just inherently not an entirely sound construct and are difficult to work with.

**Comment by JounQin** [comment] 2021-09-12 09:26
@bradzacher 

So why `ref.current = result` doesn't emit `no-unsafe-unassignment` error?

**Comment by bradzacher** [comment] 2021-09-12 10:19
`ref.current` is of type `any` because you gave it the type `ReturnValue<T>`.
The rule ignores `any` assignments to `any`

**Comment by JounQin** [comment] 2021-09-12 10:42
So if I mark the function return `ReturnType<T>` specifically, will it pass?

**Comment by bradzacher** [comment] 2021-09-13 04:24
Quick tests shows no - not sure why off the top of my head.
Functions work differently to assignments due to multiple signatures and such, so the rules logic isn't 1:1 the same (hence each one is a different rule)

**Comment by Josh-Cena** [comment] 2024-06-05 13:46
Duplicate of #2432

**Closed by Josh-Cena** 2024-06-05 13:46 UTC
Labels: bug, package: eslint-plugin, accepting prs
