### ISSUE TITLE
Docs:  Update docs for typescript configuration with the new eslint config file

### ISSUE THREAD

**Issue by igortas** [typescript-eslint/typescript-eslint#6282] opened 2022-12-27 23:06 UTC
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Docs needs to be updated, so developers knows how to use `typescript-eslint` plugin with the new `eslint` config file. Currently there is no known way how to use the `parser` option in new `languageOptions` configuration key, or `recommended` option in the `plugins` key. 

Docs for new `eslint` config:
`https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new`

Some test configuration (`eslint.config.mjs`) I've tried and it's working.

For `.mjs` extension works only with `pnpm`, `yarn` I didn't tried. `npm` complains about `.mjs` extension.

```
import react from 'eslint-plugin-react';
import imports from 'eslint-plugin-import';
import a11y from 'eslint-plugin-jsx-a11y';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import globals from 'globals';

export default [
  'eslint:recommended',
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    languageOptions: {
      sourceType: 'module',
      ecmaVersion: 'latest',
      parser: typescriptParser,
      globals: {
        ...globals.browser,
      },
    },
    linterOptions: {
      noInlineConfig: true,
      reportUnusedDisableDirectives: true,
    },
    plugins: {
      react: react.configs.recommended,
      import: imports.configs.recommended,
      'jsx-a11y': a11y.configs.recommended,
      '@typescript-eslint': typescript,
    },
    rules: {
      'no-extra-parens': 'off',
      'no-unused-vars': 'off',
      'no-extra-semi': 'off',
      'no-unused-vars': 'off',
      'no-empty-function': 'off',

      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',

      // '@typescript-eslint/no-extra-parens': 'off',
      // '@typescript-eslint/no-unused-vars': 'error',
      // '@typescript-eslint/adjacent-overload-signatures': 'error',
      // '@typescript-eslint/ban-ts-comment': 'error',
      // '@typescript-eslint/ban-types': 'error',
      // '@typescript-eslint/no-array-constructor': 'error',
      // '@typescript-eslint/no-empty-function': 'error',
      // '@typescript-eslint/no-empty-interface': 'error',
      // '@typescript-eslint/no-explicit-any': 'warn',
      // '@typescript-eslint/no-extra-non-null-assertion': 'error',
      // '@typescript-eslint/no-extra-semi': 'error',
      // '@typescript-eslint/no-inferrable-types': 'error',
      // '@typescript-eslint/no-loss-of-precision': 'error',
      // '@typescript-eslint/no-misused-new': 'error',
      // '@typescript-eslint/no-namespace': 'error',
      // '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      // '@typescript-eslint/no-non-null-assertion': 'warn',
      // '@typescript-eslint/no-this-alias': 'error',
      // '@typescript-eslint/no-unnecessary-type-constraint': 'error',
      // '@typescript-eslint/no-unused-vars': 'warn',
      // '@typescript-eslint/no-var-requires': 'error',
      // '@typescript-eslint/prefer-as-const': 'error',
      // '@typescript-eslint/prefer-namespace-keyword': 'error',
      // '@typescript-eslint/triple-slash-reference': 'error',
    },
  },
];
```
In package.json (the flag needs to be activated and path to the current directory provided `.` or something like `./src`, otherwise it will not work):
```"lint": "ESLINT_USE_FLAT_CONFIG=true eslint --fix --debug -c eslint.config.mjs ./src"```

### Affected URL(s)

https://typescript-eslint.io/linting/configs/

**Comment by bradzacher** [comment] 2022-12-27 23:20
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/5908

Please use the search.

**Closed by bradzacher** 2022-12-27 23:20 UTC
Labels: triage, documentation
