### ISSUE TITLE
[no-fallthrough] eslint switch case doesn't respect `never`

### ISSUE THREAD

**Issue by apexskier** [typescript-eslint/typescript-eslint#7641] opened 2023-09-13 20:13 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0AAUQE8AHKAYwCdZaUozFh4B7ZAV3j9I4VMgBumJpABQxWjyaJQAM0ENEsHvAjxI-JuABy4ceCYAKAPqTo-cAC5QhM0wCUTl%2BdABvGaFBEAAsmHgB3Z3AIgFEmUMsAIgBVeCDMeFQ8VFB0SGZYAFsETERRUEEtHQLwAuxzBLcAbhkAXxkZNXgNSsCoRAtMT35a8w9nYbqmX39QSDDYRAYg0AG3aYCAhkwRUABGJz8NjYZtSGVsUABeUATSs4Tmo4DYFRWLy%2Bvbvob1p4DDRAGHS7R5PNp-cB6AzGUzmCzYJqgECgAA8yGQgSC4FAAAMvEwcaAAUDAnRsZD9IZMRhQDTSkwivBMNBVIpMdjOt1tAAaWYIBjY4I05lhTDUSCY0JhWRHcHHbbYgBMTmRaIxQolZ1g0BZoqQEswoGwhkwAGtQDgeGZMTx%2BABzIIzI7Epg6RWguUunQATl9zTaMju-QAzE0gA&eslintrc=N4KABBYEQKYB4BcYDsAmBnKAuMBtckEs6ANgJbIJYBOMAxgPYC2TKqMqUANAYVAA4kArgHMKWAAIIAnvxjo61MvwQBaeeUoB6DRTW1GLNhyi8wAXRABfIA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function ensureNever(_value: never): never {
  throw new Error("Unhandled discriminated union member");
}

function test(a: number): number {
  switch (a) {
    case 1: {
      const b = "test";
      if (b == "test") {
        return 1;
      }
      ensureNever(b); // <-- the `never` return type ensure this is terminal for the function, since this always throws
    }
    case 2: // <-- this still wants a break above though
      return 2;
  }
  return 999;
}

test(3);
```

### ESLint Config

```javascript
{
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended"
    ]
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

I expect the break statement isn't necessary since the prior case block terminated in an expression returning `never` (that always throws).

### Actual Result

On line 15

```
Expected a 'break' statement before 'case'.ESLint[no-fallthrough](https://eslint.org/docs/latest/rules/no-fallthrough)
```

**Comment by bradzacher** [comment] 2023-09-13 21:46
This is expected because the rule is not type-aware. We'd need to build an extension rule.

This is a pretty rare usecase so I'm not sure if it makes sense for us to own and maintain an extension rule for it.

This is the first time in the history of the project that someone has requested this behaviour - so it's either not a common pattern, or just not a common pattern in codebases that use the rule.

The closest issue we've had filed is https://github.com/typescript-eslint/typescript-eslint/issues/3455 (which is similar but A LOT more complicated).

I'll leave this as "evaluating community engagement", but my gut is that we probably won't action this due to how rare it is.

**Comment by apexskier** [comment] 2023-09-13 23:16
Totally fair. I hadn't see #3455 when I searched, but I'd be okay if you want to close this as duplicate of that.

To add some missed details:

* I had a vague expectation that `"plugin:@typescript-eslint/eslint-recommended"` would have disabled/adjusted the failing eslint rule in some way to work around this
* The main reason I think this is an actually problem is because `ts` itself actually warns about the break statement I need to add (typescript itself actually conflicts with eslint directly here). If I had stricter typescript compiler warning requirements in my PR checks I'd be forced to actually disable a linting rule.
   <img width="381" alt="startPasswordReset ts — auth-ui - Visual Studio Code - 2023-09-13 at 17 14 17@2x" src="https://github.com/typescript-eslint/typescript-eslint/assets/329222/7773cac1-7fd8-41bf-b9f5-ac8651cc09ec">

**Comment by bradzacher** [comment] 2023-09-14 00:11
Yeah for sure - your want makes sense because there's no way to satisfy the lint rule and TS at the same time with code when using this pattern.

But you can satisfy the rule by adding a comment. [By default the rule will ignore cases when there is a comment that matches the regex `/falls?\s*through/`](https://github.com/eslint/eslint/blob/main/lib/rules/no-fallthrough.js#L17).

I.e. you can add the comment `// impossible to fall through due to the above assertion function`, and the rule would not error [playground](5.2.2&fileType=.tsx&code=KYDwDg9gTgLgBAMwK4DsDGMCWEV2CgZySmADlgA3YKACgH0KBDAGyWAC44VLqBKT7lShwA3gCg4cGAAsoEAO5dgigKJQ5tAEQBVFNMYoAJs2CG4hzATRRMAW0wpGMU3FTZct4LYBG1TbwBuMQBfMTFkdCwcKWACGBpGASQfPiSU4XFJAnlMGDRpOATeUQlJODRGAmA4AEZOTLLJNBw4uG84AF44TWc4zSDGyUwEQvaOrp7YmH8SwbKSGGJcGoHB0Ln8IhJyIRpvQNLGgHojpSFEFmYCKVkIJABzAsM2KQgb6sZvCCpEVAx3Q5wdZlCpVOAAJnYgMkCyWENWwNhUFwAE40UFQmJevEAMyBIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaAMwEN54AXAC2n1gHNr0pFo7pJwwBfEHoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false).

But this is obviously sub-par in comparison to the rule just working.

**Comment by innermatrix** [comment] 2023-09-25 21:41
@bradzacher fwiw I was just about to file this bug as well, thereby making it half as rare now 🙂

**Comment by Eldemarkki** [comment] 2023-12-22 17:11
In Next.js there are e.g. `redirect("/path")` and `notFound()` which return `never`. I think this issue affects those cases quite a lot. For example:

```tsx
function getUserType(): "unauthorized" | "normal" | "admin" {
  return "normal";
}

export default function MyPage() {
  const userType = getUserType();

  switch (userType) {
    case "unauthorized":
      redirect("/login");
      break; // <-- problem here
    case "normal":
      return <div>Welcome, user</div>;
    case "admin":
      return <div>Welcome, admin</div>;
  }
}
```

With `break;`:
![image](https://github.com/typescript-eslint/typescript-eslint/assets/38920928/b53b8398-e86f-4100-b1ed-3215f0170967)

Without `break;`:
![image](https://github.com/typescript-eslint/typescript-eslint/assets/38920928/5ab89caf-8cc3-419c-bf9e-7da25ebb9bd2)

**Comment by bradzacher** [comment] 2023-12-23 02:43
@Eldemarkki your case is easily satisfiable by [prefixing it with `return`](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCoBMk0AbFIuTAVwDsNgIO4iawIhgAUzAOYAuOAGcYUYB3EBKaRyQA3JFArVK7LjB59xSGAFUZ2gCoBPMEhGq4AIk4o2MABbRgALyQaFzgAH1cOaBAUBmCwlxQaEEVggG8qOH4zNig+FwioKJjdAF8qKiQAD0hYODpMDwYsTm5eOABZWwAFFFMnaWR0GAA6ACkAZQANIYBRBiQQJA54NMoMtF45ODYrKDsHOABeOFMLHb3HZV102QB3YBg0LzgRbZt7JGU4FYy1lCtXdyeHwKAJBSTXH6ZGDZPgCIT0GAiFwAegYEHEyUuELgaD+SHCkWiLnBq0hUJhcAAPIINAA+ADqSAY6wWABotjtKciabTdJDcf94olkiSyeSclSeYzmbgkOyEkkOFyeXy4KVKOqgA)

This has the added benefit of also making it very clear that `redirect` terminates things - which is nice for newbies and when working without intellisense (eg gh reviews)

**Comment by bradzacher** [comment] 2023-12-23 02:54
Duplicate of #3455

**Closed by bradzacher** 2023-12-23 02:54 UTC
Labels: package: eslint-plugin, enhancement: new base rule extension, evaluating community engagement
