### ISSUE TITLE
[object-shorthand] autofix breaks arrow functions with function types

### ISSUE THREAD

**Issue by MayhemYDG** [typescript-eslint/typescript-eslint#124] opened 2019-01-22 13:46 UTC
**What code were you trying to parse?**

```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key: (arg: () => any) => {}
}
```

**What did you expect to happen?**
Autofix result should be
```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key(arg: () => any) {}
}
```
**What actually happened?**
Autofix gives
```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key(arg: () any) => {}
}
```
**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.0.0` |
| `TypeScript`                | `3.2.4` |
| `ESLint`                    | `5.12.1` |
| `node`                      | `11.7.0` |
| `npm`                       | `6.5.0` |

**Comment by MayhemYDG** [comment] 2019-01-22 14:48
```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key: (arg: () => any, arg2: () => any) => {}
}
```
becomes
```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key(arg: () any, arg2: () => any) => {}
}
```

---

Following your logic, I tried with a default parameter in a js file and it bugs out as well:
```js
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key: (arg = () => {}) => {}
}
```
becomes
```js
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key(arg = () {}) => {}
};
```

---

I'll open up an issue in the ESLint repo. I don't know if we should close this one yet, maybe once it's fixed in ESLint, it might still be broken with TS types.

**Comment by platinumazure** [comment] 2019-01-22 14:51
Thanks @MayhemYDG for your tests, this all seems to point to my hypothesis as you noted.

@JamesHenry We don't have any labels related to the issue being blocked, or that this might be solvable in ESLint core. How do you want to handle the labeling of this issue? I agree with @MayhemYDG that it could be worthwhile to leave this open.

**Comment by j-f1** [comment] 2019-01-22 14:53
Let’s close this for now since the issue is with ESLint. If the upstream fix doesn’t fix our case, please comment and we’ll reopen this.

**Comment by platinumazure** [comment] 2019-01-22 14:54
@MayhemYDG Once you've opened the ESLint issue, please CC me-- I have some thoughts on how to fix. Thanks!

**Comment by MayhemYDG** [comment] 2019-01-22 15:05
Upstream issue: https://github.com/eslint/eslint/issues/11305

**Comment by platinumazure** [comment] 2019-01-22 15:46
For what it's worth: I used AST Explorer to check the parser output (although this was with `typescript-eslint-parser` rather than `@typescript-eslint/parser`) and the range info looks correct, so there's nothing we need to change there.

**Comment by MayhemYDG** [comment] 2019-02-04 11:04
@platinumazure @j-f1 
I've updated to ESLint 5.13.0, which fixes most bugs with the rule, but unfortunately the rule's autofix is still broken if the function has a return type defined:

```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
  key: (arg: any): any => {}
}
```
becomes
```ts
const test = {
  key((arg: any): any) {}
}
```
instead of
```ts
const test = {
  key(arg: any): any {}
}
```

**Comment by bradzacher** [comment] 2019-09-11 16:33
I put up a fix for this in the eslint repo:
https://github.com/eslint/eslint/pull/12260

I'll close this, feel free to track the fix via the above PR.

If that PR gets rejected, I'll reopen this issue and we can bring the rule into the plugin.

**Closed by bradzacher** 2019-09-11 16:33 UTC
Labels: bug, enhancement: new base rule extension, package: eslint-plugin
