### ISSUE TITLE
Parsing error with redux-actions

### ISSUE THREAD

**Issue by kml-w-da** [typescript-eslint/typescript-eslint#1748] opened 2020-03-16 20:24 UTC
**What code were you trying to parse?**

index.ts
```ts
export * from './bb';
```

bb.ts
```ts
import { createAction } from 'redux-actions';

export const fetch = createAction(
    'FETCHMORE',
    (streamId: string) => ({ streamId })
  );
```

**What did you expect to happen?**
In version 2.23 it works.

**What actually happened?**
/bb/index.ts
  0:0  error  Parsing error: Cannot read property 'name' of undefined

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `2.24.0` |
| `TypeScript`                           | `3.7.5` |
| `node`                                 | `10.16.0` |
| `npm`                                  | `6.13.4` |

**Comment by bradzacher** [comment] 2020-03-16 20:25
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/1746

**Closed by bradzacher** 2020-03-16 20:25 UTC
Labels: package: typescript-estree, triage
