### ISSUE TITLE
Repo: Add a "No Brown M&Ms" equivalent to CONTRIBUTING.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7163] opened 2023-07-04 16:09 UTC
### Suggestion

Shoutout to @orta for https://github.com/CocoaPods/CocoaPods/blob/40a99f47cdca42c1d813a9c693730a3102cebd13/CONTRIBUTING.md#no-brown-mms:

> If you made it all the way to the end, bravo dear user, we love you. You can include this emoji in the top of your ticket to signal to us that you did in fact read this file and are trying to conform to it as best as possible: 🌈

I love this. It's a great idea (see https://en.wikipedia.org/wiki/Van_Halen#Contract_riders for _"No Brown M&Ms"_ context).

I kind of like the idea of letting people express a bit of individuality. Maybe: their favorite emoji?

> If you made it all the way to the end, bravo dear user, we love you. Please include your favorite emoji in the top of your ticket to signal to us that you did in fact read this file and are trying to conform to it as best as possible. 💖 is a good starter if you're not sure which to use.

**Comment by NextThread** [comment] 2023-08-17 04:54
Hey, can I work on this?

**Comment by Josh-Cena** [comment] 2023-08-17 05:05
This is a duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/7216 which is already fixed!

**Closed by Josh-Cena** 2023-08-17 05:05 UTC
Labels: repo maintenance, accepting prs
