### ISSUE TITLE
Bug: [consistent-indexed-object-style] Fails to auto-fix record using a generic or an enum as the key 

### ISSUE THREAD

**Issue by emileber** [typescript-eslint/typescript-eslint#5585] opened 2022-09-01 05:52 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Repro Code

```typescript
enum MyEnum {}

type EnumObj = Record<MyEnum, string>;

type GenericObj<T, K extends keyof T> = Record<K, T[K]>;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint"],
  rules: {
    "@typescript-eslint/consistent-indexed-object-style": [
      "error",
      "index-signature"
    ]
  },
};
```

### Expected Result

```ts
enum MyEnum {}

type EnumObj = { [key in MyEnum]: string };

type GenericObj<T, K extends keyof T> = { [key in K]: T[K] };
```

### Actual Result

```ts
enum MyEnum {}

type EnumObj = { [key: MyEnum]: string };
//                ^^^
type GenericObj<T, K extends keyof T> = { [key: K]: T[K] };
//                                         ^^^
```

Triggering the following TS errors:

> An index signature parameter type must be 'string', 'number', 'symbol', or a template literal type. ts(1268)
> An index signature parameter type cannot be a literal type or generic type. Consider using a mapped object type instead. ts(1337)

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.36.1` |
| `@typescript-eslint/parser`            | `5.36.1` |
| `TypeScript`                           | `4.8.2` |
| `ESLint`                               | `8.23.0` |
| `node`                                 | `18.7.0` |

**Comment by bradzacher** [comment] 2022-09-01 07:11
Duplicate of #4730

**Closed by bradzacher** 2022-09-01 07:11 UTC
Labels: bug, package: eslint-plugin, triage
