### ISSUE TITLE
Bug: @typescript-eslint/no-unnecessary-condition don't apply on changed types with ESlint `--cache` 

### ISSUE THREAD

**Issue by QuentinLemCode** [typescript-eslint/typescript-eslint#6522] opened 2023-02-23 11:30 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

On a big project we recently added the `@typescript-eslint/no-unnecessary-condition` rules.
This rule add value to the codebase as it push developers to gain attention to types and avoid using optional where it's not needed.

As it is a big project we use the `--cache` option of ESlint, reducing our CI lint task from 15 minutes to only 1~2 minutes.

However, when a type is changed, the files using this type are not invalidated in the cache.

We are puzzled about how to solve this issue. It would be a pity disable this rule. And we can't afford to disable the cache as the CI pipeline is already long and costly.
Do you see another way to solve this in a quick win ?

Also, can we consider adding a new feature (like a new cache strategy) to invalidate cache entries for file content change and files impacted by types changed ?

### Reproduction Repository Link

https://github.com/QuentinLemCode/eslint-cache-issue

### Repro Steps

1) clone the repo
2) nvm use
3) npm install
4) npm run lint 
--> should return no error
5) edit `src/file2.ts` and remove the optional `?` on line 2, save the file
6) npm run lint
--> shoud return no error however a linting issue is present on `src/file1.ts` !

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.53.0` |
| `@typescript-eslint/parser`            | `5.53.0` |
| `TypeScript`                           | `4.9.5` |
| `ESLint`                               | `8.34.0` |
| `node`                                 | `19.6.0` |

**Comment by bradzacher** [comment] 2023-02-23 13:18
duplicate of #6373
Please use the search

**Closed by bradzacher** 2023-02-23 13:18 UTC
Labels: bug, triage
