### ISSUE TITLE
🐛 Package with devDependency on typescript@^3.9.9 can't npm install with typescript@>=4.8.4 peer dependency added in v8.18

### ISSUE THREAD

**Issue by ljharb** [typescript-eslint/typescript-eslint#10480] opened 2024-12-09 18:57 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/

### Repro Code

```TypeScript
`npm show @typescript-eslint/parser@8.17 peerDependencies`

vs

`npm show @typescript-eslint/parser@8.18 peerDependencies`
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

n/a

### Actual Result

n/a

### Additional Info

Adding a peer dependency is always a breaking change, and this one is breaking eslint-plugin-react's tests.

**Comment by ljharb** [comment] 2024-12-09 18:59
I can't figure out when this was actually added; it seems like perhaps #9165?

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 19:09
From our perspective, #10373 was a bugfix: packages _implicitly_ had a peer dependency on `typescript` via `ts-api-utils` and it was a bug that that relationship wasn't explicitly declared.

Could you please post a reproduction case we can tinker with and an explanation of why making that dependency explicit would break downstream plugins?

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 19:10
From our perspective, #10373 was a bugfix: packages _implicitly_ had a peer dependency on `typescript` via `ts-api-utils` and it was a bug that that relationship wasn't explicitly declared.

Could you please post a reproduction case we can tinker with and an explanation of why making that dependency explicit would break downstream plugins?

Also, I realize you maintain a bagillion packages and know this practice, but for our sake: please write somewhat more precise titles than _"breaking change in <version>"_. It's very worrisome to see a vague, catastrophic-sound title like that. 😄

**Comment by ljharb** [comment] 2024-12-09 19:19
Seems like `@typescript-eslint/typescript-estree` 8.18 also added the peer dep.

For a reproduction case, you can clone https://github.com/jsx-eslint/eslint-plugin-react/commit/d5da0a6cfae70fbef4d30b5161701d4b64cfff73 and see that `npm install` fails (see also https://github.com/jsx-eslint/eslint-plugin-react/actions/runs/12241703652/job/34147390210 for an example in CI)

Given that v8.0 of the estree package also depended on ts-api-utils, and v1 of ts-api-utils always had the peer dependency, I'm confused why this issue didn't come up sooner - I'd have expected the same issue to be surfaced earlier, but maybe the ts-api-utils peer dep requirement was low enough in the tree that it just ended up installing 2 copies of typescript.

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 19:26
Yeah, I'd also have expected that.

```plaintext
# npm resolution error report

While resolving: eslint-plugin-react@7.37.2
Found: typescript@3.9.10
node_modules/typescript
  dev typescript@"^3.9.9" from the root project

Could not resolve dependency:
peer typescript@">=4.8.4 <5.8.0" from @typescript-eslint/parser@8.18.0
node_modules/@typescript-eslint/parser
  dev @typescript-eslint/parser@"^2.34.0 || ^3.10.1 || ^4 || ^5 || ^6.20 || ^7.14.1 || ^8.4" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

Confirming I'm understanding the problem:
* The package declares a dependency on `^3.9.9` of `typescript`
* `@typescript-eslint/parser` requires `>=4.8.4`
    * `ts-api-utils` also has `peerDependencies: "typescript@>=4.8.4"`
* npm can't resolve that conflict and complains

Is that correct? And if so, what's the normal right way to deal with this, given that the entire major version 8 of `@typescript-eslint/*` does not support TypeScript <4.8.4?

**Comment by ljharb** [comment] 2024-12-09 20:07
That's a good question.

Certainly the peer dep should have been included as part of v8.0.0. If I was reporting an issue with *using* the software with TS 3 installed, then it would be perfectly fine to tell me to shove it :-)

In this case, the issue is with *installing* the software with TS 3 installed.

A simple fix is to remove the peer dep entry, or maybe to mark it as optional? that would restore the bug it was trying to fix, though.

An alternative for my project specifically would be upgrading it to also use TS 4 (and still 3, and eventually also 5), but that's not a reasonable ask for me to make of yall ofc.

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 20:44
> remove the peer dep entry, or maybe to mark it as optional

Maybe I'm misinterpreting: as I understand it, the `typescript` peer dependency _isn't_ optional. I think it's required: that in order to install `@typescript-eslint/parser@8`, you _must_ have  `typescript@4.8.4` installed. Otherwise you `require('typescript')`/similar might resolve to a version of `typescript` outside the supported range, which seems to only maybe coincidentally work.

I think that's exactly what's been happening: that `eslint-plugin-react` is providing `@typescript-eslint/parser` with `typescript@3` and thanks to TypeScript being pretty stable, it's Just Worked so far.

**Comment by ljharb** [comment] 2024-12-09 21:05
yes, i think that's exactly what's been happening.

That also suggests you could expand the peer dep to allow TS 3 (both here and in ts-api-utils) and it'd be fine™

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 21:23
![Arbiter in Halo 3 telling Lord Hood against a sunset: "were it so easy"](https://github.com/user-attachments/assets/d44bbd5c-83a4-40ff-8453-4d4f2b544ab6)

It might work nicely in `eslint-plugin-react`'s specific use case but there are definitely parts that will break if used more exhaustively. A first quick example is #1774 -> #2004 dropping support for some older 3.X TS versions so that we can rely on newer TypeScript APIs. More recently, #8930 -> #8938 showing trimming out a bit of old code that was necessary for supporting an old TypeScript verison. I'm sure there are a bunch of other examples one could pull out with more searching.

We keep to the same support window as DefinitelyTyped to trim down on old code and lessen the burden of supporting old TypeScript versions. I would love to support old versions but we just don't have the bandwidth to do that _and_ make meaningful progress on docs, rules, etc.

Closing out as this seems to be a result of more correctly enforcing the package's semver dependencies. I.e. a bugfix. But happy to keep talking and potentially re-open if there's something better we can do!

**Closed by JoshuaKGoldberg** 2024-12-09 21:23 UTC
Labels: bug, package: eslint-plugin, triage
