### ISSUE TITLE
[naming-convention] Only check for own code. Not from packages or global scope. Ignore own objects when using external types.

### ISSUE THREAD

**Issue by infacto** [typescript-eslint/typescript-eslint#2695] opened 2020-10-21 09:17 UTC
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

**.eslintrc.json**

```json
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "default",
        "format": ["strictCamelCase"]
      },
      {
        "selector": "variable",
        "modifiers": ["const"],
        "format": ["strictCamelCase"]
      },
      {
        "selector": "property",
        "format": ["strictCamelCase"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "property",
        "modifiers": ["static", "readonly"],
        "format": ["strictCamelCase", "UPPER_CASE"]
      },
      {
        "selector": "typeLike",
        "format": ["StrictPascalCase"]
      },
      {
        "selector": "enumMember",
        "format": ["StrictPascalCase"]
      }
    ]
  }
}
```

**http.service.ts**

```ts
import { HttpHeaders } from '@angular/common/http';

export class HttpService {
  public getBlobHeader(): HttpHeaders {
    const httpHeaders = new HttpHeaders({
      'Content-Type': 'application/octet-stream',
      Accept: 'application/json',
    });
    return httpHeaders;
  }
}
```

**tsconfig.json**

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": ["es2018", "dom"]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Actual Result**

![demo](https://user-images.githubusercontent.com/60390085/96701642-206afc00-1391-11eb-9714-8f5c5d5f4d4e.gif)

The properties are marked as problem. Because ESLint does not distinguish between own and foreign code. In this case, it's my code, yes. But forced by the external type `HttpHeaders`.

**Expected Result**

The properties of `HttpHeaders` comes from an external package. I have no control over it. I cannot force my naming convention to the Angular team. 

**Additional Info**

No solution yet. Not workaround. I don't want to speficy an ignore pattern for specific names. It's a good solution to exclude names. I had no problems with TSLint. I also used naming-conventions. See [tslint-consistent-codestyle](https://github.com/ajafff/tslint-consistent-codestyle) ([docs](https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/naming-convention.md)).

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.2.0` |
| `@typescript-eslint/parser`        | `4.2.0` |
| `TypeScript`                       | `3.9.5` |
| `ESLint`                           | `7.10.0` |
| `node`                             | `10.22.1` |

**Comment by bradzacher** [comment] 2020-10-21 16:26
There's inherently no discernible difference between
```js
const x = {
  'Content-Type': foo
};
```
and
```js
new HttpHeaders({
  'Content-Type': foo
});
```

This case is specifically called out in our docs:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#ignore-properties-that-require-quotes

Duplicate of #1483

**Closed by bradzacher** 2020-10-21 16:26 UTC
Labels: duplicate, package: eslint-plugin
