### ISSUE TITLE
Rule proposal: error on comparisons where the only comparable type is undefined

### ISSUE THREAD

**Issue by Zzzen** [typescript-eslint/typescript-eslint#5602] opened 2022-09-05 08:15 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

```ts
declare var userIdA: string | undefined ;
declare var userIdB: number | undefined;

if (userIdA === userIdB) {
    console.log('never reached');
}
```

We use swagger to generate api definition and most properties are declared optional. We may have compared objects of different shapes without typescript compiler complaining because both contain `undefined`.

### Fail Cases

```typescript
declare var userIdA: string | undefined ;
declare var userIdB: number | undefined;

if (userIdA === userIdB) {
    console.log('never reached');
}
```

### Pass Cases

```typescript
declare var userIdA: number | string | undefined ;
declare var userIdB: number | undefined;

if (userIdA === userIdB) {
    console.log('never reached');
}
```

**Comment by JoshuaKGoldberg** [comment] 2022-09-14 20:21
🤔 this feels like a rather niche proposal. It makes sense in the use case described, but I've never seen this be an issue in real world code before. Do you have any examples where this rule would have caught any bugs @Zzzen?

My instinct is that this would be best implemented in a third party plugin, and only added to typescript-eslint core if it ends up being popular.

**Comment by bradzacher** [comment] 2022-09-14 21:13
That was my thinking too. I've been humming and ha-ing over this and I wasn't sure if this was really something that causes issues in codebases.

The big reason it's not problematic code is that [TS will completely understand the comparisons and will refine the type as expected.](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA3W8CuBnEMCSwCCAXPOgC4wCWAdgObwA+aloAZlSMPANwBQoksCZDDSYcwAEJFKqALYAjLPUYs2wHt3LN4ACgxZceeAF4TI-RICU8AN7d49+GAD2ldE4ggAdBCfVtAckoQREU4KDAAC3Z-Cx4HMzE8HgB6ZIcAPQB+Owc9MXEUtPss7gBfIA). So you'll either refine into or out of a nullish type.
You marked your examples as "never reached" but that's not strictly true because the branch could be reached if and only if both values are undefined (as shown in the playground above).

So whilst it's definitely a comparison of dubious quality - with the type refinement you can actually get something out of it.

I too would like to see an example of a real world bug that was caused by this to help clarify and root the justification.

**Comment by Zzzen** [comment] 2022-09-16 14:25
Yeah, I agree it is a niche proposal. But that code is unlikely what we intend to write: [ts playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkHLAAmA-AFzIgCuAtgEbQDc+hIctEFy6YUoAcxYBfXLlCRYiFAGEA9uAgAPMDlYEE1KFAjgM0bvqgixE6PCTIAYsAA2KPISJlKvfiCHrkcgO4gDlDQMzLiiuMQQCLZwOsgICrzIMHYQlDb2LBFRMSjxIIkIYEqU8ooqLLgA9JXIYAAWwOjItqAotnJyANZNyf7IcCDEyAAOcOiYTWAAnsO5dZHdAHRVNfTUqsAbTdSY9uPLwDDIABTJ9ou+-lDIAIQAvHdxRYua2rpgRgCUak71UL5UCA+ZAAUW0cigxwARLMoLRGuhgApkBEQMAIMQoZ9QmIgA)

```ts
interface User {
    id?: number;
    name?: string;
}

interface Context {
    currentUser?: User;
}

interface File {
    id?: string;
    owner?: number;
}

declare const file: File;
declare const ctx: Context;

// this line looks fine and passes type checks.
// but it is useless.
if (file.owner !== ctx.currentUser) {
    throw new Error("permission denied")
}
```

**Comment by bradzacher** [comment] 2022-09-16 15:16
What's really funny here is that TS doesn't narrow your types because of the aforementioned structural typing.

When you compare `User | undefined` to `number | undefined`, TS cannot refine the types at all because technically `number` is assignable to `User`.

Why? Because `User` defines all optional properties - so in reality it's not much different to `{}`. Put another way - `number` **technically** had the shape `{id: undefined, name: undefined}`, thus it is assignable to `{id?: number, name?: string}`.

And this circles back to what I am saying - due to how TS's structural typing model works two types could be technically assignable / comparable even though you don't intend them to be.
Put another way - there would be a lot of cases that would appear to be false negative as defined by the user, that are actually true negatives as defined by the type system.

TS types are funky!

**Comment by Zzzen** [comment] 2022-09-16 16:22
Assignable is different from comparable.
Comparable: intersection of two types is not empty.
Assignable: source is a subtype of target

> When you compare User | undefined to number | undefined, TS cannot refine the types at all because technically number is assignable to User.

Nah
```ts
// Type 'number | undefined' is not assignable to type 'User | undefined'.
//   Type 'number' has no properties in common with type 'User'.(2322)
ctx.currentUser = file.owner;
```

**Comment by bradzacher** [comment] 2022-09-16 22:45
TS is quite helpful in assignments - it does its best in order to help you **not** shoot yourself in the foot due to its structural typing model.
TS knows that most people don't truly understand its structural typing model so it has added guard rails to watch for probable misunderstandings.

However you can see that if we do something like this where we add a "property in common", then now we've "worked around" the guard rail.
```ts
declare function acceptsObjWithOptionalProp(foo: {id?: number, toString(): string}): void;
acceptsObjWithOptionalProp(1);
```
[play](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXyjDBAAcMBnAeQCMArAdSwwAtKzdUoIAFGHEgBSIcOAFzwA3lmAB+camQBbaiBgAaeBhwBlDDCyoA5gICU48noOGAvmfgA3HNIDcAKELEyVOoxZtseFy8-AIAjCZuQA)

You can also work around the guard rail with an explicit assertion
```ts
const x = 1 as {id?: number};
```
[play](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDAjDAhhGBvAlgEwH4AuGMAVwFsAjAUwCcBfAbgCgB6dmbmAPUKA)

> Comparable: intersection of two types is not empty.

What do you mean by "intersection" here? How would you calculate this "intersection"?
I assume you mean like given `number | undefined` and `string | undefined`, the intersection of the two types is the types that are shared between them, so it would be `undefined`.

But how do you calculate this list of "types that are shared"?
Well we can calculate this by checking each type in union A against each type in union B to determine if it is "comparable to" one type in that intersection. But now our definition is recursive with no base case - so we need to define how to compare one non-union type with another non-union type.

So how can we do that?
Well the simplest way would be a raw text check. However this falls over very quickly because `1` and `number` are different and thus wouldn't be comparable (which is obviously incorrect). So we can't be that simple.

You can't just check for property equivalence either because ideally you want covariant types to be comparable - i.e. `{id?: number}` and `{id?:number, other?: string}` should be comparable as the latter is a subtype of the former.

So the best way to describe this "comparable to" check for non-union types is that the two types must be covariantly related (i.e. one must be assignable to the other).

**Comment by Zzzen** [comment] 2022-09-17 01:56
Sorry I did not make myself understood. Only union types are considered here. We will/should use `checker.isComparableTo` if it would ever become public. The algorithm of this rule is roughly:

```ts
function check(comparison: BinaryExpression) {
    const left = getTypeOfExpression(comparison.left);
    const right = getTypeOfExpression(comparison.right);

    if (!checker.isComparableTo(left, right) || !isUnionType(left) || !isUnionType(right)) {
        return;
    }

    for(const i of left) {
        for(const j of right) {
            if (checker.isComparableTo(i, j)) {
                // common type found and it is not `undefined`
                if (i !== j || i !== checker.getUndefinedType()) {
                    return
                }
            }
        }
    }
    
    errorOnNode(comparison, "the condition is met only if both sides are undefined. this is likely a typo.")
}
```

**Comment by bradzacher** [comment] 2022-09-17 08:50
No definitely - I understand the intent of the issue and your goals.
What I'm saying is that how can you tell that a check like `(string | undefined) !== (number | undefined)` should violate the rule?

What does that look like?

Well if we investigate the TS codebase we can find out! Within `src/compiler/checker.ts` (sadly can't link lines because the file is too big for GH) you'll find the function `isTypeComparableTo`, which has this description:

> A type S is comparable to a type T if some (but not necessarily all) of the possible values of S are also possible values of T.
> It is used to check following cases:
> - the types of the left and right sides of equality/inequality operators (`===`, `!==`, `==`, `!=`).
> - the types of `case` clause expressions and their respective `switch` expressions.
> - the type of an expression in a type assertion with the type being asserted.

Great! So this function is the function used for type checking equality checks - great!
But it doesn't explain what it actually does - what does "are also possible values of T" mean?
Digging into this function's actual implementation, you'll find that it eventually calls `checkTypeRelatedTo`, which has this description:

> Checks if 'source' is related to 'target' (e.g.: is a assignable to).

Digging into it more, it looks like TS is able to tell that `{id?: number}` is not comparable to `number` - which is great. However it also does mean that `{id?: number, toString(): string}` is comparable to `number`.

Which underpins what I was trying to explain in my previous comment - assignability means that two types must be covariantly related (i.e. one type is a subtype of the other type). Whilst TS has some guard-rails, ultimately structural typing means that this rule won't work as well as you might want for the "object" case.

**Comment by Zzzen** [comment] 2022-09-17 13:47
I see. It is surprising that an object with all properties being optional is comparable to basically everything.

```ts
interface Foo {
    foo?: string;
}
interface Bar {
    bar?: string;
}

declare let foo: Foo;
declare let bar: Bar;
foo = bar;  // Error: Type 'Bar' has no properties in common with type 'Foo'.
bar = foo;  // Error: Type 'Foo' has no properties in common with type 'Bar'.
foo === bar
foo === 1


declare let foo2: Required<Foo>;
declare let bar2: Required<Bar>;
foo2 = bar2;  // Error: Property 'foo' is missing in type 'Required<Bar>' but required in type 'Required<Foo>'.
bar2 = foo2;  // Error: Property 'bar' is missing in type 'Required<Foo>' but required in type 'Required<Bar>'.
foo2 === bar2   // Error: This condition will always return 'false' since the types 'Required<Foo>' and 'Required<Bar>' have no overlap.
foo2 === 1      // Error: This condition will always return 'false' since the types 'Required<Foo>' and 'string' have no overlap.
```

**Comment by bradzacher** [comment] 2022-10-02 01:02
Based on the above discussion - I don't think this rule is ultimately going to be feasible to build this rule.

I can only see it "working" if we completely restrict it and circumvent structural typing.
I.e. we enforce that two types have the same properties. But that's likely going to lead to surprising lint errors.

I think for now at least we should just close this, until such time that TS has a public-facing "are types related" API that we can leverage.

**Closed by bradzacher** 2022-10-02 01:02 UTC
Labels: package: eslint-plugin, enhancement: new plugin rule, awaiting response
