### ISSUE TITLE
Bug: [consistent-type-imports] Using with isolatedModules and emitDecoratorMetadata

### ISSUE THREAD

**Issue by HaoboZ** [typescript-eslint/typescript-eslint#5468] opened 2022-08-12 17:04 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.4&sourceType=module&code=JYWwDg9gTgLgBDAnmApnA3nA0ixcC+cAZlBCHAORQoCGAxjBQNwBQLAJinQDY3XEBXAHYNgEIXAAiXaDRjQAFGFKpYiAHI0QKAPwAuOAGcYUYEIDmASgMAFPlpQwUUaXVnyorFigAekWHCcRDQC3PA8NIaGcAAqKMYYbHBwkYgigiIKLMnJAAKu7oqWcGD2IAY4iNlwxejVydQwAlASpVBarMn4bN1AA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2uCUADgDYCuA5gJZKYAC8AnodGgMYBOlh8AtC8dXgB6dtFYB7ALaTkKaCkj4AugBp8kQgEN2aaOyxR6TFhy69+goVp17IaiBu272AeW6VxSDNlAEi7cQArMXgDSAA6IXg2TwAzSnJwwLRPRQgAX3siMiovAzw-SCNmNk5uPjQBJFDlLMh2UmIWA18CIsYS03KLaqEJL0o0RGqeDugeSklCcXZo-PxCgHdtJDsFgla-B0JRWNtsSDGJqZm59Yz1pXx0kHSgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk8sAJgK4YVTolHoAeekANOBqRkJWKgCGedAwCyjFhzZ5MTdIJrt4yPABF0cTFNiZZ6PBIZSJy1eqG0eiLMnjoiF1PsPHMZSipqQgC+IMFAA

### Repro Code

```typescript
import type { Key } from 'react';

declare function Decorator( propertyName?: string ): ParameterDecorator;

export default class Test {
	
	async func(
		@Decorator() param: Key
	) {
		return param;
	}
	
}
```

### ESLint Config

```javascript
{
	"parser"       : "@typescript-eslint/parser",
	"parserOptions": {
		"project": "./tsconfig.json"
	},
	"plugins"      : [ "@typescript-eslint" ],
	"rules"        : {
		"@typescript-eslint/consistent-type-imports": [ "warn", { "prefer": "type-imports" } ]
	}
}
```

### tsconfig

```jsonc
{
	"compilerOptions": {
		"module"                : "esnext",
		"isolatedModules"       : true,
		"emitDecoratorMetadata" : true,
		"experimentalDecorators": true
	}
}
```

### Expected Result

No errors showing for both the decorator and the type import

### Actual Result

if you use import type, you get 
`ESLint: Type import "Key" is used by decorator metadata.(@typescript-eslint/consistent-type-imports)`
while if you use just import, you get 
`TS1272: A type referenced in a decorated signature must be imported with 'import type' or a namespace import when 'isolatedModules' and 'emitDecoratorMetadata' are enabled.`
Not sure if there's a better way to do this since isolatedModules must be set

### Additional Info

This doesn't need complex setup, literally any type import will throw an error for this so I'm not sure if this needs reproduction repository

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.33.0` |
| `@typescript-eslint/parser`            | `5.33.0` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.21.0` |
| `node`                                 | `16.5.0` |

**Comment by bradzacher** [comment] 2022-08-13 10:17
This doesn't repro in the playground at all and I can't repro any changes in types in the TS playground.
Could you please provide a repro repo to help us reproduce this?

**Comment by HaoboZ** [comment] 2022-08-15 17:06
@bradzacher https://github.com/HaoboZ/consistent-type-imports-error

**Comment by vitalyiegorov** [comment] 2022-08-16 12:12
Same issue, can cofirm, started with upgrading typescript to 4.7.4

**Comment by JoshuaKGoldberg** [comment] 2022-08-16 19:55
Hmm, this is a bug starting with TypeScript 4.7. I suppose the rule could ask for compiler options and check them. But then users might be confused if they're running ESLint with different compiler options than their editor... I think that is probably fine, since that case is bad anyway. 🤷

**Comment by bradzacher** [comment] 2022-08-17 11:38
> Not sure if there's a better way to do this since isolatedModules must be set

Why *must* it be set?

---

This is really problematic from TS IMO - when `isolatedModules` is turned on TS acts in a non-isolated module way!!!

What's happening is that TS is looking at the imported name `A` and is interrogating the type. It recognises that it's a type declaration and reports an error to force you to make it a type-only import so that other tools that act on single files without type information will act correctly - i.e. ensuring that they'll emit the `+` line below, not the `-` line:
```diff
  __decorate([
      __param(0, Decorator()),
      __metadata("design:type", Function),
-     __metadata("design:paramtypes", [A]),
+     __metadata("design:paramtypes", [Object]),
      __metadata("design:returntype", Promise)
  ], Test.prototype, "func", null);
```

You can verify this is the behaviour by changing the declaration of `A` from a type to a class. When it's a class - TS will not report `TS1272` and force it to be a type-only import - it will allow either a type or a value import.

This is an issue because our rule interrogates from a pure, isolated module perspective without any types - so we don't have the information to tell that `A` is a type.

This is essentially the same issue as outlined in https://github.com/typescript-eslint/typescript-eslint/issues/3108#issuecomment-785342161, except as mentioned this is egregiously so because TS is acting in a non-isolated modules mode.

In general TS behaves *really* weirdly when it comes to `emitDecoratorMetadata`. Here's an example of a different bug we found (https://github.com/microsoft/TypeScript/issues/42679).

At this point I'm thinking that we should just flat out ignore any import that's used in a class that's got a decorator because there's no way for us to correctly report on it.

**Comment by HaoboZ** [comment] 2022-08-17 16:50
Mostly because of next.js, that field must be set, and if I want to use decorators with it, that rule is incompatible

**Comment by matthewjh** [comment] 2022-08-19 17:40
It seems to me like this is the root of the problem:

> This is an issue because our rule interrogates from a pure, isolated module perspective without any types - so we don't have the information to tell that A is a type.

I think to implement this rule as people expect, eslint does need to look at the type information. I don't think this is in any way contradictory, either: the point of type imports (or one of them) is to encode an aspect of the type information (is this a type or a value?) statically into the file so that tools like SWC which don't consume types can faithfully output working code, but of course to produce this information in the first place (or validate that it is in fact correct, as in eslint's case), requires type analysis. There is no way to verify non-local-type-dependent information without checking types.

**Comment by bradzacher** [comment] 2022-08-19 20:36
For every other case using pure AST analysis is fine - you just need to check if the imported name is used in a value position. If it is - ignore it, otherwise enforce it is a type-only import.
Which intuitively makes sense because types do not ever change emitted code - they are always scrubbed at build time.

However when `emitDecoratorMetadata` is turned on this all changes. Now types do impact emitted code!
If the name represents a value then *if and only if* it is used in a type location AND that location is in an annotation of a function signature for a class that has a decorator then and only then the import *must not* be a type-only import because TS will implicitly emit a value reference to the name.
Worth noting that it's not only value imports that impact the emittes code but types too, though this is not via an emitted reference, but instead by TS emitting the "primitive" type of the type.

So now you have this weird behaviour which is contrary to all other behaviour and requires type information so that we can detect if an imported name is a type.

> Is there some technical reason why this rule is not looking the transitive type info?

Type information is almost entirely unnecessary, as mentioned above.
It's just this option which requires it.

Type information is expensive to consume because (a) a type-aware "build" is required before linting and (b) types are computed lazily - meaning the more types you access the more time you spend linting.

Because of this cost - a lot of users chose not to use type-aware linting. So making a rule use types is something we do only when absolutely necessary because it restricts how many users can use a rule.

---

For full context:

When I first implemented this rule I didn't know about the decorator metadata case because I have never used decorator metadata. To be fair - a significant portion of our users don't either as I think it's only angular that uses it (react definitely doesn't).

When users raised this issue we investigated the logic TS used and we build special logic into the scope analyser so it would mark the references as value references and make the rule work.

Because angular used TS directly in its builds this logic of always enforcing value imports was "good enough".
Now however the ecosystem has grown and there are cases that don't use TS for builds.

---

So we are left with two choices:
1) add type-information to the rule in a breaking change and prevent users from using it so that we can fully support this case.
2) make the rule ignore all imports that are used in decorator metadata.

I think (2) is the best option because TS now has an error which handles this case.
That way we can also keep the rule light and fast.
Additionally if, for some reason, someone does want a rule to handle this case (2) means someone could build a separate type-aware rule just for that case.

**Comment by Shinigami92** [comment] 2022-08-26 06:48
I can reproduce this using NestJS

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/186839893-3542d6fe-36b1-4179-9baa-05534b1ef26a.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/186839966-065f5b38-bf68-4221-abed-3db4d2a041bb.png">

**Comment by jiby-aurum** [comment] 2022-09-15 14:06
@bradzacher wouldn't it be possible to add type-information to the rule in a non breaking change, preferably using an option ? Such that the breaking change only happens in case type aware linting is configured and `useTypeInformation` is specified on the rule.

```typescript
interface Options {
  prefer?: "type-imports" | "no-type-imports";
  disallowTypeAnnotations?: boolean;
  useTypeInformation?: boolean
}
```

**Comment by bradzacher** [comment] 2022-09-15 14:24
@jiby-aurum it's technically possible - yes - however it's not something we do due to complexity.
Configuring the tooling is already complicated enough for most users, and conditionally using type information in a rule based on a config makes it that one step more complicated.

That aside - TBH I don't think it's a good idea for us to even attempt to make this work in this case. Simply put - because we don't want to be in the position of re-implementing TS's logic.

Unfortunately as we've seen with this issue TS can change their logic from version to version. This would mean that in order for us to properly support every version of TS, we would need to inspect the TS version and fork to the appropriate logic. That's truly awful for maintenance.
Additionally TS's logic can change based on the presence of other compiler options. So combined with versioning, we could need to maintain forks within forks to properly support it.

For us as *volunteer* maintainers, it's just not worth the maintenance burden - regression testing old TS versions isn't something we've been able to setup yet, so there's no way for us to verify that the rule would work for past and future TS versions.

This is why I say that the preferred solution to the problem is for the rule to just ignore any imported name that is used in a location that might appear in decorator metadata. That means that everyone can continue freely using the rule in every codebase and we won't ever suggest or autofix changes that will introduce type errors.

**Comment by jiby-aurum** [comment] 2022-09-15 14:55
@bradzacher completely makes sense, was not aware of the complexity involved. For me personally your preferred solution perfectly gets the job done.

Thanks for the explanation 👍

**Comment by TomMettam** [comment] 2022-09-21 15:48
I reported this previously in #4608, it's existed since then.

I *am* using type-aware linting.

**Comment by Llois41** [comment] 2022-10-07 09:34
Hi @bradzacher when will this ignoring rule option be available? Asking because I'm in the middle of activating this rule in all our modules and some are blocked by this issue. :) Thanks for the explanation and good work!

**Comment by bradzacher** [comment] 2022-10-07 10:23
We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.

If this issue is important to you - consider being that champion.

**Comment by mahnke25** [comment] 2022-10-13 23:17
For what it's worth, you can more or less fix this by moving the `type` keyword inside the braces.
```
import { type Key } from 'react';
```

**Comment by djmisterjon** [comment] 2023-03-28 09:00
!! how can we fix this ? a rule ? i dont get it ! 
![image](https://user-images.githubusercontent.com/24865815/228185165-3849ec04-cc5a-4607-8dbf-00cd67aed2aa.png)

**Comment by aldenquimby** [comment] 2023-06-08 19:12
https://github.com/typescript-eslint/typescript-eslint/issues/5468#issuecomment-1278274384 was marked as off topic, but I'm re-posting it b/c it is a valid short term solution if you're blocked on this. From the initial example, instead of this:
```ts
import type { Key } from 'react';
```

Change it to this:
```ts
import { type Key } from 'react';
```

The lint rule will pass, and TypeScript will also be happy with isolatedModules + emitDecoratorMetadata

Unfortunately auto-fixing still won't work, so it's not a great long term solution

**Comment by benasher44** [comment] 2023-06-18 17:52
> [#5468 (comment)](https://github.com/typescript-eslint/typescript-eslint/issues/5468#issuecomment-1278274384) was marked as off topic, but I'm re-posting because it is a valid short term solution if you're blocked. From the initial example, instead of this:
> 
> ```ts
> import type { Key } from 'react';
> ```
> 
> Change it to this:
> 
> ```ts
> import { type Key } from 'react';
> ```
> 
> The lint rule will pass, and TypeScript will also be happy with isolatedModules + emitDecoratorMetadata
> 
> Unfortunately auto-fixing still won't work, so it's not a great long term solution. If you are converting an existing codebase, you can:
> 
>     1. Turn `emitDecoratorMetadata` off
> 
>     2. Set `"fixStyle": "inline-type-imports"` on this rule
> 
>     3. Run lint fix
> 
>     4. Turn `emitDecoratorMetadata` back on

You can also make a tsconfig.eslint.json that is used just by your eslint config to do something similar:
```json
{
  // eslint uses this file to workaround https://github.com/typescript-eslint/typescript-eslint/issues/5468
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": false
  },
}
```

**Comment by akwodkiewicz** [comment] 2024-01-23 14:33
What's also important here, but might have been overlooked, is that the TypeScript behaviour changes with the `moduleResolution`.

Even with TS 5.2, with `isolatedModules` and `emitDecoratorMetadata` you can still do a "full" import and not have TS complain, as long as you're using **an outdated `moduleResolution` setting**:

```json
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "isolatedModules": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
}
```
Even for a type of a decorated variable, TS will be fine with a "full" import -- exactly how the `consistent-type-imports` rule tells us to do, based on the `emitDecoratorMetadata`. After all, that's the reason for having this `emitDecoratorMetadata` setting for `consistent-type-imports` -- if you see that the type is eventually decorated, import the whole thing.

But the moment you change the `moduleResolution` to something modern, like `Node16` (`NodeNext`), then TypeScript starts telling you that you have to change the "full" import into a lighter "type" import. And then it's mutually exclusive to what the ESLint rule has done in the past.

So after all it's a _change_ in TS's behaviour, because the rule's behaviour with `emitDecoratorMetadata` used to be correct (and still is, in outdated TS projects).

I have a feeling that simply turning `emitDecoratorMetadata` off (just like the previous comment suggests https://github.com/typescript-eslint/typescript-eslint/issues/5468#issuecomment-1596222250) is the only way to go (unless we want to make additional tsconfig parsing of moduleResolution).

---

When you use SWC the rule actually behaves correctly, because it is still the case that importing the whole object is necessary for SWC to correctly emit decorator metadata. Otherwise it's just decorating the variables with `design:paramtypes` set to an empty array.

But if I'm using SWC, then my moduleResolution is not set to NodeNext, but to Bundler.

...however I thought that by changing the moduleResolution to NodeNext I will trigger the issue in this other project, but I cannot. It's some kind of a heisenbug that I cannot put my finger on.

The most relevant issue to this in the TS repo I was able to find is this: https://github.com/microsoft/TypeScript/issues/54717

But I wasn't able to find any data that explicitly states that the behaviour of `import type` vs `import` has changed for Node16.

**Closed** 2024-03-24 23:35 UTC
Labels: bug, package: eslint-plugin, accepting prs
