### ISSUE TITLE
[consistent-type-imports] Issues with Angular's Dependency Injection

### ISSUE THREAD

**Issue by lachieh** [typescript-eslint/typescript-eslint#2713] opened 2020-10-27 01:20 UTC
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
```
{
  "rules": {
    "@typescript-eslint/consistent-type-imports": 'error'
  }
}
```
```ts
import { ApiService } from '@app/core';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html'
})
export class RuleDetailsComponent implements OnChanges {
  constructor(private api: ApiService) {}
}
```

**Expected Result**
I expected the imports not to be replaced with Type Only imports

**Actual Result**

Injected dependencies are replaced with type only imports

```ts
import type { ApiService } from '@app/core';
```
This causes errors in compilation like this:
```bash
    ERROR in src/app/rules/rule-details/rule-details.component.ts:20:61 - error NG2003: No suitable injection token for parameter 'dialog' of class 'RuleDetailsComponent'.
      Consider changing the type-only import to a regular import, or use the @Inject decorator to specify an injection token.
```

**Additional Info**
I have a feeling this is also related to #2559. I am unfamiliar with NestJS it seems like they handle dependency injection in a similar manner.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.5.0` |
| `@typescript-eslint/parser`        | `4.5.0` |
| `TypeScript`                       | `4.0.3` |
| `ESLint`                           | `7.12.0` |
| `node`                             | `14.4.0` |
| `@angular/core`                        | `10.2.0` |

**Comment by bradzacher** [comment] 2020-10-27 01:23
duplicate of #2559

**Closed by bradzacher** 2020-10-27 01:23 UTC
Labels: duplicate, package: eslint-plugin

**Comment by lachieh** [comment] 2020-10-27 01:27
Thanks, I'll follow progress there.
