### ISSUE TITLE
Bug: [prefer-nullish-coalescing] TypeError: Cannot read properties of undefined (reading 'some') when left-hand-side is unknown

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8276] opened 2024-01-20 04:02 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=CYUwxgNghgTiAEYD2A7AzgF3gNyhAriAFzz4oDWKSA7igNwBQuBCAPq-AN4C%2BjQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6KL2jjokcGAC%2BILUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
declare const value: unknown;
value || {};
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/prefer-nullish-coalescing": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

No crash. Perhaps a lint report.

### Actual Result

```plaintext
TypeError: Cannot read properties of undefined (reading 'some')
Occurred while linting /input.tsx:2
Rule: "@typescript-eslint/prefer-nullish-coalescing"
    at LogicalExpression[operator = "||"] (https://typescript-eslint.io/sandbox/index.js:143:58720)
    at https://typescript-eslint.io/sandbox/index.js:106:2597
    at https://typescript-eslint.io/sandbox/index.js:100:32964
    at Array.forEach (<anonymous>)
    at Object.emit (https://typescript-eslint.io/sandbox/index.js:100:32953)
    at _x.applySelector (https://typescript-eslint.io/sandbox/index.js:41:22861)
    at _x.applySelectors (https://typescript-eslint.io/sandbox/index.js:41:23157)
    at _x.enterNode (https://typescript-eslint.io/sandbox/index.js:41:23248)
    at yx.enterNode (https://typescript-eslint.io/sandbox/index.js:35:23816)
    at https://typescript-eslint.io/sandbox/index.js:106:3033 2:1 - 2:12
```

### Additional Info

Discovered in https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/pull/117.

**Comment by bradzacher** [comment] 2024-01-20 06:07
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/8261

**Closed** 2024-01-20 06:07 UTC
Labels: bug, package: eslint-plugin, accepting prs

**Comment by JoshuaKGoldberg** [comment] 2024-01-20 06:28
Ha, I did search... whoops.
