### ISSUE TITLE
not use non-public api: "eslint/lib/util/traverser"

### ISSUE THREAD

**Issue by aladdin-add** [typescript-eslint/typescript-eslint#603] opened 2019-06-10 06:04 UTC
```bash
Failed to load parser '@typescript-eslint/parser' declared in '--config » ../../../index.js » plugin:@typescript-eslint/recommended » ./configs/base.json': Cannot find module 'eslint/lib/util/traverser'
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.10.2` |
| `@typescript-eslint/parser`        | `1.10.2` |
| `ESLint`                           | `6.0.0-rc.0` |

**Comment by mysticatea** [comment] 2019-06-10 11:18
This is a duplicate of #563 :)

**Closed** 2019-06-10 13:24 UTC
Labels: package: eslint-plugin, triage

**Comment by JamesHenry** [comment] 2019-06-10 13:25
Thanks @aladdin-add, as @mysticatea indicates, please subscribe to the other issue for updates
