### ISSUE TITLE
Configs: Add a new config similar to `disable-type-checked`, but also disabling other rules not applicable to JS files

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#9888] opened 2024-08-27 09:48 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Hi,
I'm migrating my configs to v8 and as part of that wanted to switch to `disable-type-checked` for my `*.js` files, however I encountered an error with rules such as `explicit-module-boundary-types` - even though these rules aren't applicable (or even satisfiable) for plain JS files (I'm not using jsdoc), they are not type-checked, so not in the `disable-type-checked` config. I tried to do something like

```js
{
  files: ['**/*.js'],
  ...tseslint.configs.disableTypeChecked,
  rules: {
    "@typescript-eslint/explicit-module-boundary-types": "off",
  },
},
```

but that doesn't work due to the way object spreading works... I know I could probably do it with 2 separate configs, but that is quite a complicated way of doing a thing that presumably a lot of people want to do - disable all rules that don't make sense for plain JS files.

To that end, I'd like to propose a new config that is a superset of `disable-type-checked` and also disables other rules that are not applicable to plain js files. I don't think it makes sense to do this as part of `disable-type-checked` as this is a slightly different use-case. I don't have a list of rules ready - wanted to get a feel for the general idea first. I don't think there'd be actually that many.

### Impacted Configurations

No current configs.

**Comment by kirkwaiblinger** [comment] 2024-08-27 17:53
More or less duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/8955

**Comment by marekdedic** [comment] 2024-08-27 19:11
> More or less duplicate of #8955

Thanks, didn't find that one when searching for previous issues. The issue is closed, it seems like they proposed modifying the `disable-type-checked` config, which was argued isn't a good idea - I agree with that and propose adding a new config exactly for that reason.

**Comment by marekdedic** [comment] 2024-08-27 19:20
Thanks, didn't find it through search, but this is a dupe!

**Closed** 2024-08-27 19:35 UTC
Labels: package: eslint-plugin, triage, preset config change
