### ISSUE TITLE
Eslint throws an error in v2.8.0

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#1233] opened 2019-11-19 09:08 UTC
Running with `--debug`, output attached: 
[output.txt](https://github.com/typescript-eslint/typescript-eslint/files/3862880/output.txt)

Original failing PR: https://github.com/skaut/wordpress-version-checker/pull/93

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.8.0` |
| `@typescript-eslint/parser`        | `2.8.0` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.6.0` |
| `node`                             | `11.15.0` |
| `npm`                              | `6.13.1` |

**Comment by glen-84** [comment] 2019-11-19 09:19
Duplicate of #1226.

**Closed** 2019-11-19 17:07 UTC
Labels: package: eslint-plugin, triage
