### ISSUE TITLE
[@typescript-eslint/no-unused-vars] Spread syntax is not recognized

### ISSUE THREAD

**Issue by wangcch** [typescript-eslint/typescript-eslint#2489] opened 2020-09-05 08:04 UTC
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:react/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
  "plugins": ["react", "react-hooks", "@typescript-eslint", "prettier"],
  "env": {
    "browser": true,
    "jest": true
  },
  "rules": {
    "no-unused-vars": "off",
    "no-global-assign": "off",
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/ban-ts-comment": "warn",
    "@typescript-eslint/unbound-method": "warn",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-unused-vars": "error",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn"
  },
  "settings": {
    "react": {
      "pragma": "React",
      "version": "detect"
    }
  }
}
```

```TS
export type DemoResult<T extends any[]> = {
  callback: (...args: T) => void;
};
```

**Expected Result**

nothing

**Actual Result**

`'T' is defined but never used.eslint(@typescript-eslint/no-unused-vars)`

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.0.1` |
| `@typescript-eslint/parser`        | `4.0.1` |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `7.8.1` |
| `node`                             | `12.8.3` |

**Comment by bradzacher** [comment] 2020-09-05 08:42
Duplicate of #2449

**Closed by bradzacher** 2020-09-05 08:42 UTC
Labels: duplicate, package: eslint-plugin
