### ISSUE TITLE
Configs: Make consistent-type-imports 'error' for the recommended config

### ISSUE THREAD

**Issue by Sweater-Baron** [typescript-eslint/typescript-eslint#9036] opened 2024-05-01 14:37 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

It seems to me that using the `@typescript-eslint/consistent-type-imports` rule to enforce the use of `import type` where possible:

1. Is beneficial ([this blog post](https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how/) by maintainer @JoshuaKGoldberg  explains it well)
2. Is easy (`eslint --fix` just does the thing you want automatically)
3. And has no meaningful drawbacks.

Given all of that, is there any reason not to add it to the recommended configs?

### Impacted Configurations

recommended-type-checked
recommended-type-checked-only
strict-type-checked
strict-type-checked-only

**Comment by bradzacher** [comment] 2024-05-01 14:54
The reason we can't really add this to the recommended set is that it fixes to an opinionated style. It does top-level type specifier by default but not everyone likes that style.

That being said it could be in the strict set - which is intentionally opinionated.

**Comment by kirkwaiblinger** [comment] 2024-05-01 15:43
hmm, similar discussion to https://github.com/typescript-eslint/typescript-eslint/issues/8667

**Comment by kirkwaiblinger** [comment] 2024-05-01 17:04
@rubiesonthesky is that addressed by https://github.com/typescript-eslint/typescript-eslint/issues/8335 and https://typescript-eslint.io/blog/changes-to-consistent-type-imports-with-decorators or a separate problem?

**Comment by bradzacher** [comment] 2024-05-01 21:26
@rubiesonthesky see [playground](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=PTAEAEBcGcFoEsDmA7A9gJwKYCh4FsAHDSUAb1AElkArTAY0gEMAjAG01AF9QAzdVPKADk4RskQBXVo3TA6GTEIDc2EBBgIUC3IWJlQACQCiAJQDyRgMpde-QUIB0wPKjoBrWAAtM-TNGWqYFBwSGhYOkToJOQAMqiIiD42fALCDk6s8YnoDtA%2BAG7wdIpKoGoAPLCg6FIcdJ5iidCgkJ7wzZCoLQCeBBz4kZDY2OBUtAws7AAU5AT8hQAmmAtUAFzC-KiQQlwAlNiYAB6DoHTS0M0GPqiWBUUcpNigp6jI0JA1DBhTc-D5jJAOJkEj51nEQehdvpuGUwJUWm1mnQxEISMwOJBev1dFEADSgAAG4OyBNA7TJNHogIWoG84WeiUgV180CmUMez2erXaDmB2V58SmQgA4phIJB4OJadc-KB0g4hLsVJzqmKJOhkIZTBZLMquNhONggA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra0ipWpQC2xDtHyoMkRNGhTI4MAF8QaoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk6AHolsvOkXgIaoAi6cmHPLExlKeTAFd0AGnA068ZHl79BwgLLpOAE0EcKYcVNk0oJccmh4AchNSoAwgAs%2BAa1GHJ6OQF8QPoA&tokens=false) where it is working as expected and NOT reporting.

**Comment by bradzacher** [comment] 2024-05-01 21:35
Ultimately this is in fact a stylistic concern that does not change a thing in many codebases:

- if you transpile with TS then using type-qualifiers doesn't change anything.
- if you transpile with non-TS tools then this may or may not change anything (tools like SWC will do a good job of guessing and eliding imports only used in type locations).

Add to that the fact that you really _need_ a fixer for this rule - and no matter what you choose that fixer is enforcing a stylistic choice. Which is why the fixer is configurable.

Add to that the fact that out-of-the-box any codebase using legacy decorators + `emitDecoratorMetadata` will get incorrect reports without additional config.

I don't think this is a good candidate for `recommended`. So I'm a strong -1 for this.

**Comment by Josh-Cena** [comment] 2024-05-01 21:38
I also don't think consistent-* rules should be in recommended because they are after all stylistic. I do think this is fine to be in strict though.

**Comment by Sweater-Baron** [comment] 2024-05-02 14:14
That all makes sense, I agree it should only be in strict/stylistic after all

**Comment by JoshuaKGoldberg** [comment] 2024-05-09 21:16
I'm -1 on this being included in any preset config. There's no one single style that fits everyone.

A lot of web apps are in a framework like Vite where the import style doesn't generally matter functionally. For those, it really doesn't matter whether you use `type` or not. So asking for a slightly more verbose style that includes `type` really just makes the code less readable.

ACK that the rules are super useful in projects where the import style does matter - including typescript-eslint. But I don't see any functional benefit to enforcing this style for others.

**Comment by JoshuaKGoldberg** [comment] 2024-05-10 04:52
> Its the explicitness of declaring "this import will be elided" that adds clarity and predictability to the code.

If you don't care about which imports will be elided, then that clarity and predictability generally don't mean much. In an app where everything gets bundled into optimized chunks for production, what tangible benefits does this give?

**Comment by bradzacher** [comment] 2024-05-10 05:27
> In an app where everything gets bundled into optimized chunks for production, what tangible benefits does this give?

Well most FE build pipelines now avoid TS for transpilation because its performance is not good at scale. So instead they look for alternatives that are not type-aware.

These tools can often guess at what to elide - but they can also get it wrong easily. But with type-only imports it's no longer ambiguous what is elided and the tools can be guaranteed to work correctly.

It also increases the predictability of the build which makes it easier to understand why things are/aren't included in the resulting bundle - which is really helpful when trying to optimise bundle sizes and understand bundle regressions.

At Canva we used TS as our transpiler for many years and they also have used `consistent-type-imports` for as long as it has existed - both dates long before I joined the company.

**Comment by JoshuaKGoldberg** [comment] 2024-05-10 14:55
ACK that in projects where build predictability and knowing what gets elided are important, `consistent-type-imports: `"no-type-imports"` is useful. My pushback is that I think there are many projects where those _don't_ matter. For many projects, most files don't have side effects and they don't have build predicatability or runtime performance.

The _drawbacks_ of enabling `consistent-type-imports` to `"no-type-imports"` on those projects are:
* It results in overly verbose imports, taking up code space
* It adds conceptual overhead: developers need to do slightly more work to read the imports

If we had a `stylistic` split between the "starter" and "comprehensive" configs the way `recommended` and `strict` are split, I'd say this might make sense in the "comprehensive" version. But for a standard starter like `stylistic`, I think it doesn't pass the bar of _"would this go against the desired pattern for a nontrivial percentage of projects that are set up well"_.

**Comment by bradzacher** [comment] 2024-05-11 02:01
> My pushback is that I think there are many projects where those don't matter. For many projects, most files don't have side effects and they don't have build predicatability or runtime performance issues. So the net benefit of a stylistic rule like this is ... roughly zero.

That's what I'm disagreeing with though.
As a counter point - you could say the same thing about `no-unused-vars`. "well the minifier will tree-shake the unused imports and variables. Even if it doesn't/there isn't one - the imports won't have side-effects and most of the variables won't either so there won't be runtime perf issues"

Yet `no-unused-vars` is in the _recommended_ set.

You could say similar things about `prefer-const` "the predictability of using const provides zero value for most codebases and you could write all your code without it and have no bugs".

Yet it's in our `eslint-recommended` set (and thus our recommended set).

---

What I'm saying is that a best practice can exist even if some codebases don't see tangible value from the practice. Standardising the ecosystem can provide value for the majority even if the minority just goes along with the standard.

**Comment by Josh-Cena** [comment] 2024-05-11 04:31
What Brad said. More syntactic marker, even if unnecessary, is generally a good thing as it enforces invariants and decreases the entropy of your code. It's the same reason why we enforce `override`.

**Comment by JoshuaKGoldberg** [comment] 2024-05-13 00:59
Both of those rules and the keyword provide directly apparent benefits:
* `no-unused-vars`: at least more succinct and readable code, and sometimes even finding excess code paths or constructs that can be removed
* `prefer-as-const`: at least more succinct and readable code
* `override`: catches issues with inheritance shenanigans that sometimes aren't easy to catch otherwise

OTOH, the benefits of `consistent-type-imports` are much less apparent than the drawbacks.

> even if the minority just goes along with the standard

What we've seen is that if we include rules where the _perceived_ benefits are much less than the drawbacks -even with great docs- then people will protest and develop an aversion to using us. It's rare that we can get the community into a "just goes along with the standard" situation. Even things like floating/safe promises have taken a lot of ... community encouragement. Our easiest successes have been enforcing a standard agreed upon by many (or at least many of the influential folks) in the community.

---

Anyway, if I'm being outvoted here, then I'm ok with taking a step back and trying it out. We'll end up flighting this in community repos and seeing how it feels on them.

**Comment by bradzacher** [comment] 2024-05-13 02:52
> than the drawbacks

But what are the drawbacks? It has an autofixer!
We can query sourcegraph to figure out if inline or top-level is the most prevelant style so we can set the default for the autofixer and then it's invisible for people - the upgrade would just be "run with `--fix`".

The same can't be said for `no-unused-vars`. For example in the Canva codebase it wasn't turned on for a long time and so when they turned it on with the defaults it reported thousands of errors. Most of the errors were on unused parameters. But still they had to change the recommended config because the default style didn't suit and it was too large a task to fix by hand. 

> no-unused-vars: ... sometimes even finding excess code paths or constructs that can be removed

A good minifier will do that automatically too!

> prefer-as-const: at least more succinct and readable code

There's a non-trivial number of people that would disagree with you there :) but we recommend the rule all the same!

**Comment by bradzacher** [comment] 2024-05-13 07:15
> Isn’t the drawback that you will break code in repos that use legacy decorators?

Only if you have the combination of:
- legacy decorators
- experimental metadata
- not using type-aware linting
- imported values used only type locations AND runtime dependency on those values being named in decorator metadata

Then yes, you would get incorrect errors by default and would need to take a moment to set the parser options to indicate to our tooling to ignore files with decorators.

Though note that the false positives would only be in the files with decorators and that use imported values only in a type location that is covered by decorator metadata. I.e. It's realistically a small, small fraction of overall reports in the codebase.

**Comment by bradzacher** [comment] 2024-05-13 08:57
Not to be sassy but - `@angular/cli` has 2.7m dls. @typescript-eslint/eslint-plugin` has 26.3m.

So half of all angular repos would be ~5% of our users. Which isn't _super_ common in the grand scheme of things!

**Closed** 2024-08-22 14:54 UTC
Labels: package: eslint-plugin, triage, preset config change
