### ISSUE TITLE
Eslint 6 support

### ISSUE THREAD

**Issue by golopot** [typescript-eslint/typescript-eslint#639] opened 2019-06-22 19:13 UTC
**Reproduce**
```
$ yarn add eslint typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser
$ npx eslint .
Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc » plugin:@typescript-eslint/recommended » ./configs/base.json': Cannot find module 'eslint/lib/util/traverser'
Require stack:
- /home/jchn/test-teslint/node_modules/@typescript-eslint/parser/dist/parser.js
- /home/jchn/test-teslint/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /home/jchn/test-teslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /home/jchn/test-teslint/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/jchn/test-teslint/node_modules/eslint/lib/cli-engine/index.js
- /home/jchn/test-teslint/node_modules/eslint/lib/cli.js
- /home/jchn/test-teslint/node_modules/eslint/bin/eslint.js
```
Eslint 6 is released today. Both the parser and the plugin does not work in eslint 6. Failure in parser also fails the test of other eslint plugins.

**Comment by platinumazure** [comment] 2019-06-22 19:33
Duplicate of #563, fixed on master and just needs to be released.

**Comment by JamesHenry** [comment] 2019-06-22 19:37
As per the README, every commit to master is published on npm, there is never any need to wait to get the latest updates

**Closed** 2019-06-22 19:37 UTC
Labels: package: parser, triage

**Comment by JamesHenry** [comment] 2019-06-23 23:03
1.11.0 has now also been released which contains the necessary update
