### ISSUE TITLE
This module asks for eslint, that is already installed

### ISSUE THREAD

**Issue by crystalfp** [typescript-eslint/typescript-eslint#2089] opened 2020-05-24 18:18 UTC
Updating eslint in the project node_modules gives warning.

**Repro**
```
npm rm -D eslint
npm i -D eslint
```
```JSON
{
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.0.0",
    "@typescript-eslint/parser": "^3.0.0",
    "acorn": "^7.2.0",
    "eslint": "^7.1.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-array-plural": "^1.2.0",
    "eslint-plugin-const-case": "^1.2.2",
    "eslint-plugin-dollar-sign": "^1.0.2",
    "eslint-plugin-eslint-comments": "^3.1.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jest": "^23.13.1",
    "eslint-plugin-jest-formatting": "^1.2.0",
    "eslint-plugin-jquery": "^1.5.1",
    "eslint-plugin-no-useless-assign": "^1.0.3",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-optimize-regex": "^1.2.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-requirejs": "^4.0.0",
    "eslint-plugin-security": "^1.4.0",
    "eslint-plugin-unicorn": "^20.0.0",
    "typescript": "^3.9.3"
}
```

**Expected Result**
To have the plugin aligned with latest version of eslint

**Actual Result**
from two different projects. In both eslint is already installed.
```
npm WARN @typescript-eslint/experimental-utils@2.34.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@3.0.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.

```
**Additional Info**
none

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.0.0` |
| `@typescript-eslint/parser`        | `3.0.0` |
| `TypeScript`                       | `3.9.3` |
| `ESLint`                           | `7.1.0` |
| `node`                             | `14.2.0` |
| `npm`                              | `6.14.5` |

**Comment by bradzacher** [comment] 2020-05-24 21:32
Same as #2088 - I am unable to reproduce this.
I'm going to close this to consolidate discussion there.

**Closed by bradzacher** 2020-05-24 21:32 UTC
Labels: package: utils, triage
