### ISSUE TITLE
Bug: @typescript-eslint/no-unnecessary-type-parameters conflates undefined and null values

### ISSUE THREAD

**Issue by cowwoc** [typescript-eslint/typescript-eslint#9938] opened 2024-09-05 09:45 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=MYGwhgzhAEAqCmEAuxLwDy2vAHk%2BAdgCYwCux8AZgJYHxHQA%2B0BpIIT0AyvEugKIA%2BTvwDaAXQA00IQFgAUAG8F0aAAcATtQBuYfNA3wwRAPYEQAT2i6QpeAC44AbgUr1pAEYhqwaMDPIGqTASCYaABQ2do6wAJRuyvKqqkgAFtQQAHRR8NAAvNZgtvAuSdAAvq5lAPQAVLUqtTJReojQYH5mRNRI1GbQ-Wm5OZmNjdAAAmpgGmAAtp3EPX0E0AC00EOL3b2DJtgt%2BOMThkikGgQwAAZIQfBX0NSUm6nDRXaPMLQ21Axhj88tld-EtdgQHqdzpdoFdKEUIPdStAmiYhhoAO4ZeDSSEXa5wkAIq6NapuNSeby%2BH5EPQrABiYGoIHo4RBOxWjki7wccFi%2BWEHhMJmZYAIfMSyQMvCh0AAhGzlmZwmkMtlubEkRUqqpyV4fIVvDT8OF4mUJckVVlqbSzAymSztPzoObJU9oJF8nkCuQiFRaPRxW5JSl0lkzABVCg0OhEE2a4NSs4XaAEhHx5KVMqu54er0FVjsQNZ4OWzJmABybBAcaDwdxq1TJVrqkzCfrmzu6fKGtr7dudk1mbJFP1Eaj-tj4ugteq1UeBHwC5WRUs2DmaiQFjcrfcet8FarJud0%2BLs-ni7BK6s8HXm%2B3CiH8jo6LgiBQaHCPr9MdiasNrTjIA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2jNANgJZLyYBO0AxgPYC2dyK0KkANFAA4ECuA5iUwABeAE9O0NFXJFO8ALSTipAPSVaDJi3liJ8qgAtqAaxbsuvAUmG7J02QqUl4KtPBlUFt-UaqnWHJDc-IIi4nYycoqEzq5ixG5EVDrhPiZmALps4FwAhuRo0ORYUGESUpGOMaqc%2BYXF2RBBliQY2HhlEQ7RyvCQWTmQ5DQ0fdjuPNCNUOQ8BJIlwAC%2BIEtAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
The playground code passes under Typescript 5.4.5 but fails under 5.5.4 with the error: "Unnecessary conditional, the types have no overlap. 28:11 - 28:21"

It's not clear why comparing the value to `undefined` prevents a subsequent comparison against `null` as the two values are not equal.
```

### ESLint Config

```javascript
See the playground code
```

### Expected Result

The same result when running under both Typescript versions

### Actual Result

Pass under Typescript 5.4.5 but fail under Typescript 5.5.4

**Comment by cowwoc** [comment] 2024-09-05 10:38
This issue is not reproducible in Typescript 5.6.1-rc or the 5.7.0 nightly builds. It's not clear whether this is a Typescript bug or some weird interaction between Typescript and the rule...

**Comment by cowwoc** [comment] 2024-09-05 10:44
This seems to work fine in newer versions (5.6.1-rc and nightly builds of 5.7). It's not clear whether this is a bug in Typescript or a bug in the rule that is triggered by some change to the language.

**Comment by bradzacher** [comment] 2024-09-05 10:48
In TS 5.4.5 after the `=== undefined` TS refines `T` to `T & ({} | null)`
In TS 5.5 instead it is refined to `T & {}`

This is why the rule reports in 5.5 - because by definition `T & {}` can never be `null`.

As for why TS emits another type in 5.5 - I don't know - we would need to file an issue with TS to figure out if this is a regression or not.

**Comment by cowwoc** [comment] 2024-09-05 14:48
@bradzacher Are you able to file a ticket with them and link back here?

**Comment by bradzacher** [comment] 2024-09-05 14:48
Given the behaviour doesn't reproduce in the 5.6rc - I'm going to close this as a TS bug.

**Closed** 2024-09-05 14:48 UTC
Labels: bug, package: eslint-plugin, triage, external

**Comment by cowwoc** [comment] 2024-09-05 15:03
@bradzacher I would feel more comfortable letting this go if I could track down a relevant commit seeing this getting fixed in v5.6... Or, if we could figure out what lines of code they changed in v5.5 then we could monitor it for changes going into v5.6 to make sure that it was really fixed.

**Comment by bradzacher** [comment] 2024-09-05 22:18
There is a command to bisect TS versions.
I forget what it is as I've only used it once.

@jakebailey have you got a link to the bisect tooling off the top of your head so we can figure out the fix commit?

**Comment by jakebailey** [comment] 2024-09-05 23:22
The tool is: https://www.npmjs.com/package/every-ts

You'd `every-ts dir` to get the path to link (`npm install typescript@link:$(every-ts dir)` or something), then use `every-ts bisect start`, `every-ts bisect bad`, `every-ts bisect good` etc like [git bisect](https://git-scm.com/docs/git-bisect).

**Comment by Josh-Cena** [comment] 2024-09-05 23:24
`every-ts`
