### ISSUE TITLE
Add the `start` and `end` properties on nodes

### ISSUE THREAD

**Issue by ehmicky** [typescript-eslint/typescript-eslint#695] opened 2019-07-11 11:31 UTC
**What code were you trying to parse?**

Any code.

**What did you expect to happen?**

The returned nodes should include the `start` and `end` properties. Those properties are different from `loc.start` and `loc.end` since they are not line|column-wise. They are not standardized by ESTree, but are output by Esprima, Acorn, Espree and @babel/parser.

**What actually happened?**

The `start` and `end` properties were not defined.

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `1.11.0` |
| `TypeScript`                           | `3.5.3` |
| `node`                                 | `12.6.0` |
| `npm`                                  | `6.10.0` |

**Comment by JamesHenry** [comment] 2019-07-11 11:36
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/405, ESLint itself is adding checks to the RuleTester to prevent the use of these non-standard properties

**Closed by JamesHenry** 2019-07-11 11:36 UTC
Labels: package: typescript-estree, triage

**Comment by ehmicky** [comment] 2019-07-11 11:40
Makes sense, thanks for linking to that issue.
