### ISSUE TITLE
eslint --fix stalled forever.

### ISSUE THREAD

**Issue by jerome-benoit** [typescript-eslint/typescript-eslint#809] opened 2019-08-06 12:14 UTC
**What code were you trying to parse?**

```
import config from '../../config';
import faker from 'faker';
import moment from 'moment';
import { ObjectID } from 'mongodb';
import CentralServerService from '../client/CentralServerService';
import CompanyStorage from '../../storage/mongodb/CompanyStorage';
import Constants from '../../utils/Constants';
import CONTEXTS from './ContextConstants';
import Factory from '../../factories/Factory';
import global from '../../types/GlobalType';
import MongoDBStorage from '../../storage/mongodb/MongoDBStorage';
import Site from '../../types/Site';
import SiteAreaContext from './SiteAreaContext';
import SiteAreaStorage from '../../storage/mongodb/SiteAreaStorage';
import SiteContext from './SiteContext';
import SiteStorage from '../../storage/mongodb/SiteStorage';
import TenantContext from './TenantContext';
import TenantFactory from '../../factories/TenantFactory';
import TenantStorage from '../../../src/storage/mongodb/TenantStorage';
import User from '../../types/User';
import UserFactory from '../../factories/UserFactory';
import UserStorage from '../../storage/mongodb/UserStorage';
import Utils from '../../utils/Utils';

const NBR_USERS = 10; // Number of total users : they are all connected to the sites
const NBR_COMPANIES = 5; // Number of companies
const NBR_SITES = 5; // Number of sites PER company
const NBR_SITEAREAS = 5; // Number of site areas per site
const NBR_CHARGINGSTATIONS = 5; // Number of charging stations per site area
const BIG_CONTEXT = [{
  tenantName: 'Big',
  id: 'b1b1b1b1b1b1b1b1b1b1b1b1',
  subdomain: 'big',
  componentSettings: {
    pricing: {
      type: 'simple',
      content: {
        simple: {
          price: 1,
          currency: 'EUR'
        }
      },
    },
    ocpi: {
      type: 'gireve',
      content: {
        countryCode: 'FR',
        partyId: 'UT',
        businessDetails: {
          name: 'Test OCPI',
          website: 'http://www.uttest.net'
        }
      }
    },
    organization: {
    },
  },
}];

export default class ContextBuilder {

  private superAdminCentralServerService: CentralServerService;
  private tenantsContexts: TenantContext[];
  private initialized: boolean;

  constructor() {
    // Create a super admin interface
    this.superAdminCentralServerService = new CentralServerService(null, { email: config.get('superadmin.username'), password: config.get('superadmin.password') });
    this.tenantsContexts = [];
    // Create MongoDB
    global.database = new MongoDBStorage(config.get('storage'));
    this.initialized = false;
  }

  async _init() {
    if (!this.initialized) {
      // Connect to the the DB
      await global.database.start();
    }
    this.initialized = true;
  }

  async destroy() {
    if (this.tenantsContexts && this.tenantsContexts.length > 0) {
      return setTimeout(() => { // Delay deletion as unit tests are faster than processing
        this.tenantsContexts.forEach(async (tenantContext) => {
          // pragma console.log('DESTROY context ' + tenantContext.getTenant().id + ' ' + tenantContext.getTenant().subdomain);
          await this.superAdminCentralServerService.deleteEntity(this.superAdminCentralServerService.tenantApi, tenantContext.getTenant());
        });
      }, 10000);
    }
    // Delete all tenants
    for (const tenantContextDef of BIG_CONTEXT) {
      const tenantEntity = await TenantStorage.getTenantByName(tenantContextDef.tenantName);
      if (tenantEntity) {
        await this.superAdminCentralServerService.tenantApi.delete(tenantEntity.id);
      }
    }

  }

  /**
   * It will first destroy all Unit Test tenants
   * Then it will create new ones with the minimum entities
   * All definition is coming from ContextConstants.js
   *
   * @memberof ContextBuilder
   */
  async prepareContexts() {
    await this._init();
    await this.destroy();
    // Prepare list of tenants to create
    const tenantContexts = BIG_CONTEXT;
    // Build each tenant context
    for (const tenantContextDef of tenantContexts) {
      await this._buildTenantContext(tenantContextDef);
    }
  }

  /**
   * Private method
   * It will build the necessary tenants
   * Precondition: The tenant MUST not exist already in the DB
   *
   * @param {*} tenantContextDef
   * @returns
   * @memberof ContextBuilder
   */
  async _buildTenantContext(tenantContextDef: any) {
    // Build component list
    const components = {};
    if (tenantContextDef.componentSettings) {
      for (const component in Constants.COMPONENTS) {
        const componentName = Constants.COMPONENTS[component];
        if (tenantContextDef.componentSettings.hasOwnProperty(componentName)) {
          components[componentName] = {
            active: true
          };
          if (tenantContextDef.componentSettings[componentName].hasOwnProperty('type')) {
            components[componentName]['type'] = tenantContextDef.componentSettings[componentName].type;
          }
        }
      }
    }
    // Check if tenant exist
    const existingTenant = await TenantStorage.getTenant(tenantContextDef.id);
    if (existingTenant) {
      console.log(`Tenant ${tenantContextDef.id} already exist with name ${existingTenant.name}. Please run a destroy context`);
      throw new Error('Tenant id exist already');
    }
    let buildTenant: any = {};
    // Create Tenant
    const dummyTenant = TenantFactory.buildTenantCreate();
    dummyTenant.name = tenantContextDef.tenantName;
    dummyTenant.subdomain = tenantContextDef.subdomain;
    dummyTenant.id = tenantContextDef.id;
    buildTenant = await this.superAdminCentralServerService.createEntity(
      this.superAdminCentralServerService.tenantApi, dummyTenant);
    // Update components
    buildTenant.components = components;
    await this.superAdminCentralServerService.updateEntity(
      this.superAdminCentralServerService.tenantApi, buildTenant);
    console.log('CREATE tenant context ' + buildTenant.id +
      ' ' + buildTenant.subdomain);
    // Retrieve default admin
    const existingUserList = (await UserStorage.getUsers(buildTenant.id, {}, Constants.DB_PARAMS_MAX_LIMIT)).result;
    let defaultAdminUser: User = null;
    // Search existing admin
    if (existingUserList && Array.isArray(existingUserList)) {
      defaultAdminUser = existingUserList.find((user) => {
        return user.id === CONTEXTS.TENANT_USER_LIST[0].id || user.email === config.get('admin.username') ||
          user.role === 'A';
      });
    }
    if ((defaultAdminUser.id !== CONTEXTS.TENANT_USER_LIST[0].id) || (defaultAdminUser.status !== 'A')) {
      // It is a different default user so first delete it
      await UserStorage.deleteUser(buildTenant.id, defaultAdminUser.id);
      // Activate user
      defaultAdminUser.status = CONTEXTS.TENANT_USER_LIST[0].status;
      // Generate the password hash
      const newPasswordHashed = await Utils.hashPasswordBcrypt(config.get('admin.password'));
      // Update the email
      defaultAdminUser.email = config.get('admin.username');
      // Add a Tag ID
      defaultAdminUser.tagIDs = CONTEXTS.TENANT_USER_LIST[0].tagIDs ? CONTEXTS.TENANT_USER_LIST[0].tagIDs : [faker.random.alphaNumeric(8).toUpperCase()];
      // Fix id
      defaultAdminUser.id = CONTEXTS.TENANT_USER_LIST[0].id;
      const userId = await UserStorage.saveUser(buildTenant.id, defaultAdminUser);
      // Save password
      await UserStorage.saveUserPassword(buildTenant.id, userId, newPasswordHashed);
    }

    // Create Central Server Service
    const localCentralServiceService: CentralServerService = new CentralServerService(buildTenant.subdomain);

    // Create Tenant component settings
    if (tenantContextDef.componentSettings) {
      console.log(`settings in tenant ${buildTenant.name} as ${JSON.stringify(tenantContextDef.componentSettings)}`);
      const allSettings: any = await localCentralServiceService.settingApi.readAll({}, Constants.DB_PARAMS_MAX_LIMIT);
      for (const setting in tenantContextDef.componentSettings) {
        let foundSetting: any = null;
        if (allSettings && allSettings.data && allSettings.data.result && allSettings.data.result.length > 0) {
          foundSetting = allSettings.data.result.find((existingSetting) => existingSetting.identifier === setting);
        }
        if (!foundSetting) {
          // Create new settings
          const settingInput = {
            identifier: setting,
            content: tenantContextDef.componentSettings[setting].content
          };
          console.log(`CREATE settings for ${setting} in tenant ${buildTenant.name}`);
          await localCentralServiceService.createEntity(localCentralServiceService.settingApi,
            settingInput);
        } else {
          console.log(`UPDATE settings for ${setting} in tenant ${buildTenant.name}`);
          foundSetting.content = tenantContextDef.componentSettings[setting].content;
          await localCentralServiceService.updateEntity(localCentralServiceService.settingApi,
            foundSetting);
        }
      }
    }
    let userListToAssign: User[] = null;
    let userList: User[] = null;
    // Read admin user
    const adminUser: User = (await localCentralServiceService.getEntityById(
      localCentralServiceService.userApi, defaultAdminUser, false)).data;
    userListToAssign = [adminUser]; // Default admin is always assigned to site
    userList = [adminUser]; // Default admin is always assigned to site
    // Prepare users
    // Skip first entry as it is the default admin already consider above
    for (let index = 1; index <= NBR_USERS; index++) {
      const userDef = {
        id: '',
        role: CONTEXTS.USER_CONTEXTS.BASIC_USER.role,
        status: CONTEXTS.USER_CONTEXTS.BASIC_USER.status,
        assignedToSite: CONTEXTS.USER_CONTEXTS.BASIC_USER.assignedToSite,
        emailPrefix: 'basic-',
        tagIDs: []
      };
      userDef.id = new ObjectID().toHexString();
      const createUser: User = UserFactory.build();
      userDef.tagIDs.push(`A1234${index}`);
      // Update the password
      const newPasswordHashed = await Utils.hashPasswordBcrypt(config.get('admin.password'));
      createUser.role = userDef.role;
      createUser.status = userDef.status;
      createUser.id = userDef.id;
      if (userDef.tagIDs) {
        createUser.tagIDs = userDef.tagIDs;
      }
      const user: User = createUser;
      await UserStorage.saveUser(buildTenant.id, user, false);
      await UserStorage.saveUserPassword(buildTenant.id, user.id, newPasswordHashed);
      if (userDef.assignedToSite) {
        userListToAssign.push(user);
      }
      // Set back password to clear value for login/logout
      const userModel = user;
      (userModel as any).passwordClear = config.get('admin.password'); // FIXME: What is this?
      userList.push(userModel);
    }
    // Persist tenant context
    const newTenantContext = new TenantContext(tenantContextDef.tenantName, buildTenant, localCentralServiceService, null);
    this.tenantsContexts.push(newTenantContext);
    newTenantContext.addUsers(userList);
    // Check if Organization is active
    if (buildTenant.components && buildTenant.components.hasOwnProperty(Constants.COMPONENTS.ORGANIZATION) &&
      buildTenant.components[Constants.COMPONENTS.ORGANIZATION].active) {
      // Create the company
      for (let counterComp = 1; counterComp <= NBR_COMPANIES; counterComp++) {
        const companyDef = {
          id: new ObjectID().toHexString()
        };
        const dummyCompany: any = Factory.company.build();
        dummyCompany.id = companyDef.id;
        dummyCompany.createdBy = { id: adminUser.id };
        dummyCompany.createdOn = moment().toISOString();
        await CompanyStorage.saveCompany(buildTenant.id, dummyCompany);
        newTenantContext.getContext().companies.push(dummyCompany);
        console.log(`Create company : ${dummyCompany.id}`);
        // Build sites/sitearea according to tenant definition
        for (let counterSite = 1; counterSite <= NBR_SITES; counterSite++) {
          const siteContextDef = {
            id: new ObjectID().toHexString(),
            name: CONTEXTS.SITE_CONTEXTS.SITE_BASIC,
            allowAllUsersToStopTransactions: false,
            autoUserSiteAssignment: false,
            companyID: companyDef.id
          };
          let site: Site = null;
          // Create site
          const siteTemplate = Factory.site.build({
            companyID: siteContextDef.companyID,
            userIDs: userListToAssign.map((user) => user.id)
          });
          siteTemplate.name = siteContextDef.name;
          siteTemplate.allowAllUsersToStopTransactions = siteContextDef.allowAllUsersToStopTransactions;
          siteTemplate.autoUserSiteAssignment = siteContextDef.autoUserSiteAssignment;
          siteTemplate.id = siteContextDef.id;
          site = siteTemplate;
          site.id = await SiteStorage.saveSite(buildTenant.id, siteTemplate, true);
          console.log(`* Create site : ${siteTemplate.id}`);
          await SiteStorage.addUsersToSite(buildTenant.id, site.id, userListToAssign.map((user) => user.id));
          const siteContext = new SiteContext(site, newTenantContext);
          newTenantContext.addSiteContext(siteContext);
          // Create site areas of current site
          for (let counterSiteA = 1; counterSiteA <= NBR_SITEAREAS; counterSiteA++) {
            const siteAreaDef = {
              id: new ObjectID().toHexString(),
              name: `${CONTEXTS.SITE_CONTEXTS.SITE_BASIC}-${CONTEXTS.SITE_AREA_CONTEXTS.WITHOUT_ACL}`,
              accessControl: false,
              siteName: siteTemplate.name
            };
            const siteAreaTemplate = Factory.siteArea.build();
            siteAreaTemplate.id = siteAreaDef.id;
            // pragma siteAreaTemplate.name = siteAreaDef.name;
            siteAreaTemplate.accessControl = siteAreaDef.accessControl;
            siteAreaTemplate.siteID = site.id;
            const sireAreaID = await SiteAreaStorage.saveSiteArea(buildTenant.id, siteAreaTemplate);
            console.log(`** Create sitearea : ${siteAreaTemplate.id}`);
            const siteAreaModel = await SiteAreaStorage.getSiteArea(buildTenant.id, sireAreaID);
            const siteAreaContext = new SiteAreaContext(siteAreaModel, newTenantContext);
            siteContext.addSiteArea(siteAreaContext);
            // Create Charging Station for site area
            for (let counterCS = 1; counterCS <= NBR_CHARGINGSTATIONS; counterCS++) {
              const chargingStationDef = {
                baseName: new ObjectID().toHexString(),
                ocppVersion: '1.6',
                siteAreaNames: [siteAreaTemplate.id]
              };
              const chargingStationTemplate = Factory.chargingStation.build();
              chargingStationTemplate.id = chargingStationDef.baseName;
              console.log(`*** Create charging station : ${chargingStationTemplate.id}`);
              await newTenantContext.createChargingStation(chargingStationDef.ocppVersion, chargingStationTemplate, null, siteAreaModel);
            }
          }
        }
      }
    }
    return newTenantContext;
  }
}
```

**What did you expect to happen?**

eslint --fix should successfully finish. 

**What actually happened?**

eslint --fix is stalled forever.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.13.0`|
| `TypeScript`                | `3.5.3` |
| `ESLint`                    | `6.1.0` |
| `node`                      | `10.16.1` |
| `npm`                       | `6.9.0` |

**Comment by jerome-benoit** [comment] 2019-08-06 12:17
.eslint.json:

```
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  "rules": {
    "indent": "off",
    "@typescript-eslint/indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "@typescript-eslint/array-type": "off",
    "semi": "off",
    "@typescript-eslint/semi": [
      "error",
      "always"
    ],
    "space-before-blocks": [
      "error",
      "always"
    ],
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/member-ordering": "error",
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/promise-function-async": "error",
    "curly": "error",
    "brace-style": "error",
    "eqeqeq": [
      "error",
      "always"
    ],
    "no-else-return": "error",
    "no-eq-null": "error",
    "no-undefined": "error",
    "no-extra-bind": "error",
    "no-lone-blocks": "error",
    "no-multi-spaces": "error",
    "no-empty": "error",
    "require-await": "error",
    "no-return-assign": [
      "error",
      "always"
    ],
    "no-useless-catch": "error",
    "no-useless-return": "error",
    "no-shadow": "error",
    "no-multiple-empty-lines": [
      "error",
      {
        "max": 2,
        "maxEOF": 1
      }
    ],
    "block-spacing": "error",
    "capitalized-comments": [
      "error",
      "always",
      {
        "ignoreConsecutiveComments": true,
        "ignorePattern": "pragma|ignored"
      }
    ],
    "eol-last": [
      "error",
      "always"
    ],
    "consistent-this": [
      "error",
      "self"
    ],
    "func-call-spacing": [
      "error",
      "never"
    ],
    "keyword-spacing": [
      "error"
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "max-len": [
      "warn",
      {
        "code": 140
      }
    ],
    "no-lonely-if": "error",
    "no-trailing-spaces": "error",
    "no-whitespace-before-property": "error",
    "space-before-function-paren": [
      "error",
      {
        "anonymous": "never",
        "named": "never",
        "asyncArrow": "always"
      }
    ],
    "space-in-parens": [
      "error",
      "never"
    ],
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": [
      "error",
      "always"
    ],
    "switch-colon-spacing": "error",
    "arrow-body-style": [
      "error",
      "as-needed"
    ],
    "arrow-parens": [
      "error",
      "always"
    ],
    "arrow-spacing": "error",
    "no-duplicate-imports": "error",
    "no-var": "error",
    "prefer-const": "error",
    "sort-imports": "warn",
    "object-curly-spacing": [
      "error",
      "always"
    ],
    "lines-between-class-members": [
      "error",
      "always",
      {
        "exceptAfterSingleLine": true
      }
    ],
    "quotes": [
      "error",
      "single"
    ]
  }
}
```

**Comment by bradzacher** [comment] 2019-08-06 15:49
Hey there @jerome-benoit 
This is not a bug with the parser, the parser doesn't handle fixes.

There's a lot of rules in your config which have fixers, and there is a lot of code in your example.

Could you please narrow the repro down so we can figure out what the problem is?
Ideally you should be able to narrow the example code down to less than 50 lines instead of 300, and the config should be able to be less than 10.

Please run eslint with the `--debug` as well as your other flags, and that will help you narrow down exactly what's happening.
Please post it here as well so we can have a look.

**Comment by jerome-benoit** [comment] 2019-08-06 21:18
Le 06/08/2019 à 17:49, Brad Zacher a écrit :

> Please run eslint with the |--debug| as well as your other flags, and
> that will help you narrow down exactly what's happening.
>
Already done. It just hangs on phase 2 without giving more informations
on the rule or the line.

> Please post it here as well so we can have a look.
>
The eslint options are --fix --ext .js,.ts against the configuration
file given.

But I can't reproduce the issue on Linux or Mac OSX. So it seems related
to the setup of my work laptop under Windows, probably related to the
antivirus.

So you can probably close it.

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by bradzacher** [comment] 2019-08-06 23:21
Alright, I'll close this - feel free to comment back if you can figure out the minimal repro case!

**Closed by bradzacher** 2019-08-06 23:21 UTC
Labels: awaiting response, package: eslint-plugin
