### ISSUE TITLE
[member-ordering] Support abstract members

### ISSUE THREAD

**Issue by mattacosta** [typescript-eslint/typescript-eslint#933] opened 2019-09-01 21:01 UTC
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/member-ordering": ["warn", {
            "default": [
                "public-static-field",
                "protected-static-field",
                "private-static-field",
                "public-instance-field",
                "protected-instance-field",
                "private-instance-field",
                "constructor",
                "public-static-method",
                "protected-static-method",
                "private-static-method",
                "public-instance-method",
                "protected-instance-method",
                "private-instance-method"
            ]
        }],
  }
}
```

```TS
abstract class Foo {

  public abstract aaa: number;

  public bbb: boolean = true;

}
```

**Expected Result**
No warning. The "abstract" keyword should have no effect.

**Actual Result**
`Member bbb should be declared before all private instance method definitions.`

**Additional Info**
The syntax nodes for abstract members are not handled, which causes them to be placed at the end of the line.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.0.0` |
| `@typescript-eslint/parser`        | `2.0.0` |
| `TypeScript`                       | `3.5.2` |
| `ESLint`                           | `6.3.0` |
| `node`                             | `10.15.3` |

**Comment by bradzacher** [comment] 2019-09-01 21:26
duplicate of #395

**Closed** 2019-09-01 21:29 UTC
Labels: package: eslint-plugin, triage
