### ISSUE TITLE
Rule proposal: Unreachable swtich default case

### ISSUE THREAD

**Issue by kkimdev** [typescript-eslint/typescript-eslint#7627] opened 2023-09-11 03:26 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

When all the enum cases are listed in a switch statement, `default:` block is unreachable.  To my knowledge, there is no existing rule that detects such cases.

Note: This could be a special case of a more general unreachable code detection rule.

### Fail Cases

```typescript
enum Animal {
    cow
}

const main = (animal: Animal) => {
    switch (animal) {
        case Animal.cow:
            return 3;
        default:
            return 4;
    }
};
```

### Pass Cases

```typescript
enum Animal {
    cow,
    horse
}

const main = (animal: Animal) => {
    switch (animal) {
        case Animal.cow:
            return 3;
        default:
            return 4;
    }
};
```

**Comment by Josh-Cena** [comment] 2023-09-11 03:28
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/3616

**Closed by Josh-Cena** 2023-09-11 03:28 UTC
Labels: package: eslint-plugin, triage, enhancement: new plugin rule

**Comment by kkimdev** [comment] 2023-09-11 04:50
Thanks!

PR work in progress: https://github.com/typescript-eslint/typescript-eslint/pull/7539
