### ISSUE TITLE
Bug: ban-types renames locally shadowed builtin uppercase type

### ISSUE THREAD

**Issue by Jokero** [typescript-eslint/typescript-eslint#6262] opened 2022-12-21 19:20 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=C4TwDgpgBAysBOBLAdgcwCoHsCqzGeQB44k0oIAPYCZAEwGcp6EVUA+KAXlhbMurqMABgBIA3igBmEeFAAyEYNXgBfcVJlQAShGYqhAKChQA-PMXKoAHx6kMOPAUI7mbI1ABcUZBABuMgG4gA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWAI1gMq+QomGRU8APZoeAXxCGgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
type StringToUnion<String extends string> = String extends `${infer Letter}${infer Rest}`
  ? Letter | StringToUnion<Rest>
  : never;
```

### ESLint Config

```javascript
module.exports = {
  "parser": "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/ban-types": "error"
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

The rule does not return an error and does not change `String` in ``String extends `${infer Letter}${infer Rest}`` to `string` when `--fix` is used.

### Actual Result

eslint returns:
```
error  Don't use `String` as a type. Use string instead  @typescript-eslint/ban-types
```

**Comment by Josh-Cena** [comment] 2022-12-21 19:26
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/5505. Please see the rationale in that issue.

**Comment by Josh-Cena** [comment] 2022-12-21 19:28
BTW, type parameters in these utility types are typically single-letter like `S`. At most `Str`. I've rarely seen utilities spelling out entire variable names, because they are not meaningful anyway.

**Comment by Jokero** [comment] 2022-12-21 19:49
@Josh-Cena Such a quick reply 😄 

Thanks for the link to another issue, I didn't find it.

I personally don't like single letter (or truncated) variable and parameter names, because they might confuse. The entire name is always clear.

I've created the issue, because this rule resulted in a bug in my application. After replacing `String` to `string` (`--fix` option), my custom type stopped working as expected. I extend `"plugin:@typescript-eslint/recommended"` rules.

In this case there are few options:
1) rename `String` to `S` or something else (although this won't protect from similar issue in the future, as other people might face it)
2) disable the rule and lose its benefits (like ban of `const str: String = 'foo';`)

Another theoretical option is to distinguish such case as mine and make it not fixable (to not introduce a bug).

**Comment by Josh-Cena** [comment] 2022-12-21 19:52
I do believe the autofixer should never introduce bugs—we should change it to a suggestion instead. Curious to hear what others think.

**Comment by Josh-Cena** [comment] 2022-12-21 19:55
Also, just like `i` as a loop variable is a convention, in utility types, `S` for string,  `O` for object, `P`/`K` for property/key, `F`/`R` for first/rest (as in `[infer F, ...infer R]`, `` `${infer F}${infer R}` ``) are all widely-accepted conventions, so using `S` is definitely idiomatic in this context.

**Comment by Jokero** [comment] 2022-12-21 20:02
I cannot agree it's a convention. Mostly it's ok for pseudocode or in indie projects. The size of variable does not matter these times. Anyway, don't want to argue on this topic.

I have counter examples for utility types https://github.com/sindresorhus/type-fest/blob/v3.4.0/source/replace.d.ts#L58

**Comment by Josh-Cena** [comment] 2022-12-21 20:08
I would suggest looking at TS's own types:

```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
type Extract<T, U> = T extends U ? T : never;
type Capitalize<S extends string> = intrinsic;
```

Sindre often "does his own thing", but other libraries like `ts-toolbelt` and `utility-types` all adopt the short identifiers convention. But anyway, that's definitely off-topic.

**Comment by bradzacher** [comment] 2022-12-21 20:11
Shadowing global library type names is a BAD idea. It is a code smell that complicates your code. Same reason you shouldn't declare a local function called `String` - it's very easy to do the wrong thing and get confused.

The rule is intentionally very simple - all it does is checks for a given type name, regardless of context.

The default config relies upon the assumption that you're not locally shadowing global types.

I personally don't think it's worth us adding logic to try to determine if a fix is safe because the cases like thus are so, so, so very rare.
How rare? Well the rule has been implemented in this **_exact_** form for over 4 years, and I believe this is the first issue we've had about an incorrect fix like this.

In theory there definitely is the possibility that an incorrect fix would be made. In practice however that possibility is minuscule for most codebases (1 in 20 million based on our user base).

**Comment by Jokero** [comment] 2022-12-21 20:26
I agree that shadowing (both intentional and unintentional as in my case) is a bad idea. Sad I was unlucky enough to hit the issue 😄 

If it's really so rare case, let's close the issue. If I ever have time for it, I will prepare the fix

**Comment by Josh-Cena** [comment] 2022-12-21 20:28
IMO, scope-unaware variable auto-renaming is virtually never safe, and it's unfortunate if we unnoticedly introduce bugs in users' code. Remember that autofixes are often run as CI jobs and/or precommit hooks and sometimes slip through reviews.

**Comment by Jokero** [comment] 2022-12-21 20:30
This is what happened with me as I run `eslint --fix` in precommit hook

**Comment by bradzacher** [comment] 2022-12-21 20:55
@Josh-Cena to be clear - I didn't say it was safe, I said that the chance of it actually being unsafe is rare for the default config.

It's rare because the default config only operates on global library types, and rare that people shadow those names - it's really just one of those unwritten rules that everyone agrees that you just don't do.
It's like calling a variable `undefined` - yeah technically it's valid and correct JS to do so, but everyone understands its a bad idea.

Also in the vast majority of cases users use an IDE plugin to get lint errors live, which means that they get warned of cases like this before it becomes a CLI silently autofixed case.

Again not arguing it is a safe fixer (it's provably not as shown). I'm just saying that in practice the combination of factors required for it to be unsafe make it a really, really rare case (as evidenced by the user report rate over 4 years).

---

For context talking hard numbers.

This rule pre-dates this project. It was ported from TSLint to `eslint-plugin-typescript` 4y ago. The fixer was added at this time. A few days after it was added it became part of the very first recommended set with pretty much the exact current default config.

Which is why I say it's rare in practice - 4y of being a recommended rule with this config and 1 report puts the incident rate at something like 1 in a billion.

Still, just one incident means it's an unsafe fixer.

The point I'm making is that at such a low practical incident rate I personally don't think that it is worth the effort to build and maintain logic to check the scope to determine safety.

**Comment by Jokero** [comment] 2022-12-21 20:56
I've found this nice rule allowing to prevent such issues:
```
"@typescript-eslint/naming-convention": ["error", {
    "selector": "typeParameter",
    "format": null,
    "custom": {
        "regex": "^(String|Boolean|Number|Object)$", // can be extended with other upper-case types
        "match": false
    }
}],
```
Maybe it's a good candidate for the recommended list of rules.

**Comment by Jokero** [comment] 2022-12-21 21:08
To be honest, when I added `String`, I could not imagine that this could happen, because I would never have thought of using the `String` type anywhere to declare a variable/parameter type. Only `string` is in my head.

> Also in the vast majority of cases users use an IDE plugin to get lint errors live, which means that they get warned of cases like this before it becomes a CLI silently autofixed case.

Thanks for the tip. Unfortunately, eslint is disabled by default in Intellij IDEA and WebStorm.

**Comment by Josh-Cena** [comment] 2022-12-21 21:16
> I personally don't think that it is worth the effort to build and maintain logic to check the scope to determine safety.

To be clear, I was talking about changing it to suggestions—TS-ESLint seems to generally have the issue about being too aggressive with auto-fixes. Or do we still prefer convenience to avoiding niche bugs?

**Comment by bradzacher** [comment] 2022-12-21 22:21
@Josh-Cena I think the chance of breakage is definitely a factor when considering making such a change.

Should we degrade everyone's experience and make it a suggestion fixer so that we don't break code one out of a billion times? IMO no.

If that rate was much higher then for sure it would be a no brainier to make code changes here. But it is just such a rare set of circumstances for it to actually cause an issue, so I don't think it's best for UX to change it.

In an ideal world yeah the stance would be 100% safe or else, but in the real world I think it's okay to accept a tiny amount of unsafety, as long as it's really rare or difficult to hit, for the betterment of everyone else.

**Comment by bradzacher** [comment] 2023-01-20 00:24
I'll mark this as accepted - i think we can continue to report on this case, but specifically disable the fixer if we do a check and find that the type is not a global type.

**Comment by bradzacher** [comment] 2024-08-08 21:28
Ban types is deprecated and it's replacement has scope analysis to support this. Closing as fixed.

**Closed by bradzacher** 2024-08-08 21:28 UTC
Labels: bug, package: eslint-plugin, accepting prs
