### ISSUE TITLE
Docs: make error message for no-var-requires rule more explicit

### ISSUE THREAD

**Issue by Almouro** [typescript-eslint/typescript-eslint#5451] opened 2022-08-09 17:07 UTC
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Hi,

This package is wonderful and very helpful, thanks for that! ❤️

I've just realized that inline requires are not typed with TypeScript. There's already a rule for it `no-var-requires` but I previously thought it was only about style. 

I'd like to request a small improvement to add a message like [this one for instance](https://github.com/typescript-eslint/typescript-eslint/compare/main...Almouro:add-require-error-message?expand=1#diff-65303eef1a467498113a30f580fce183a7bfc52b572d32335de8f594925fb6b0R16): 
```
Require statement not part of import statement and won't be typed. 
If you need inline requires, use dynamic imports instead.
 ```

I think it'd be useful for devs to have this in their IDE of choice to fully understand the consequence of not following the rule.

If you're happy with it, I'm happy to submit the PR 

### Affected URL(s)

https://typescript-eslint.io/rules/no-var-requires

**Comment by bradzacher** [comment] 2022-08-09 19:58
The message is intended to direct you to use the proper import equals syntax instead:

```ts
import Foo = require('Foo')
```

This *will* be typed by TS.

In terms of a dynamic import - the issue is that this requires asynchrony, which can be difficult to implement into some code.

We cpuld probably split the error for both cases and detect the dynamic case vs the top-level case.

**Comment by JoshuaKGoldberg** [comment] 2024-06-01 14:51
Now that `no-var-requires` is deprecated (#8092), we can close this out.

If anybody wants to file an equivalent issue on `no-require-imports` then they're more than welcome to. Cheers! 👋

**Closed by JoshuaKGoldberg** 2024-06-01 14:51 UTC
Labels: package: eslint-plugin, documentation, accepting prs
