### ISSUE TITLE
Dead links on npm

### ISSUE THREAD

**Issue by aerfio** [typescript-eslint/typescript-eslint#879] opened 2019-08-18 20:16 UTC
When you try to access links from https://www.npmjs.com/package/@typescript-eslint/eslint-plugin#supported-rules they all yield 404, but if you try to access them from https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/README.md it's ok

Sorry for not using template but it's not rule specific 😛

**Comment by JamesHenry** [comment] 2019-08-19 07:25
I cannot reproduce this, it works fine when clicking the first link.

Maybe it was a temporary issue with npm?

**Comment by JamesHenry** [comment] 2019-08-19 07:26
Oh I apologize, I now understand what you mean, we'll look into this

**Comment by armano2** [comment] 2020-01-19 20:22
This seems to be an issue with npm page, not our package

looks liek they are not reading correctly `repository.directory` field from package.json

**Comment by JamesHenry** [comment] 2020-09-01 10:09
I've raised this for discussion on NPM's github, closing this in favour of that: https://github.com/npm/rfcs/discussions/215

**Closed by JamesHenry** 2020-09-01 10:09 UTC
Labels: documentation, package: eslint-plugin
