### ISSUE TITLE
Bug: no-unnecessary-condition Doesn't handle exhaustiveness checking cases well

### ISSUE THREAD

**Issue by sbdchd** [typescript-eslint/typescript-eslint#5423] opened 2022-08-05 02:31 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=FAEwpgxgNghgTmABBA9gOwM4BdEEstgC2AXIgN6JYCeADmKQEQBmKKDiAvogD7nV2MARvAYdgoSLASImAVzQQsudIhgYMYOFgByYAG6aAFAA9SafZoCUZi3ADc43E0SH8RAHT8kAXl+JmrAyW5MCIyOgYKFBg7lAoAOaGDABirGyWwFxgUBp4zq4EhJ60Pn4MwnBBIWGomFExcYnlIhlZOUhkoarqmjq2BUStQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFIAEAuAngA4oDG0AlkXgLQrwUB2eA9IwPY2yOOKkrIAhtAI1S7RgBMKeChPRRE0aO2iQQ4MAF8QWoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
declare const item: { type: "foo" } | {type: "bar"}

declare function assertNever(x: never): never;

if (item.type === "foo") {
  console.log("Fooo")
} else if (item.type === "bar") {
  console.log("bar")
} else {
  assertNever(item)
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

I think it might be complicated to handle, but if it could detect that exhaustiveness checking is happening, then maybe it could skip erroring

### Actual Result

Warns about unnecessary condition when the condition is necessary for narrowing the type to never for the else branch.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.31.0` |
| `@typescript-eslint/parser`            | `5.31.0` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.20.0` |
| `node`                                 | `18.7.0` |

**Comment by bradzacher** [comment] 2022-08-05 03:45
Duplicate of #4682

Prefer using a switch statement for this sort of logic.

**Closed by bradzacher** 2022-08-05 03:46 UTC
Labels: bug, package: eslint-plugin, triage
