### ISSUE TITLE
typescript is a dependency but only included as a devDependency

### ISSUE THREAD

**Issue by RebeccaStevens** [typescript-eslint/typescript-eslint#770] opened 2019-07-29 03:37 UTC
This issue is with regards to the package **@typescript-eslint/typescript-estree**.

The compiled version of parser.js contains this line:

```js
const ts = __importStar(require("typescript")); // leave this as * as ts so people using util package don't need syntheticDefaultImports
```

If TypeScript isn't present, the package cannot be used.

In my case, I have an eslint plugin that use this package under the hood. The plugin fails to load if TypeScript isn't present (i.e. the plugin is being used to lint a project that doesn't use TypeScript).

```sh
$ /path/to/project/node_modules/.bin/eslint .
Error: Failed to load plugin 'someplugin' declared in '.eslintrc': Cannot find module 'typescript'
Require stack:
- /path/to/project/node_modules/@typescript-eslint/typescript-estree/dist/parser.js
- /path/to/project/node_modules/eslint-plugin-someplugin/lib/index.js
- /path/to/project/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /path/to/project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /path/to/project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /path/to/project/node_modules/eslint/lib/cli-engine/index.js
- /path/to/project/node_modules/eslint/lib/cli.js
- /path/to/project/node_modules/eslint/bin/eslint.js
Referenced from: /path/to/project/.eslintrc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (/path/to/project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/path/to/project/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:25)
    at Module._compile (/path/to/project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I believe the solution to this issue would be to have @typescript-eslint/typescript-estree declare TypeScript as either a dependency or a peerDependency.

**Comment by platinumazure** [comment] 2019-07-29 12:07
Hi @RebeccaStevens, thanks for the issue.

Typescript is configured as a peer dependency of this project. This means you are expected to specify typescript as a dependency or devDependency in your consuming project.

See this section of the README for more information: https://github.com/typescript-eslint/typescript-eslint/blob/master/README.md#supported-typescript-version

**Comment by LinusU** [comment] 2019-07-29 12:21
Seems like `@typescript-eslint/typescript-estree` specifically doesn't specify `typescript` as a peer-dependency though 🤔 

https://github.com/typescript-eslint/typescript-eslint/blob/f953cbdba45c6259664ae0b3ea2d198098d8923d/packages/typescript-estree/package.json#L43-L61

**Comment by platinumazure** [comment] 2019-07-29 12:36
Oh, oops, I didn't see which package the issue was about.

Yeah, I'm not sure in that case. I suppose there would still need to be a peer dependency as otherwise the parser would become indirectly dependent on typescript. I don't know what the intended setup is when you're consuming typescript-estree directly.

**Comment by JamesHenry** [comment] 2019-07-29 12:36
It was removed to help create-react-app: https://github.com/typescript-eslint/typescript-eslint/pull/443

**Comment by bradzacher** [comment] 2019-07-29 16:09
James has it correct - we did this on purpose.
Originally our peer dependency was `typescript: "*"`, which is a pretty useless dependency in so far as it only checks to make sure that typescript is installed.

We removed it so that tools such as create-react-app could create generic tools which service not only TS, but also non-TS codebases without throwing a large number of warnings at the user about missing peers for packages that don't actually get used.

We figured it was safe to remove the peer dependency because:
- it is only a warning at install time if you are missing the dep, which a lot of devs ignore anyways.
- if you're using any part of our toolchain, 99.9999% of the time you're using typescript in your codebase.
- as soon as you test the code you've written against our tools, it will instantly hard fail due to the missing import.

Yarn has some config to stop warnings showing up for peer dependencies, but NPM didn't support the same config (probably still doesn't? I haven't checked), so we didn't think it was a good idea to half fix the problem.

If you have a case that is in the 0.0001% in which you are using our tooling to build typescript tools _without_ writing your tools in typescript, then please let us know - I'd be interested to hear about it.

Otherwise - this is working as intended, so I'm going to close this for admin purposes.
Feel free to comment here to let us know your use case though.

**Closed by bradzacher** 2019-07-29 16:09 UTC
Labels: package: typescript-estree, triage

**Comment by RebeccaStevens** [comment] 2019-07-30 01:53
I've managed to resolve this issue for the project I'm working on.

The project I'm working on uses `AST_NODE_TYPES` from `@typescript-eslint/typescript-estree` and was including `@typescript-eslint/typescript-estree` as a dependency because of it.
I modified the build process to bundle this so now `@typescript-eslint/typescript-estree` is now only a dev dependency and thus uses of the project will no longer get errors if TypeScript is missing.

**Comment by bradzacher** [comment] 2019-07-30 02:08
This will not work as you expect - `AST_NODE_TYPES` is an enum, i.e. a runtime dependency.
Also noticed that you moved `experimental-utils` to be a dev dep - this will break your plugin as well, as you are consuming runtime functions from that package (the `ESLintUtils.RuleCreator`).

There should be no need for an eslint plugin to ever directly use `typescript-estree`. 
You should instead use our package `experimental-utils`, which exports all of the types and enums you need to write rules in typescript, without the dependency on typescript.
NOTE - `experimental-utils` should be a hard dependency of your package, or else you will have runtime errors.

Note that typescript's auto-importer doesn't care if packages are transient dependencies, so I'd recommend linting your project with `eslint-plugin-import` to make sure that nobody accidentally uses the wrong auto-import.

---

Looking at your github history, the plugin you're working on is `eslint-plugin-functional`, correct?
Yeah, if you correct your imports from `typescript-estree` to `experimental-utils`, everything will work.

I also notice that you're importing from `experimental-utils/dist` - you shouldn't deep link import from packages, as the folder structure is an internal implementation detail, and could break at any time.

**Comment by RebeccaStevens** [comment] 2019-07-30 04:56
@bradzacher, Thanks for your help.

Yes I am working on `eslint-plugin-functional`

I've now eliminated `typescript-estree` from the project and am no longer bundling any of the `@typescript-eslint` packages into the build.

However, I haven't been able to eliminated imports of `"@typescript-eslint/experimental-utils/dist/ts-eslint"`. Most of the exports of `ts-eslint` are not exported by the top-level `experimental-utils` ([only these ones are](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/src/index.ts#L14-L18)). I believe all the import I'm using from are defined in [the Rule file](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/src/ts-eslint/Rule.ts).
Is it possible for me to import these things without needing to import from `"../dist/.."`?

**Comment by bradzacher** [comment] 2019-07-30 05:10
Everything you want should be exposed via the `TSESLint` export from the package.

---

@JamesHenry - maybe we should do a special publish step for `experimental-utils` so that it's easier to consume?
i.e. copy the `package.json`/`README.md`/etc to the `dist` folder and publish from there?

That would flatten the folder so users can import directly instead of using namespaces:
```ts
import { ReportDescriptor } from '@typescript-eslint/experimental-utils/ts-eslint';
// vs
import { TSESLint } from '@typescript-eslint/experimental-utils';
type ReportDescriptor = TSESLint.ReportDescriptor;
```
