### ISSUE TITLE
Change ESLint rule creator doc URL base to the website

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#4487] opened 2022-01-26 15:09 UTC
### Suggested Changes

```ts
export const createRule = ESLintUtils.RuleCreator(
  name =>
    `https://github.com/typescript-eslint/typescript-eslint/blob/v${version}/packages/eslint-plugin/docs/rules/${name}.md`,
);
```

It currently points to the GitHub interface; however, since we have a website already, let's change that to the website instead.

### Affected URL(s)

None...

**Comment by JoshuaKGoldberg** [comment] 2022-01-27 04:26
Makes sense! I thought we had a todo for this somewhere but can't find it now... yes please!

**Comment by snitin315** [comment] 2022-01-27 09:28
I will work on it as my first contribution.

**Comment by JoshuaKGoldberg** [comment] 2022-02-12 17:53
My mistake, duplicate of #4368. Sorry for the noise folks!

**Closed by JoshuaKGoldberg** 2022-02-12 17:53 UTC
Labels: good first issue, documentation, accepting prs
