### ISSUE TITLE
Configs: Disable explicit-function-return-type in preset "disableTypeChecked"

### ISSUE THREAD

**Issue by yf-yang** [typescript-eslint/typescript-eslint#9917] opened 2024-09-03 03:30 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

https://typescript-eslint.io/rules/explicit-function-return-type/#configuring-in-a-mixed-jsts-codebase

This rule requires typescript annotations.

### Impacted Configurations

typescript-eslint/disable-type-checked

**Comment by bradzacher** [comment] 2024-09-03 12:32
Duplicate of #8955
Please use the search.

**Closed by bradzacher** 2024-09-03 12:32 UTC
Labels: package: eslint-plugin, triage, preset config change
