### ISSUE TITLE
ESLint: Cannot read property 'loc' of undefined. Please see the 'ESLint' output channel for details.

### ISSUE THREAD

**Issue by WDever** [typescript-eslint/typescript-eslint#441] opened 2019-04-19 04:53 UTC
**What code were you trying to parse?**

```ts
import * as React from 'react';
import styled from 'styled-components';

const TestStyledComponent = styled.div`
  // css
`;

class Example extends React.Component<ExampleProps, ExampleState> {
  public render () {
    return (
      <TestStyledComponent />
    );
  };
}

export default Example;
```

**What did you expect to happen?**
No Error
**What actually happened?**
ESLint: Cannot read property 'loc' of undefined. Please see the 'ESLint' output channel for details.

```
[Error - 1:08:08 PM] ESLint stack trace:
[Error - 1:08:08 PM] TypeError: Cannot read property 'loc' of undefined
    at Object.VariableDeclaration [as listener] (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/rules/indent.js:1361:69)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/rules/indent.js:1537:55)
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/rules/indent.js:1537:26)
    at listeners.(anonymous function).forEach.listener (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint/lib/util/node-event-generator.js:303:14)
```

when I write const in tsx, ESlint send an errror.

my eslint.js:
```
module.exports = {
  parser: '@typescript-eslint/parser',
  extends: [
    'plugin:@typescript-eslint/recommended',
    'react-app',
    'plugin:prettier/recommended',
    'prettier',
  ],
  plugins: ['@typescript-eslint', 'react'],
  rules: {
    '@typescript-eslint/indent': ['error', 2],
    // "@typescript-eslint/explicit-function-return-type": ["false"],
    '@typescript-eslint/explicit-function-return-type': 0,
    // "prettier/prettier": ["error", {
    //   "singleQuote": true,
    //   "parser": "flow"
    // }],
    // "no-unused-vars": ["error", { "vars": "all", "args": "none", "ignoreRestSiblings": true }],
    'no-unused-vars': 0,
    '@typescript-eslint/no-empty-interface': 0,
    'prettier/prettier': 0,
    '@typescript-eslint/no-parameter-properties': 0,
    // "@typescript-eslint/no-unused-vars": 0,
    // "@typescript-eslint/no-unused-vars": ["error", { "vars": "all", "args": "after-used", "ignoreRestSiblings": false }],
  },
};

```
**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.6.0` |
| `TypeScript`                | `3.3.3333` |
| `ESLint`                    | `create-react-app default` |
| `node`                      | `11.10.0` |
| `npm`                       | `6.8.0` |

**Comment by bradzacher** [comment] 2019-04-19 07:26
I am unable to repro this against master.

I'm not sure what eslint version you have installed, because your provided stack trace lists [indent.js:1361](https://github.com/eslint/eslint/blob/master/lib/rules/indent.js#L1361) as the source of the `Cannot read property 'loc' of undefined` error, but there is no way for that error to be reported on that line.

Please do the following:
- run eslint with the `--debug` flag from the CLI to verify

**Comment by WDever** [comment] 2019-04-19 14:21
My ESLint version is 5.16.
When I ran ESLint with --debug flag, it prints:
```
  eslint:cli CLI args: [ 'src/components/sideBar/sideBar.component.tsx', '--debug' ] +0ms
  eslint:cli Running on files +5ms
  eslint:glob-utils Creating list of files to process. +0ms
  eslint:ignored-paths baseDir = "/Users/wdever/Documents/Projects/hanlight-frontend-web" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +2ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +0ms
  eslint:ignored-paths Looking for ignore file in /Users/wdever/Documents/Projects/hanlight-frontend-web +11ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:ignored-paths contains: +3ms
  eslint:ignored-paths   target = "/Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx" +0ms
  eslint:ignored-paths   result = false +0ms
  eslint:ignored-paths contains: +1ms
  eslint:ignored-paths   target = "/Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx" +0ms
  eslint:ignored-paths   result = false +0ms
  eslint:cli-engine Processing /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx +0ms
  eslint:cli-engine Linting /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx +0ms
  eslint:config Constructing config file hierarchy for /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/wdever/Documents/Projects/hanlight-frontend-web/.eslintrc.js +1ms
  eslint:config-file Loading JS config file: /Users/wdever/Documents/Projects/hanlight-frontend-web/.eslintrc.js +0ms
  eslint:plugins Failed to load plugin @typescript-eslint/eslint-plugin. +0ms

Oops! Something went wrong! :(

ESLint: 5.16.0.
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure @typescript-eslint/eslint-plugin is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i @typescript-eslint/eslint-plugin@latest --save-dev

Path to ESLint package: /Users/wdever/.config/yarn/global/node_modules/eslint

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by bradzacher** [comment] 2019-04-19 15:59
> Path to ESLint package: /Users/wdever/.config/yarn/global/node_modules/eslint

You need to run the package locally instead of globally:
`yarn eslint <args> --debug`

If you run it globally (`eslint <args> --debug`) it will not use your local package's dependencies, so it will fail like it just did.

**Comment by Molunerfinn** [comment] 2019-04-20 10:33
I have the same issue.
My eslint version is `5.16.0`
My eslintrc.js is:
```js
module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "standard",
    "standard-react",
    "react-app"
  ],
  plugins: [
    "@typescript-eslint",
    "react",
  ]
}
```
After you type the `const`, this error will display in VSCode:
![loc-undefined](https://user-images.githubusercontent.com/12621342/56456135-98bac080-639a-11e9-8e75-2800b6cb0b46.gif)

**Comment by bradzacher** [comment] 2019-04-20 11:24
Can you save that code when it breaks and then run eslint with the - - debug flag?

The screenshot of the vscode bug toast isn't all that helpful.
Need some form of a stack trace along with information about what versions of everything you're using @Molunerfinn.

**Comment by Molunerfinn** [comment] 2019-04-20 11:27
Sure.
The log is :

```
➜ .\node_modules\.bin\eslint .\src\App.tsx --debug
  eslint:cli CLI args: [ '.\\src\\App.tsx', '--debug' ] +0ms
  eslint:cli Running on files +12ms
  eslint:glob-utils Creating list of files to process. +0ms
  eslint:ignored-paths baseDir = "D:\\Coding\\graduation-backend-platform" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +4ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +1ms
  eslint:ignored-paths Looking for ignore file in D:\Coding\graduation-backend-platform +1ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:ignored-paths contains: +4ms
  eslint:ignored-paths   target = "D:\\Coding\\graduation-backend-platform\\src\\App.tsx" +0ms
  eslint:ignored-paths   result = false +1ms
  eslint:ignored-paths contains: +0ms
  eslint:ignored-paths   target = "D:\\Coding\\graduation-backend-platform\\src\\App.tsx" +1ms
  eslint:ignored-paths   result = false +0ms
  eslint:cli-engine Processing D:\Coding\graduation-backend-platform\src\App.tsx +0ms
  eslint:cli-engine Linting D:\Coding\graduation-backend-platform\src\App.tsx +1ms
  eslint:config Constructing config file hierarchy for D:\Coding\graduation-backend-platform\src +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading D:\Coding\graduation-backend-platform\.eslintrc.js +2ms
  eslint:config-file Loading JS config file: D:\Coding\graduation-backend-platform\.eslintrc.js +0ms
  eslint:plugins Loaded plugin @typescript-eslint (@typescript-eslint/eslint-plugin@1.6.0) (from D:\Coding\graduation-backend-platform\node_modules\@typescript-eslint\eslint-plugin\dist\index.js) +0ms
  eslint:plugins Loaded plugin react (eslint-plugin-react@7.12.4) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-react\index.js) +126ms
  eslint:config-file Loading react-app +448ms
  eslint:config-file Attempting to resolve eslint-config-react-app +1ms
  eslint:config-file Loading JS config file: D:\Coding\graduation-backend-platform\node_modules\eslint-config-react-app\index.js +3ms
  eslint:plugins Loaded plugin import (eslint-plugin-import@2.17.2) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-import\lib\index.js) +186ms
  eslint:plugins Loaded plugin flowtype (eslint-plugin-flowtype@3.6.1) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-flowtype\dist\index.js) +34ms
  eslint:plugins Loaded plugin jsx-a11y (eslint-plugin-jsx-a11y@6.2.1) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-jsx-a11y\lib\index.js) +174ms
  eslint:config-file Loading standard-react +430ms
  eslint:config-file Attempting to resolve eslint-config-standard-react +1ms
  eslint:config-file Loading JS config file: D:\Coding\graduation-backend-platform\node_modules\eslint-config-standard-react\index.js +3ms
  eslint:config-file Loading D:\Coding\graduation-backend-platform\node_modules\eslint-config-standard-jsx\index.js +15ms
  eslint:config-file Loading JS config file: D:\Coding\graduation-backend-platform\node_modules\eslint-config-standard-jsx\index.js +1ms
  eslint:config-file Loading standard +12ms
  eslint:config-file Attempting to resolve eslint-config-standard +1ms
  eslint:config-file Loading JS config file: D:\Coding\graduation-backend-platform\node_modules\eslint-config-standard\index.js +2ms
  eslint:plugins Loaded plugin node (eslint-plugin-node@8.0.1) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-node\lib\index.js) +165ms
  eslint:plugins Loaded plugin promise (eslint-plugin-promise@4.1.1) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-promise\index.js) +22ms
  eslint:plugins Loaded plugin standard (eslint-plugin-standard@4.0.0) (from D:\Coding\graduation-backend-platform\node_modules\eslint-plugin-standard\index.js) +7ms
  eslint:config Using D:\Coding\graduation-backend-platform\.eslintrc.js +1s
  eslint:config-ops Using config from partial cache +0ms
  eslint:config-ops Apply environment settings to config +1ms
  eslint:config-ops Creating config for environment es6 +1ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment browser +0ms
  eslint:config-ops Creating config for environment commonjs +1ms
  eslint:config-ops Creating config for environment jest +0ms
  eslint:linter Linting code for D:\Coding\graduation-backend-platform\src\App.tsx (pass 1) +0ms
  eslint:linter An error occurred while traversing +105ms
  eslint:linter Filename: D:\Coding\graduation-backend-platform\src\App.tsx +1ms
  eslint:linter Line: 1 +1ms
  eslint:linter Parser Options: { ecmaVersion: 9,
  ecmaFeatures: { globalReturn: false, jsx: true },
  sourceType: 'module' } +0ms
  eslint:linter Parser Path: D:\Coding\graduation-backend-platform\node_modules\@typescript-eslint\parser\dist\parser.js +2ms
  eslint:linter Settings: { react: { version: 'detect' } } +1ms
TypeError: Cannot read property 'loc' of undefined
Occurred while linting D:\Coding\graduation-backend-platform\src\App.tsx:1
    at Object.VariableDeclaration [as listener] (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\rules\indent.js:1370:69)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\rules\indent.js:1546:55)
    at Array.forEach (<anonymous>)
    at Program:exit (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\rules\indent.js:1546:26)
    at listeners.(anonymous function).forEach.listener (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (D:\Coding\graduation-backend-platform\node_modules\eslint\lib\util\node-event-generator.js:303:14)
```

**Comment by bradzacher** [comment] 2019-04-20 16:56
awesome, thanks.
looks like a bug to do with the conversion logic for indent.

I'm in the middle of the rewrite, of the indent rule which should fix issues like this.

**Comment by WDever** [comment] 2019-04-21 08:47
I'm really sorry. I check your comments right now.

when I ran ```yarn eslint <> --debug```:
```  eslint:cli CLI args: [ 'src/components/sideBar/sideBar.component.tsx', '--debug' ] +0ms
  eslint:cli Running on files +5ms
  eslint:glob-utils Creating list of files to process. +0ms
  eslint:ignored-paths baseDir = "/Users/wdever/Documents/Projects/hanlight-frontend-web" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +0ms
  eslint:ignored-paths Looking for ignore file in /Users/wdever/Documents/Projects/hanlight-frontend-web +0ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:ignored-paths contains: +2ms
  eslint:ignored-paths   target = "/Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx" +0ms
  eslint:ignored-paths   result = false +0ms
  eslint:ignored-paths contains: +0ms
  eslint:ignored-paths   target = "/Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx" +0ms
  eslint:ignored-paths   result = false +0ms
  eslint:cli-engine Processing /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx +0ms
  eslint:cli-engine Linting /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx +1ms
  eslint:config Constructing config file hierarchy for /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/wdever/Documents/Projects/hanlight-frontend-web/.eslintrc.js +1ms
  eslint:config-file Loading JS config file: /Users/wdever/Documents/Projects/hanlight-frontend-web/.eslintrc.js +0ms
  eslint:plugins Loaded plugin @typescript-eslint (@typescript-eslint/eslint-plugin@1.6.0) (from /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +0ms
  eslint:plugins Loaded plugin react (eslint-plugin-react@7.12.4) (from /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-plugin-react/index.js) +143ms
  eslint:config-file Loading prettier +687ms
  eslint:config-file Attempting to resolve eslint-config-prettier +0ms
  eslint:config-file Loading JS config file: /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-config-prettier/index.js +1ms
  eslint:config-file Loading plugin:prettier/recommended +2ms
  eslint:config-file Attempting to resolve eslint-plugin-prettier +1ms
  eslint:config-file Loading JS config file: /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js +1ms
  eslint:plugins Loaded plugin prettier (eslint-plugin-prettier@3.0.1) (from /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js) +196ms
  eslint:config-file Loading prettier +9ms
  eslint:config-file Attempting to resolve eslint-config-prettier +0ms
  eslint:config-file Loading react-app +1ms
  eslint:config-file Attempting to resolve eslint-config-react-app +0ms
  eslint:config-file Loading JS config file: /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-config-react-app/index.js +1ms
  eslint:plugins Loaded plugin import (eslint-plugin-import@2.16.0) (from /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-plugin-import/lib/index.js) +164ms
  eslint:plugins Loaded plugin flowtype (eslint-plugin-flowtype@3.4.2) (from /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-plugin-flowtype/dist/index.js) +31ms
  eslint:plugins Loaded plugin jsx-a11y (eslint-plugin-jsx-a11y@6.2.1) (from /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/eslint-plugin-jsx-a11y/lib/index.js) +182ms
  eslint:config-file Loading plugin:@typescript-eslint/recommended +410ms
  eslint:config-file Attempting to resolve @typescript-eslint/eslint-plugin +0ms
  eslint:config-file Loading JS config file: /Users/wdever/Documents/Projects/hanlight-frontend-web/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslint:config Using /Users/wdever/Documents/Projects/hanlight-frontend-web/.eslintrc.js +1s
  eslint:config-ops Using config from partial cache +0ms
  eslint:config-ops Apply environment settings to config +1ms
  eslint:config-ops Creating config for environment browser +0ms
  eslint:config-ops Creating config for environment commonjs +0ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:config-ops Creating config for environment jest +0ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:linter Linting code for /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx (pass 1) +0ms
  eslint:traverser Unknown node type "TSInterfaceDeclaration": Estimated visitor keys ["type","body","id","range","loc"] +0ms
  eslint:traverser Unknown node type "TSInterfaceBody": Estimated visitor keys ["type","body","range","loc"] +0ms
  eslint:traverser Unknown node type "TSInterfaceDeclaration": Estimated visitor keys ["type","body","id","range","loc"] +0ms
  eslint:traverser Unknown node type "TSInterfaceBody": Estimated visitor keys ["type","body","range","loc"] +0ms
  eslint:linter Generating fixed text for /Users/wdever/Documents/Projects/hanlight-frontend-web/src/components/sideBar/sideBar.component.tsx (pass 1) +105ms
  eslint:source-code-fixer Applying fixes +0ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
  eslint:cli-engine Linting complete in: 1251ms +1s
✨  Done in 1.82s.
```

**Comment by vadim-96** [comment] 2019-05-01 05:26
@bradzacher How long to wait for that fix?

**Comment by bradzacher** [comment] 2019-05-01 12:25
Like I said, I'm in the middle of a rewrite to handle all of these cases properly.

It's going to be a while as indent is a huge rule.

**Comment by roeintense** [comment] 2019-06-03 13:50
@bradzacher any reocmmendations on workaround while rewrite is in flight?

**Comment by bradzacher** [comment] 2019-06-03 16:16
it's hard to say - this is a very, very generic error; it could be from any number of rules.
Indent is just one rule that causes an error in a specific case.

Usually this error occurs the vscode extension attempts to lint incomplete code.
The incomplete code can cause the parser to create a weird AST which isn't technically valid TS/JS 
99% of the time when you see this error popup in vscode, just ignore/close it and keep working.

A lot times rule authors make assumptions about the shape of AST because they assume 100% valid code. Which is fine in the majority of cases, but edge cases sometimes happen (esp with the extension running on incomplete code).

For example, in the gif above - a common assumption is that there's at least 1 declaration in a variable declaration, as the code is not valid JS without it
However in that gif, there is a dangling `const` reserved word, which the parser accepts and creates a weird case where the AST has a variable declaration with no declaration - invalid code that won't run, but parsable code none-the-less.
![image](https://user-images.githubusercontent.com/7462525/58817100-d0469a80-85df-11e9-97fa-25d7cbd0b0f2.png)

If you see the toast popup very regularly, create a repro case so we can investigate and fix the exact failing case.

**Comment by piousdeer** [comment] 2019-06-15 07:16
[Here's a repro repo](https://github.com/piousdeer/typescript-eslint-411). Please fix it, thanks!

**Comment by kaicataldo** [comment] 2019-06-15 16:57
We’ve been discussing if we want to add the ability to handle recoverable errors in ESLint core. This type of error was actually one of the concerns that was brought up during that discussion. See https://github.com/eslint/rfcs/pull/19 for more details.

**Comment by 2alin** [comment] 2019-06-21 11:46
Same problem here, is there any workaround? This is the only reason that makes me not use ESLint in a typescript team project.

**Comment by bradzacher** [comment] 2019-06-21 16:04
@2alin - what is your repro case for "the same problem"? Is it *exactly* the same problem as one of the ones? If not then please elaborate with a repro.
It's hard to recommend a workaround for you if we don't know what's causing your problem.

If it's an error that's only showing up within your IDE, then just ignore the error and the eslint extension will recover as soon as you save the file again.
In this instance - the error probably occurred because you attempted to lint a semantically invalid file.

If the issue persists through file saves, then it's probably not a semantically invalid file, and might be a bug in a rule. Try doing a CLI run to see if that errors in the same way.

If it's an error that occurs during a CLI run, then please, _please_, ***please*** comment with the output of running your eslint command with the `--debug` flag so that we can read through the output to determine the error.

---

this debug log https://github.com/typescript-eslint/typescript-eslint/issues/441#issuecomment-485097423 and this repro https://github.com/typescript-eslint/typescript-eslint/issues/441#issuecomment-502342268 is an issue with the indent rule caused by linting an incomplete variable declaration (i.e they attempted to lint `const;`).
The workaround is to finish writing valid code, and the error will disappear.

Your use case might be different. I don't know - I don't have your codebase. Help me to help you.

**Comment by eyedean** [comment] 2019-06-23 17:55
@bradzacher Thanks for being on top of it.

The issue for me is not that IDE will not recover or it shows up during CLI run.  It's just when I type `const` an error tooltip pops up from the bottom right corner of VS Code and it's so distracting.

I bet your PR is going to fix it as it's on `VariableDeclaration` of `indent.js` for me when the passed `node` argument's `declarations` property is empty/null.  Thanks again. :)

**Closed** 2019-06-28 15:32 UTC
Labels: bug, package: parser

**Comment by moun3iim** [comment] 2019-12-03 05:12
> I have the same issue.
> My eslint version is `5.16.0`
> My eslintrc.js is:
> 
> ```js
> module.exports = {
>   parser: "@typescript-eslint/parser",
>   extends: [
>     "standard",
>     "standard-react",
>     "react-app"
>   ],
>   plugins: [
>     "@typescript-eslint",
>     "react",
>   ]
> }
> ```
> 
> After you type the `const`, this error will display in VSCode:
> ![loc-undefined](https://user-images.githubusercontent.com/12621342/56456135-98bac080-639a-11e9-8e75-2800b6cb0b46.gif)

I have the same issue, the error appears when I try to type `const`. anyone can help me to fix it?

**Comment by bradzacher** [comment] 2019-12-03 05:12
please open a new issue and fill out the details.
