### ISSUE TITLE
Enhancement: [prefer-optional-chain] support simple if statements

### ISSUE THREAD

**Issue by grant** [typescript-eslint/typescript-eslint#7604] opened 2023-09-05 15:41 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/prefer-optional-chain

### Description

I propose there should be an option to lint and fix optional methods:

```ts
if (onDismiss) onDismiss(event);
// -->
onDismiss?.(event);
```

See https://github.com/tc39/proposal-optional-chaining/#overview-and-motivation for exact syntax:

> The call variant of Optional Chaining is useful for dealing with interfaces that have optional methods:
> 
> ```js
> iterator.return?.() // manually close an iterator
> ```

Linting and fixing could be an option of rule [`prefer-optional-chain`](https://typescript-eslint.io/rules/prefer-optional-chain), off by default, with configuration such as:

```ts
type Options = [
  {
    ...
    /** Checks function calls that can use optional chaining with method calls. */
    optionalMethods?: boolean;
  },
];
```

### Fail

```typescript
if (onDismiss) onDismiss(event);
```

### Pass

```typescript
onDismiss?.(event);
```

**Comment by bradzacher** [comment] 2023-09-05 22:11
Correction/generalisation for this request - you're not specifically looking for optional chain methods - you're looking for detection in the form of `if (expression) expression.chain`.

Most usecases of this would likely just be methods though (an alternate form of `expression && expression.chain()`

**Comment by grant** [comment] 2023-09-05 22:36
For my use case, I am specifically looking for method optional chaining, and not supporting every variant of optional chaining (although those options would be nice).

```tsx
if (onDismiss) onDismiss(event);
// -->
onDismiss?.(event);
```

when

```tsx
optionalMethods?: boolean;
```

And _not requesting_ :

```ts
if (myArray && myArray[0]) return true;
// -->
if (myArray?.[0]) return true;
```

I assume that would be another eslint option.

**Comment by bradzacher** [comment] 2023-09-05 22:54
I'm not sure I understand - why would you want one and not the other?
Why not make everything optional chaining instead of leaving things in an inconsistent state?

**Comment by grant** [comment] 2023-09-05 23:09
I think it would be a much larger ask to enable this rule for all variants of optional chaining without having options to turn off them. It would result in a very large diff.

```ts
interface Options {
  optionalFunctionCall?: boolean; // default true?
  optionalStaticProperty?: boolean; // default true (already implemented with prefer-optional-chain)
  optionalDynamicProperty?: boolean; // default true?
}
```

I don't care about what the defaults would be, but I assume there's some policy with breaking changes.

**Comment by bradzacher** [comment] 2023-09-06 00:12
The rule has a fixer which will help turn it on across a codebase.

Options are expensive to build and maintain as each option exponentially increases test complexity - so we want really good usecases for adding options.

Migration usecases are not something we build options for - migrations are temporary, but options are forever. Instead our recommendation is to migrate via turning a rule on as a warning, and using [`--max-warnings`](https://eslint.org/docs/latest/use/command-line-interface#--max-warnings) to allow you to fix cases over time and eventually turn the rule on to an error.

**Comment by grant** [comment] 2023-09-06 00:47
Without options is fine.

I feel like it would be a breaking change if someone updated there typescript eslint package version and automatically had all of these other optional chain cases changed, without a way to disable this enhancement, but perhaps that's fine. I don't know as much around the codebase or versioning / options expensiveness.

**Comment by bradzacher** [comment] 2023-09-06 03:40
https://typescript-eslint.io/users/versioning#eslint-plugin-and-eslint-plugin-tslint

For the average codebase that already uses this rule - the instances of `if (expression) expression.chain` are already likely low - so it falls within the bounds of a minor bump for us :)

**Comment by omril1** [comment] 2024-04-26 13:52
This looks like a similar to what was suggested in #6309, and the limitations there also apply to here

**Comment by Josh-Cena** [comment] 2024-06-01 07:15
In fact I would call it a duplicate of #6309 since if we detect `if (x) x.something` we would automatically fix `if (x) x()`.

**Closed by Josh-Cena** 2024-06-01 07:15 UTC
Labels: package: eslint-plugin, enhancement: plugin rule option, accepting prs
