### ISSUE TITLE
Repo: handle exceptions that occur while testing a rule better

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8942] opened 2024-04-17 21:49 UTC
### Suggestion

If you throw an exception in a rule (within the RuleListener object handlers, not at the top level of the `create()` function), the whole test suite fails with an unhelpful error message, rather than failing just the individual test run and printing a useful error message. For instance, here's what happens when I throw an exception in a line affected by just one test case: 

```
 FAIL  tests/rules/no-unnecessary-type-arguments.test.ts
  ● Test suite failed to run

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Object'
        |     property 'params' -> object with constructor 'Array'
        |     index 0 -> object with constructor 'Object'
        --- property 'parent' closes the circle
        at stringify (<anonymous>)
```

@JoshuaKGoldberg has a hacky workaround. Feel free to share in case that makes it easier to pinpoint the root cause?

**Comment by bradzacher** [comment] 2024-04-17 21:57
The root causes is jest using worker threads and communicating things across threads.

Specifically when you throw an error in a selector eslint will include the current AST node in the error. The AST is cyclic and thus the error.

**Comment by JoshuaKGoldberg** [comment] 2024-04-18 20:24
Ha, yeah, I saw this recently and got around it hackily by adding to the file mentioned in the error:

```plaintext
      at messageParent (../../node_modules/jest-worker/build/workers/messageParent.js:29:19)
```

```diff
} else if (typeof parentProcess.send === 'function') {
+   console.log(message?.[1]?.[1]);
    parentProcess.send([_types.PARENT_MESSAGE_CUSTOM, message]); 
```

Is this a bug in Jest? If so, is it resolved by bumping to the latest version? Someone should look into this. 😄

**Comment by JoshuaKGoldberg** [comment] 2024-07-03 19:09
This is https://github.com/jestjs/jest/issues/14840, I think.

**Comment by bradzacher** [comment] 2024-07-03 20:19
```
} catch (e) {
  removeCycles(e.node)
  throw e;
}
```

**Comment by abrahamguo** [comment] 2024-08-03 11:53
Would it be acceptable to add something to RuleTester to remove cycles when an exception is thrown, so that we don't have to wait for an upstream fix?

**Comment by bradzacher** [comment] 2024-08-25 13:23
I don't see why not.
It seems sane to just remove the `.parent` from the AST by default to avoid such problems.

**Closed** 2024-10-15 01:41 UTC
Labels: repo maintenance, accepting prs
