### ISSUE TITLE
Configs: Add "disable all" config

### ISSUE THREAD

**Issue by FloEdelmann** [typescript-eslint/typescript-eslint#9855] opened 2024-08-21 13:05 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

In my [project](https://github.com/FloEdelmann/vue-ts-types), I use both [eslint-plugin-package-json](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json)'s `recommended` config (only for the `package.json` file) and typescript-eslint's `strictTypeChecked` and `stylisticType` configs:

```ts
export default typescriptEslint.config(
  eslint.configs.recommended,
  ...typescriptEslint.configs.strictTypeChecked,
  ...typescriptEslint.configs.stylisticTypeChecked,
  eslintConfigPackageJson,
)
```

Without further configuration, linting throws an error:

```
Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Parser: jsonc-eslint-parser
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting …/package.json
```

I don't want the typescript-eslint rules to run on JSON files, so this is what I ended up with:

```ts
const disabledTypeScriptEslintRules = Object.fromEntries(
  typescriptEslint.configs.all
    .flatMap((config) => Object.keys(config.rules ?? []))
    .filter((ruleName) => ruleName.startsWith('@typescript-eslint/'))
    .map((ruleName) => [ruleName, 'off']),
);

export default typescriptEslint.config(
  eslint.configs.recommended,
  ...typescriptEslint.configs.strictTypeChecked,
  ...typescriptEslint.configs.stylisticTypeChecked,
  {
    // disable all TypeScript-related rules because they interfere with JSON parsing
    files: ['**/package.json'],
    languageOptions: eslintConfigPackageJson.languageOptions,
    plugins: eslintConfigPackageJson.plugins,
    rules: {
      ...disabledTypeScriptEslintRules,
      ...eslintConfigPackageJson.rules,
    },
  },
);
```

(See https://github.com/FloEdelmann/vue-ts-types/blob/e18fcd24536f182fdcd7a7e08bd3aab97e4d5e96/eslint.config.js#L134-L142)

This configuration could look a little bit simpler if there was a typescript-eslint config that disables all typescript-eslint rules, similar to [`disableTypeChecked`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-eslint/src/configs/disable-type-checked.ts).

### Impacted Configurations

None, only add a new one.

**Comment by bradzacher** [comment] 2024-08-21 14:15
It would be worth submitting this feedback to eslint upstream.

Esp as they consider building support for easy integration of more and more languages - this sort of problem will become more common.

Having a way to "isolate" a language or glob from the rest of the config would be a valuable improvement.

----

All that being said. The error you're seeing is due to type-aware lint rules not working on those files. You can fix that with the config you mentioned - `disableTypeChecked`.

Eg

```js
export default tseslint.config(
  {
    files: ['**/*.json"],
    extends: [tseslint.configs.disableTypeChecked],
  },
);
```

**Comment by FloEdelmann** [comment] 2024-08-21 14:22
Adding that to the naive config in my post above leads to the same error for the `consistent-type-assertions` rule, which does not require type information. So only disabling type-aware rules doesn't resolve the issue.

Regarding reporting upstream: I feel like I have too little information what to put in such an issue for eslint. Would you be able to do that?

**Comment by JoshuaKGoldberg** [comment] 2024-08-21 14:28
This would be a good FAQ to put somewhere on the site. What this issue is essentially asking to be able to do is:

1. For _all_ files: turn on JS/TS rules
2. For _JSON_ files: turn on JSON rules, turn off TS rules, and allow JS rules to do nothing

...but I think it'd be a cleaner structure to instead:

1. For _JS/TS_ files: turn on JS/TS rules
2. For _JSON_ files: turn on JSON rules

I.e.:

```ts
import js from "@eslint/js";
import packageJson from "eslint-plugin-package-json/configs/recommended";
import tseslint from "typescript-eslint";

export default [
	{
		files: ["**/package.json"],
		...packageJson,
	},
	...tseslint.config({
		extends: [
			js.configs.recommended,
			...tseslint.configs.strictTypeChecked,
			...tseslint.configs.stylisticTypeChecked,
		],
		files: ["**/*.ts"],
	}),
];
```

**Comment by bradzacher** [comment] 2024-08-21 14:51
> leads to the same error for the consistent-type-assertions rule

Honestly we should count that as a bug.
The issue is that the rule is using the TS AST which comes from parser services.

The util shouldn't eagerly error in this case though, I don't think. It should lazily error when the rule accesses the services instead - I.e. Make the properties getters that throw.

Also we could probably fix the rule to not use the TS AST. I think we updated the utils to allow us to leverage the estree ast for operator precedence now?

**Comment by FloEdelmann** [comment] 2024-08-21 15:27
I didn't expect this little feature request to split into three sub-issues :sweat_smile: 

1. allow ESLint to isolate a language or glob from the rest of the config
2. FAQ about ESLint config structuring
3. `consistent-type-assertions` should not error when parser services are not available

Should we open separate issues for 2. and 3.? (And keep this issue for discussion about 1. if/until it can be raised upstream?)

**Comment by JoshuaKGoldberg** [comment] 2024-09-04 12:34
For discussion on 1 - marking as `evaluating community engagement`. I don't think we've had a lot of requests for _"disable all"_ configs before. Looking back over the filed issues, I still have a gut feeling that it's a "code smell" for ESLint configs. Disabling everything from a plugin for some files is a sign that the plugin's rules shouldn't have been enabled on that file in the first place IMO.

**Closed** 2024-11-21 17:37 UTC
Labels: package: eslint-plugin, preset config change, evaluating community engagement
