### ISSUE TITLE
Enhancement: [no-useless-constructor] Rule for Protected Base Class Constructors

### ISSUE THREAD

**Issue by taisei-yamamoto-an** [typescript-eslint/typescript-eslint#8059] opened 2023-12-13 07:30 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-useless-constructor/

### Description

I would like to propose a modification to the `@typescript-eslint/no-useless-constructor` rule, particularly in scenarios where a class with a protected constructor is extended.

### Current Behavior

When extending a class with a protected constructor, like the following example, the @typescript-eslint/no-useless-constructor rule triggers an error if the derived class's constructor uses the default public access modifier and only calls super() with the same parameters.

### Suggested Change:

I propose that the rule should not flag an error in cases where the base class constructor is protected and the derived class constructor is using the default public access modifier. The rationale is that changing the access level from protected to public in the derived class is a meaningful alteration, and thus the constructor should not be considered 'useless'.

### Fail

```TypeScript
class BaseError extends Error {
  protected constructor(message: string) {
    super(message);
  }
}

class DerivedError extends BaseError {
  constructor(message: string) {
    super(message);
  }
}
```

### Pass

```TypeScript
class BaseError extends Error {
  protected constructor(message: string) {
    super(message);
  }
}

class DerivedError extends BaseError {
  public constructor(message: string) { // I don't want to declare 'public'
    super(message);
  }
}
```

### Additional Info

This change would acknowledge the design intent where extending classes may need to expose a more accessible constructor while maintaining the encapsulation of the base class.

Thank you for considering this suggestion. I believe this modification would enhance the rule's applicability and prevent unnecessary warnings in valid inheritance scenarios.

**Comment by bradzacher** [comment] 2023-12-13 10:36
duplicate of #948, #6094.

This requires type information and is not something we'll be looking to add to the rule.

**Closed by bradzacher** 2023-12-13 10:36 UTC
Labels: package: eslint-plugin, triage, enhancement: plugin rule option
