### ISSUE TITLE
Configs: extend `project: true` to allow `tsconfig.eslint.json` or custom `tsconfig.*.json` files

### ISSUE THREAD

**Issue by saltman424** [typescript-eslint/typescript-eslint#7943] opened 2023-11-17 03:08 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Currently, there are four possible values for [project](https://typescript-eslint.io/packages/parser/#project):
1. `true`
2. path
3. glob pattern
4. list of paths or glob patterns

The latter three offer a lot of flexibility, but use a fundamentally different approach than the first option. Because of that, the first one is necessary for performance in large mono-repos: https://github.com/typescript-eslint/typescript-eslint/issues/1192

However, the first one always uses `tsconfig.json` for linting. So if you have a large mono-repo, in order to be able to lint efficiently, you cannot dedicate `tsconfig.json` to building or being a base tsconfig for other `tsconfig.*.json`, you have to use it for linting. Before migrating to a mono-repo, my team would use `tsconfig.json` for building, `tsconfig.lint.json` for linting, and `tsconfig.test.json` for testing. No longer being able to do is not ideal.

I would like to propose one or both of:
1. Adding a fifth option to the list above: `{ nearest: string | string[] }`. E.g. `project: { nearest: 'tsconfig.eslint.json' }` or `project: { nearest: [ 'tsconfig.json', 'tsconfig.eslint.json' ] }`
2. Modifying the default logic of `true` to also pick up `tsconfig.eslint.json` files, since that seems to be the "advised" naming convention (e.g. as seen [here](https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file))

### Impacted Configurations

[project](https://typescript-eslint.io/packages/parser/#project)

**Comment by bradzacher** [comment] 2023-11-17 03:58
duplicate of #7383

**Closed by bradzacher** 2023-11-17 03:58 UTC
Labels: package: typescript-estree, triage
