### ISSUE TITLE
Rule proposal: `private-style`

### ISSUE THREAD

**Issue by sosukesuzuki** [typescript-eslint/typescript-eslint#6288] opened 2022-12-30 06:28 UTC
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Currently, TypeScript offers two ways to implement private class properties.

1. `private` modifier (a.k.a. soft private)

```ts
class Foo {
  private foo: string = "foo";
}
```

2. `#` (a.k.a hard private, ES private)

```ts
class Foo {
  #foo: string = "foo";
}
```

**The new rule I propose is `@typescript-eslint/private-style`.** This rule requires consistent private styles.

```json
{
  "rules": {
    "typescript-eslint/private-style": ["error", "hard"],
    // or
    "typescript-eslint/private-style": ["error", "soft"]
  }
}
```

### Fail Cases

```typescript
/* eslint typescript-eslint/private-style: ["error", "hard"] */

class Foo {
  private foo: string = "foo";
}

// or

/* eslint typescript-eslint/private-style: ["error", "soft"] */

class Foo {
  #foo: string = "foo";
}
```

### Pass Cases

```typescript
/* eslint typescript-eslint/private-style: ["error", "hard"] */

class Foo {
  #foo: string = "foo";
}

// or

/* eslint typescript-eslint/private-style: ["error", "soft"] */

class Foo {
  private foo: string = "foo";
}
```

**Comment by Josh-Cena** [comment] 2022-12-30 06:30
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/1391

**Comment by sosukesuzuki** [comment] 2022-12-30 06:32
Ah sorry

**Comment by Josh-Cena** [comment] 2022-12-30 06:32
It's fine—it's not always easy to search 😄

**Closed** 2022-12-30 06:31 UTC
Labels: duplicate, package: eslint-plugin
